### ISSUE TITLE
Error 500 on /settings/profile on a unsuspended account

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#10177]
### Expected behaviour

The user should be able to view and edit their profile settings

### Actual behaviour

The user get an error 500 on ` /settings/profile`.

Here is the error:

```
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40] method=GET path=/settings/profile format=html controller=Settings::ProfilesController action=show status=500 error='NoMethodError: undefined method `<<' for {}:Hash
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40]
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40] NoMethodError (undefined method `<<' for {}:Hash
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40]
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40] app/models/account.rb:269:in `block in build_fields'
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40] app/models/account.rb:268:in `times'
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40] app/models/account.rb:268:in `build_fields'
Mar 05 09:05:43 mstdn bundle[211]: [66c612f8-d09f-4009-aeb2-6a29fa457e40] app/controllers/settings/profiles_controller.rb:15:in `show'
```

### Steps to reproduce the problem

- User is suspended
- User is unsuspended (they are able to log in but all of their content was deleted)
- User tries to edit their profile by going to `/settings/profile`.

### Specifications

Mastodon 2.7.3

**Comment by angristan** [comment]
I'm still getting the error with 2.7.4:

```rb
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12] method=GET path=/settings/profile format=html controller=Settings::ProfilesController action=show status=500 error='NoMethodError: undefined method `<<' for {}:Hash
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12]
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12] NoMethodError (undefined method `<<' for {}:Hash
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12]
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12] app/models/account.rb:270:in `block in build_fields'
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12] app/models/account.rb:269:in `times'
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12] app/models/account.rb:269:in `build_fields'
Mar 07 09:03:14 mstdn bundle[4703]: [580f4921-de97-4d06-981f-61326cc44e12] app/controllers/settings/profiles_controller.rb:15:in `show'
```
