### ISSUE TITLE
ReferenceError: window is not defined when pre-compiling all CSS and JavaScript files

### ISSUE THREAD

**Issue by savaricous** [tootsuite/mastodon#1029]
Getting this error when running "RAILS_ENV=production bundle exec rails assets:precompile"
```
Browserify: /home/mastodon/live/node_modules/.bin/browserify --transform [ babelify --presets [ es2015 react ] ] --extension=".jsx" --list -o "/home/mastodon/live/tmp/cache/browserify-rails/output20170406-16750-j3hsvi" -
rails aborted!
BrowserifyRails::BrowserifyError: Error while running `/home/mastodon/live/node_modules/.bin/browserify --transform [ babelify --presets [ es2015 react ] ] --extension=".jsx" --list -o "/home/mastodon/live/tmp/cache/browserify-rails/output20170406-16750-j3hsvi" -`:

events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: window is not defined (While processing preset: "/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/react-rails-1.10.0/lib/assets/react-source/production/react.js") while parsing file: /home/mastodon/live/app/assets/javascripts/_stream_0.js
    at Object.<anonymous> (/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/react-rails-1.10.0/lib/assets/react-source/production/react.js:1:301)
    at t (/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/react-rails-1.10.0/lib/assets/react-source/production/react.js:1:169)
    at /home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/react-rails-1.10.0/lib/assets/react-source/production/react.js:1:256
    at Object.<anonymous> (/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/react-rails-1.10.0/lib/assets/react-source/production/react.js:1:261)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/browserify-rails-4.1.0/lib/browserify-rails/browserify_processor.rb:221:in `run_browserify'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/browserify-rails-4.1.0/lib/browserify-rails/browserify_processor.rb:144:in `dependencies'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/browserify-rails-4.1.0/lib/browserify-rails/browserify_processor.rb:121:in `commonjs_module?'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/browserify-rails-4.1.0/lib/browserify-rails/browserify_processor.rb:93:in `should_browserify?'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/browserify-rails-4.1.0/lib/browserify-rails/browserify_processor.rb:35:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/browserify-rails-4.1.0/lib/browserify-rails/browserify_processor.rb:16:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by savarice72511** [comment]
Note: I got it working on Ubuntu 16.04, however with Debian 8 I had this issue.
