### ISSUE TITLE
Relay usage “Rejected Announce activity”

### ISSUE THREAD

**Issue by mahescho** [tootsuite/mastodon#10324]
As  https://discourse.joinmastodon.org didn't help I'm writing here:

I try to use relays and I get log entries like this:

    mastrodon bundle[11676]: Rejected Announce activityhttps://relay.mastodon.host/activities/a7296176-ffa7-4dd2-a8db-f43fef892e24 from https://relay.mastodon.host/actor

    mastrodon bundle[11676]: Rejected Announce activity https://relay.social.seattle.wa.us/activities/a95b88f8-0bf5-44bd-9a2f-7276107542c8 from https://relay.social.seattle.wa.us/actor
what am I doing wrong?

The logs read actor but I subscribed inbox …

What I'm talking about is this:

![Relays](https://user-images.githubusercontent.com/5101589/54684487-c0f19e00-4b14-11e9-97be-54f01cf0b5bc.png)

**Comment by KScabledog** [comment]
I thought I'd give the relay feature a try but it's not working for me either.  I'm running v2.7.4 and tried the same relays and a few others and seeing the same messages in my logs as well.

**Comment by TheEpTic** [comment]
I'm kinda curious about this too, does someone have any idea what would cause this? 👀

**Comment by Gargron** [comment]
This is a bit odd, because I don't believe the pub-relay sends `Announce` activities, it just forwards signed ones:

https://source.joinmastodon.org/mastodon/pub-relay/blob/master/src/web_server/inbox_handler.cr#L61-65

The messages in your logs have an `Announce` type *and* an ID that refers to the relay itself, which the pub-relay does not create.

I don't know what code those relays are running, but it's not what we expect.

**Comment by TheEpTic** [comment]
They seem to be running https://git.pleroma.social/pleroma/relay which claims to be Mastodon compatible, I guess it's not?

**Comment by IzaliaMae** [comment]
I put up a 2.7.0 instance and it worked fine with my relay as well as the one at relay.mastodon.host, so clearly some commit between then and now botched pleroma relay support. Gonna continue to narrow down when it broke.

Btw are there any known masto relays that I could try? Just curious if relay support in general is broken

**Comment by TheEpTic** [comment]
I believe the latest version of both work together. My friend has a relay here —> https://relay.cloutfla.re/ and it’s working fine. The only issue they’ve had is it doesn’t register pleroma instances properly sometimes. I’m not sure but give that relay a try if you wanna test it, it works for me and others :)

Appreciate you guys helping with this ❤️

**Comment by Gargron** [comment]
Right, the abuse filter added in 2.7.2 did not foresee Announces from relays, since that's now how pub-relay works. But there's nothing wrong with doing it via Announces, so I will submit a fix.

**Comment by kaniini** [comment]
Thanks @Gargron for the quick fix!

**Comment by TheEpTic** [comment]
Thank you for the quick fix Gargron! I just manually applied it to my instance and it's perfect!

If anyone else wants to do the same, just apply the changes ^ to your local install and restart ❤️

**Comment by mahescho** [comment]
Thanks, works for me!

**Comment by TheEpTic** [comment]
I have similar errors but I feel like this is more of an issue with those sending the message and not mastodon itsself? I could be wrong but here's another error incase it helps:

```
Mar 28 09:48:10 mastodon bundle[27657]: 2019-03-28T09:48:10.410Z 27657 TID-oraylqlqd WARN: {"context":"Job raised exception","job":{"class":"ActivityPub::ProcessingWorker","args":[20,"{\"object\": \"https://toot.site/users/deathy/statuses/101827640522948188\", \"to\": [\"https://relay.mastodon.host/actor/followers\"], \"type\": \"Announce\", \"@context\": \"https://www.w3.org/ns/activitystreams\", \"id\": \"https://relay.mastodon.host/activities/68dab379-408a-4ba4-bfdc-ac54c37ef64c\", \"actor\": \"https://relay.mastodon.host/actor\"}",null],"retry":true,"queue":"default","backtrace":true,"jid":"02c78b1c1e79d9efca0c72c1","created_at":1553766490.2163653,"enqueued_at":1553766490.2165008},"jobstr":"{\"class\":\"ActivityPub::ProcessingWorker\",\"args\":[20,\"{\\\"object\\\": \\\"https://toot.site/users/deathy/statuses/101827640522948188\\\", \\\"to\\\": [\\\"https://relay.mastodon.host/actor/followers\\\"], \\\"type\\\": \\\"Announce\\\", \\\"@context\\\": \\\"https://www.w3.org/ns/activitystreams\\\", \\\"id\\\": \\\"https://relay.mastodon.host/activities/68dab379-408a-4ba4-bfdc-ac54c37ef64c\\\", \\\"actor\\\": \\\"https://relay.mastodon.host/actor\\\"}\",null],\"retry\":true,\"queue\":\"default\",\"backtrace\":true,\"jid\":\"02c78b1c1e79d9efca0c72c1\",\"created_at\":1553766490.2163653,\"enqueued_at\":1553766490.2165008}"}
Mar 28 09:48:10 mastodon bundle[27657]: 2019-03-28T09:48:10.410Z 27657 TID-oraylqlqd WARN: ActiveRecord::RecordInvalid: Validation failed: Uri has already been taken
Mar 28 09:48:10 mastodon bundle[27657]: 2019-03-28T09:48:10.410Z 27657 TID-oraylqlqd WARN: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:80:in `raise_validation_error'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:in `save!'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `block in save!'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:257:in `transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `save!'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:in `save!'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:53:in `create!'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity/create.rb:38:in `block in process_status'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/.rbenv/versions/2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity/create.rb:37:in `process_status'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity/create.rb:14:in `block in perform'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity/create.rb:7:in `perform'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/fetch_remote_status_service.rb:23:in `call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity.rb:159:in `fetch_remote_original_status'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity.rb:153:in `status_from_object'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/activitypub/activity/announce.rb:7:in `perform'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:43:in `process_item'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:34:in `block in process_items'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:34:in `reverse_each'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:34:in `each'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:34:in `map'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:34:in `process_items'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/services/activitypub/process_collection_service.rb:21:in `call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/workers/activitypub/processing_worker.rb:9:in `perform'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/app/lib/sidekiq_error_handler.rb:5:in `call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:23:in `call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
Mar 28 09:48:10 mastodon bundle[27657]: /home/cloutflare/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'

```

**Comment by cham2019** [comment]
Sorry to re-open this.  I am experiencing same thing.
I'tm trying to add c.im relay:

I have hundreds of these logs:

May  4 15:47:42 vm bundle[1935]: [a20] method=POST path=/inbox format=json controller=ActivityPub::InboxesController action=create **status=202** duration=11.25 view=0.00 db=1.06 key=https://relay.c.im/actor#main-key

May  4 15:47:42 vm bundle[835]: **Rejected Announce activity** https://relay.c.im/activities/3427e630-1309-4a24-a389-b976cd514aca from https://relay.c.im/actor

I can't get this relay to be enabled.  I remember it used to work before (when I had former version of Mastodon)

Now i am running the last version (4.1.2).  I opened ports 80,443 to that domain  relay.c.im, and I tested to see if i can call URL statuses or users from c.im and it worked. So, not sure why the relay can't get connected.
