### ISSUE TITLE
Enabling CDN_HOST in .env.production using Docker not working

### ISSUE THREAD

**Issue by sys0dm1n** [tootsuite/mastodon#1044]
[After creating account with the CDN enabled, everything works fine, once I activate my account as admin and relogin I get a 500 error:
```
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]   User Load (2.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]   Account Load (1.7ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]   Doorkeeper::Application Load (1.0ms)  SELECT  "oauth_applications".* FROM "oauth_applications" WHERE "oauth_applications"."superapp" = $1 ORDER BY "oauth_applications"."id" ASC LIMIT $2  [["superapp", true], ["LIMIT", 1]]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]    (0.3ms)  BEGIN
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]   Doorkeeper::AccessToken Exists (1.5ms)  SELECT  1 AS one FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "12ff4d3707bc6cb1349924ccd665ad2c51be748f2cc6eaeb45d97teg57f7f6ad"], ["LIMIT", 1]]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]   SQL (0.8ms)  INSERT INTO "oauth_access_tokens" ("resource_owner_id", "token", "created_at", "scopes") VALUES ($1, $2, $3, $4) RETURNING "id"  [["resource_owner_id", 1], ["token", "12ff4d3707bc6cb1349924ccd665ad2c51be748f2cc6eaeb45d97teg57f7f6ad"], ["created_at", 2017-04-06 09:19:23 UTC], ["scopes", "read write follow"]]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]    (53.2ms)  COMMIT
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]   Web::Setting Load (0.8ms)  SELECT  "web_settings".* FROM "web_settings" WHERE "web_settings"."user_id" = 1 LIMIT $1  [["LIMIT", 1]]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: undefined method `protocol' for nil:NilClass' duration=149.59 view=0.00 db=74.98
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] ActionView::Template::Error (undefined method `protocol' for nil:NilClass):
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]     1: object false
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]     2:
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]     3: node(:meta) do
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]     4:   {
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]     5:     access_token: @token,
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]     6:     locale: I18n.locale,
[e250e0dc-4609-42a7-86cb-d110e15fb7e6]
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] app/helpers/routing_helper.rb:15:in `full_asset_url'
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] app/views/api/v1/accounts/show.rabl:7:in `block in eval_source'
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] app/views/home/initial_state.json.rabl:3:in `_app_views_home_initial_state_json_rabl__2640368252757860549_47188558647720'
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] app/views/home/index.html.haml:4:in `block in _app_views_home_index_html_haml___1091379632994850368_47188559182200'
[e250e0dc-4609-42a7-86cb-d110e15fb7e6] app/views/home/index.html.haml:1:in `_app_views_home_index_html_haml___1091379632994850368_47188559182200'
```
 Thank you for your support].

* * * *

- [yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by josh04** [comment]
You might need to add http:// or https:// to your CDN_HOST. 

Beyond that, static content paths were incorrect so I tried changing line 15 in routing_helper.rb to
`    Rails.configuration.x.use_s3 ? source : Rails.configuration.action_controller.asset_host ? ActionController::Base.helpers.asset_url(source) : File.join(root_url, ActionController::Base.helpers.asset_url(source))`
but past that I had XSS violation difficulties and shelved using CDN_HOST for now, so I can't help further.

**Comment by hrefhref** [comment]
I'm using CDN_HOST and I get incorrect paths for avatars too. All other assets seems to works fine.

**Comment by ashfurrow** [comment]
It [sounds like](https://github.com/tootsuite/mastodon/pull/1459#issuecomment-295903259) this issue was fixed in 1.2.2. I'm going to close the issue, but feel free to re-open if it's still not working for you.

**Comment by mikoim** [comment]
same issue happened to me.
In my environment, mastodon does not work without https://github.com/tootsuite/mastodon/pull/1459 and protocol prefix in CDN_HOST.

Mastodon 1.3.2

```
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: undefined method `protocol' for nil:NilClass' duration=20.01 view=0.00 db=5.43
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]   
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] ActionView::Template::Error (undefined method `protocol' for nil:NilClass):
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]     1: object false
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]     2: 
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]     3: node(:meta) do
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]     4:   {
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]     5:     streaming_api_base_url: @streaming_api_base_url,
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]     6:     access_token: @token,
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21]   
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] app/helpers/routing_helper.rb:15:in `full_asset_url'
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] app/views/api/v1/accounts/show.rabl:7:in `block in eval_source'
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] app/views/home/initial_state.json.rabl:3:in `_app_views_home_initial_state_json_rabl___1656391612272861884_47356972264220'
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] app/views/home/index.html.haml:2:in `block in _app_views_home_index_html_haml__22268551354754501_47356955605140'
web_1        | [895b388e-a955-4bcc-8c73-592517b4ef21] app/views/home/index.html.haml:1:in `_app_views_home_index_html_haml__22268551354754501_47356955605140'
```

**Comment by josh04** [comment]
Sorry, can confirm, problem wasn't fixed for me either.

**Comment by ashfurrow** [comment]
Yikes, thanks for letting us know. I'll re-open the issue; any further details you can provide?

**Comment by Gargron** [comment]
It looks like CDN_HOST will need the protocol part going forward.

**Comment by mikoim** [comment]
#1459 or #2741 fixed this issue. In any case protocol in CDN_HOST is needed.

**Comment by ashfurrow** [comment]
Okay, sounds like this has been resolved. Okay to close?

**Comment by mikoim** [comment]
I agree.

@josh04 @sys0dm1n @hrefhref What do you think?

**Comment by josh04** [comment]
I haven't updated yet but from looking at the change I expect it will resolve the problem for me. I'll confirm here when I do.
