### ISSUE TITLE
Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2

### ISSUE THREAD

**Issue by savaricous** [tootsuite/mastodon#1045]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart mastodon@
6 info start mastodon@
7 verbose unsafe-perm in lifecycle true
8 info mastodon@ Failed to exec start script
9 verbose stack Error: mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid mastodon@
11 verbose cwd /home/mastodon/live
12 error Linux 4.8.0-45-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
14 error node v4.8.2
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
17 error Exit status 1
18 error Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
18 error This is most likely a problem with the mastodon package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel-node ./streaming/index.js --presets es2015,stage-2
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs mastodon
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls mastodon
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by mhellwig** [comment]
yep, also getting this error

**Comment by savaricous** [comment]
Anyone have an idea how to fix this? I tried and failed.

**Comment by mint7** [comment]
Same error. 

In addition : status mastodon-web.service -l 

```
Apr 07 14:58:05 Mastodon1 bundle[1154]: [8529e630-251f-4639-8353-cafb9eae610c] RuntimeError (Name or service not known):
Apr 07 14:58:05 Mastodon1 bundle[1154]: [8529e630-251f-4639-8353-cafb9eae610c]
Apr 07 14:58:05 Mastodon1 bundle[1154]: [8529e630-251f-4639-8353-cafb9eae610c] app/models/setting.rb:14:in `[]'
Apr 07 14:58:05 Mastodon1 bundle[1154]: [8529e630-251f-4639-8353-cafb9eae610c] app/controllers/about_controller.rb:7:in `index'
Apr 07 14:58:05 Mastodon1 bundle[1154]: [813cc46f-e3db-426b-92da-9bfafc4b2dcb] method=GET path=/about format=html controller=AboutController action=index status=500 error='RuntimeError: Name...9.79 view=0.00
Apr 07 14:58:05 Mastodon1 bundle[1154]: [813cc46f-e3db-426b-92da-9bfafc4b2dcb]
Apr 07 14:58:05 Mastodon1 bundle[1154]: [813cc46f-e3db-426b-92da-9bfafc4b2dcb] RuntimeError (Name or service not known):
Apr 07 14:58:05 Mastodon1 bundle[1154]: [813cc46f-e3db-426b-92da-9bfafc4b2dcb]
Apr 07 14:58:05 Mastodon1 bundle[1154]: [813cc46f-e3db-426b-92da-9bfafc4b2dcb] app/models/setting.rb:14:in `[]'
Apr 07 14:58:05 Mastodon1 bundle[1154]: [813cc46f-e3db-426b-92da-9bfafc4b2dcb] app/controllers/about_controller.rb:7:in `index'
```

**Comment by Erreur32** [comment]
Same here :(

 logtail npm-debug.log

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.8.6
3 info using node@v5.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mastodon@~prestart: mastodon@
6 silly lifecycle mastodon@~prestart: no script for prestart, continuing
7 info lifecycle mastodon@~start: mastodon@
8 verbose lifecycle mastodon@~start: unsafe-perm in lifecycle true
9 verbose lifecycle mastodon@~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mastodon/live/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle mastodon@~start: CWD: /home/mastodon/live
11 silly lifecycle mastodon@~start: Args: [ '-c',
11 silly lifecycle   'babel-node ./streaming/index.js --presets es2015,stage-2' ]
12 silly lifecycle mastodon@~start: Returned: code: 1  signal: null
13 info lifecycle mastodon@~start: Failed to exec start script
14 verbose stack Error: mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid mastodon@
16 verbose cwd /home/mastodon/live
17 error Linux 3.14.32-xxxx-std-ipv6-64
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
19 error node v5.11.1
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
22 error Exit status 1
23 error Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mastodon package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node ./streaming/index.js --presets es2015,stage-2
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mastodon
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mastodon
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
` mastodon-streaming.service start request repeated too quickly, refusing to start.
  Failed to start mastodon-streaming.
  Unit mastodon-streaming.service entered failed state.

`

**Comment by mint7** [comment]
fixed by :
`REDIS_HOST=127.0.0.1`

**Comment by Erreur32** [comment]
Not working for me ...

**Comment by simbalion** [comment]
I'm having the same issue, neither of the recommended solutions helped, npm-debug.log output is slightly different:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart mastodon@
6 info start mastodon@
7 verbose unsafe-perm in lifecycle true
8 info mastodon@ Failed to exec start script
9 verbose stack Error: mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid mastodon@
11 verbose cwd /home/mastodon/live
12 error Linux 3.16.0-4-amd64
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
14 error node v4.8.2
15 error npm  v2.15.11
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
20 error spawn ENOENT
21 error Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
21 error This is most likely a problem with the mastodon package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     babel-node ./streaming/index.js --presets es2015,stage-2
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs mastodon
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls mastodon
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
