### ISSUE TITLE
Error 500 on image upload after 2.8.2 upgrade - NoMethodError (undefined method `blurhash=' ...

### ISSUE THREAD

**Issue by kevinflo** [tootsuite/mastodon#10725]
Upon users uploading an image as part of a toot they see error 500. When I check the logs I'm seeing
```
[b085be6c-7ed5-42c0-bf79-cda777a15ef7] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=500 error='NoMethodError: undefined method `blurhash=' for #<MediaAttachment:0x00007f20af375f10>' duration=500.97 view=0.00 db=0.84
[b085be6c-7ed5-42c0-bf79-cda777a15ef7]   
[b085be6c-7ed5-42c0-bf79-cda777a15ef7] NoMethodError (undefined method `blurhash=' for #<MediaAttachment:0x00007f20af375f10>):
[b085be6c-7ed5-42c0-bf79-cda777a15ef7]   
[b085be6c-7ed5-42c0-bf79-cda777a15ef7] lib/paperclip/blurhash_transcoder.rb:11:in `make'
[b085be6c-7ed5-42c0-bf79-cda777a15ef7] app/controllers/api/v1/media_controller.rb:13:in `create'

```

Is anyone else seeing this issue or does anyone know of a fix?

**Comment by kevinflo** [comment]
did --force-recreate on the docker up and it worked, no idea why
