### ISSUE TITLE
Problem using docker-compose on tag v1.1

### ISSUE THREAD

**Issue by TristanCP** [tootsuite/mastodon#1153]
I'm trying to run "docker-compose up -d" on tag v1.1

It's going good until this happens (tons of warnings, then errors) :

```
yarn install v0.21.3
warning mastodon: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning store@1.3.20: The engine "browser" appears to be invalid.
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "chai-enzyme@0.6.1" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
warning "react-decoration@1.4.0" has incorrect peer dependency "react-addons-perf@15.3.2".
warning "react-redux-loading-bar@2.4.1" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0".
warning "react-storybook-addon-intl@0.1.0" has incorrect peer dependency "@kadira/storybook@^1.35.1".
[4/4] Building fresh packages...
error /mastodon/node_modules/utf-8-validate: Command failed.
Exit code: 1
Command: sh
Arguments: -c prebuild-install || node-gyp rebuild
Directory: /mastodon/node_modules/utf-8-validate
Output:
prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds/utf-8-validate-v3.0.1-node-v48-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-websockets-utf-8-validate-releases-download-v3.0.1-utf-8-validate-v3.0.1-node-v48-linux-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/utf-8-validate/releases/download/v3.0.1/utf-8-validate-v3.0.1-node-v48-linux-x64.tar.gz
prebuild-install WARN install socket hang up
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.7.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (/usr/lib/node_modules/yarn/node_modules/node-gyp/lib/configure.js:482:19)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/yarn/node_modules/node-gyp/lib/configure.js:396:16)
gyp ERR! stack     at F (/usr/lib/node_modules/yarn/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/yarn/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/yarn/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/yarn/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/yarn/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.8.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mastodon/node_modules/utf-8-validate
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c export http_proxy=http://$proxy_ip:3128  && BUILD_DEPS="     postgresql-dev     libxml2-dev     libxslt-dev     build-base"  && apk -U upgrade && apk add     $BUILD_DEPS     nodejs     libpq     libxml2     libxslt     ffmpeg     file     imagemagick  && npm install -g npm@3 && npm install -g yarn  && bundle install --deployment --without test development  && yarn  && npm cache clean  && apk del $BUILD_DEPS  && rm -rf /tmp/* /var/cache/apk/*' returned a non-zero code: 1
```
* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by TristanCP** [comment]
I'm behind a company proxy which I've set in http_proxy inside Dockerfile.

Now, I've just added :
```
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```
with proper values and Dockerfile formatting in case env vars are not enough for npm.

with these settings, everything works fine, so I guess you can close my issue.
