### ISSUE TITLE
mastodon-web RuntimeError related to settings cache

### ISSUE THREAD

**Issue by woganmay** [tootsuite/mastodon#1157]
I'm trying to start the mastodon-web service (as defined in the Production guide readme), after following all of the steps. Log:

    [28537] Puma starting in cluster mode...
    [28537] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
    [28537] * Min threads: 5, max threads: 5
    [28537] * Environment: production
    [28537] * Process workers: 2
    [28537] * Preloading application
    Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
    [28537] * Listening on tcp://0.0.0.0:3000
    [28537] Use Ctrl-C to stop
    [28537] - Worker 0 (pid: 28594) booted, phase: 0
    [28537] - Worker 1 (pid: 28604) booted, phase: 0
    [0885ac6e-0c89-4a51-91ea-e682fbd746a0] method=GET path=/about format=html controller=AboutController action=index status=500 error='RuntimeError: Name or service not known' duration=103.76 view=0.00
    [0885ac6e-0c89-4a51-91ea-e682fbd746a0]
    [0885ac6e-0c89-4a51-91ea-e682fbd746a0] RuntimeError (Name or service not known):
    [0885ac6e-0c89-4a51-91ea-e682fbd746a0]
    [0885ac6e-0c89-4a51-91ea-e682fbd746a0] app/models/setting.rb:14:in `[]'
    [0885ac6e-0c89-4a51-91ea-e682fbd746a0] app/controllers/about_controller.rb:7:in `index'

Am I missing a Gem to make `Rails.cache` work?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by woganmay** [comment]
My bad! Turns out I did not read the instructions too thoroughly. I had `REDIS_HOST=redis` instead of `REDIS_HOST=localhost` in my `.env.production`
