### ISSUE TITLE
pam authentication fails at build step

### ISSUE THREAD

**Issue by ear7h** [tootsuite/mastodon#11653]
### Expected behaviour

Setting `PAM_ENABLED=true` shouldn't cause any errors.

### Actual behaviour

Running `RAILS_ENV=production bin/rails assets:precompile` or `service mastodon-web restart` fails with the following error when `PAM_ENABLED=true`

```text
Aug 24 22:35:42 ear7h bundle[23342]: [23342] * Preloading application
Aug 24 22:35:44 ear7h bundle[23342]: [23342] ! Unable to load application: NoMethodError: undefined method `usernamefield=' for Devise:Module
Aug 24 22:35:44 ear7h bundle[23342]: bundler: failed to load command: puma (/home/mastodon/live/vendor/bundle/ruby/2.6.0/bin/puma)
Aug 24 22:35:44 ear7h bundle[23342]: NoMethodError: undefined method `usernamefield=' for Devise:Module
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/config/initializers/devise.rb:348:in `block in <top (required)>'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/devise-4.6.2/lib/devise.rb:311:in `setup'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/config/initializers/devise.rb:72:in `<top (required)>'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:415:in `call'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `call'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
Aug 24 22:35:44 ear7h bundle[23342]:   /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
Aug 24 22:35:44 ear7h systemd[1]: mastodon-web.service: Main process exited, code=exited, status=1/FAILURE
Aug 24 22:35:44 ear7h systemd[1]: mastodon-web.service: Unit entered failed state.
Aug 24 22:35:44 ear7h systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
Aug 24 22:35:45 ear7h systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
```

### Steps to reproduce the problem

1. Install mastodon according to [these instructions](https://docs.joinmastodon.org/administration/installation/)
2. add the following lines to `.env.production`
```env
PAM_ENABLED=false
PAM_DEFAULT_SERVICE=rpam
PAM_CONTROLED_SERVICE=rpam
```

### Specifications
```text
$ uname -a
Linux ear7h 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
```

mastodon v2.9.3 06f906acace5770fc10f333a203b036c5b72c849

### personal notes

It looks like the problem is in this file.

https://github.com/tootsuite/mastodon/blob/06f906acace5770fc10f333a203b036c5b72c849/config/initializers/devise.rb#L346-L354

I tried commenting out these lines and it eventually got to an error `NameError: uninitialized constant Devise::Models::PamAuthenticatable`. I'm not familiar with ruby/rails, and a grep search wasn't very helpful at finding what the `config` variable is or where it really comes from. I'm willing to send in a PR but I just don't know where start.

**Comment by ixs** [comment]
To add a bit further information as I stumbled over the same problem trying to actually use pam support:

The error message `NoMethodError: undefined method `usernamefield=' for Devise:Module` is caused by setting `ENABLE_PAM=true` while not having https://github.com/devkral/devise_pam_authenticatable2 installed as a gem.

The problem is caused by the default build (as well as the Dockerfile) not installing the required gem by default which causes the error message to pop up when enabling pam support.

The corect way of enabling PAM support is to install the gem with by executing `bundle config with 'pam_authentication'` *before* running `bundle install`. This also requires an installation of `libpam-devel` or `pam-devel` (depending on OS) at buildtime and an installed `pam` or `libpam` package at runtime.

I'm sure this error could be caught in a better way, but here's at least some info to help people stumbling over the same problem.
