### ISSUE TITLE
"Update profile" on remotly deleted account causes 500 error

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#11865]
### Expected behaviour

Update profile on remotely deleted user will be delete a record due to 410 gone
\+ Maybe delete suspend because it is deleted account?

### Actual behaviour

It causes 500 error and logs are here
```
2019-09-16T15:30:20.345078781Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] method=POST path=/admin/accounts/46626/redownload format=html controller=Admin::AccountsController action=redownload status=500 e
rror='Mastodon::UnexpectedResponseError: https://pawoo.net/users/Naomii39.atom returned code 410' duration=109.60 view=0.00 db=2.44                                                                                
2019-09-16T15:30:20.345690717Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf]                                                                                                                                  
2019-09-16T15:30:20.345791888Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] Mastodon::UnexpectedResponseError (https://pawoo.net/users/Naomii39.atom returned code 410):                                     
2019-09-16T15:30:20.345832565Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf]                                                                                                                                  
2019-09-16T15:30:20.345917747Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:196:in `block in atom_body'                                                              
2019-09-16T15:30:20.345922717Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/lib/request.rb:59:in `perform'                                                                                               
2019-09-16T15:30:20.345925687Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:195:in `atom_body'                                                                       
2019-09-16T15:30:20.345928053Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:210:in `atom'                                                                            
2019-09-16T15:30:20.345930320Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:175:in `canonical_uri'                                                                   
2019-09-16T15:30:20.345932737Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:85:in `ostatus_ready?'                                                                   
2019-09-16T15:30:20.345935020Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:77:in `links_missing?'                                                                   
2019-09-16T15:30:20.345937311Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/services/resolve_account_service.rb:51:in `call'                                                                             
2019-09-16T15:30:20.345939565Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/controllers/admin/accounts_controller.rb:78:in `redownload'                                                                  
2019-09-16T15:30:20.345941922Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/controllers/concerns/localized.rb:18:in `block in set_locale'                                                                
2019-09-16T15:30:20.345944186Z app[web.1]: [3aadf807-a6a8-40d1-a048-3672a5022cdf] app/controllers/concerns/localized.rb:17:in `set_locale'                                                                         

```

### Steps to reproduce the problem

Press "Update profile" button on admin page of remotely deleted user

### Specifications

On Mastodon version 2.9.3

**Comment by Gargron** [comment]
Fixed by #11869, I think
