### ISSUE TITLE
Web interface crashes in google-chrome when scrolling

### ISSUE THREAD

**Issue by 1183519e** [tootsuite/mastodon#12195]
### Expected behaviour

I can scroll through the columns of the web interface.

### Actual behaviour

In google chrome 76.0.3809.132, mastodon v3.0.1 crashed reproducible after scrolling one column to the point where I guess the next toots would be loaded.

### Steps to reproduce the problem

Start Chrome, visit the instance I'm using, scroll.

### Specifications

Error stack as offered by the crash notice:
```
TypeError: Cannot read property 'getWrappedInstance' of null
    at https://chaos.social/packs/js/application-225ec106883e47522fe3.chunk.js:1:31329
    at pi (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:75173)
    at mi (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:75715)
    at vi (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:77391)
    at zi (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:81515)
    at Ki (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:85080)
    at https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:98357
    at Object.t.unstable_runWithPriority (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:43:3200)
    at Ns (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:98291)
    at Fs (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:98067)

```

**Comment by ThibG** [comment]
Is there more information in the browser console (ctrl+shift+i)? Are you using single-column mode or the “advanced interface” (multiple columns)?

**Comment by 1183519e** [comment]
Advanced/multiple columns.

Console output (all but the bottom two are yellow, bottom two are red):
`bootstrap:149 A preload for 'https://chaos.social/packs/js/features/compose-321858840f7f2ff22149.chunk.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
i.e @ bootstrap:149

bootstrap:149 A preload for 'https://chaos.social/packs/js/features/home_timeline-f548818a36b8595c2eae.chunk.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
i.e @ bootstrap:149

bootstrap:149 A preload for 'https://chaos.social/packs/js/features/notifications-ce60e15a065e99f905cf.chunk.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
i.e @ bootstrap:149

bootstrap:149 A preload for 'https://chaos.social/packs/js/features/getting_started-1a76e0ce8057e14e0e5c.chunk.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
i.e @ bootstrap:149

The resource https://chaos.social/packs/js/features/notifications-ce60e15a065e99f905cf.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

The resource https://chaos.social/packs/js/features/getting_started-1a76e0ce8057e14e0e5c.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

The resource https://chaos.social/packs/js/features/compose-321858840f7f2ff22149.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

The resource https://chaos.social/packs/js/features/home_timeline-f548818a36b8595c2eae.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

2react-dom.production.min.js:4408 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at vi (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:77668)
    at zi (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:81515)
    at Ki (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:85080)
    at https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:98357
    at Object.t.unstable_runWithPriority (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:43:3200)
    at Ns (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:98291)
    at Fs (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:98067)
    at Ps (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:97412)
    at Ss (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:96433)
    at es (https://chaos.social/packs/js/common-0b42e33e5c2d82f113f9.js:34:95300)
di @ react-dom.production.min.js:4408

react-dom.production.min.js:4408 TypeError: Cannot read property 'getWrappedInstance' of null
    at index.js:167
    at pi (react-dom.production.min.js:4419)
    at mi (react-dom.production.min.js:4511)
    at vi (react-dom.production.min.js:4655)
    at zi (react-dom.production.min.js:4914)
    at Ki (react-dom.production.min.js:5104)
    at react-dom.production.min.js:5975
    at Object.t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ns (react-dom.production.min.js:5974)
    at Fs (react-dom.production.min.js:5958)`
