### ISSUE TITLE
Issue with using S3/Minio for follow/block imports

### ISSUE THREAD

**Issue by JantsoP** [tootsuite/mastodon#1229]
So i have found this issue last night. If you are using S3 or Minio as your asset manager, Follow/Block import wont work at all. Images etc works fine no issue there.

So the server takes the file and i can see it in my bucket BUT the Mastodon wont see it. Sidekiq just reports the same error over and over again

> 2017-04-08T05:20:30.975Z1 TID-29mjprll4 WARN: Errno::ENOENT: No such file or directory @ rb_sysopen - /imports/data/000/000/016/original/follows.csv
2017-04-08T05:20:30.975Z 1 TID-29mjprll4 WARN: /usr/local/lib/ruby/2.3.0/csv.rb:1265:in `initialize'

I did some changes to the import_worker.rb with help of ninjawedding on Discort and ran changed values to `CSV.foreach(open(import.data.path))` but then i get error 

> 2017-04-08T05:23:17.447Z 1 TID-144ct29fo WARN: Errno::ENOENT: No such file or directory @ rb_sysopen - /imports/data/000/000/017/original/follows.csv
2017-04-08T05:23:17.447Z 1 TID-144ct29fo WARN: /usr/local/lib/ruby/2.3.0/open-uri.rb:37:in `initialize'

I then decided to take out the Minio config and it started working fine. But when i take it back, it will break. I have spent hours on this and nothing seem to work so any help would be nice :)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JantsoP** [comment]
So me and @Gargron managed to get somewhere. If we change the import.data.path to import.data url it will then try and get from the URL, but with same result :/

**Comment by JantsoP** [comment]
So thanks to @Gargron , we managed to fix it.

How to fix it (docker images atm)
1. Stop your instance (docker-compose stop)
2. Do git pull
3. Edit file in app/workers/import.worker.rb
4. Change lines `CSV.foreach(import.data.path) do |row|` to `CSV.new(open(import.data.url)).each do |row|`
5. do docker-compose build and wait
6. do docker-compose up -d and see how the import works now with S3 and Minio set ups :)
