### ISSUE TITLE
Relocation error withing node streaming service

### ISSUE THREAD

**Issue by BastienDurel** [tootsuite/mastodon#12656]
Hello,

I upgraded my mastodon box, and the streaming service does not run anymore (npm run start crashes)

### Expected behaviour

npm run start should run a long lasting service

### Actual behaviour

npm run start crashes on startup

### Steps to reproduce the problem

running ```/usr/bin/npm run start``` leads to a crash

### Specifications

I'm running v3.0.1 on Alpine 3.11, with node@v12.14.0 and npm@6.13.4

I've erased my node_modules and ran ```npm install --production```

The complete error is the following : 
```
mastodon:~/live$ /usr/bin/npm run start

> @tootsuite/mastodon@ start /home/mastodon/live
> node ./streaming/index.js

/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js:34
        throw e.message = e.message + " check './node_modules/@clusterws/cws/build_log.txt' for post install build logs", 
        ^

Error: Error relocating /home/mastodon/live/node_modules/@clusterws/cws/dist/cws_linux_72.node: _ZN4node6AssertEPA4_KPKc: symbol not found check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js:32:16
    at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js:37:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tootsuite/mastodon@ start: `node ./streaming/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tootsuite/mastodon@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Here is the build log : [build_log.txt](https://github.com/tootsuite/mastodon/files/3987987/build_log.txt)
And there the nodejs debug log : [2019-12-20T10_42_10_887Z-debug.log](https://github.com/tootsuite/mastodon/files/3987995/2019-12-20T10_42_10_887Z-debug.log)

**Comment by Gargron** [comment]
Try running `yarn install` again to recompile that dependency, it looks like maybe you upgraded system libraries and now dynamic links are broken in some binary.

**Comment by BastienDurel** [comment]
I ran it too, but before purging node_modules.

Re-running it does not help though : 
```
mastodon:~/live$ yarn install
yarn install v1.19.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 83.97s.
mastodon:~/live$ /usr/bin/npm run start

> @tootsuite/mastodon@ start /home/mastodon/live
> node ./streaming/index.js

/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js:34
        throw e;
        ^

Error: Error relocating /home/mastodon/live/node_modules/@clusterws/cws/dist/cws_linux_72.node: _ZN4node6AssertEPA4_KPKc: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js:32:16
    at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js:36:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tootsuite/mastodon@ start: `node ./streaming/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tootsuite/mastodon@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mastodon/.npm/_logs/2019-12-20T11_35_30_385Z-debug.log

````

**Comment by BastienDurel** [comment]
Upgrading @clusterws/cws to 0.16.1 fixes the error
