### ISSUE TITLE
Announcements won't get live

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#12960]
Log:

```
sidekiq_1    | 2020-01-25T20:29:59.383Z 7 TID-ow0c5jgmj WARN: {"context":"Job raised exception","job":{"class":"PublishScheduledAnnouncementWorker","args":[7],"retry":true,"queue":"default","jid":"b5dbba43d093ec67e012037d","created_at":1579984199.3635542,"enqueued_at":1579984199.3636708},"jobstr":"{\"class\":\"PublishScheduledAnnouncementWorker\",\"args\":[7],\"retry\":true,\"queue\":\"default\",\"jid\":\"b5dbba43d093ec67e012037d\",\"created_at\":1579984199.3635542,\"enqueued_at\":1579984199.3636708}"}
sidekiq_1    | 2020-01-25T20:29:59.383Z 7 TID-ow0c5jgmj WARN: NameError: uninitialized constant PublishScheduledAnnouncementWorker
sidekiq_1    | Did you mean?  PublishScheduledStatusWorker
sidekiq_1    | 2020-01-25T20:29:59.383Z 7 TID-ow0c5jgmj WARN: /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:274:in `block in constantize'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:271:in `each'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:271:in `inject'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:271:in `constantize'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:133:in `block (5 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:43:in `block in call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:42:in `call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Happening on `90b13ffd009a431dbe98c37bc92ee59a6f0535f2`

**Comment by Gargron** [comment]
Restart Sidekiq, probably

**Comment by koyuawsmbrtn** [comment]
> Restart Sidekiq, probably

I'm running Mastodon over `docker-compose` and Sidekiq is hidden away from the admin panel. It just says 404.

**Comment by koyuawsmbrtn** [comment]
Issue seems to be fixed when using the right docker image and running the new database migrations.
