### ISSUE TITLE
Sidekiq graph unreachable 

### ISSUE THREAD

**Issue by dadall** [tootsuite/mastodon#12998]
### Expected behaviour

Reach https://instance.tld/sidekiq

### Actual behaviour

> We're sorry, but something went wrong on our end.

### Specifications

Running Mastodon 3.1.0rc1 on Debian Stretch. Upgrade went fine, NodeJS 10.18

### Logs 

```
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be]
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] NoMethodError (undefined method `public_id' for #<String:0x00007f31e2015a20>
 Did you mean?  public_send):
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be]
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/session/cookie_store.rb:111:in `write_session'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:391:in `commit_session'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:271:in `context'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:263:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:19:in `block in call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:19:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `block in call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:28:in `tagged'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:71:in `tagged'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:524:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
 [b8b3f9aa-5233-4a5f-856b-c14321d0a0be] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by angristan** [comment]
Same here:

```
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2]
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] NoMethodError (undefined method `public_id' for #<String:0x00007f578f3b8cb8>
Jan 28 19:28:51 masto bundle[2336]: Did you mean?  public_send):
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2]
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/session/cookie_store.rb:111:in `write_session'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:391:in `commit_session'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:271:in `context'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:263:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:19:in `block in call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:19:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `block in call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:28:in `tagged'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:71:in `tagged'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/static.rb:127:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:524:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
Jan 28 19:28:51 masto bundle[2336]: [aa33ac96-3748-4b77-9d71-fde42f3f22f2] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by dadall** [comment]
Update : sidekiq works as expected. This is just an issue about this web view.

**Comment by ThibG** [comment]
Duplicate of #12698, which offers a workaround

Not sure how we can avoid having this issue at all :/

**Comment by angristan** [comment]
Thanks. Clearing cookies and logging-in again indeed fixes it. It's not a major hassle but one can't guess it's a session issue 🧐

**Comment by dadall** [comment]
Well : I think a warming can be added to the Upgrade notes :) 

Thanks for the quick answer @ThibG.

I close the issue.
