### ISSUE TITLE
Requesting backup for heavy account fails

### ISSUE THREAD

**Issue by tcitworld** [tootsuite/mastodon#13123]
User with 283 Mo of media files requests a backup.

The BackupWorker is seen as active in sidekiq jobs, but then goes to the failed jobs with the following error:
```
NoMethodError: undefined method `bytesize' for nil:NilClass
```

The database entry in the `backups` table isn't updated after the error.

Backups are successfully run with an user with 151Mo of media files and less.

Note: Media files are uploaded on a S3-compatible storage.

### Expected behaviour

Ability to backup user account

### Actual behaviour

User never receives backup link

### Specifications

Mastodon 3.1.1

**Comment by ThibG** [comment]
Do you have the full backtrace? The only `bytesize` calls I can see in the codebase should definitely not be called on `nil`…

**Comment by tcitworld** [comment]
Sorry, forgot to add that logs (sidekiq & mastodon) didn't show anything at any step of the process.

I have `RAILS_LOG_LEVEL=error` and can lower it if you think it can show something more, as well as adding a few logging calls here and there.

**Comment by ThibG** [comment]
I don't think lowering the loglevel would bring any more info, unfortunately.
Wasn't there at least part of a stack trace where you got “NoMethodError: undefined method `bytesize' for nil:NilClass”?

**Comment by tcitworld** [comment]
Unfortunately that's all the Error column in Sidekiq UI had. Maybe there's more if I try to inspect data directly in Redis, but I don't know about this either.

**Comment by Gargron** [comment]
@tcitworld If you click on the job there should be a stacktrace

**Comment by tcitworld** [comment]
Indeed, missed it, sorry about this. Seems like an issue with some media attachment name.

```
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/package/tar_writer.rb:312:in `split_name'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/package/tar_writer.rb:216:in `add_file_simple'
/home/mastodon/live/app/services/backup_service.rb:163:in `download_to_tar'
/home/mastodon/live/app/services/backup_service.rb:69:in `block (2 levels) in dump_media_attachments!'
/home/mastodon/live/app/services/backup_service.rb:68:in `each'
/home/mastodon/live/app/services/backup_service.rb:68:in `block in dump_media_attachments!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/batches.rb:222:in `loop'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/batches.rb:222:in `in_batches'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/home/mastodon/live/app/services/backup_service.rb:67:in `dump_media_attachments!'
/home/mastodon/live/app/services/backup_service.rb:47:in `block (3 levels) in build_archive!'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/package/tar_writer.rb:86:in `new'
/home/mastodon/live/app/services/backup_service.rb:46:in `block (2 levels) in build_archive!'
/home/mastodon/live/app/services/backup_service.rb:45:in `wrap'
/home/mastodon/live/app/services/backup_service.rb:45:in `block in build_archive!'
/home/mastodon/live/app/services/backup_service.rb:44:in `open'
/home/mastodon/live/app/services/backup_service.rb:44:in `build_archive!'
/home/mastodon/live/app/services/backup_service.rb:15:in `call'
/home/mastodon/live/app/workers/backup_worker.rb:21:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.18/lib/sidekiq_unique_jobs/server/middleware.rb:29:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:164:in `block in process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:109:in `local'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:43:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/reloader.rb:73:in `block in wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.1/lib/active_support/reloader.rb:72:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:42:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by ThibG** [comment]
ok it seems like there is a media attachment that for some reason doesn't have a file attached
not sure how that could occur, but does the following patch fix anything?

```patch
diff --git a/app/services/backup_service.rb b/app/services/backup_service.rb
index d1090dff1..736da15d1 100644
--- a/app/services/backup_service.rb
+++ b/app/services/backup_service.rb
@@ -66,6 +66,7 @@ class BackupService < BaseService
   def dump_media_attachments!(tar)
     MediaAttachment.attached.where(account: account).reorder(nil).find_in_batches do |media_attachments|
       media_attachments.each do |m|
+        next unless m.file && m.file.path
         download_to_tar(tar, m.file, m.file.path)
       end
 
```

**Comment by tcitworld** [comment]
Thanks, the user confirmed this fixes it indeed.
