### ISSUE TITLE
Search for "@xyz" 500s

### ISSUE THREAD

**Issue by snarfed** [tootsuite/mastodon#13150]
Discovered last October, [discussed with @ashfurrow et al on this small thread on mastodon.technology.](https://mastodon.technology/@snarfed/102973956125353721) Still happens, so I figured I'd file it. Thanks in advance!

### Expected behaviour

Returns search results

### Actual behaviour

HTTP 500 error. I haven't yet stood up a local Mastodon instance of my own to get logs, but that would probably be the next step.

### Steps to reproduce the problem

Enter `"@xyz"` in the search box and press enter. You can replace `xyz` with anything, as long as it's at least one character long.

### Specifications

Reproduced on three v3.1.1 instances: mastodon.technology, mastodon.art, and mas.to.

I'm on Firefox 73, Mac OS X 10.15.3, but I doubt anything client side is related.

Thanks in advance for looking!

**Comment by SuperSandro2000** [comment]
Can't confirm on my instance.

**Comment by ykzts** [comment]
```plain
[71802401-d2d1-489f-a3c5-9bbb2d41356d] method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=500 error='Addressable::URI::InvalidURIError: Invalid character in host: 'ykzts"'' duration=7.15 view=0.00 db=2.37
[71802401-d2d1-489f-a3c5-9bbb2d41356d]   
[71802401-d2d1-489f-a3c5-9bbb2d41356d] Addressable::URI::InvalidURIError (Invalid character in host: 'ykzts"'):
[71802401-d2d1-489f-a3c5-9bbb2d41356d]   
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/lib/tag_manager.rb:21:in `normalize_domain'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/resolve_account_service.rb:71:in `process_options!'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/resolve_account_service.rb:19:in `call'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/account_search_service.rb:32:in `exact_match'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/account_search_service.rb:22:in `search_service_results'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/account_search_service.rb:14:in `call'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/search_service.rb:28:in `perform_accounts_search!'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/search_service.rb:18:in `block in call'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/search_service.rb:12:in `tap'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/services/search_service.rb:12:in `call'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/controllers/api/v2/search_controller.rb:21:in `search_results'
[71802401-d2d1-489f-a3c5-9bbb2d41356d] app/controllers/api/v2/search_controller.rb:14:in `index'
```

This Issue is reproduced on my server (v3.1.1). A bug that needs to be investigated.

**Comment by ThibG** [comment]
This is caused by any query string with a “@” and no “ ” to be passed as an acct: URI to resolve… I wonder what would be best between rejecting it outright, or only considering the part that matches `MENTION_RE`, for instance
