### ISSUE TITLE
tootctl media remove-orphans: TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#13168]
After processing a few hundred thousands media files, tootctl crashed:

```
bundler: failed to load command: bin/tootctl (bin/tootctl)--=---=---=---=---=---=---=---=---=-|  ETA: ??:??:??
TypeError: no implicit conversion of nil into String
  /home/mastodon/live/app/models/media_attachment.rb:180:in `extname'
  /home/mastodon/live/app/models/media_attachment.rb:180:in `variant?'
  /home/mastodon/live/lib/mastodon/media_cli.rb:91:in `block (2 levels) in remove_orphans'
  /home/mastodon/live/lib/mastodon/media_cli.rb:85:in `each'
  /home/mastodon/live/lib/mastodon/media_cli.rb:85:in `block in remove_orphans'
  /home/mastodon/live/lib/mastodon/media_cli.rb:69:in `loop'
  /home/mastodon/live/lib/mastodon/media_cli.rb:69:in `remove_orphans'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  bin/tootctl:5:in `<top (required)>'
```

Let me know if I can do anything to provide more information, like issuing a specific SQL query.

### Specifications

`v3.1.2`

**Comment by ThibG** [comment]
Could you try with #13168?

**Comment by angristan** [comment]
I edited `app/models/media_attachment.rb` to dump the variables in `variant?`.

The command fails when iterating on `file_file_name` being `nil` and `other_file_name` being `56f639dd0fb3f5ba.mp3`.

`56f639dd0fb3f5ba.mp3` is in my bucket, but not in the database.

**Comment by angristan** [comment]
With your diff, the file is removed:

```
Found and removed orphan: media_attachments/files/012/910/738/original/56f639dd0fb3f5ba.mp3
```
