### ISSUE TITLE
Error will occur when I use chrome translate

### ISSUE THREAD

**Issue by yeezylife** [tootsuite/mastodon#13325]
![无标题](https://user-images.githubusercontent.com/30175425/77825040-c929e380-7141-11ea-9681-28b05df75dc8.jpg)

Everytime I use translate on chrome，this will happen..

**Comment by yeezylife** [comment]
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.


Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at js (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1037183)
    at Du (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1056257)
    at t.unstable_runWithPriority (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1077368)
    at Xa (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002295)
    at Fu (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1054137)
    at wu (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1044456)
    at https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002586
    at t.unstable_runWithPriority (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1077368)
    at Xa (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002295)
    at Ja (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002531)


js (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1037183)
Du (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1056257)
t.unstable_runWithPriority (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1077368)
Xa (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002295)
Fu (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1054137)
wu (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1044456)
https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002586
t.unstable_runWithPriority (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1077368)
Xa (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002295)
Ja (https://static-cdn.mastodon.social/packs/js/common-cd5b39196fec993a0d0b.js:2:1002531)

**Comment by ThibG** [comment]
This is Google translate messing with the DOM.
Apparently it may be possible to workaround by adding classes so that only whitelisted leaf DOM nodes would be modified by Google translate: https://github.com/facebook/react/issues/11538#issuecomment-576315002
