### ISSUE TITLE
Scalingo setup: single user mode config results in successful install but fails with “we’re sorry, but something went wrong”

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#1332]
At the end of a successful single user mode Mastodon installation via the [Scalingo online setup form](https://my.scalingo.com/deploy?source=https://github.com/tootsuite/mastodon#master), the instance fails to load. Seems like what’s happening is that the page is trying to forward to the first account but there is no first account.

## Settings on Scalingo installation form:

![screen shot 2017-04-09 at 13 58 11](https://cloud.githubusercontent.com/assets/41798/24836760/449412dc-1d2d-11e7-90b6-09caab7ec804.png)

## Tail of the installation form log output (successful installation):

<img width="547" alt="screen shot 2017-04-09 at 14 00 59" src="https://cloud.githubusercontent.com/assets/41798/24836746/1247fa50-1d2d-11e7-9f95-029d34eb28d5.png">

## Error log

The error in the logs seems to be related to not having a username:

```
2017-04-09 12:48:13.335819671 +0200 CEST [postdeploy-5893]    (1.9ms)  COMMIT
2017-04-09 12:48:13.808622628 +0200 CEST [manager] container [postdeploy-5893] has stopped with exit code: 0
2017-04-09 12:48:58.086345989 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7]   Account Load (9.5ms)  SELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id" ASC LIMIT $1  [["LIMIT", 1]]
2017-04-09 12:48:58.102247679 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]' duration=197.37 view=0.00 db=41.30
2017-04-09 12:48:58.102787881 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7]
2017-04-09 12:48:58.102872672 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7] ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]):
2017-04-09 12:48:58.102917472 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7]
2017-04-09 12:48:58.102955594 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7] app/controllers/home_controller.rb:15:in `authenticate_user!'
2017-04-09 12:48:58.102997587 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7] app/controllers/concerns/localized.rb:24:in `block in set_locale'
2017-04-09 12:48:58.103034114 +0200 CEST [web-1] [7b4a26c5-5872-49dd-8247-3e7b11af9bc7] app/controllers/concerns/localized.rb:23:in `set_locale'
2017-04-09 12:49:06.616329569 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60]   Account Load (2.2ms)  SELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id" ASC LIMIT $1  [["LIMIT", 1]]
2017-04-09 12:49:06.617470636 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]' duration=5.99 view=0.00 db=2.20
2017-04-09 12:49:06.618303486 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60]
2017-04-09 12:49:06.618370642 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60] ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]):
2017-04-09 12:49:06.618418070 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60]
2017-04-09 12:49:06.618468101 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60] app/controllers/home_controller.rb:15:in `authenticate_user!'
2017-04-09 12:49:06.618515373 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60] app/controllers/concerns/localized.rb:24:in `block in set_locale'
2017-04-09 12:49:06.618555630 +0200 CEST [web-1] [379c73c2-6806-4db5-a009-c1c93253be60] app/controllers/concerns/localized.rb:23:in `set_locale'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Komic** [comment]
you need to disable single user mode, create your account, then re-enable it

**Comment by wxcafe** [comment]
@aral did this answer your question? Please close the issue if your problem is fixed :)

**Comment by Gargron** [comment]
Should I make single user mode smarter and allow sign up if users table is empty?

**Comment by wxcafe** [comment]
That might be a nice thing imo.

**Comment by aral** [comment]
@komic I see. That’s a definite usability issue. The first experience after a successful installation shouldn’t be an error condition.

@Gargron Yes, please :) Ideally:

1. Single user mode install successfully completes
2. You hit the web interface and it goes directly to the sign up form for the single account
3. You create the account
4. You’re up an running.

This way, the person is led through the setup process (which ends when the person can successfully start using Mastodon, not when the installation script completes) and never feels lost.

If this involves a lot of work, a temporary workaround would be to disable the person from being able to set single account mode to true on (or remove the option from) the Scalingo form.
