### ISSUE TITLE
Web UI crashes when deleting announcement

### ISSUE THREAD

**Issue by bubblineyuri** [tootsuite/mastodon#13362]
### Logs

```
TypeError: Cannot read property 'get' of undefined


TypeError: Cannot read property 'get' of undefined
    at t._markAnnouncementAsRead (https://koyu.space/packs/js/features/home_timeline-eb427959489e8c1d5424.chunk.js:1:14515)
    at t.componentDidUpdate (https://koyu.space/packs/js/features/home_timeline-eb427959489e8c1d5424.chunk.js:1:14360)
    at Du (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1057580)
    at t.unstable_runWithPriority (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1077060)
    at Xa (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1001987)
    at Fu (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1053829)
    at wu (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1044148)
    at https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1002278
    at t.unstable_runWithPriority (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1077060)
    at Xa (https://koyu.space/packs/js/common-ee9226a17a0221aba66c.js:2:1001987)


_markAnnouncementAsRead (webpack:///app/javascript/mastodon/features/getting_started/components/announcements.js:382:22)
componentDidUpdate (webpack:///app/javascript/mastodon/features/getting_started/components/announcements.js:375:9)
componentDidUpdate (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6326:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:270:11)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2794:9)
Yj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6105:2)
Zj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5408:6)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2829:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:270:11)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2794:9)
```

### Specifications

**Browser:** Google Chrome 80.0.3987.149 
**Operating System:** Arch Linux (last updated March 31st 19:12 UTC+2)
**Mastodon version:** 3.1.2 (stable)
**Instance:** [koyu.space](https://koyu.space)

**Comment by ThibG** [comment]
Fixed by #13283 and #13312
