### ISSUE TITLE
v3.1.3 media attachments problem

### ISSUE THREAD

**Issue by hugogameiro** [tootsuite/mastodon#13403]
Testing v3.1.3 I am getting the following error in Sidekiq logs:

```
2020-04-05T17:34:32.116Z pid=6 tid=ow6k6u3hu class=PostProcessMediaWorker jid=3511dd86bc96659dd079dc04 INFO: start
[paperclip] copying media_attachments/files/000/000/475/original/65a1593901cb5f13.gif to local file /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u.gif
Command :: file -b --mime '/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u.gif'
[paperclip] Trying to link /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u.gif to /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-1gor6hk.gif
Command :: file -b --mime '/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-1gor6hk.gif'
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: ffmpeg -i "/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u.gif" 2>&1
[paperclip] [transcoder] Transocding supported file /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u.gif
[AV] Adding output parameter ["acodec", "aac"]
[AV] Adding output parameter ["strict", "experimental"]
[AV] Adding output parameter ["loglevel", "fatal"]
[AV] Adding output parameter ["movflags", "faststart"]
[AV] Adding output parameter ["pix_fmt", "yuv420p"]
[AV] Adding output parameter ["vf", "scale='trunc(iw/2)*2:trunc(ih/2)*2'"]
[AV] Adding output parameter ["vsync", "cfr"]
[AV] Adding output parameter ["c:v", "h264"]
[AV] Adding output parameter ["maxrate", "1300K"]
[AV] Adding output parameter ["bufsize", "1300K"]
[AV] Adding output parameter ["frames:v", 10800]
[AV] Adding output parameter ["crf", 18]
[AV] Adding output parameter ["map_metadata", "-1"]
[AV] Running command: ffmpeg -i "/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u.gif" -acodec aac -strict experimental -loglevel fatal -movflags faststart -pix_fmt yuv420p -vf scale='trunc(iw/2)*2:trunc(ih/2)*2' -vsync cfr -c:v h264 -maxrate 1300K -bufsize 1300K -frames:v 10800 -crf 18 -map_metadata -1 -y "/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u20200405-6-1bsm64l.mp4"
[paperclip] [transcoder] Successfully transcoded ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u to #<File:0x00007fbeb2f0dd90>
[paperclip] Trying to link /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-flqe3u20200405-6-1bsm64l.mp4 to /tmp/1a610fb05a0222dc35060ee3ea28930120200405-6-1x7zdtq.mp4
[paperclip] deleting media_attachments/files/000/000/475/original/65a1593901cb5f13.gif
[paperclip] saving media_attachments/files/000/000/475/original/65a1593901cb5f13.mp4
[paperclip] deleting media_attachments/files/000/000/475/original/65a1593901cb5f13.gif
2020-04-05T17:34:33.358Z pid=6 tid=ow6k6u3hu class=PostProcessMediaWorker jid=3511dd86bc96659dd079dc04 elapsed=1.242 INFO: fail
2020-04-05T17:34:33.358Z pid=6 tid=ow6k6u3hu WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"class":"PostProcessMediaWorker","args":[475],"jid":"3511dd86bc96659dd079dc04","created_at":1586108072.116253,"enqueued_at":1586108072.1163433},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"dead\":false,\"class\":\"PostProcessMediaWorker\",\"args\":[475],\"jid\":\"3511dd86bc96659dd079dc04\",\"created_at\":1586108072.116253,\"enqueued_at\":1586108072.1163433}"}
2020-04-05T17:34:33.358Z pid=6 tid=ow6k6u3hu WARN: Fog::Storage::OpenStack::NotFound: Expected(204) <=> Actual(404 Not Found)
excon.error.response
  :body          => "<html><h1>Not Found</h1><p>The resource could not be found.</p></html>"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "70"
    "Content-Type"           => "text/html; charset=UTF-8"
    "Date"                   => "Sun, 05 Apr 2020 17:34:33 GMT"
    "X-IPLB-Instance"        => "33617"
    "X-Openstack-Request-Id" => "tx1197e06bbcf842d08fd44-005e8a16a9"
    "X-Trans-Id"             => "tx1197e06bbcf842d08fd44-005e8a16a9"
  }
  :host          => "storage.gra.cloud.ovh.net"
  :local_address => "XX.XX.XX.XX"
  :local_port    => 53850
  :path          => "/XX/XX/XX/media_attachments%2Ffiles%2F000%2F000%2F475%2Foriginal%2F65a1593901cb5f13.gif"
  :port          => 443
  :reason_phrase => "Not Found"
  :remote_ip     => "XX.XX.XX.XX"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"

2020-04-05T17:34:33.358Z pid=6 tid=ow6k6u3hu WARN: /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/excon-0.71.0/lib/excon/middlewares/expects.rb:13:in `response_call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/excon-0.71.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/excon-0.71.0/lib/excon/connection.rb:448:in `response'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/excon-0.71.0/lib/excon/connection.rb:279:in `request'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/httplog-1.4.2/lib/httplog/adapters/excon.rb:30:in `block in request'
/opt/ruby/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/httplog-1.4.2/lib/httplog/adapters/excon.rb:29:in `request'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/fog-openstack-0.3.7/lib/fog/openstack/core.rb:53:in `request'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/fog-openstack-0.3.7/lib/fog/storage/openstack/requests/delete_object.rb:12:in `delete_object'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/fog-openstack-0.3.7/lib/fog/storage/openstack/models/file.rb:70:in `destroy'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/storage/fog.rb:135:in `block in flush_deletes'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/storage/fog.rb:133:in `each'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/storage/fog.rb:133:in `flush_deletes'
/opt/mastodon/lib/paperclip/attachment_extensions.rb:24:in `reprocess_original!'
/opt/mastodon/app/workers/post_process_media_worker.rb:28:in `perform'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:196:in `execute_job'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/opt/mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.21/lib/sidekiq_unique_jobs/server/middleware.rb:29:in `call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:163:in `block in process'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_retry.rb:111:in `local'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/rails.rb:43:in `block in call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:72:in `wrap'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/rails.rb:42:in `call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:257:in `stats'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_logger.rb:13:in `call'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_retry.rb:78:in `global'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:124:in `block in dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/logger.rb:10:in `with'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_logger.rb:33:in `prepare'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:123:in `dispatch'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:162:in `process'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:78:in `process_one'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:68:in `run'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/util.rb:15:in `watchdog'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/util.rb:24:in `block in safe_thread'
2020-04-05T17:35:04.753Z pid=6 tid=ow6j934o2 class=PostProcessMediaWorker jid=3511dd86bc96659dd079dc04 INFO: start
[paperclip] copying media_attachments/files/000/000/475/original/65a1593901cb5f13.mp4 to local file /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a.mp4
Command :: file -b --mime '/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a.mp4'
[paperclip] Trying to link /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a.mp4 to /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-11rc4zx.mp4
Command :: file -b --mime '/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-11rc4zx.mp4'
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: ffmpeg -i "/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a.mp4" 2>&1
[paperclip] [transcoder] Transocding supported file /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a.mp4
[AV] Adding output parameter ["acodec", "aac"]
[AV] Adding output parameter ["strict", "experimental"]
[AV] Adding output parameter ["loglevel", "fatal"]
[AV] Adding output parameter ["map_metadata", "-1"]
[AV] Adding output parameter ["c:v", "copy"]
[AV] Adding output parameter ["c:a", "copy"]
[AV] Running command: ffmpeg -i "/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a.mp4" -acodec aac -strict experimental -loglevel fatal -map_metadata -1 -c:v copy -c:a copy -y "/tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a20200405-6-1kwinhl.mp4"
[paperclip] [transcoder] Successfully transcoded ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a to #<File:0x00007fbeb3e7b3b8>
[paperclip] Trying to link /tmp/ae5d25fc78f3dbfa6d82c0f94f4bee7f20200405-6-h8ml7a20200405-6-1kwinhl.mp4 to /tmp/dfce16e9b6e0910d1db0663f48fcb98b20200405-6-10y80xi.mp4
[paperclip] deleting media_attachments/files/000/000/475/original/65a1593901cb5f13.mp4
[paperclip] saving media_attachments/files/000/000/475/original/65a1593901cb5f13.mp4
2020-04-05T17:35:05.830Z pid=6 tid=ow6j934o2 class=PostProcessMediaWorker jid=3511dd86bc96659dd079dc04 elapsed=1.076 INFO: done
```
This is an upload of a 12kb animated gif uploading to an OpenStack Swift Object Storage. It takes 30 seconds to process because it fails after the initial process.

Looking at the error I assume the problematic part is:
```
[paperclip] deleting media_attachments/files/000/000/475/original/65a1593901cb5f13.gif
[paperclip] saving media_attachments/files/000/000/475/original/65a1593901cb5f13.mp4
[paperclip] deleting media_attachments/files/000/000/475/original/65a1593901cb5f13.gif
```
There is a double call for deletion of the same file `media_attachments/files/000/000/475/original/65a1593901cb5f13.gif` and probably it fails on the second deletion because it was already deleted.

It ends up successful because on the retry it works.

This only happens on files that are transcoded for a different file format/extension (eg: uploading a mov file) or animated gif (as gifs are transcoded to mp4).

Using the same server but local storage, it works fine but I still see the double deletion:
```
2020-04-05T19:02:33.852Z pid=6 tid=oxjk7u8za class=PostProcessMediaWorker jid=bc79d4bf8ec3c4a6eeb9750b INFO: start
Command :: file -b --mime '/tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww.gif'
[paperclip] Trying to link /tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww.gif to /tmp/18391639375f51d932daf119058b64f220200405-6-74ufsz.gif
Command :: file -b --mime '/tmp/18391639375f51d932daf119058b64f220200405-6-74ufsz.gif'
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: ffmpeg -i "/tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww.gif" 2>&1
[paperclip] [transcoder] Transocding supported file /tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww.gif
[AV] Adding output parameter ["acodec", "aac"]
[AV] Adding output parameter ["strict", "experimental"]
[AV] Adding output parameter ["loglevel", "fatal"]
[AV] Adding output parameter ["movflags", "faststart"]
[AV] Adding output parameter ["pix_fmt", "yuv420p"]
[AV] Adding output parameter ["vf", "scale='trunc(iw/2)*2:trunc(ih/2)*2'"]
[AV] Adding output parameter ["vsync", "cfr"]
[AV] Adding output parameter ["c:v", "h264"]
[AV] Adding output parameter ["maxrate", "1300K"]
[AV] Adding output parameter ["bufsize", "1300K"]
[AV] Adding output parameter ["frames:v", 10800]
[AV] Adding output parameter ["crf", 18]
[AV] Adding output parameter ["map_metadata", "-1"]
[AV] Running command: ffmpeg -i "/tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww.gif" -acodec aac -strict experimental -loglevel fatal -movflags faststart -pix_fmt yuv420p -vf scale='trunc(iw/2)*2:trunc(ih/2)*2' -vsync cfr -c:v h264 -maxrate 1300K -bufsize 1300K -frames:v 10800 -crf 18 -map_metadata -1 -y "/tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww20200405-6-fakcs4.mp4"
[paperclip] [transcoder] Successfully transcoded 18391639375f51d932daf119058b64f220200405-6-rle2ww to #<File:0x00007ff06605fb00>
[paperclip] Trying to link /tmp/18391639375f51d932daf119058b64f220200405-6-rle2ww20200405-6-fakcs4.mp4 to /tmp/c95f58fa068c4e83aba0a4fae50af3d020200405-6-116i4h3.mp4
[paperclip] deleting /opt/mastodon/public/system/media_attachments/files/000/000/487/original/3688100dadd21ed7.gif
[paperclip] deleting /opt/mastodon/public/system/media_attachments/files/000/000/487/original/3688100dadd21ed7.gif
2020-04-05T19:02:34.031Z pid=6 tid=oxjk7u8za class=PostProcessMediaWorker jid=bc79d4bf8ec3c4a6eeb9750b elapsed=0.18 INFO: done
```
Suspect this might be the cause: https://github.com/tootsuite/mastodon/blob/c6ccd9d054f8ff174b3fb6f7848631473768a57d/lib/paperclip/attachment_extensions.rb#L23

**Comment by hugogameiro** [comment]
In fact, deleting the line https://github.com/tootsuite/mastodon/blob/c6ccd9d054f8ff174b3fb6f7848631473768a57d/lib/paperclip/attachment_extensions.rb#L23 solves my issue and stops the double deletions.

If I understand correctly this was introduced to avoid the problem https://github.com/tootsuite/mastodon/pull/13210#discussion_r389373908 with `reprocess!` 

> Calling reprocess WILL NOT delete existing files

 but I couldn't reproduce that case where original files are left behind after reprocess.

From what I read here https://github.com/thoughtbot/paperclip/issues/785#issuecomment-5601036 the reprocess clears the old files:
> when you're calling reprocess! in the new version, we actually re-assigning the attachment to itself. What this means is that old files are cleared and copied to Tempfile before Paperclip start to process them again as usual. Is that the case you're seeing or not?

From the PaperClip code https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L94

> What gets called when you call instance.attachment = File. It clears errors, assigns attributes, and processes the file. It also queues up the previous file for deletion, to be flushed away on #save of its host.

Not sure if I am missing something and I haven't tested S3 (only local and Swift) but maybe there is no need for this workaround.
