### ISSUE TITLE
tootctl media remove-orphans: exception in preload_records_from_mixed_objects

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#13401]
I just updated to 3.1.3. I was very excited to test https://github.com/tootsuite/mastodon/pull/13316, but here's what I get:

```
mastodon@masto ~/live> env RAILS_ENV=production bin/tootctl media remove-orphans
Traceback (most recent call last):=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---|  ETA: ??:??:??
	15: from bin/tootctl:5:in `<main>'
	14: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	12: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	10: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 8: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 7: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 6: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 5: from /home/mastodon/live/lib/mastodon/media_cli.rb:71:in `remove_orphans'
	 4: from /home/mastodon/live/lib/mastodon/media_cli.rb:71:in `loop'
	 3: from /home/mastodon/live/lib/mastodon/media_cli.rb:85:in `block in remove_orphans'
	 2: from /home/mastodon/live/lib/mastodon/media_cli.rb:278:in `preload_records_from_mixed_objects'
	 1: from /home/mastodon/live/lib/mastodon/media_cli.rb:278:in `map'
/home/mastodon/live/lib/mastodon/media_cli.rb:281:in `block in preload_records_from_mixed_objects': undefined method `join' for "count":String (NoMethodError)
```

```
mastodon@masto ~/live> git status
HEAD detached at v3.1.3
nothing to commit, working tree clean
```

**Comment by Gargron** [comment]
This is super disappointing, I don't know how I didn't catch this -- I've tested the command and it worked and it even helped someone in production without failing. Super weird.

**Comment by angristan** [comment]
Let me know if I can provide any data to help debug this (unless you've already found the bug!)

**Comment by Gargron** [comment]
It's a super simple bug, a left-over from reorganizing variables during development, and I haven't found it because the command doesn't use that code when run with local filesystem setting.
