### ISSUE TITLE
Database migration failed

### ISSUE THREAD

**Issue by Takumiboo** [tootsuite/mastodon#13427]
### Expected behaviour
Success database migration

### Actual behaviour
Database migration failed.
After reboot, timeline isn't shown and 500 error on bottom-left.

### Steps to reproduce the problem
```
$ git checkout v3.1.3
$ bundle install 
$ yarn install
$ RAILS_ENV=production bundle exec rails db:migrate
rails aborted!
ActiveRecord::DuplicateMigrationNameError:

Multiple migrations have the name RemoveUnneededIndexes.

bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

$ RAILS_ENV=production bundle exec rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
rails aborted!
ActiveRecord::DuplicateMigrationNameError:

Multiple migrations have the name RemoveUnneededIndexes.

/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1316:in `validate'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1185:in `initialize'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1036:in `new'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1036:in `up'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/strong_migrations-0.6.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command.rb:48:in `invoke'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
```

### Specifications
v3.1.2 -> v3.1.3 85f0e0a
Non-Docker
CentOS Linux release 7.7.1908 (Core)

**Comment by ThibG** [comment]
This definitely shouldn't happen. Have you ever switched to a fork or manually edited migrations?
What does `grep -r RemoveUnneededIndexes db/` return?

**Comment by Takumiboo** [comment]
No fork and manual migrations.

It says
```
$ grep -r RemoveUnneededIndexes db/
db/migrate/20190326015651_remove_unneeded_indexes.rb:class RemoveUnneededIndexes < ActiveRecord::Migration[5.2]
db/migrate/20161122163057_remove_unneeded_indexes.rb:class RemoveUnneededIndexes < ActiveRecord::Migration[5.0]
```

**Comment by ThibG** [comment]
ok, this is weird… what does `db/migrate/20190326015651_remove_unneeded_indexes.rb` contain?
what does `git log db/migrate/20190326015651_remove_unneeded_indexes.rb` say?

**Comment by Takumiboo** [comment]
```
$ cat db/migrate/20190326015651_remove_unneeded_indexes.rb
class RemoveUnneededIndexes < ActiveRecord::Migration[5.2]
  def change
  end
end
```
`$ git log db/migrate/20190326015651_remove_unneeded_indexes.rb` said no output.

**Comment by ThibG** [comment]
You can safely remove this file and run the migrations again, but I have no idea where this file comes from…

**Comment by ThibG** [comment]
Have you per any chance followed maintenance instructions from PgHero (/pghero) on your instance? It seems it may suggest creating a migration with that name.

**Comment by Takumiboo** [comment]
I deleted ``db/migrate/20190326015651_remove_unneeded_indexes.rb`` and run migrations again and then works fine!
Thank you for your cooperation!!
