### ISSUE TITLE
tootctl media remove-orphans fails on import object

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#13425]
The command worked flawlessly for hundreds of thousands of avatars, headers, emojis, but when it begins processing the first import, it fails, so I guess it's related to the object type?

To get some info, I added `puts record.inspect` above line 94:

https://github.com/tootsuite/mastodon/blob/c99bc5d51bb588a56c7c8cfcee3a3a5ab3841a95/lib/mastodon/media_cli.rb#L87-L94

```
...
a bunch of emojis...
...
#<CustomEmoji id: 164291, shortcode: "pat_blobbercollie", domain: "maw.moe", image_file_name: "71a72ccd363b8d30.png", image_content_type: "image/png", image_file_size: 15421, image_updated_at: "2020-04-06 21:04:49", created_at: "2020-04-06 21:04:49", updated_at: "2020-04-06 21:04:49", disabled: false, uri: "https://maw.moe/emojis/5039", image_remote_url: "https://cdn.maw.moe/mstdn/custom_emojis/images/000...", visible_in_picker: true, category_id: nil>
#<Import type: "following", approved: false, created_at: "2019-01-26 00:47:36", updated_at: "2019-01-26 00:47:36", data_file_name: "friends.csv", data_content_type: "text/plain", data_file_size: 4720, data_updated_at: "2019-01-26 00:47:36", account_id: 82828, id: 388, overwrite: false>
bundler: failed to load command: bin/tootctl (bin/tootctl)
NoMethodError: undefined method `datum' for #<Import:0x000055a12913c0e8>
Did you mean?  data
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.2/lib/active_model/attribute_methods.rb:430:in `method_missing'
  /home/mastodon/live/lib/mastodon/media_cli.rb:95:in `public_send'
  /home/mastodon/live/lib/mastodon/media_cli.rb:95:in `block (2 levels) in remove_orphans'
  /home/mastodon/live/lib/mastodon/media_cli.rb:87:in `each'
  /home/mastodon/live/lib/mastodon/media_cli.rb:87:in `block in remove_orphans'
  /home/mastodon/live/lib/mastodon/media_cli.rb:71:in `loop'
  /home/mastodon/live/lib/mastodon/media_cli.rb:71:in `remove_orphans'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  bin/tootctl:5:in `<top (required)>'
```

**Comment by angristan** [comment]
Fixed in #13685
