### ISSUE TITLE
Profile content become unavailable

### ISSUE THREAD

**Issue by matunixe** [tootsuite/mastodon#1375]
Hello,

Some accounts on the [Unixcorns instance](https://unixcorn.xyz) become unavailable, giving a 500 error when you visited them on the web app. For exemple when you try to access: 

- https://unixcorn.xyz/@unixcorn
- https://unixcorn.xyz/@yvesago

Here is a screenshot of what happen on the *unixcorn* account (I own this one):

![screen shot 2017-04-09 at 23 32 18](https://cloud.githubusercontent.com/assets/10813340/24841142/f0a7aa3a-1d7c-11e7-9b13-67f380c75f35.png)

Here is the syslog of the server when I try to access https://unixcorn.xyz/web/getting-started (sorry some data may be irrelevant):
```
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907]
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907] ActionView::Template::Error (undefined method `object_type' for nil:NilClass
Apr  9 21:01:54 unixcorn bundle[10703]: Did you mean?  object_id):
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907]     1: collection @statuses
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907]     2: extends 'api/v1/statuses/show'
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907]
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907] app/lib/tag_manager.rb:91:in `url_for'
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907] app/views/api/v1/statuses/_mention.rabl:1:in `block in eval_source'
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907] app/views/api/v1/accounts/statuses.rabl:3:in `_app_views_api_v__accounts_statuses_rabl___2471962538421671262_70272910937580'
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907] app/controllers/concerns/localized.rb:24:in `block in set_locale'
Apr  9 21:01:54 unixcorn bundle[10703]: [f8d6f253-eca3-45a8-9bbc-ecbdf2866907] app/controllers/concerns/localized.rb:23:in `set_locale'
Apr  9 21:01:54 unixcorn bundle[10703]: [6a140ec7-848a-4d00-8d6f-bb454d30428f]   #033[1m#033[36mAccount Load (0.7ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'unixcorn') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
Apr  9 21:01:54 unixcorn bundle[10703]: [6a140ec7-848a-4d00-8d6f-bb454d30428f]   #033[1m#033[36mCACHE (0.0ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'unixcorn') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
Apr  9 21:01:54 unixcorn bundle[10703]: [6a140ec7-848a-4d00-8d6f-bb454d30428f]   #033[1m#033[36mCACHE (0.0ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'unixcorn') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
Apr  9 21:01:54 unixcorn bundle[10703]: [6a140ec7-848a-4d00-8d6f-bb454d30428f]   #033[1m#033[36mCACHE (0.0ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'unixcorn') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
Apr  9 21:01:54 unixcorn bundle[10703]: [6a140ec7-848a-4d00-8d6f-bb454d30428f]   #033[1m#033[36mCACHE (0.0ms)#033[0m  #033[1m#033[34mSELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'unixcorn') AND "accounts"."domain" IS NULL LIMIT $1#033[0m  [["LIMIT", 1]]
```

I really don't understand what's happening here, if you need some other log to help me with this I will gladly give them.
Thanks in advance for helping.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by matunixe** [comment]
Since the last v1.1.1 update I get the notifications back to the *unixcorn*s account:

![screen shot 2017-04-10 at 10 51 20](https://cloud.githubusercontent.com/assets/10813340/24853551/c6ff9120-1ddb-11e7-97b6-9c2e0bb92485.png)

Sadly the public profile remain unavailable. ☹️

**Comment by matunixe** [comment]
### Another interesting development

This user, *allilengyi* have the same problem described here before. But I, *mathias* **can properly see his profile and browse it correctly**.

Here are some infos provided by the user:
```
@mathias Hey, whenever I try to viel my profile I get either 

500 internal server error or 
Ooops! An unexpected error occured.

neither does https://unixcorn.xyz/@allilengyi 
work.
```
![57269735a6736a9a](https://cloud.githubusercontent.com/assets/10813340/24854490/ef8ba52c-1dde-11e7-9729-45c516669718.png)

**Comment by matunixe** [comment]
Since upgrade to v1.1.2 everything works. Don't understand why but, heh, it's working! 😀
