### ISSUE TITLE
tootctl media remove-orphans crashes

### ISSUE THREAD

**Issue by dadall** [tootsuite/mastodon#13762]
### Expected behaviour

Remove orphans.

### Actual behaviour

Failed : 

``` Found and removed orphan: accounts/headers/000/098/292/original/f1e1328e4d5bc31e.png
Found and removed orphan: cache/media_attachments/files/000/731/459/original/e57ce1481e1625aa.jpeg
Found and removed orphan: cache/media_attachments/files/000/731/459/small/e57ce1481e1625aa.jpeg
Traceback (most recent call last):-=---=---=---=---=---=---=---=---=---=---=---=---=---=-|  ETA: ??:??:??
        16: from bin/tootctl:5:in `<main>'
        15: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in`run'
        11: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `blockin subcommand'
        10: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         9: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in`run'
         6: from /home/mastodon/live/lib/mastodon/media_cli.rb:122:in `remove_orphans'
         5: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:43:in `find'
         4: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:43:in `each'
         3: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:48:in `block in find'
         2: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:48:in `catch'
         1: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/home/mastodon/live/lib/mastodon/media_cli.rb:131:in `block in remove_orphans': undefined method `join' for nil:NilClass (NoMethodError)

```

### Specifications

- Mastodon 3.1.4
- Debian 9.12
- Ruby 2.6.6

**Comment by ThibG** [comment]
Can you add the following line in `lib/media_cli.rb` at line 130 and run the command again?

```ruby
          path_segments.delete('cache')

          say("File name: #{path_segments}") if path_segments.size < 3

          model_name      = path_segments.first.classify
```

**Comment by ThibG** [comment]
I have opened a PR (#13764) to fix this, but I'm still curious about the result of running the command again with the modification I posted in the previous command.

**Comment by dadall** [comment]
@ThibG here is the diff : 

``` mastodon@diaspodon:~/live$ git diff lib/mastodon/media_cli.rb
diff --git a/lib/mastodon/media_cli.rb b/lib/mastodon/media_cli.rb
index 2b1653335..6a49b7fee 100644
--- a/lib/mastodon/media_cli.rb
+++ b/lib/mastodon/media_cli.rb
@@ -127,6 +127,8 @@ module Mastodon
           path_segments = key.split(File::SEPARATOR)
           path_segments.delete('cache')

+          say("File name: #{path_segments}") if path_segments.size < 3
+
           model_name      = path_segments.first.classify
           record_id       = path_segments[2..-2].join.to_i
           attachment_name = path_segments[1].singularize
```

Result : 

```
mastodon@diaspodon:~/live$ RAILS_ENV=production bin/tootctl media remove-orphans
Found and removed orphan: accounts/avatars/000/094/908/original/807b8b28d94984dc.jpeg                                                                                                                              
Found and removed orphan: accounts/avatars/000/095/615/original/080a4011d93f611c.jpeg                                                                                                                              
Found and removed orphan: accounts/headers/000/091/525/original/d2ac1408113bcbed.jpeg                                                                                                                              
File name: ["cfb13ca6ad7f6b2dd0bc74cf5c91993dc1d05dfc.csv"]--=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=-|  ETA: ??:??:??
Traceback (most recent call last):
        16: from bin/tootctl:5:in `<main>'
        15: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        10: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         9: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         6: from /home/mastodon/live/lib/mastodon/media_cli.rb:122:in `remove_orphans'
         5: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:43:in `find'
         4: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:43:in `each'
         3: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:48:in `block in find'
         2: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:48:in `catch'
         1: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/home/mastodon/live/lib/mastodon/media_cli.rb:133:in `block in remove_orphans': undefined method `join' for nil:NilClass (NoMethodError)
```

:cry:

**Comment by ThibG** [comment]
@dadall thanks, it's about what I expected. Not sure why `public/system/cfb13ca6ad7f6b2dd0bc74cf5c91993dc1d05dfc.csv` is here. Could you look how old it is? (`stat public/system/cfb13ca6ad7f6b2dd0bc74cf5c91993dc1d05dfc.csv`)

I think you can safely remove it and try again.

Also, the issue has been fixed, you can apply https://github.com/tootsuite/mastodon/commit/199bbbcb9fe0620000538ae0c7766ff4a8f4cf0c
