### ISSUE TITLE
Batch deleting custom emoji throws 500

### ISSUE THREAD

**Issue by SuperSandro2000** [tootsuite/mastodon#13897]
### Expected behaviour

Delete a batch of custom emojis without any errors

### Actual behaviour

Server sends 500.

### Steps to reproduce the problem

Try deleting an entire page of custom emojis.

### Specifications

v3.1.4

```
method=POST path=/admin/custom_emojis/batch format=html controller=Admin::CustomEmojisController action=batch status=500 error='AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".' duration=11.81 view=0.00 db=1.81 location=https://mastodon.supersandro.de/admin/custom_emojis
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
app/controllers/application_controller.rb:146:in `block (2 levels) in respond_with_error'
app/controllers/application_controller.rb:145:in `respond_with_error'
app/controllers/application_controller.rb:84:in `forbidden'
```

**Comment by ThibG** [comment]
I'm unable to reproduce this. Is that the whole trace? Can you reliably reproduce it? If so, could you try removing `rescue_from Mastodon::NotPermittedError, with: :forbidden` from `app/controllers/application_controller.rb`, restart `mastodon-web`, and try again?

**Comment by SuperSandro2000** [comment]
> Is that the whole trace?

On the default log level yes.

> Can you reliably reproduce it?

Every time I try to copy/delete one or multiple emojis with my moderator account to/from my local instance this crash happens.

> Also, are you a moderator or admin on that instance?

I am pretty sure it happened to the admin account, too but right now I can only reliable reproduce it with my moderator account.

The trail with the removed rescue. It looks like the moderator does not have permission but the button is still shown.

```
method=POST path=/admin/custom_emojis/batch format=html controller=Admin::CustomEmojisController action=batch status=500 error='Mastodon::NotPermittedError: Mastodon::NotPermittedError' duration=7.30 view=0.00 db=1.50 location=https://mastodon.supersandro.de/admin/custom_emojis
Mastodon::NotPermittedError (Mastodon::NotPermittedError):
app/controllers/concerns/authorization.rb:15:in `rescue in authorize'
app/controllers/concerns/authorization.rb:12:in `authorize'
app/models/form/custom_emoji_batch.rb:99:in `block in delete!'
app/models/form/custom_emoji_batch.rb:99:in `delete!'
app/models/form/custom_emoji_batch.rb:26:in `save'
app/controllers/admin/custom_emojis_controller.rb:33:in `batch'
app/controllers/concerns/localized.rb:18:in `block in set_locale'
app/controllers/concerns/localized.rb:17:in `set_locale'
```

**Comment by hirusi** [comment]
I am seeing the same error while using the `Copy` action as an administrator on my instance. Exactly the same error. Potentially, this hasn't been fixed for `Copy` even though it might have been for delete.
