### ISSUE TITLE
Web UI keeps crashing

### ISSUE THREAD

**Issue by mstdn** [tootsuite/mastodon#14257]
Since the latest update Mastodon keeps crashing on the local timeline.
### Actual behaviour

Crashing on local timeline in web UI. Chrome, Safari etc.

### Steps to reproduce the problem

Updated to the latest master

### Specifications

- master

Stacktrace:

`TypeError: Cannot read property 'getContext' of undefined
 
 
TypeError: Cannot read property 'getContext' of undefined
    at t.n._decode (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:399298)
    at t.n.componentDidMount (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:398935)
    at os (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:1017180)
    at pu (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:1035054)
    at t.unstable_runWithPriority (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:1054366)
    at Ha (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:978832)
    at du (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:1031526)
    at Zs (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:1027680)
    at https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:979123
    at t.unstable_runWithPriority (https://mstdn.social/packs/js/common-c9aab179fda176522e19.js:2:1054366)
 
 
decode (webpack:///app/javascript/mastodon/features/status/components/card.js:121:36)
this.props.card.get (webpack:///app/javascript/mastodon/features/status/components/card.js:98:11)
Ji (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5161:45)
q.focus (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6408:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)`

**Comment by mstdn** [comment]
It appears to be only for my account..

**Comment by Sasha-Sorokin** [comment]
https://github.com/tootsuite/mastodon/blob/961789d511ad8742b8bc75d145b3a83ec5d03ad8/app/javascript/mastodon/features/status/components/card.js#L121

Affecting PR: #13985.

**Comment by Sasha-Sorokin** [comment]
Seems like `componentDidMount` is [called](https://github.com/tootsuite/mastodon/blob/961789d511ad8742b8bc75d145b3a83ec5d03ad8/app/javascript/mastodon/features/status/components/card.js#L97-L99), but [`canvas` element](https://github.com/tootsuite/mastodon/blob/961789d511ad8742b8bc75d145b3a83ec5d03ad8/app/javascript/mastodon/features/status/components/card.js#L241) wasn't mounted due to [lots of conditions](https://github.com/tootsuite/mastodon/blob/961789d511ad8742b8bc75d145b3a83ec5d03ad8/app/javascript/mastodon/features/status/components/card.js#L254-L301), therefore [its ref](https://github.com/tootsuite/mastodon/blob/961789d511ad8742b8bc75d145b3a83ec5d03ad8/app/javascript/mastodon/features/status/components/card.js#L185-L187) was never set to any element and still is `undefined`, and calling function on `undefined` is of course causes an error. Either conditions for rendering `canvas` must be fixed or safeguard must [be added](https://github.com/tootsuite/mastodon/blob/961789d511ad8742b8bc75d145b3a83ec5d03ad8/app/javascript/mastodon/features/status/components/card.js#L115) in case `canvas` is not defined.

**Comment by Sasha-Sorokin** [comment]
Ah, yes. /cc @ThibG :point_up:

**Comment by ThibG** [comment]
Indeed, there are code paths where we don't actually render the canvas but the `componentDidUpdate` code tries to access it anyway… fixing that

**Comment by mstdn** [comment]
Just updated with the latest code and got the following crash:

TypeError: Cannot read property 'getContext' of undefined


TypeError: Cannot read property 'getContext' of undefined
    at t.n._decode (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:399312)
    at t.n.componentDidMount (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:398935)
    at os (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:1017194)
    at pu (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:1035068)
    at t.unstable_runWithPriority (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:1054380)
    at Ha (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:978846)
    at du (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:1031540)
    at Zs (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:1027694)
    at https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:979137
    at t.unstable_runWithPriority (https://mstdn.social/packs/js/common-1c0a032c4578ab63af3d.js:2:1054380)


decode (webpack:///app/javascript/mastodon/features/status/components/card.js:121:36)
this.props.card.get (webpack:///app/javascript/mastodon/features/status/components/card.js:98:11)
Ji (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5161:45)
q.focus (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6408:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)

**Comment by ThibG** [comment]
Oops sorry I missed one of the call sites. Can you try https://github.com/tootsuite/mastodon/pull/14261?

**Comment by mstdn** [comment]
> Oops sorry I missed one of the call sites. Can you try #14261?

Applying now :)

**Comment by mstdn** [comment]
> Oops sorry I missed one of the call sites. Can you try #14261?

Is this going to be merged or should I do this manually for mstdn?

**Comment by ThibG** [comment]
It will get merged, you just can apply it right now to make sure it works
