### ISSUE TITLE
UI crash

### ISSUE THREAD

**Issue by mstdn** [tootsuite/mastodon#14277]
Latest master code made the UI crash.

### Actual behaviour

Instant crash

### Specifications

See stack:

ValidationError: The blurhash string must be at least 6 characters

ValidationError: The blurhash string must be at least 6 characters
    at new t (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:538419)
    at i (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1097226)
    at t.default (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1097877)
    at https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:256930
    at as (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1016608)
    at gu (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1035687)
    at t.unstable_runWithPriority (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1053957)
    at Ha (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:978423)
    at mu (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1035446)
    at Zs (https://mstdn.social/packs/js/common-26882e9fe7a728473d03.js:2:1026995)

ValidationError (webpack:///node_modules/blurhash/dist/error.js:39:23)
validateBlurhash (webpack:///node_modules/blurhash/dist/decode.js:20:10)
decode (webpack:///node_modules/blurhash/dist/decode.js:63:2)
Blurhash (webpack:///app/javascript/mastodon/components/blurhash.js:42:26)
Ii (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5142:20)
Error(u (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6494:20)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Dj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6474:11)
yj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5870:2)

**Comment by mstdn** [comment]
Can't seem to reproduce but still wanna report this :-)

**Comment by Sasha-Sorokin** [comment]
Do you have access to console? I don't see this stacktrace very helpful, React probably prints stack of components to console.

**Comment by Gargron** [comment]
@Sasha-Sorokin Probably an empty blurhash value is passed?

**Comment by mstdn** [comment]
Sorry, already reverted!

**Comment by Sasha-Sorokin** [comment]
@Gargron yes, I guess. Going to add check for that.
