### ISSUE TITLE
500 Internal Server Error: Creating account with malformed language choice (locale)

### ISSUE THREAD

**Issue by vatlidak** [tootsuite/mastodon#14531]
500 Internal Server Error when creating a fresh mastodon account with malformed language

### Expected behavior
400 Bad Request

### Actual behavior
500 Internal Server Error

### Steps to reproduce the problem
```
echo -e '{"username":"dfdsaff5196738b0439a8368dd4","email":"mail@mastodon.com","password":"anotherString","agreement":true,"locale":"\xfefr"}' | curl -v  --insecure -H 'Authorization: Bearer [FILTERED]' -H "Content-Type: application/json" -X 'POST' 'https://localhost/api/v1/accounts' -d @- -H "Host: localhost" -H "Accept: */*"

```

### Specifications
Version 3.1.1 running on local Ubuntu deployment.

### Stack traces
```

Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089] method=POST path=/api/v1/accounts format=*/* controller=Api::V1::AccountsController action=create status=500 error='ArgumentError: invalid byte sequence in UTF-8' duration=97.79 view=0.00 db=2.71
Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089]
Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089] ArgumentError (invalid byte sequence in UTF-8):
Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089]
Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089] app/services/app_sign_up_service.rb:10:in `call'
Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089] app/controllers/api/v1/accounts_controller.rb:24:in `create'
Aug 08 17:17:44 server2-1 bundle[5102]: [11ade7e3-e487-4594-ba20-aed52a6c4089] app/middleware/handle_bad_encoding_middleware.rb:16:in `call'
```

### Comments

This bug was found using REST API fuzzing.

**Comment by mjankowski** [comment]
I think this can be closed for same reasons as https://github.com/mastodon/mastodon/issues/14533#issuecomment-1561700899
