### ISSUE TITLE
[make_admin] Create admin account crash

### ISSUE THREAD

**Issue by magikcypress** [tootsuite/mastodon#1467]
I did not get to create a admin account :(

```
$ RAILS_ENV=production bundle exec rails --trace mastodon:make_admin USERNAME=cyp** Invoke mastodon:make_admin (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute mastodon:make_admin
  Account Load (0.8ms)  SELECT  "accounts".* FROM "accounts" WHERE (lower(accounts.username) = 'cyp') AND "accounts"."domain" IS NULL LIMIT $1  [["LIMIT", 1]]
rails aborted!
NoMethodError: undefined method `user' for nil:NilClass
/opt/mastodon/live/lib/tasks/mastodon.rake:7:in `block (2 levels) in <top (required)>'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/mastodon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/opt/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => mastodon:make_admin
```

Why does the 'user' method not exist?

Thanks

**Comment by Fastidious** [comment]
Register as the user first, **then** make it admin with the rake.

**Comment by magikcypress** [comment]
thank you so much for your quick reply, it works fine.

Do you know if it is possible to create a user with command line without going through the web interface?

**Comment by Fastidious** [comment]
@magikcypress there is an issue — and a PR, I think — to do this. It is coming!

**Comment by magikcypress** [comment]
Cool ! I am working on an application for YunoHost and it would be great to be able to create a user and then an administrator during the installation.
