### ISSUE TITLE
Issue running db migration in 3.2

### ISSUE THREAD

**Issue by GibsonGibson** [tootsuite/mastodon#14777]
When running the DB migration command 

> RAILS_ENV=production bundle exec rails db:migrate

I get the following wall of text:

> > mastodon@glitchy5:~/live$ RAILS_ENV=production bundle exec rails db:migrate --trace
> ** Invoke db:migrate (first_time)
> ** Invoke db:load_config (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute db:load_config
> ** Execute db:migrate
> Migrating to IncreaseBackupSize (20191212003415)
> == 20191212003415 IncreaseBackupSize: migrating ===============================
> [strong_migrations] DANGER: No lock timeout set
> -- transaction_open?()
>    -> 0.0001s
> rails aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> Your database user is not allowed to create, drop, or execute triggers on the
> table backups.
> 
> If you are using PostgreSQL you can solve this by logging in to the Mastodon
> database (mastodon_production) using a super user and running:
> 
>     ALTER USER postgres WITH SUPERUSER
> 
> The query will grant the user super user permissions, ensuring you don't run
> into similar problems in the future (e.g. when new tables are created).
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:885:in `check_trigger_permissions!'
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:484:in `rename_column_concurrently'
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:548:in `change_column_type_concurrently'
> /home/mastodon/live/db/migrate/20191212003415_increase_backup_size.rb:10:in `block in up'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:17:in `block in safety_assured'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/checker.rb:17:in `safety_assured'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:16:in `safety_assured'
> /home/mastodon/live/db/migrate/20191212003415_increase_backup_size.rb:9:in `up'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:817:in `exec_migration'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:797:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:796:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:5:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:977:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1036:in `up'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1011:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/database_tasks.rb:4:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
> /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command.rb:48:in `invoke'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
> bin/rails:4:in `<main>'
> 
> Caused by:
> Your database user is not allowed to create, drop, or execute triggers on the
> table backups.
> 
> If you are using PostgreSQL you can solve this by logging in to the Mastodon
> database (mastodon_production) using a super user and running:
> 
>     ALTER USER postgres WITH SUPERUSER
> 
> The query will grant the user super user permissions, ensuring you don't run
> into similar problems in the future (e.g. when new tables are created).
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:885:in `check_trigger_permissions!'
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:484:in `rename_column_concurrently'
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:548:in `change_column_type_concurrently'
> /home/mastodon/live/db/migrate/20191212003415_increase_backup_size.rb:10:in `block in up'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:17:in `block in safety_assured'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/checker.rb:17:in `safety_assured'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:16:in `safety_assured'
> /home/mastodon/live/db/migrate/20191212003415_increase_backup_size.rb:9:in `up'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:817:in `exec_migration'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
> /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:797:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:796:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/migration.rb:5:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:977:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1036:in `up'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1011:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.7.1/lib/strong_migrations/database_tasks.rb:4:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
> /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command.rb:48:in `invoke'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
> bin/rails:4:in `<main>'
> Tasks: TOP => db:migrate
> mastodon@glitchy5:~/live$ If you are using PostgreSQL you can solve this by logging in to the Mastodon
> If: command not found
> mastodon@glitchy5:~/live$ database (mastodon_production) using a super user and running:
> bash: syntax error near unexpected token `mastodon_production'

Checking \du shows that postgres has Superuser.

Has anyone else seen this, or have some illumination? Searching has not yet revealed a good solution.

**Comment by GibsonGibson** [comment]
Disregard. it was a forgotten DB config change from earlier migration.
