### ISSUE TITLE
Unable to reply to posts - error 500, apparently related to PostgreSQL

### ISSUE THREAD

**Issue by csolisr** [tootsuite/mastodon#14811]
### Expected behaviour

When replying to a post, it should be sent with a HTTP code of "200 OK"

### Actual behaviour

When replying to a post, it replies with a HTTP code of "500 Internal Server Error". Digging further into the logs, `journalctl -u mastodon-web` outputs the following lines:

```
[db538277-d558-4c82-951b-2e4831f9c67f] method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=500 error='ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  right sibling's left-link doesn't match: block 17238 links to 17239 instead of expected 17233 in index "index_statuses_on_in_reply_to_id"
INSERT INTO "statuses" ("text", "created_at", "updated_at", "in_reply_to_id", "reply", "language", "conversation_id", "local", "account_id", "application_id", "in_reply_to_account_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"' duration=329.51 view=0.00 db=28.61
[db538277-d558-4c82-951b-2e4831f9c67f]
[db538277-d558-4c82-951b-2e4831f9c67f] ActiveRecord::StatementInvalid (PG::InternalError: ERROR:  right sibling's left-link doesn't match: block 17238 links to 17239 instead of expected 17233 in index "index_statuses_on_in_reply_to_id"
INSERT INTO "statuses" ("text", "created_at", "updated_at", "in_reply_to_id", "reply", "language", "conversation_id", "local", "account_id", "application_id", "in_reply_to_account_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"):
[db538277-d558-4c82-951b-2e4831f9c67f]
[db538277-d558-4c82-951b-2e4831f9c67f] lib/mastodon/snowflake.rb:11:in `around_create'
[db538277-d558-4c82-951b-2e4831f9c67f] app/services/post_status_service.rb:66:in `block in process_status!'
[db538277-d558-4c82-951b-2e4831f9c67f] app/services/post_status_service.rb:65:in `process_status!'
[db538277-d558-4c82-951b-2e4831f9c67f] app/services/post_status_service.rb:38:in `call'
[db538277-d558-4c82-951b-2e4831f9c67f] app/controllers/api/v1/statuses_controller.rb:38:in `create'
```

### Steps to reproduce the problem

1. Logging into my account
2. Attempting to send a reply to a post from an user from a different server

### Specifications

Tested first with the latest stable version (v3.2.0), then upgraded to the latest master at the time to see if the problem was solved (commit code 214bf68e0284c6ce988f87b01963956f7c240e2b )

**Comment by ThibG** [comment]
This sounds like a badly-corrupted database rather than a Mastodon issue. Try `REINDEX TABLE statuses` in PostgreSQL

**Comment by csolisr** [comment]
Just verified that reindexing the table does solve the problem, thanks for the help
