### ISSUE TITLE
Gandi.net SMTP details stoped working after 1.1.1 update

### ISSUE THREAD

**Issue by kyzh** [tootsuite/mastodon#1488]
I've had issue sending email since 1.1.1, but I think I found the root cause.
Here is a summary of the issue

**Prerequisite**
- use Gandi.net SMTP servers
- use a Docker instance of mastodon

**Step to reproduce:**
- Bring a fresh new instance of mastodon up via docker compose
- Change the environment variable for SMTP to gandi.net like so [1]
- Use a functionality that sends an email

**Outcome**
The sideqik process fails to send an email [2]

**Desired outcome**
Emails get send through [3]

**Note**
The last working version was prior 1.1.1
A workaround/fix is in https://github.com/tootsuite/mastodon/pull/1486 
RBenv might behave differently.
It is my understanding that rbenv has sane default and therefore might always have a ca-cert to use

[1]
```
SMTP_SERVER=mail.gandi.net
SMTP_PORT=587
SMTP_LOGIN=notification@kyzh.co.uk
SMTP_PASSWORD=password
SMTP_FROM_ADDRESS=notification@kyzh.co.uk
```
[2]
```
2017-04-10T22:24:40.695Z 1 TID-gpjn5wqz4 ActionMailer::DeliveryJob JID-d58d385a6f731b3b321f9fe2 INFO: start
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[ActiveJob] [ActionMailer::DeliveryJob] [0d52bd74-0a5e-4a49-9e17-79be323485b1] Performing ActionMailer::DeliveryJob from Sidekiq(mailers) with arguments: "UserMailer", "reset_password_instructions", "deliver_now", #<GlobalID:0x0055bf18ee9cb0 @uri=#<URI::GID gid://mastodon/User/1>>, "-BJKSijFFSWatRzDHav7", {}
[ActiveJob] [ActionMailer::DeliveryJob] [0d52bd74-0a5e-4a49-9e17-79be323485b1] UserMailer#reset_password_instructions: processed outbound mail in 5.4ms
[ActiveJob] [ActionMailer::DeliveryJob] [0d52bd74-0a5e-4a49-9e17-79be323485b1] Sent mail to user@kyzh.co.uk (148.4ms)
[ActiveJob] [ActionMailer::DeliveryJob] [0d52bd74-0a5e-4a49-9e17-79be323485b1] Date: Mon, 10 Apr 2017 22:24:40 +0000
From: notification@kyzh.co.uk
To: user@kyzh.co.uk
Message-ID: <58ec0628adcb7_12adf8c6ea1905388e@c39837b45e05.mail>
Subject: Reset password instructions
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_58ec0628acc24_12adf8c6ea1905377f";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_58ec0628acc24_12adf8c6ea1905377f
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello user@kyzh.co.uk!

Someone has requested a link to change your password on Mastodon. You can do this through the link below.

https://masto.kyzh.co.uk/auth/password/edit?reset_password_token=-BJKSijFFSWatRzDHav7

If you didn't request this, please ignore this email.
Your password won't change until you access the link above and create a new one.

---

Mastodon notifications from masto.kyzh.co.uk
Change e-mail preferences: https://masto.kyzh.co.uk/settings/preferences

----==_mimepart_58ec0628acc24_12adf8c6ea1905377f
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Hello user@kyzh.co.uk!</p>

<p>Someone has requested a link to change your password on Mastodon. You can do this through the link below.</p>

<p><a href="https://masto.kyzh.co.uk/auth/password/edit?reset_password_token=-BJKSijFFSWatRzDHav7">Change my password</a></p>

<p>If you didn't request this, please ignore this email.</p>
<p>Your password won't change until you access the link above and create a new one.</p>

----==_mimepart_58ec0628acc24_12adf8c6ea1905377f--

[ActiveJob] [ActionMailer::DeliveryJob] [0d52bd74-0a5e-4a49-9e17-79be323485b1] Performed ActionMailer::DeliveryJob from Sidekiq(mailers) in 157.9ms
2017-04-10T22:24:40.862Z 1 TID-gpjn5wqz4 ActionMailer::DeliveryJob JID-d58d385a6f731b3b321f9fe2 INFO: fail: 0.167 sec
2017-04-10T22:24:40.863Z 1 TID-gpjn5wqz4 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"0d52bd74-0a5e-4a49-9e17-79be323485b1","queue_name":"mailers","priority":null,"arguments":["UserMailer","reset_password_instructions","deliver_now",{"_aj_globalid":"gid://mastodon/User/1"},"-BJKSijFFSWatRzDHav7",{"_aj_symbol_keys":[]}],"locale":"en"}],"retry":true,"jid":"d58d385a6f731b3b321f9fe2","created_at":1491863018.04518,"enqueued_at":1491863080.693877,"error_message":"SSL_connect returned=1 errno=0 state=error: certificate verify failed","error_class":"OpenSSL::SSL::SSLError","failed_at":1491863018.2302532,"retry_count":1,"retried_at":1491863080.861848},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"0d52bd74-0a5e-4a49-9e17-79be323485b1\",\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"reset_password_instructions\",\"deliver_now\",{\"_aj_globalid\":\"gid://mastodon/User/1\"},\"-BJKSijFFSWatRzDHav7\",{\"_aj_symbol_keys\":[]}],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"d58d385a6f731b3b321f9fe2\",\"created_at\":1491863018.04518,\"enqueued_at\":1491863080.693877,\"error_message\":\"SSL_connect returned=1 errno=0 state=error: certificate verify failed\",\"error_class\":\"OpenSSL::SSL::SSLError\",\"failed_at\":1491863018.2302532,\"retry_count\":0}"}
2017-04-10T22:24:40.863Z 1 TID-gpjn5wqz4 WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
2017-04-10T22:24:40.864Z 1 TID-gpjn5wqz4 WARN: /usr/local/lib/ruby/2.3.0/net/smtp.rb:587:in `connect'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:587:in `tlsconnect'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:564:in `do_start'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/mastodon/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
/mastodon/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
/mastodon/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `block in deliver'
/mastodon/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.0.2/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
/mastodon/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.0.2/lib/action_mailer/base.rb:541:in `deliver_mail'
/mastodon/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `deliver'
/mastodon/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.0.2/lib/action_mailer/message_delivery.rb:96:in `block in deliver_now'
/mastodon/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.0.2/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/mastodon/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.0.2/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
/mastodon/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.0.2/lib/action_mailer/delivery_job.rb:14:in `perform'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/execution.rb:34:in `block in perform_now'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/mastodon/vendor/bundle/ruby/2.3.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:285:in `block in halting'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:447:in `block in around'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/logging.rb:44:in `block in tag_logger'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/logging.rb:44:in `tag_logger'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:285:in `block in halting'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:447:in `block in around'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/execution.rb:33:in `perform_now'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/execution.rb:22:in `block in execute'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/reloader.rb:68:in `block in wrap'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:81:in `wrap'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/reloader.rb:67:in `wrap'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:285:in `block in halting'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:447:in `block in around'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_execute_callbacks'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/execution.rb:20:in `execute'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:86:in `block in call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:85:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/server/middleware.rb:15:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

[3]
```
mastodon@masto:~$ docker logs -f mastodon_sidekiq_1
2017-04-10T23:02:11.421Z 1 TID-gpyng71yo INFO: Booting Sidekiq 4.2.7 with redis options {:host=>"redis", :port=>"6379", :password=>false, :url=>nil}
Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
2017-04-10T23:02:13.753Z 1 TID-gpyng71yo INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
2017-04-10T23:02:13.756Z 1 TID-gpyng71yo INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-04-10T23:02:13.756Z 1 TID-gpyng71yo INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-04-10T23:02:13.759Z 1 TID-gpyng71yo INFO: Starting processing, hit Ctrl-C to stop

2017-04-10T23:02:41.581Z 1 TID-gpyo4wdw0 ActionMailer::DeliveryJob JID-e406865aeb353664e3ce81ee INFO: start
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[ActiveJob] [ActionMailer::DeliveryJob] [e53deb45-cdd6-43df-85ee-bb72c0286145] Performing ActionMailer::DeliveryJob from Sidekiq(mailers) with arguments: "UserMailer", "confirmation_instructions", "deliver_now", #<GlobalID:0x0055ce52a9b5c0 @uri=#<URI::GID gid://mastodon/User/1>>, "5dhfJP3Qa6BSUHSrgbEG", {}
[ActiveJob] [ActionMailer::DeliveryJob] [e53deb45-cdd6-43df-85ee-bb72c0286145] UserMailer#confirmation_instructions: processed outbound mail in 470.6ms
[ActiveJob] [ActionMailer::DeliveryJob] [e53deb45-cdd6-43df-85ee-bb72c0286145] Sent mail to user@kyzh.co.uk (432.4ms)
[ActiveJob] [ActionMailer::DeliveryJob] [e53deb45-cdd6-43df-85ee-bb72c0286145] Date: Mon, 10 Apr 2017 23:02:42 +0000
From: notification@kyzh.co.uk
To: user@kyzh.co.uk
Message-ID: <58ec0f121f7a9_12ae72a21525041769@8eb4177b2030.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_58ec0f121e0cb_12ae72a2152504165e";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_58ec0f121e0cb_12ae72a2152504165e
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Welcome user@kyzh.co.uk!

You can confirm your Mastodon account email through the link below:

https://masto.kyzh.co.uk/auth/confirmation?confirmation_token=5dhfJP3Qa6BSUHSrgbEG

---

Mastodon notifications from masto.kyzh.co.uk
Change e-mail preferences: https://masto.kyzh.co.uk/settings/preferences

----==_mimepart_58ec0f121e0cb_12ae72a2152504165e
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome user@kyzh.co.uk!</p>

<p>You can confirm your Mastodon account email through the link below:</p>

<p><a href="https://masto.kyzh.co.uk/auth/confirmation?confirmation_token=5dhfJP3Qa6BSUHSrgbEG">Confirm my account</a></p>

----==_mimepart_58ec0f121e0cb_12ae72a2152504165e--

[ActiveJob] [ActionMailer::DeliveryJob] [e53deb45-cdd6-43df-85ee-bb72c0286145] Performed ActionMailer::DeliveryJob from Sidekiq(mailers) in 909.23ms
2017-04-10T23:02:42.560Z 1 TID-gpyo4wdw0 ActionMailer::DeliveryJob JID-e406865aeb353664e3ce81ee INFO: done: 0.98 sec
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyzh** [comment]
I can provide gandi.net test credentials to the team for testing too

**Comment by mjankowski** [comment]
Probably same as https://github.com/tootsuite/mastodon/issues/1496

**Comment by wxcafe** [comment]
yup, duplicate, closing
