### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by wayspurrchen** [tootsuite/mastodon#1540]
While trying to import a list of followers from my old account, I received the following error:

```
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e] Command :: file -b --mime '/tmp/RackMultipart20170411-3433-r6f1u6.csv'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e] Command :: file -b --mime '/tmp/d306c37e058603cfea275b98b3286af820170411-3433-1rqpubp.csv'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e]    (0.2ms)  BEGIN
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e] Command :: file -b --mime '/tmp/d306c37e058603cfea275b98b3286af820170411-3433-brwsa6.csv'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e]   SQL (0.8ms)  INSERT INTO "imports" ("account_id", "type", "created_at", "updated_at", "data_file_name", "data_conte
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e]    (0.8ms)  COMMIT
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: 2017-04-11T14:08:25.448Z 3388 TID-gozzj770c ImportWorker JID-4142777d6d405a3bbb283044 INFO: start
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]:   Import Load (0.6ms)  SELECT  "imports".* FROM "imports" WHERE "imports"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3352]: [d8b9adab-30b4-45e1-9b29-66816089006e] method=POST path=/settings/import format=html controller=Settings::ImportsController action=create status=302 duratio
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]:   Account Load (1.1ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: 2017-04-11T14:08:25.460Z 3388 TID-gozzj770c ImportWorker JID-4142777d6d405a3bbb283044 INFO: fail: 0.011 sec
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: 2017-04-11T14:08:25.460Z 3388 TID-gozzj770c WARN: {"context":"Job raised exception","job":{"class":"ImportWorker","args":[2],"retry":false,"queue":"pull","j
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: 2017-04-11T14:08:25.460Z 3388 TID-gozzj770c WARN: Errno::ENOENT: No such file or directory @ rb_sysopen - /system/aa9b39950078a5e8f0b6fe695e567ecf88f227fa.c
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: 2017-04-11T14:08:25.460Z 3388 TID-gozzj770c WARN: /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `initialize'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/app/workers/import_worker.rb:44:in `process_follows'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/app/workers/import_worker.rb:17:in `perform'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:90:in `block in call'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:89:in `call'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.0/lib/sidekiq_unique_jobs/server/middleware.rb:15:in `call'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
Apr 11 14:08:25 ubuntu-mstdn-seeker bundle[3388]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

* * * *

- [:check:] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
This change from `path` to `url` might have broken import? https://github.com/tootsuite/mastodon/commit/e30bbb1cb097ded7db59e905287f85f9f2b5d1b8

**Comment by wayspurrchen** [comment]
Is there a specific commit I should roll back to? I'm starting a new instance and I'd like to make sure that people porting over can import their follows. :)
