### ISSUE TITLE
blank login page after upgrade from 3.2.2 to 3.3.0

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15505]
So after upgrading my site style broke, then it got solved since fault was cloudflare.

But now main problem is when i login the site goes completely blank, nothing on it. just dark background shows.

So how do i fix this??

**Comment by jakesullyneytiri** [comment]
Update: After doing some checks the style seems messed up on mobile phones when they browse so i think some where with assets/cache is faulty here but idk where and how to fix this as well.

**Comment by jakesullyneytiri** [comment]
After some digging into finding some errors this is error i found

`Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] Chewy request strategy is `custom_sidekiq`
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::T
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 1. You want to set webpacker.yml value of compile to true for your environment
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]:    unless you are using the `webpack -w` or the webpack-dev-server.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 2. webpack has not yet re-run to reflect updates.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 4. Your webpack configuration is not creating a manifest.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: Your manifest contains:
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: {
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: }
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: ' duration=321.70 view=0.00 db=37.96
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] ActionView::Template::Error (Webpacker can't find features/getting_started.js in /home/mastodon/live
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 1. You want to set webpacker.yml value of compile to true for your environment
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]:    unless you are using the `webpack -w` or the webpack-dev-server.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 2. webpack has not yet re-run to reflect updates.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 4. Your webpack configuration is not creating a manifest.
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: Your manifest contains:
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: {
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: }
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: ):
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]     1: - content_for :header_tags do
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]     2:   = preload_pack_asset 'features/getting_started.js', crossorigin: 'anonymous'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]     3:   = preload_pack_asset 'features/compose.js', crossorigin: 'anonymous'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]     4:   = preload_pack_asset 'features/home_timeline.js', crossorigin: 'anonymous'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]     5:   = preload_pack_asset 'features/notifications.js', crossorigin: 'anonymous'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97]
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] lib/webpacker/helper_extensions.rb:15:in `preload_pack_asset'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] app/views/home/index.html.haml:2:in `block in _app_views_home_index_html_haml___1038188996788402802_
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] app/views/home/index.html.haml:1:in `_app_views_home_index_html_haml___1038188996788402802_161740'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Jan 06 14:35:17 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [01ffd36c-2a30-44f6-af0b-399620f8fb97] app/controllers/concerns/localized.rb:15:in `set_locale'
Jan 06 14:35:19 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [40607ed8-30cd-45d5-9873-0d847970519a] Chewy request strategy is `custom_sidekiq`
Jan 06 14:35:19 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: [40607ed8-30cd-45d5-9873-0d847970519a] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::T
Jan 06 14:35:19 mastodon-ubuntu-s-4vcpu-8gb-lon1-01 bundle[15826]: 1. You want to set webpacker.yml value of compile to true for your environment
`

**Comment by jakesullyneytiri** [comment]
but now log isn't giving error anymore, but still i got blank page and style isn't willing to load properly on any other devices/computers.

**Comment by jakesullyneytiri** [comment]
Update:

After some struggling it seems it was a cache fault from cloudflare after all. Since now after bypassing cache and doing some flushing here and there it seems to be fixing site issue and site is functioning correctly again.

So i will be closing this for now and if issue comes back i will re-open this or open new issue.
