### ISSUE TITLE
Attempting to use tootctl accounts unfollow leads to NameError

### ISSUE THREAD

**Issue by davidwolfpaw** [tootsuite/mastodon#15635]
### Expected behaviour

The accounts, whether local or remote, should have been unfollowed by all local users

### Actual behaviour
A NameError occurs: `undefined local variable or method `processed' for #<Mastodon::AccountsCLI:0x0000558c14d2a7d0> (NameError)`

### Steps to reproduce the problem

Running `accounts unfollow`, attempting on several local and remote accounts, leads to the following error:

```
~/live$ RAILS_ENV=production bin/tootctl accounts unfollow [user@remote.host]
0/0 |===========================================================================| Time: 00:00:00
Traceback (most recent call last):
	10: from bin/tootctl:8:in `<main>'
	 9: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	 8: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 7: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 6: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 5: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	 4: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	 3: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 2: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 1: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/home/mastodon/live/lib/mastodon/accounts_cli.rb:409:in `unfollow': undefined local variable or method `processed' for #<Mastodon::AccountsCLI:0x0000558c14d2a7d0> (NameError)
```

### Specifications

This is in a vanilla install of Mastodon v3.3.0

**Comment by ThibG** [comment]
Does the following patch help?

```patch
diff --git a/lib/mastodon/accounts_cli.rb b/lib/mastodon/accounts_cli.rb
index 653bfca30..74162256f 100644
--- a/lib/mastodon/accounts_cli.rb
+++ b/lib/mastodon/accounts_cli.rb
@@ -402,7 +402,7 @@ module Mastodon
         exit(1)
       end
 
-      parallelize_with_progress(target_account.followers.local) do |account|
+      processed, = parallelize_with_progress(target_account.followers.local) do |account|
         UnfollowService.new.call(account, target_account)
       end
 
```

**Comment by davidwolfpaw** [comment]
@ThibG unfortunately it does not. I instead receive the following error:

```
Traceback (most recent call last):
	19: from bin/tootctl:5:in `<main>'
	18: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	17: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	16: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
	15: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
	14: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	13: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	12: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	11: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	10: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 9: from /home/mastodon/live/lib/cli.rb:6:in `<top (required)>'
	 8: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	 7: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	 6: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
	 5: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
	 4: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 3: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 2: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': /home/mastodon/live/lib/mastodon/accounts_cli.rb:401: module definition in method body (SyntaxError)
        module Mastodon
        ^~~~~~~~~~~~~~~
/home/mastodon/live/lib/mastodon/accounts_cli.rb:523: syntax error, unexpected end-of-input, expecting `end'
```

**Comment by ThibG** [comment]
what… this shouldn't happen, how did you apply the patch? what does `git diff lib/mastodon` output?

**Comment by davidwolfpaw** [comment]
I manually copied it in. Should there have been a separate patch file?

I do see the error though, have updated it, and it appears to be working. Thank you for the update!

**Comment by ThibG** [comment]
> I do see the error though, have updated it, and it appears to be working. Thank you for the update!

Alright, I'll submit a fix then, thanks!

**Comment by davidwolfpaw** [comment]
Thanks for the quick fix!
