### ISSUE TITLE
After 3.3.0 upgrade on 1-click install image: PG::UndefinedTable: ERROR:  relation "ip_blocks" does not exist

### ISSUE THREAD

**Issue by thewismit** [tootsuite/mastodon#15696]
This was listed as a previous bug but I don't believe this is the same situation.

### Expected behaviour

Mastodon should work? Maybe, I'm not sure, sorry.

### Actual behaviour

```
Feb  9 16:33:12 mastodon bundle[949]: [a083a75b-e57c-4022-af32-c40fde74b9ea] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "ip_blocks" does not exist
Feb  9 16:33:12 mastodon bundle[949]: LINE 8:                WHERE a.attrelid = '"ip_blocks"'::regclass
Feb  9 16:33:12 mastodon bundle[949]:                                           ^
Feb  9 16:33:12 mastodon bundle[949]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
Feb  9 16:33:12 mastodon bundle[949]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
Feb  9 16:33:12 mastodon bundle[949]:                      c.collname, col_description(a.attrelid, a.attnum) AS comment
Feb  9 16:33:12 mastodon bundle[949]:                 FROM pg_attribute a
Feb  9 16:33:12 mastodon bundle[949]:                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
Feb  9 16:33:12 mastodon bundle[949]:                 LEFT JOIN pg_type t ON a.atttypid = t.oid
Feb  9 16:33:12 mastodon bundle[949]:                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
Feb  9 16:33:12 mastodon bundle[949]:                WHERE a.attrelid = '"ip_blocks"'::regclass
Feb  9 16:33:12 mastodon bundle[949]:                  AND a.attnum > 0 AND NOT a.attisdropped
Feb  9 16:33:12 mastodon bundle[949]:                ORDER BY a.attnum
Feb  9 16:33:12 mastodon bundle[949]: ):
Feb  9 16:33:12 mastodon bundle[949]: [a083a75b-e57c-4022-af32-c40fde74b9ea]
Feb  9 16:33:12 mastodon bundle[949]: [a083a75b-e57c-4022-af32-c40fde74b9ea] app/models/ip_block.rb:31:in `block in blocked?'
Feb  9 16:33:12 mastodon bundle[949]: [a083a75b-e57c-4022-af32-c40fde74b9ea] app/models/ip_block.rb:31:in `blocked?'
Feb  9 16:33:12 mastodon bundle[949]: [a083a75b-e57c-4022-af32-c40fde74b9ea] config/initializers/rack_attack.rb:46:in `block in <class:Attack>'
```

### Steps to reproduce the problem

followed the documentation for a non-docker version
here: https://docs.joinmastodon.org/admin/upgrading/
and here: https://github.com/tootsuite/mastodon/releases/tag/v3.3.0

Actual input is this

```
sudo su mastodon 
cd /home/mastodon/live/
git fetch --tags
git checkout v.3.3.0
# update versions of ruby that are available if Mastodon upgraded as-well
git -C /home/mastodon/.rbenv/plugins/ruby-build pull
rbenv install 2.7.2
#install dependencies
bundle install
yarn install
SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate\
RAILS_ENV=production bundle exec rails assets:precompile
systemctl restart mastodon-sidekiq
systemctl reload mastodon-web
systemctl restart mastodon-streaming
RAILS_ENV=production bin/tootctl cache clear
RAILS_ENV=production bundle exec rails db:migrate
systemctl restart mastodon-sidekiq
systemctl reload mastodon-web
systemctl restart mastodon-streaming
```

### Specifications

3.3.0

**Comment by ClearlyClaire** [comment]
It seems like the database migrations haven't run correctly.

Can you try `bundle exec rails db:migrate` again and report if it complains about anything?
