### ISSUE TITLE
Mastodon Streaming / CWS Web Sockets seems irrevocably broken. Node.js compatibility issue

### ISSUE THREAD

**Issue by diegoboten** [tootsuite/mastodon#15898]
For the latest Mastodon release: 

If you yarn-install the node-modules for any Node.js version under version 14, you will get a "warning: cast between incompatible function types" error on addon.cpp (part of @Clusterws/CWS) which will break mastodon-streaming.

If you yarn-install the node-modules for any Node.js version 14 or above, it will not contain the correct module (cws_linux_88) as well get a gyp error, which will also break mastodon-streaming.

Example: (from CWS build log) 

```
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

Mastodon-streaming is hence, currently broken and inoperable, no matter which Node environment you use.

Environments tested: Ubuntu 20 and 18. 
Node.js environments tested (10, 12, 13, 14, and 15)

tootctl cache cleared and node_modules deleted before each yarn install build. 
bundle exec rake tmp:cache:clear before rebuilding Mastodon. 

Other mastodon services compile and run fine. 

Journalctl status Mastodon-streaming output: 

```
Mar 14 07:54:40 ip- systemd[1]: Started mastodon-streaming.
Mar 14 07:54:41 ip- node[5869]: /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
Mar 14 07:54:41 ip- node[5869]:         throw err;
Mar 14 07:54:41 ip- node[5869]:         ^
Mar 14 07:54:41 ip- node[5869]: Error: Cannot find module '../dist/bindings/cws_linux_88'
Mar 14 07:54:41 ip- node[5869]: Require stack:
Mar 14 07:54:41 ip- node[5869]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
Mar 14 07:54:41 ip- node[5869]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/server.js
Mar 14 07:54:41 ip- node[5869]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/client.js
Mar 14 07:54:41 ip- node[5869]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js
Mar 14 07:54:41 ip- node[5869]: - /home/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
Mar 14 07:54:41 ip- node[5869]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
Mar 14 07:54:41 ip- node[5869]:     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
Mar 14 07:54:41 ip- node[5869]:     at Module.require (node:internal/modules/cjs/loader:995:19)
Mar 14 07:54:41 ip- node[5869]:     at require (node:internal/modules/cjs/helpers:92:18)
Mar 14 07:54:41 ip- node[5869]:     at /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
Mar 14 07:54:41 ip- node[5869]:     at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
Mar 14 07:54:41 ip- node[5869]:     at Module._compile (node:internal/modules/cjs/loader:1091:14)
Mar 14 07:54:41 ip- node[5869]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
Mar 14 07:54:41 ip- node[5869]:     at Module.load (node:internal/modules/cjs/loader:971:32)
Mar 14 07:54:41 ip- node[5869]:     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
Mar 14 07:54:41 ip- node[5869]:   code: 'MODULE_NOT_FOUND',
Mar 14 07:54:41 ip- node[5869]:   requireStack: [
Mar 14 07:54:41 ip- node[5869]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
Mar 14 07:54:41 ip- node[5869]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
Mar 14 07:54:41 ip- node[5869]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
Mar 14 07:54:41 ip- node[5869]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
Mar 14 07:54:41 ip- node[5869]:     '/home/mastodon/live/streaming/index.js'
Mar 14 07:54:41 ip- node[5869]:   ]
Mar 14 07:54:41 ip- node[5869]: }
Mar 14 07:54:41 ip- systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 07:54:41 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 14 07:54:41 ip- systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 1.
Mar 14 07:54:41 ip- systemd[1]: Stopped mastodon-streaming.
Mar 14 07:54:41 ip- systemd[1]: Started mastodon-streaming.
Mar 14 07:54:41 ip- node[5908]: /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
Mar 14 07:54:41 ip- node[5908]:         throw err;
Mar 14 07:54:41 ip- node[5908]:         ^
Mar 14 07:54:41 ip- node[5908]: Error: Cannot find module '../dist/bindings/cws_linux_88'
Mar 14 07:54:41 ip- node[5908]: Require stack:
Mar 14 07:54:41 ip- node[5908]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
Mar 14 07:54:41 ip- node[5908]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/server.js
Mar 14 07:54:41 ip- node[5908]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/client.js
Mar 14 07:54:41 ip- node[5908]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js
Mar 14 07:54:41 ip- node[5908]: - /home/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
Mar 14 07:54:41 ip- node[5908]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
Mar 14 07:54:41 ip- node[5908]:     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
Mar 14 07:54:41 ip- node[5908]:     at Module.require (node:internal/modules/cjs/loader:995:19)
Mar 14 07:54:41 ip- node[5908]:     at require (node:internal/modules/cjs/helpers:92:18)
Mar 14 07:54:41 ip- node[5908]:     at /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
Mar 14 07:54:41 ip- node[5908]:     at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
Mar 14 07:54:41 ip- node[5908]:     at Module._compile (node:internal/modules/cjs/loader:1091:14)
Mar 14 07:54:41 ip- node[5908]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
Mar 14 07:54:41 ip- node[5908]:     at Module.load (node:internal/modules/cjs/loader:971:32)
Mar 14 07:54:41 ip- node[5908]:     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
Mar 14 07:54:41 ip- node[5908]:   code: 'MODULE_NOT_FOUND',
Mar 14 07:54:41 ip- node[5908]:   requireStack: [
Mar 14 07:54:41 ip- node[5908]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
Mar 14 07:54:41 ip- node[5908]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
Mar 14 07:54:41 ip- node[5908]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
Mar 14 07:54:41 ip- node[5908]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
Mar 14 07:54:41 ip- node[5908]:     '/home/mastodon/live/streaming/index.js'
Mar 14 07:54:41 ip- node[5908]:   ]
Mar 14 07:54:41 ip- node[5908]: }
Mar 14 07:54:41 ip- systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 07:54:41 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 14 07:54:41 ip- systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 2.
Mar 14 07:54:41 ip- systemd[1]: Stopped mastodon-streaming.
Mar 14 07:54:41 ip- systemd[1]: Started mastodon-streaming.
Mar 14 07:54:42 ip- node[5915]: /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
Mar 14 07:54:42 ip- node[5915]:         throw err;
Mar 14 07:54:42 ip- node[5915]:         ^
Mar 14 07:54:42 ip- node[5915]: Error: Cannot find module '../dist/bindings/cws_linux_88'
Mar 14 07:54:42 ip- node[5915]: Require stack:
Mar 14 07:54:42 ip- node[5915]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
Mar 14 07:54:42 ip- node[5915]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/server.js
Mar 14 07:54:42 ip- node[5915]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/client.js
Mar 14 07:54:42 ip- node[5915]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js
Mar 14 07:54:42 ip- node[5915]: - /home/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
Mar 14 07:54:42 ip- node[5915]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
Mar 14 07:54:42 ip- node[5915]:     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
Mar 14 07:54:42 ip- node[5915]:     at Module.require (node:internal/modules/cjs/loader:995:19)
Mar 14 07:54:42 ip- node[5915]:     at require (node:internal/modules/cjs/helpers:92:18)
Mar 14 07:54:42 ip- node[5915]:     at /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
Mar 14 07:54:42 ip- node[5915]:     at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
Mar 14 07:54:42 ip- node[5915]:     at Module._compile (node:internal/modules/cjs/loader:1091:14)
Mar 14 07:54:42 ip- node[5915]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
Mar 14 07:54:42 ip- node[5915]:     at Module.load (node:internal/modules/cjs/loader:971:32)
Mar 14 07:54:42 ip- node[5915]:     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
Mar 14 07:54:42 ip- node[5915]:   code: 'MODULE_NOT_FOUND',
Mar 14 07:54:42 ip- node[5915]:   requireStack: [
Mar 14 07:54:42 ip- node[5915]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
Mar 14 07:54:42 ip- node[5915]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
Mar 14 07:54:42 ip- node[5915]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
Mar 14 07:54:42 ip- node[5915]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
Mar 14 07:54:42 ip- node[5915]:     '/home/mastodon/live/streaming/index.js'
Mar 14 07:54:42 ip- node[5915]:   ]
Mar 14 07:54:42 ip- node[5915]: }
Mar 14 07:54:42 ip- systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 07:54:42 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 14 07:54:42 ip- systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 3.
Mar 14 07:54:42 ip- systemd[1]: Stopped mastodon-streaming.
Mar 14 07:54:42 ip- systemd[1]: Started mastodon-streaming.
Mar 14 07:54:42 ip- node[5922]: /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
Mar 14 07:54:42 ip- node[5922]:         throw err;
Mar 14 07:54:42 ip- node[5922]:         ^
Mar 14 07:54:42 ip- node[5922]: Error: Cannot find module '../dist/bindings/cws_linux_88'
Mar 14 07:54:42 ip- node[5922]: Require stack:
Mar 14 07:54:42 ip- node[5922]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
Mar 14 07:54:42 ip- node[5922]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/server.js
Mar 14 07:54:42 ip- node[5922]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/client.js
Mar 14 07:54:42 ip- node[5922]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js
Mar 14 07:54:42 ip- node[5922]: - /home/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
Mar 14 07:54:42 ip- node[5922]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
Mar 14 07:54:42 ip- node[5922]:     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
Mar 14 07:54:42 ip- node[5922]:     at Module.require (node:internal/modules/cjs/loader:995:19)
Mar 14 07:54:42 ip- node[5922]:     at require (node:internal/modules/cjs/helpers:92:18)
Mar 14 07:54:42 ip- node[5922]:     at /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
Mar 14 07:54:42 ip- node[5922]:     at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
Mar 14 07:54:42 ip- node[5922]:     at Module._compile (node:internal/modules/cjs/loader:1091:14)
Mar 14 07:54:42 ip- node[5922]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
Mar 14 07:54:42 ip- node[5922]:     at Module.load (node:internal/modules/cjs/loader:971:32)
Mar 14 07:54:42 ip- node[5922]:     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
Mar 14 07:54:42 ip- node[5922]:   code: 'MODULE_NOT_FOUND',
Mar 14 07:54:42 ip- node[5922]:   requireStack: [
Mar 14 07:54:42 ip- node[5922]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
Mar 14 07:54:42 ip- node[5922]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
Mar 14 07:54:42 ip- node[5922]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
Mar 14 07:54:42 ip- node[5922]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
Mar 14 07:54:42 ip- node[5922]:     '/home/mastodon/live/streaming/index.js'
Mar 14 07:54:42 ip- node[5922]:   ]
Mar 14 07:54:42 ip- node[5922]: }
Mar 14 07:54:42 ip- systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 07:54:42 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 14 07:54:43 ip- systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 4.
Mar 14 07:54:43 ip- systemd[1]: Stopped mastodon-streaming.
Mar 14 07:54:43 ip- systemd[1]: Started mastodon-streaming.
Mar 14 07:54:43 ip- node[5942]: /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
Mar 14 07:54:43 ip- node[5942]:         throw err;
Mar 14 07:54:43 ip- node[5942]:         ^
Mar 14 07:54:43 ip- node[5942]: Error: Cannot find module '../dist/bindings/cws_linux_88'
Mar 14 07:54:43 ip- node[5942]: Require stack:
Mar 14 07:54:43 ip- node[5942]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
Mar 14 07:54:43 ip- node[5942]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/server.js
Mar 14 07:54:43 ip- node[5942]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/client.js
Mar 14 07:54:43 ip- node[5942]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js
Mar 14 07:54:43 ip- node[5942]: - /home/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
Mar 14 07:54:43 ip- node[5942]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
Mar 14 07:54:43 ip- node[5942]:     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
Mar 14 07:54:43 ip- node[5942]:     at Module.require (node:internal/modules/cjs/loader:995:19)
Mar 14 07:54:43 ip- node[5942]:     at require (node:internal/modules/cjs/helpers:92:18)
Mar 14 07:54:43 ip- node[5942]:     at /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
Mar 14 07:54:43 ip- node[5942]:     at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
Mar 14 07:54:43 ip- node[5942]:     at Module._compile (node:internal/modules/cjs/loader:1091:14)
Mar 14 07:54:43 ip- node[5942]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
Mar 14 07:54:43 ip- node[5942]:     at Module.load (node:internal/modules/cjs/loader:971:32)
Mar 14 07:54:43 ip- node[5942]:     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
Mar 14 07:54:43 ip- node[5942]:   code: 'MODULE_NOT_FOUND',
Mar 14 07:54:43 ip- node[5942]:   requireStack: [
Mar 14 07:54:43 ip- node[5942]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
Mar 14 07:54:43 ip- node[5942]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
Mar 14 07:54:43 ip- node[5942]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
Mar 14 07:54:43 ip- node[5942]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
Mar 14 07:54:43 ip- node[5942]:     '/home/mastodon/live/streaming/index.js'
Mar 14 07:54:43 ip- node[5942]:   ]
Mar 14 07:54:43 ip- node[5942]: }
Mar 14 07:54:43 ip- systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 07:54:43 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 14 07:54:44 ip- systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 5.
Mar 14 07:54:44 ip- systemd[1]: Stopped mastodon-streaming.
Mar 14 07:54:44 ip- systemd[1]: mastodon-streaming.service: Start request repeated too quickly.
Mar 14 07:54:44 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 14 07:54:44 ip- systemd[1]: Failed to start mastodon-streaming.

```

**Comment by shleeable** [comment]
yeah, node 12 only atm. Known issue.

**Comment by diegoboten** [comment]
Node 12 isn't working either now. Unfortunately not seeing a bug report for this known issue, so I've opened one up.

If CWS is now a dead library, is this even fixable?

**Comment by ClearlyClaire** [comment]
I can't reproduce it with Node 12.21.0, and I actually cannot see a build failure in your previous comment.

Can you check mastodon-streaming's logs to check whether it's actually the same error as in your first comment?

**Comment by diegoboten** [comment]
Here's what I am doing:

Switching Node environment to 12.21.0 then I delete node_modules and all its contents. 

Then clear cache and yarn install: 
```
RAILS_ENV=production bin/tootctl cache clear
RAILS_ENV=production bundle exec rake tmp:cache:clear
yarn install
```
Which gives me: 

```
RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.5
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 31.85s.
Compiling...
Compiled all packs in /home/mastodon/live/public/packs
```

So far so good. 

```
sudo systemctl restart mastodon-{web,sidekiq,streaming}

systemctl status mastodon-streaming
```

gives me


```

     Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2021-03-20 05:18:29 UTC; 1min 0s ago
    Process: 126510 ExecStart=/usr/bin/node ./streaming (code=exited, status=1/FAILURE)
   Main PID: 126510 (code=exited, status=1/FAILURE)

Mar 20 05:18:29 ip- systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 5.
Mar 20 05:18:29 ip- systemd[1]: Stopped mastodon-streaming.
Mar 20 05:18:29 ip- systemd[1]: mastodon-streaming.service: Start request repeated too quickly.
Mar 20 05:18:29 ip- systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 20 05:18:29 ip- systemd[1]: Failed to start mastodon-streaming.

```

Ok. So then 

```
journalctl -u mastodon-streaming

```

Which results in:

```
Mar 20 05:18:28 ip-172-31-53-150 systemd[1]: Started mastodon-streaming.
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:         throw err;
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:         ^
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: Error: Cannot find module '../dist/bindings/cws_linux_88'
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: Require stack:
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/server.js
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/client.js
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: - /home/mastodon/live/node_modules/@clusterws/cws/dist/index.js
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: - /home/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Module.require (node:internal/modules/cjs/loader:995:19)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at require (node:internal/modules/cjs/helpers:92:18)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at /home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Object.<anonymous> (/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Module._compile (node:internal/modules/cjs/loader:1091:14)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Module.load (node:internal/modules/cjs/loader:971:32)
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:   code: 'MODULE_NOT_FOUND',
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:   requireStack: [
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     '/home/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:     '/home/mastodon/live/streaming/index.js'
Mar 20 05:18:29 ip-172-31-53-150 node[126510]:   ]
Mar 20 05:18:29 ip-172-31-53-150 node[126510]: }
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 5.
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: Stopped mastodon-streaming.
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: mastodon-streaming.service: Start request repeated too quickly.
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Mar 20 05:18:29 ip-172-31-53-150 systemd[1]: Failed to start mastodon-streaming.

```

The relevant line is  **Error: Cannot find module '../dist/bindings/cws_linux_88'**

Which cannot be built because it doesn't exist in CWS, and CWS will not update.

So this is how it's broken in Node 12. 

It's actually broken in ALL Node versions now. The CWS_linux files that are available are for versions of Node that are too low for the GEM install process. 

So Mastodon-streaming is now effectively broken.

**Comment by ClearlyClaire** [comment]
again, I'm unable to reproduce the issue :/

```
[mastodon@mastodev live]$ node -v
v12.21.0
[mastodon@mastodev live]$ node-gyp  -v
v7.1.2
[mastodon@mastodev live]$ rm -rf node_modules/
[mastodon@mastodev live]$ RAILS_ENV=production bin/tootctl cache clear
RAILS_ENV=production bundle exec rake tmp:cache:clear
OK
[mastodon@mastodev live]$ yarn install
yarn install v1.22.10
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 16.75s.
[mastodon@mastodev live]$ node ./streaming/index.js
info Starting streaming API server master with 1 workers 
info Starting worker 1 
info Worker 1 now listening on 127.0.0.1:4000 
```
but yeah, cWS being deprecated, we should move to something else anyway…
