### ISSUE TITLE
SSL routines', 'ssl3_get_record', 'wrong version number

### ISSUE THREAD

**Issue by Happyfeet01** [tootsuite/mastodon#15915]
Hello,

i moved an instance to an new Server. Now i get this Messge when i try to login with "toot login"

`Choose an instance [mastodon.social]: fulda.social
Looking up instance info...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fulda.social', port=443): Max retries exceeded with url: /api/v1/instance (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.21.0', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 480, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 456, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 174, in login
    app = create_app_interactive(instance=args.instance, scheme=args.scheme)
  File "/usr/lib/python3/dist-packages/toot/auth.py", line 43, in create_app_interactive
    return config.load_app(instance) or register_app(instance, scheme)
  File "/usr/lib/python3/dist-packages/toot/auth.py", line 15, in register_app
    instance = api.get_instance(domain, scheme)
  File "/usr/lib/python3/dist-packages/toot/api.py", line 265, in get_instance
    return http.anon_get(url).json()
  File "/usr/lib/python3/dist-packages/toot/http.py", line 57, in anon_get
    response = send_request(request)
  File "/usr/lib/python3/dist-packages/toot/http.py", line 12, in send_request
    response = session.send(prepared, allow_redirects=allow_redirects, **settings)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='fulda.social', port=443): Max retries exceeded with url: /api/v1/instance (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))`

Whats happen here? 

On my Server is TLSv1.1, 1.2 and 1.3 supported

**Comment by ClearlyClaire** [comment]
No idea what's happening, and I actually can't reproduce it here.

```
$ toot login
fulda.social

This authentication method requires you to log into your Mastodon instance
in your browser, where you will be asked to authorize toot to access
your account. When you do, you will be given an authorization code
which you need to paste here.

This is the login URL:
https://fulda.social/oauth/authorize/?response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=read+write+follow&client_id=…
```

**Comment by Gargron** [comment]
This isn't an issue with the software in this Git repository
