### ISSUE TITLE
tootctl maintenance fix-duplicates crashes with error: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_statuses_on_uri"

### ISSUE THREAD

**Issue by hutchisr** [tootsuite/mastodon#15922]
### Expected behaviour

Attempting to run `docker-compose run --rm web ./bin/tootctl maintenance fix-duplicates` should allow me to fix database corruption

### Actual behaviour

The command crashes due to database corruption: 

```
This task will take a long time to run and is potentially destructive.
Please make sure to stop Mastodon and have a backup.
Continue? Yes
Deduplicating accounts… for local accounts, you will be asked to chose which account to keep unchanged.
Traceback (most recent call last):
	54: from ./bin/tootctl:8:in `<main>'
	53: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	52: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	51: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	50: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	49: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	48: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	47: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	46: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	44: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:145:in `fix_duplicates'
	43: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:175:in `deduplicate_accounts!'
	42: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/result.rb:57:in `each'
	41: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/result.rb:57:in `each'
	40: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/result.rb:57:in `block in each'
	39: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:181:in `block in deduplicate_accounts!'
	38: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:518:in `deduplicate_remote_accounts!'
	37: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:518:in `each'
	36: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:525:in `block in deduplicate_remote_accounts!'
	35: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `destroy'
	34: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
	33: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
	32: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
	31: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
	30: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
	29: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
	28: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
	27: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
	26: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `block in destroy'
	25: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `destroy'
	24: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_destroy_callbacks'
	23: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
	22: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `block in destroy'
	21: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:341:in `destroy'
	20: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/locking/optimistic.rb:109:in `destroy_row'
	19: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/counter_cache.rb:196:in `destroy_row'
	18: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:677:in `destroy_row'
	17: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:681:in `_delete_row'
	16: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:207:in `_delete_record'
	15: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `delete'
	14: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:176:in `delete'
	13: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:94:in `exec_delete'
	12: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
	11: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
	10: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
	 9: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
	 8: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
	 7: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `synchronize'
	 6: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
	 5: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
	 4: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 3: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 2: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 1: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `exec_params': ERROR:  duplicate key value violates unique constraint "index_statuses_on_uri" (PG::UniqueViolation)
DETAIL:  Key (uri)=(<REDACTED>) already exists.
CONTEXT:  SQL statement "UPDATE ONLY "public"."statuses" SET "in_reply_to_account_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "in_reply_to_account_id""
	54: from ./bin/tootctl:8:in `<main>'
	53: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	52: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	51: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	50: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	49: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	48: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	47: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	46: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	44: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:145:in `fix_duplicates'
	43: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:175:in `deduplicate_accounts!'
	42: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/result.rb:57:in `each'
	41: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/result.rb:57:in `each'
	40: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/result.rb:57:in `block in each'
	39: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:181:in `block in deduplicate_accounts!'
	38: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:518:in `deduplicate_remote_accounts!'
	37: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:518:in `each'
	36: from /opt/mastodon/lib/mastodon/maintenance_cli.rb:525:in `block in deduplicate_remote_accounts!'
	35: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `destroy'
	34: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
	33: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
	32: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
	31: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
	30: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
	29: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
	28: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
	27: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
	26: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `block in destroy'
	25: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `destroy'
	24: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_destroy_callbacks'
	23: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
	22: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `block in destroy'
	21: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:341:in `destroy'
	20: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/locking/optimistic.rb:109:in `destroy_row'
	19: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/counter_cache.rb:196:in `destroy_row'
	18: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:677:in `destroy_row'
	17: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:681:in `_delete_row'
	16: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:207:in `_delete_record'
	15: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `delete'
	14: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:176:in `delete'
	13: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:94:in `exec_delete'
	12: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
	11: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
	10: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
	 9: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
	 8: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
	 7: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `synchronize'
	 6: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
	 5: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
	 4: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 3: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 2: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 1: from /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `exec_params': PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_statuses_on_uri" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (uri)=(<REDACTED>) already exists.
CONTEXT:  SQL statement "UPDATE ONLY "public"."statuses" SET "in_reply_to_account_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "in_reply_to_account_id""
: DELETE FROM "accounts" WHERE "accounts"."id" = $1
```

### Steps to reproduce the problem

Unknown

### Specifications

using v3.3.0 docker

**Comment by ClearlyClaire** [comment]
1. have you ensured the server was stopped before running the task?
2. if so, what happens if you edit `lib/mastodon/maintenance_cli.rb` to move the `deduplicate_accounts!` on line 145 below `deduplicate_statuses!` on line 159?

**Comment by hutchisr** [comment]
Yes, made sure to bring everything down before running it.

I ended up just manually running a query to delete statuses with duplicate uris and it was able to complete, but changing the order the maintenance script runs might be a good idea to prevent this from being an issue for someone else
