### ISSUE TITLE
Error 500 on /api/v1/favourite: NoMethodError: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by angristan** [tootsuite/mastodon#15946]
### Expected behaviour

User should be able to see all their favourites

### Actual behaviour

As some point the user receives an error 500:

```
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] method=GET path=/api/v1/favourites format=html controller=Api::V1::FavouritesController action=index status=500 error='NoMethodError: undefined method `id' for nil:NilClass' duration=35.74 view=0.00 db=17.20
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1]
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] NoMethodError (undefined method `id' for nil:NilClass):
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1]
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] app/controllers/concerns/cache_concern.rb:36:in `map'
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] app/controllers/concerns/cache_concern.rb:36:in `cache_collection'
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] app/controllers/api/v1/favourites_controller.rb:20:in `cached_favourites'
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] app/controllers/api/v1/favourites_controller.rb:16:in `load_statuses'
Mar 23 11:18:17 yuri bundle[682]: [41d07a3b-4f69-440b-a127-113157fe9fd1] app/controllers/api/v1/favourites_controller.rb:9:in `index'
```

### Steps to reproduce the problem

> when I try to go far into my likes history I get some HTTP 500 error on the `https://mstdn.io/api/v1/favourites?max_id=1314631` endpoint

This might be specific to this user.

### Specifications

v.3.3.0

Let me know if I can provide more info.  Could it be another broken foreign key issue?

**Comment by angristan** [comment]
Not a bug, see https://github.com/tootsuite/mastodon/issues/12916#issuecomment-841871652
