### ISSUE TITLE
Streaming errors. "Error: Invalid access token"

### ISSUE THREAD

**Issue by raymestalez** [tootsuite/mastodon#1615]
After pulling the most recent code, and rebuilding containers, I'm getting errors:

```
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63 Error: Invalid access token
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Query.<anonymous> (/mastodon/streaming/index.js:101:15)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Query.handleReadyForQuery (/mastodon/node_modules/pg/lib/query.js:112:10)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Connection.<anonymous> (/mastodon/node_modules/pg/lib/client.js:172:19)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at emitOne (events.js:101:20)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Connection.emit (events.js:188:7)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Socket.<anonymous> (/mastodon/node_modules/pg/lib/connection.js:121:12)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at emitOne (events.js:96:13)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Socket.emit (events.js:188:7)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at readableAddChunk (_stream_readable.js:176:18)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Socket.Readable.push (_stream_readable.js:134:10)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63  { Error: Invalid access token
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Query.<anonymous> (/mastodon/streaming/index.js:101:15)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Query.handleReadyForQuery (/mastodon/node_modules/pg/lib/query.js:112:10)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Connection.<anonymous> (/mastodon/node_modules/pg/lib/client.js:172:19)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at emitOne (events.js:101:20)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Connection.emit (events.js:188:7)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Socket.<anonymous> (/mastodon/node_modules/pg/lib/connection.js:121:12)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at emitOne (events.js:96:13)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Socket.emit (events.js:188:7)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at readableAddChunk (_stream_readable.js:176:18)
streaming_1  | ERR! 63f4ee7a-88b8-42e0-9e04-5b081f9c9b63     at Socket.Readable.push (_stream_readable.js:134:10) statusCode: 401 }
```

Does anyone know what that means?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by raymestalez** [comment]
Tried to revert to [0687ab8](https://github.com/tootsuite/mastodon/commit/0687ab8ae3c2573ba2aa1d37f62e3583d0c7ab01), as recommended in [this issue](https://github.com/tootsuite/mastodon/issues/1491), but it still doesn't work.

**Comment by raymestalez** [comment]
Sorry, nevermind, it appears I've messed up with my nginx config.

**Comment by tchncs** [comment]
@raymestalez while i so far match the official recommended nginx config for streaming, what was your cause?
I got this (or similar) problem after the latest upgrade. Maybe you have a hint that triggers an idea over here.

**Comment by Gargron** [comment]
>Error: Invalid access token

is not a server error, it's a user error. It means the access token someone tried to access with was invalid. This was added recently, as previously the streaming API mistakenly ignored that some access tokens were revoked or expired.
