### ISSUE TITLE
Development of Mastodon: RAILS_ENV=development rails db:setup got no such file

### ISSUE THREAD

**Issue by guanyun-helo** [tootsuite/mastodon#16179]
### Expected behaviour
Create the databases mastodon_development and mastodon_tes

### Actual behaviour
````
 RAILS_ENV=development rails db:setup
Traceback (most recent call last):
	4: from bin/rails:3:in `<main>'
	3: from bin/rails:3:in `require_relative'
	2: from /home/guanyun/project/mastodon/config/boot.rb:8:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

````

### Steps to reproduce the problem
Follow the doc of develop Mastodon
https://docs.joinmastodon.org/dev/setup/

### Specifications
commit hash : 68181b95064d522dbd9b41b15e7716d03c333c0e
system: ubuntu 1804

**Comment by guanyun-helo** [comment]
Just want to know the fastest way to develop Mastodon locally.
