### ISSUE TITLE
SAML login attempt results in `OpenSSL::X509::CertificateError (nested asn1 error)` stack trace

### ISSUE THREAD

**Issue by decentral1se** [tootsuite/mastodon#16327]
### Expected behaviour

I'm using Mastodon and Keycloak SSO. I've setup SAML authentication on both sides. SAML login should succeed.

### Actual behaviour

When I try to log in, Mastodon throws a stack trace with an error from `OpenSSL::X509::CertificateError (nested asn1 error)`. This happens on the final step of the SSO flow. The validation of the certificate. While in previous attempts the fingerprint/certificate did not validate, I received a proper error message and could respond to it. Here, I receive a stack trace so it feels like a bug.

Here are the full logs:

```
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] OpenSSL::X509::CertificateError (nested asn1 error):
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa]   
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/settings.rb:157:in `initialize'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/settings.rb:157:in `new'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/settings.rb:157:in `get_idp_cert'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/response.rb:837:in `validate_signature'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/response.rb:381:in `block in validate'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/response.rb:381:in `all?'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/response.rb:381:in `validate'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] ruby-saml (1.11.0) lib/onelogin/ruby-saml/response.rb:77:in `is_valid?'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth-saml (1.10.3) lib/omniauth/strategies/saml.rb:136:in `handle_response'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth-saml (1.10.3) lib/omniauth/strategies/saml.rb:49:in `block in callback_phase'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth-saml (1.10.3) lib/omniauth/strategies/saml.rb:218:in `with_settings'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth-saml (1.10.3) lib/omniauth/strategies/saml.rb:45:in `callback_phase'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth (1.9.1) lib/omniauth/strategy.rb:238:in `callback_call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth (1.9.1) lib/omniauth/strategy.rb:189:in `call!'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack-attack (6.5.0) lib/rack/attack.rb:99:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] makara (0.5.0) lib/makara/middleware.rb:16:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/deflater.rb:44:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack-attack (6.5.0) lib/rack/attack.rb:113:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] warden (1.2.9) lib/warden/manager.rb:34:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/etag.rb:27:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/head.rb:12:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] activesupport (6.1.3.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] chewy (5.2.0) lib/chewy/railtie.rb:19:in `block in call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] chewy (5.2.0) lib/chewy/strategy.rb:70:in `wrap'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] chewy (5.2.0) lib/chewy.rb:201:in `strategy'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] chewy (5.2.0) lib/chewy/railtie.rb:19:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `block in call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:37:in `tagged'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `tagged'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/static.rb:24:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/ssl.rb:77:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] actionpack (6.1.3.2) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] railties (6.1.3.2) lib/rails/engine.rb:539:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] puma (5.3.0) lib/puma/configuration.rb:249:in `call'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] puma (5.3.0) lib/puma/request.rb:76:in `block in handle_request'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] puma (5.3.0) lib/puma/thread_pool.rb:338:in `with_force_shutdown'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] puma (5.3.0) lib/puma/request.rb:75:in `handle_request'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] puma (5.3.0) lib/puma/server.rb:437:in `process_client'
social_example_com_web.1.chg2r74a3ak0@hoster-collective    | [c6b1c2d9-26c5-456c-95a7-cb4cf1a0e0aa] puma (5.3.0) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

### Steps to reproduce the problem

- Setup a Keycloak 12.0.4
- Setup a Mastodon 3.4.0
- Use something like the following config on Mastodon side:

```
SAML_ENABLED=true
SAML_ACS_URL="https://example.mastodon.com/auth/auth/saml/callback"
SAML_ISSUER=mastodon
SAML_IDP_SSO_TARGET_URL="https://example.keycloak.com/auth/realms/example-realm/protocol/saml"
SAML_IDP_CERT="-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
SAML_IDP_CERT_FINGERPRINT="..."
SAML_NAME_IDENTIFIER_FORMAT="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
# SAML_CERT=
SAML_SECURITY_WANT_ASSERTION_SIGNED=true
# SAML_SECURITY_WANT_ASSERTION_ENCRYPTED=
SAML_SECURITY_ASSUME_EMAIL_IS_VERIFIED=true
SAML_ATTRIBUTES_STATEMENTS_UID=uid
SAML_ATTRIBUTES_STATEMENTS_EMAIL=email
# SAML_ATTRIBUTES_STATEMENTS_FULL_NAME=
SAML_ATTRIBUTES_STATEMENTS_FIRST_NAME=first_name
SAML_ATTRIBUTES_STATEMENTS_LAST_NAME=last_name
# SAML_UID_ATTRIBUTE=
# SAML_ATTRIBUTES_STATEMENTS_VERIFIED=
# SAML_ATTRIBUTES_STATEMENTS_VERIFIED_EMAIL=
```

- Setup a Keycloak SAML client following [these docs](https://blog.rosenberg-watt.com/2019/11/15/mastodon-and-keycloak-saml/) and turning off `Client Signature Required` because that [is a bug](https://stackoverflow.com/questions/50619575/keycloak-and-spring-saml-sigalg-was-null) in Keycloak (:see_no_evil:)

### Specifications

`v3.4.0` mastodon.

`12.0.4` keycloak.

**Comment by decentral1se** [comment]
To clarify the previous message I was getting before this was:

> ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Fingerprint mismatch

So, I am quite confident that I get them to match in my `.env` config.

**Comment by decentral1se** [comment]
From f47c177eb741a99fef5708175a0a3d4dfcc02639 I see that @kaiyou is also using a SAML config, got any ideas here? (hope you don't mind the ping)

**Comment by weex** [comment]
Searches for "nested asn1 error" say you might try with a newline at the end of your cert.

The code probably just needs to catch and log the exception.

**Comment by decentral1se** [comment]
Yeah tried that new line thing @weex, thanks. Unfortunately, didn't work :( I think you're right about the exception catching! It seems like it is to do with something else here. In any case, I ended up using the #16221 and that works really nicely.

**Comment by xgaia** [comment]
Hello here, the `SAML_IDP_CERT` variable must contain the certificate without the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` part.

```
SAML_IDP_CERT=blablabla
```
Instead of

```
SAML_IDP_CERT=-----BEGIN CERTIFICATE-----blablabla-----END CERTIFICATE-----
```
