### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by Pym** [tootsuite/mastodon#1644]
Hello,

I'm trying to run `docker-compose build` but I got this vague error.

P.S. I'm using a BareMetal C1 @ [Scaleway](https://www.scaleway.com/pricing/).

```
$ docker-compose build
redis uses an image, skipping
db uses an image, skipping
Building streaming
Step 1 : FROM ruby:2.4.1-alpine
 ---> 5eadd5d1419a
Step 2 : LABEL maintainer "https://github.com/tootsuite/mastodon" description "A GNU Social-compatible microblogging server"
 ---> Using cache
 ---> 4a90441934d8
Step 3 : ENV RAILS_ENV production NODE_ENV production
 ---> Using cache
 ---> f434ba755d62
Step 4 : EXPOSE 3000 4000
 ---> Using cache
 ---> 1e989cab23b2
Step 5 : WORKDIR /mastodon
 ---> Using cache
 ---> 8e451403f98f
Step 6 : COPY Gemfile Gemfile.lock package.json yarn.lock /mastodon/
 ---> Using cache
 ---> 997d16b9d3a5
Step 7 : RUN BUILD_DEPS="     postgresql-dev     libxml2-dev     libxslt-dev     build-base"  && apk -U upgrade && apk add     $BUILD_DEPS     nodejs     libpq     libxml2     libxslt     ffmpeg     file     imagemagick  && npm install -g npm@3 && npm install -g yarn  && bundle install --deployment --without test development  && yarn  && yarn cache clean  && npm -g cache clean  && apk del $BUILD_DEPS  && rm -rf /tmp/* /var/cache/apk/*
 ---> Running in b5caf1c39c05
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x3339c8, 0x107e6ac0)
	/usr/local/go/src/runtime/panic.go:481 +0x330
github.com/urfave/cli.HandleAction.func1(0x107c1958)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x328
panic(0x3339c8, 0x107e6ac0)
	/usr/local/go/src/runtime/panic.go:443 +0x448
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x107c15e0, 0x1071a240, 0x107c1668)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x13c
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x1075cf30, 0xb6556490, 0x107e6ac0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x498
main.glob.func8(0x1078e320, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x58
reflect.Value.call(0x2e90f8, 0x3efd4c, 0x13, 0x362250, 0x4, 0x107c1918, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0xeb4
reflect.Value.Call(0x2e90f8, 0x3efd4c, 0x13, 0x107c1918, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0x84
github.com/urfave/cli.HandleAction(0x2e90f8, 0x3efd4c, 0x1078e320, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x230
github.com/urfave/cli.Command.Run(0x364678, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3ce288, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xcd0
github.com/urfave/cli.(*App).Run(0x10780240, 0x10762050, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x84c
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xbb4
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c BUILD_DEPS="     postgresql-dev     libxml2-dev     libxslt-dev     build-base"  && apk -U upgrade && apk add     $BUILD_DEPS     nodejs     libpq     libxml2     libxslt     ffmpeg     file     imagemagick  && npm install -g npm@3 && npm install -g yarn  && bundle install --deployment --without test development  && yarn  && yarn cache clean  && npm -g cache clean  && apk del $BUILD_DEPS  && rm -rf /tmp/* /var/cache/apk/*' returned a non-zero code: 2
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ericblade** [comment]
Only references I see to that specific error message indicate that someone is building something for the wrong platform . . . ? arm vs x64 ?

**Comment by Gargron** [comment]
This is a Go language stacktrace. Docker is written in Go. This is Docker crashing. I don't know why, but restarting the Docker service might help.

**Comment by vielmetti** [comment]
I'm not familiar with Scaleway, but that message is consistent with Docker running an image that is not the correct architecture:

`	panic: standard_init_linux.go:175: exec user process caused "exec format error"`

You running on ARM?

**Comment by Pym** [comment]
@vielmetti indeed! I just realised this... I had no idea that it wasn't compatible 😞 

Related to #802, closing.
