### ISSUE TITLE
Can't federate: "uninitialized constant XrdController"

### ISSUE THREAD

**Issue by CapacitorSet** [tootsuite/mastodon#1793]
I set up a Mastodon instance. However, when I try to do a remote follow, the remote server requests two files in .well-known giving a 404 error:

```
a.b.c.d - - [14/Apr/2017:13:17:48 +0000] "GET /.well-known/host-meta HTTP/1.1" 200 203 "-" "http.rb/2.2.1"
a.b.c.d - - [14/Apr/2017:13:17:48 +0000] "GET /.well-known/webfinger?resource=acct:username@host HTTP/1.1" 404 34 "-" "http.rb/2.2.1"
```

Also, the log gives an `ActionController::RoutingError`, with the following stack trace:

```
ActionController::RoutingError (uninitialized constant XrdController):
  
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `const_get'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `block in constantize'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `each'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `inject'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `constantize'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:583:in `get'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:614:in `constantize'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/http/request.rb:81:in `controller_class'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:44:in `controller'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:30:in `serve'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `each'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `serve'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:725:in `call'
vendor/bundle/ruby/2.4.0/gems/http_accept_language-2.1.0/lib/http_accept_language/middleware.rb:14:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/deflater.rb:35:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/lograge-0.4.1/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:122:in `block in call'
vendor/bundle/ruby/2.4.0/gems/rack-timeout-0.4.2/lib/rack/timeout/support/timeout.rb:19:in `timeout'
vendor/bundle/ruby/2.4.0/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:121:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:81:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
You might need to restart your server?

Those files were moved recently, so if you are running a very new deploy and haven't done a full server restart, it might be looking for things which don't exist anymore.

**Comment by CapacitorSet** [comment]
Ehh, dunno, I eventually rebuilt Mastodon and now it works smoothly.

Closing this.
