### ISSUE TITLE
Brand new instance with SINGLE_USER_MODE=true fails with an exception

### ISSUE THREAD

**Issue by saper** [tootsuite/mastodon#1817]
Trying to access brand new `SINGLE_USER_MODE=true` instance right after installation causes:

````
[f593578a-1a02-4572-98a1-ff79126279df] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]' duration=99.90 view=0.00 db=20.01
[f593578a-1a02-4572-98a1-ff79126279df]   
[f593578a-1a02-4572-98a1-ff79126279df] ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]):
[f593578a-1a02-4572-98a1-ff79126279df]   
[f593578a-1a02-4572-98a1-ff79126279df] app/controllers/home_controller.rb:15:in `authenticate_user!'
[f593578a-1a02-4572-98a1-ff79126279df] app/controllers/concerns/localized.rb:24:in `block in set_locale'
[f593578a-1a02-4572-98a1-ff79126279df] app/controllers/concerns/localized.rb:23:in `set_locale'
````
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jamesmwright** [comment]
Try to change the value to =false and reload the web and worker components and see if it comes up. Or try visiting https://instance.tld/auth/sign_in and see if that page loads. Then create a user and promo it to admin using the cmd: 

RAILS_ENV=production bundle exec rails mastodon:make_admin USERNAME=new_usr_just_created

Let me know if that helps. Take care. ~James
