### ISSUE TITLE
Ox can not dump control character

### ISSUE THREAD

**Issue by alpaca-tc** [tootsuite/mastodon#1870]
`AtomSerializer` depends on [Ox](https://github.com/ohler55/ox).
Currently some user have saved control character. However `AtomSerializer` can not dump it.

```
CONTROL_CHARACTER = ["\v", "\f", "\b"]

CONTROL_CHARACTER.each do |string|
  Ox.dump(Account.new(note: string)) 
end
# "\v" => SyntaxError: '\#x08' is not a valid XML character.
# "\f" => SyntaxError: '\#x0c' is not a valid XML character.
# "\b" => SyntaxError: '\#x0b' is not a valid XML character.
```

Should we remove control character from string attribute?
I don’t know what to do about that. 😕 

```
*A* `SyntaxError` *occurred while* `GET </users/XXXXXXXXX.atom>` *was processed by* `accounts#show`
Exception
----------------
'\#x08' is not a valid XML character.

XXX/app/lib/atom_serializer.rb:10:in `dump'
XXX/app/lib/atom_serializer.rb:10:in `render'
XXX/app/controllers/accounts_controller.rb:20:in `block (2 levels) in show'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Opened #1876 with a fix but - are these *all* problematic characters, or are there more?

**Comment by alpaca-tc** [comment]
@Gargron I try to remove invalid chars from attributes. I would it be alright to continue...? I have no confidence 😕 

```
# 1. Do not allow invalid chars
class XmlString < ActiveModel::Type::String
  # https://www.w3.org/TR/2000/REC-xml-20001006#charsets
  XML_CHARS = /[\u0000-\u10FFFF]/ # \u10FFFF < is valid
  INVALID_XML_CHARS = /[^\u0009\u000a\u000d\u0020-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]/

  private

  def cast_value(*)
    super.gsub(XML_CHARS) { |char| char.remove(INVALID_XML_CHARS) }
  end
end

ActiveRecord::Type.register(:xml_string, XmlString)
Account.attribute(:note, :xml_string) # All string attributes for atom should be register this.
```

```
# 2. Remove invalid chars everytime
class AtomSerializer
  # https://www.w3.org/TR/2000/REC-xml-20001006#charsets
  XML_CHARS = /[\u0000-\u10FFFF]/ # \u10FFFF < is valid
  INVALID_XML_CHARS = /[^\u0009\u000a\u000d\u0020-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]/

  class << self
    def render(element)
      document = Ox::Document.new(version: '1.0')
      document << element
      ('<?xml version="1.0"?>' + Ox.dump(remove_invalid_string(element))).force_encoding('UTF-8')
    end

    private

    def remove_invalid_string(element)
      # Remove invalid attributes from element somehow
    end
  end
end
```
