### ISSUE TITLE
Issue with Rake Users Clear

### ISSUE THREAD

**Issue by xvilo** [tootsuite/mastodon#1963]
I've just updated to `V1.2` and tried the new ` rake mastodon:users:clear` command. Only to see this output:
```
**************************************************
⛔️ WARNING: Sidekiq testing API enabled, but this is not the test environment.  Your jobs will not go to Redis.
**************************************************
rake aborted!
NameError: uninitialized constant ActiveRecordQueryTrace
/home/mastodon/live/config/environments/development.rb:85:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:599:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:599:in `block in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
/home/mastodon/live/config/environment.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
Tasks: TOP => mastodon:users:clear => environment
(See full trace by running task with --trace)
```

This seems to me as an Error, can somebody explain? What am I doing wrong? 
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Angristan** [comment]
`RAILS_ENV=production bundle exec rake mastodon:users:clear`

**Comment by Gargron** [comment]
Indeed, you didn't set the environment to be used.

**Comment by M-D-M** [comment]
Do the cronjobs in the production guide need to be changed? https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md

Tried running these manually and got the same error as xvilo did.

**Comment by Angristan** [comment]
The cronjob works fine here.

**Comment by M-D-M** [comment]
Yeah, nevermind -- remembered that part of the cronjob config is to put "RAILS_ENV=production" above the job.
