### ISSUE TITLE
All requests are failing with a 500 error

### ISSUE THREAD

**Issue by crodas** [tootsuite/mastodon#2023]
I believe something is wrong with my caching and settings for some odd reasons.

```log
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] method=GET path=/about format=*/* controller=AboutController action=show status=500 error='ActionView::Template::Error: Name or service not known' duration=101.72 view=0.00
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] ActionView::Template::Error (Name or service not known):
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]      5:   = Rails.configuration.x.local_domain
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]      6:
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]      7: - content_for :header_tags do
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]      8:   %meta{ property: 'og:site_name', content: site_title }/
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]      9:   %meta{ property: 'og:type', content: 'website' }/
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]     10:   %meta{ property: 'og:title', content: Rails.configuration.x.local_domain }/
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]     11:   %meta{ property: 'og:description', content: strip_tags(@instance_presenter.site_description.blank? ? t('about.about_mastodon') : @instance_presenter.site_description) }/
[7ed8b895-9969-49e3-99cc-a66c5c064d1a]
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] app/models/setting.rb:14:in `[]'
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] app/helpers/site_title_helper.rb:5:in `site_title'
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] app/views/about/show.html.haml:8:in `block in _app_views_about_show_html_haml___2497941020885188308_47170059334140'
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] app/views/about/show.html.haml:7:in `_app_views_about_show_html_haml___2497941020885188308_47170059334140'
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] app/controllers/concerns/localized.rb:24:in `block in set_locale'
[7ed8b895-9969-49e3-99cc-a66c5c064d1a] app/controllers/concerns/localized.rb:23:in `set_locale'
```

**Comment by mjankowski** [comment]
Is this a new problem on what had been a working instance, or a problem setting up a new instance?

**Comment by crodas** [comment]
@mjankowski Setting up a new instance.

**Comment by mjankowski** [comment]
is `LOCAL_DOMAIN` set?

**Comment by Gargron** [comment]
Your redis host should probably be localhost

**Comment by crodas** [comment]
This is embarasing @Gargron, and yes. It fixes the problem. Can I create a pull request to either update the docs or change the `.env.production.sample` file?
