### ISSUE TITLE
Did update docker with master, then: "Error: Invalid access token"

### ISSUE THREAD

**Issue by saschafoerster** [tootsuite/mastodon#2035]
I followed the update instructions on your page for the docker installation, 

> Updating
> 
> This approach makes updating to the latest version a real breeze.
> 
> git pull to download updates from the repository
> docker-compose build to compile the Docker image out of the changed source files
> (optional) docker-compose run --rm web rails db:migrate to perform database migrations. Does nothing if your database is up to date
> (optional) docker-compose run --rm web rails assets:precompile to compile new JS and CSS assets
> docker-compose up -d to re-create (restart) containers and pick up the changes

but then the master version got installed. I tried to revert it back to v.1.12 but I still have plenty of errors: 

```
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3 Error: Invalid access token
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Query.<anonymous> (/mastodon/streaming/index.js:103:15)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Query.handleReadyForQuery (/mastodon/node_modules/pg/lib/query.js:112:10)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Connection.<anonymous> (/mastodon/node_modules/pg/lib/client.js:172:19)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at emitOne (events.js:101:20)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Connection.emit (events.js:188:7)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Socket.<anonymous> (/mastodon/node_modules/pg/lib/connection.js:121:12)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at emitOne (events.js:96:13)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Socket.emit (events.js:188:7)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at readableAddChunk (_stream_readable.js:176:18)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at Socket.Readable.push (_stream_readable.js:134:10)
streaming_1  | ERR! d98f13e5-9e83-467d-aa8d-934cc5af62f3     at TCP.onread (net.js:551:20)

```

I tried this, but it didn't really help:

> I had the same issue today - looks like the current HEAD is somehow broken. So here is what I did:
> 	• Make a full backup!
> 	• Backup .env.production and docker-compose.yml separetely (yes, I use docker)
> 	• Delete the complete local copy of the repository (make sure you keep your production data)
> 	• Delete precompiled assets
> 	• Do a clone as described here: https://github.com/tootsuite/mastodon#checking-out (e.g., the latest tagged(!) version)
> 	• merge the changes from the new docker-compose.yml (hint: "image" entries were added)
> 	• Do the db:migrate and assets:precompile tasks
> And everything worked again. However, this comes without guarantee. But it helped me.

* * * *

- [Sorry ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by saschafoerster** [comment]
I got Bonn.social back, but it seems as if all users and the toots are lost... :( is there any way of restoration without backups from postgresql?

**Comment by saschafoerster** [comment]
Okay, found the answer... it is not possible. So let's start fresh! ;)
