### ISSUE TITLE
Can't view /admin/pubsubhubbub

### ISSUE THREAD

**Issue by azzeman** [tootsuite/mastodon#2093]
I updated my instance today - everything works great. Federation, time-lines etc. But i can't click "PubSubHubbub" without getting an exception. 

I'm running mastodon in Ubuntu 16.04 - i followed every update-step that could find this is what my logs show:

```
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130] method=GET path=/admin/pubsubhubbub format=html controller=Admin::PubsubhubbubController action=index status=500 error='ActionView::Template::Error: undefined method `acct' for nil:NilClass' duration=19.06 view=0.00 db=1.97
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130] ActionView::Template::Error (undefined method `acct' for nil:NilClass):
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     13:     - @subscriptions.each do |subscription|
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     14:       %tr
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     15:         %td
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     16:           %samp= subscription.account.acct
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     17:         %td
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     18:           %samp= subscription.callback_url
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]     19:         %td
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130]
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130] app/views/admin/pubsubhubbub/index.html.haml:16:in `block in _app_views_admin_pubsubhubbub_index_html_haml__2677224090489302569_47459017425780'
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130] app/views/admin/pubsubhubbub/index.html.haml:13:in `_app_views_admin_pubsubhubbub_index_html_haml__2677224090489302569_47459017425780'
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130] app/controllers/concerns/localized.rb:24:in `block in set_locale'
Apr 18 19:00:32 masto bundle[241]: [57354fe6-9ea4-42e6-a6d7-58083712d130] app/controllers/concerns/localized.rb:23:in `set_locale'
```
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
There must be a subscription record on your instance which no longer has an account ... maybe the account got deleted?

**Comment by azzeman** [comment]
Hm. I haven't deleted any account. But i did run RAILS_ENV=production rake mastodon:users:clear

That should't create this issue - i guess.

**Comment by azzeman** [comment]
There was an id in the database that was broken - don't know how. I got some help on IRC doing a database question

`select s.id from subscriptions s left join accounts a on a.id = s.account_id where a.id is null;
`
That resulted in a ID that i deleted. (If you try this your self, make sure you do a dbbackup)

`delete from subscriptions where id='XXXXX'; `

Now it works great again 👍
