### ISSUE TITLE
Static gif upload fails

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2108]
When trying to upload any non-animated gif, the upload fails with a 500

Tested on v1.2

```
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] Command :: file -b --mime '/tmp/d60cc6a6fba8b5fe7c9d59f6c5fdef0a20170418-14-1c8sm2r.gif'
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] Command :: identify -format %n '/tmp/d60cc6a6fba8b5fe7c9d59f6c5fdef0a20170418-14-g31j0f.gif'
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] Command :: identify -format %n '/tmp/d60cc6a6fba8b5fe7c9d59f6c5fdef0a20170418-14-g31j0f.gif'
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] Command :: file -b --mime '/tmp/d60cc6a6fba8b5fe7c9d59f6c5fdef0a20170418-14-12znes6.gif'
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=500 error='IOError: closed stream' duration=106.30 view=0.00 db=5.52
[795947d7-3a61-4fc6-8ee8-3c7f0055a531]   
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] IOError (closed stream):
[795947d7-3a61-4fc6-8ee8-3c7f0055a531]   
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] app/controllers/api/v1/media_controller.rb:13:in `create'
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] app/controllers/concerns/localized.rb:24:in `block in set_locale'
[795947d7-3a61-4fc6-8ee8-3c7f0055a531] app/controllers/concerns/localized.rb:23:in `set_locale'
```

Heres the image i've been testing with
![hit-the-pinata](https://cloud.githubusercontent.com/assets/315139/25155666/977b15c0-2496-11e7-8a68-7904bc117205.gif)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by hugogameiro** [comment]
This was happening to me too and after installing version 1.2.1 that was released an hour ago, it's still happening.

**Comment by saper** [comment]
Getting 422 with 09dad88853966ca1f2de96881393da65f55340d7
````
[e3bdd66d-4aaa-4844-a581-7f9e0d04a7c0] Command :: file -b --mime '/tmp/1d105e25766154a7d210c72e0c38a7e920170419-51851-1pmh4ns.mp4'
[e3bdd66d-4aaa-4844-a581-7f9e0d04a7c0] [paperclip] Content Type Spoof: Filename 026cc5a67380f399.mp4 (image/gif from Headers, ["application/mp4", "audio/mp4", "video/mp4", "video/vnd.objectvideo"] from Extension), content type discovered from file command: image/gif. See documentation to allow this combination.
[e3bdd66d-4aaa-4844-a581-7f9e0d04a7c0] Command :: file -b --mime '/tmp/1d105e25766154a7d210c72e0c38a7e920170419-51851-n9jqrm.mp4'
[e3bdd66d-4aaa-4844-a581-7f9e0d04a7c0] [paperclip] Content Type Spoof: Filename 026cc5a67380f399.mp4 (image/gif from Headers, ["application/mp4", "audio/mp4", "video/mp4", "video/vnd.objectvideo"] from Extension), content type discovered from file command: image/gif. See documentation to allow this combination.
[e3bdd66d-4aaa-4844-a581-7f9e0d04a7c0] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=422 duration=774.71 view=0.60 db=7.81
````
and
````
$ file /tmp/1d105e25766154a7d210c72e0c38a7e920170419-51851-n9jqrm.mp4
/tmp/1d105e25766154a7d210c72e0c38a7e920170419-51851-n9jqrm.mp4: GIF image data, version 87a, 620 x 577
````

So `file(1)` is right here
