### ISSUE TITLE
Streaming crash randomly /  ws.on('error', function (e)

### ISSUE THREAD

**Issue by valentin2105** [tootsuite/mastodon#2114]
Hi
I encounter random crash with Streaming process,

I'm in latest release (v1.2) with latest Node installed (via the official Dockerfile). 

Here is the error (who pop and crash streaming < every hours).

```
verb 4b881d6f-34b7-45d1-b757-fd95d76e96f5 Starting stream from timeline:21512 for 21512
/mastodon/streaming/index.js:299
    ws.on('error', function (e) {
                                ^

Error: not opened
    at WebSocket.ping (/mastodon/node_modules/ws/lib/WebSocket.js:309:13)
    at Timeout._onTimeout (/mastodon/streaming/index.js:223:42)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mastodon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./streaming/index.js --presets es2015,stage-2
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mastodon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mastodon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mastodon/npm-debug.log

> mastodon@ start /mastodon
> babel-node ./streaming/index.js --presets es2015,stage-2
```
Any idea why I got this ? 

For now, I load balance between two streaming process, so, no downtime, but It's a bit problematic.

Thanks.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by valentin2105** [comment]
Solved with 1.2.2. (run fine from 2hours)
