### ISSUE TITLE
Error 500 when tooting or viewing ATOM feed

### ISSUE THREAD

**Issue by wirehack7** [tootsuite/mastodon#2206]
I'm on v1.2.2 now and I'm getting server error 500 when trying to toot something or viewing the ATOM feed. This happens **only** when tooting or for the ATOM feed. All other interaction (liking, boosting, following etc) are working.
OS: Ubuntu 16.04 LTS
Using Mastodon with Docker and Nginx.
Before the update to v1.2.2 it worked.

Log of NGINX:
```
*.*.*.* - - [20/Apr/2017:11:37:56 +0200] "POST /api/v1/statuses HTTP/1.1" 500 990 "https://social.0day.agency/web/getting-started" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 OPR/44.0.2510.857"
*.*.*.* - - [20/Apr/2017:11:40:31 +0200] "GET /users/wirehack7.atom HTTP/1.1" 500 990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 OPR/44.0.2510.857"
```
I searched the issues and found one with error 500, too. But it not fully describes the problem.
Any advice on what is going wrong with the latest release?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Check the logs in `docker logs mastodon_web_1 | grep status=500` then grep again with the unique request ID to get the full stacktrace of the corresponding error

**Comment by wirehack7** [comment]
Log shows that:
```
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=500 error='ActiveModel::UnknownAttributeError: unknown attribute 'language' for Status.' duration=29.39 view=0.00 db=2.71

[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=500 error='ActiveModel::UnknownAttributeError: unknown attribute 'language' for Status.' duration=29.39 view=0.00 db=2.71
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea]   
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] ActiveModel::UnknownAttributeError (unknown attribute 'language' for Status.):
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea]   
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] app/services/post_status_service.rb:17:in `call'
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] app/controllers/api/v1/statuses_controller.rb:60:in `create'
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] app/controllers/concerns/localized.rb:24:in `block in set_locale'
[838e2e7f-fcb0-4929-9bc0-1c177138d9ea] app/controllers/concerns/localized.rb:23:in `set_locale'

```

Shall I migrate the db again or will data get lost? @Gargron

**Comment by wirehack7** [comment]
Ok, sorry. It's written here: https://github.com/tootsuite/mastodon/releases/tag/v1.2.2
