### ISSUE TITLE
Error when doing db:migrate during upgrade from 1.2.2 to 1.3.2

### ISSUE THREAD

**Issue by imshyuan** [tootsuite/mastodon#2640]
I get the following error when doing db:migrate during upgrade 1.2.2 to 1.3.2. My site seems to work fine on 1.3.2 now, but is there a need to fix this?

```
mastodon@host:~/live$ RAILS_ENV=production bundle exec rails db:migrate
Migrating to CreateBlockMutes (20180428000000)
== 20180428000000 CreateBlockMutes: migrating =================================
-- create_table("block_mutes", {:force=>:casecade})
   -> 0.0150s
-- add_column(:blocks, :block, :boolean, {:null=>false})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "block" contains null values
: ALTER TABLE "blocks" ADD "block" boolean NOT NULL
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_column'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/home/mastodon/live/db/migrate/20180428000000_create_block_mutes.rb:11:in `change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  column "block" contains null values
: ALTER TABLE "blocks" ADD "block" boolean NOT NULL
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_column'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/home/mastodon/live/db/migrate/20180428000000_create_block_mutes.rb:11:in `change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
PG::NotNullViolation: ERROR:  column "block" contains null values
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_column'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/home/mastodon/live/db/migrate/20180428000000_create_block_mutes.rb:11:in `change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
master is not [v1.3.2](https://github.com/tootsuite/mastodon/releases/tag/v1.3.2). Please try with v1.3.2 tag.

**Comment by imshyuan** [comment]
@ykzts Hi, what do you mean by "please try with v1.3.2 tag"? Was I wrong with I execute "$ git pull"? Any help is much appreciated!

**Comment by ykzts** [comment]
@imshyuan 

```shell
$ git fetch
$ git checkout -b v1.3.2 refs/tags/v1.3.2
```

try it!

**Comment by imshyuan** [comment]
@ykzts I executed the two lines, this is what I got, are they okay? 
```
mastodon@host:~/live$ git fetch
mastodon@host:~/live$ git checkout -b v1.3.2 refs/tags/v1.3.2
M       app/assets/images/background-photo.jpg
M       app/assets/images/logo.png
M       app/assets/images/logo.svg
M       public/android-chrome-192x192.png
M       public/apple-touch-icon.png
M       public/favicon.ico
Switched to a new branch 'v1.3.2'
```

When I re-executed db:migrate and assets:precompile, there wasn't any lengthy output, does this mean i am clear from errors?
```
mastodon@host:~/live$ RAILS_ENV=production bundle exec rails db:migrate
mastodon@host:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
mastodon@host:~/live$
```

Thank you very much for your help! (I am a novice to github, so there are things I don't quite understand how they work)
