### ISSUE TITLE
Clear search button not working

### ISSUE THREAD

**Issue by lorthirk** [tootsuite/mastodon#2786]
Steps to reproduce:

1. Enter something in the search field on the left
1. Click on the "Clear" button at the right edge of the search field

Affected version: 1.2.2

Chrome call stack:
```
Uncaught TypeError: Cannot read property 'props' of undefined
    at value (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:35:20519)
    at Object.invokeGuardedCallback (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:993:62)
    at executeDispatch (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:672:595)
    at Object.executeDispatchesInOrder (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:672:1013)
    at executeDispatchesAndRelease (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:653:880)
    at executeDispatchesAndReleaseTopLevel (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:653:1125)
    at Array.forEach (native)
    at forEachAccumulated (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:1512:79)
    at Object.processEventQueue (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:653:3569)
    at runEventQueueInBatch (https://mastodonti.co/assets/application-7e9709f95d3e05fff11b54263843c132bc3eb36d22db935a211a092472a7f3ad.js:1002:104)
```
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by treby** [comment]
I tried to reproduce this bug on my instance(1.3.3), but couldn't. At least the edge version, this bug seems to be fixed.
