### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by maximeborges** [tootsuite/mastodon#2857]
I recreated a new mastodon instance on my new server, but this time not using Docker, and I get the following error when the application have to send an email (registration, password recovering):
![image](https://cloud.githubusercontent.com/assets/159235/25775775/6d425c76-32ad-11e7-9cc8-901a717adc47.png)
I used the same subdomain that I used for my previous instance, and the same mailgun account and ID, so I d'ont really know what is wrong. I'm using the 1.3-stable branch.

Full trace: 
```
redis (3.3.3) lib/redis/connection/ruby.rb:229:in `getaddrinfo'
redis (3.3.3) lib/redis/connection/ruby.rb:229:in `connect'
redis (3.3.3) lib/redis/connection/ruby.rb:313:in `connect'
redis (3.3.3) lib/redis/client.rb:336:in `establish_connection'
redis (3.3.3) lib/redis/client.rb:101:in `block in connect'
redis (3.3.3) lib/redis/client.rb:293:in `with_reconnect'
redis (3.3.3) lib/redis/client.rb:100:in `connect'
redis (3.3.3) lib/redis/client.rb:364:in `ensure_connected'
redis (3.3.3) lib/redis/client.rb:221:in `block in process'
redis (3.3.3) lib/redis/client.rb:306:in `logging'
redis (3.3.3) lib/redis/client.rb:220:in `process'
redis (3.3.3) lib/redis/client.rb:187:in `call_pipelined'
redis (3.3.3) lib/redis/client.rb:157:in `block in call_pipeline'
redis (3.3.3) lib/redis/client.rb:293:in `with_reconnect'
redis (3.3.3) lib/redis/client.rb:155:in `call_pipeline'
redis (3.3.3) lib/redis.rb:2304:in `block in multi'
redis (3.3.3) lib/redis.rb:58:in `block in synchronize'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
redis (3.3.3) lib/redis.rb:58:in `synchronize'
redis (3.3.3) lib/redis.rb:2296:in `multi'
sidekiq (4.2.10) lib/sidekiq/client.rb:178:in `block in raw_push'
connection_pool (2.2.1) lib/connection_pool.rb:64:in `block (2 levels) in with'
connection_pool (2.2.1) lib/connection_pool.rb:63:in `handle_interrupt'
connection_pool (2.2.1) lib/connection_pool.rb:63:in `block in with'
connection_pool (2.2.1) lib/connection_pool.rb:60:in `handle_interrupt'
connection_pool (2.2.1) lib/connection_pool.rb:60:in `with'
sidekiq (4.2.10) lib/sidekiq/client.rb:177:in `raw_push'
sidekiq (4.2.10) lib/sidekiq/client.rb:68:in `push'
sidekiq (4.2.10) lib/sidekiq/client.rb:126:in `push'
activejob (5.0.2) lib/active_job/queue_adapters/sidekiq_adapter.rb:20:in `enqueue'
activejob (5.0.2) lib/active_job/enqueuing.rb:76:in `block in enqueue'
activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
activejob (5.0.2) lib/active_job/logging.rb:15:in `block (3 levels) in <module:Logging>'
activejob (5.0.2) lib/active_job/logging.rb:44:in `block in tag_logger'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
activejob (5.0.2) lib/active_job/logging.rb:44:in `tag_logger'
activejob (5.0.2) lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
activesupport (5.0.2) lib/active_support/callbacks.rb:391:in `instance_exec'
activesupport (5.0.2) lib/active_support/callbacks.rb:391:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:285:in `block in halting'
activesupport (5.0.2) lib/active_support/callbacks.rb:447:in `block in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_enqueue_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
activejob (5.0.2) lib/active_job/enqueuing.rb:72:in `enqueue'
activejob (5.0.2) lib/active_job/configured_job.rb:13:in `perform_later'
actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:121:in `enqueue_delivery'
actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:76:in `deliver_later'
app/models/user.rb:27:in `send_devise_notification'
devise (4.2.1) lib/devise/models/confirmable.rb:119:in `send_confirmation_instructions'
devise (4.2.1) lib/devise/models/confirmable.rb:181:in `send_on_create_confirmation_instructions'
activesupport (5.0.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:232:in `block in conditional'
activesupport (5.0.2) lib/active_support/callbacks.rb:456:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:456:in `each'
activesupport (5.0.2) lib/active_support/callbacks.rb:456:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_commit_callbacks'
activerecord (5.0.2) lib/active_record/transactions.rb:354:in `committed!'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/transaction.rb:87:in `commit_records'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/transaction.rb:178:in `commit_transaction'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.2) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.2) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
activerecord (5.0.2) lib/active_record/transactions.rb:319:in `block in save'
activerecord (5.0.2) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
activerecord (5.0.2) lib/active_record/transactions.rb:318:in `save'
activerecord (5.0.2) lib/active_record/suppressor.rb:41:in `save'
bullet (5.5.1) lib/bullet/active_record5.rb:5:in `save'
devise (4.2.1) app/controllers/devise/registrations_controller.rb:17:in `create'
actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
bullet (5.5.1) lib/bullet/rack.rb:12:in `call'
http_accept_language (2.1.0) lib/http_accept_language/middleware.rb:14:in `call'
rack (2.0.1) lib/rack/deflater.rb:35:in `call'
rack-attack (5.0.1) lib/rack/attack.rb:147:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:100:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by Gargron** [comment]
Your redis host is set incorrectly. Outside of docker it's most likely localhost.

**Comment by maximeborges** [comment]
Thanks ! I will try to improve the development guide, I got lost so many times trying to follow it...
