### ISSUE TITLE
mastodon:push:clear doesn't work

### ISSUE THREAD

**Issue by yukota** [tootsuite/mastodon#2860]
Execute below command in v1.3.3.
`docker-compose run --rm web rake mastodon:push:clear
`

In this time, below error occured.
```
rake aborted!
NoMethodError: undefined method `successful?' for #<HTTP::Response:0x007fe20cf64c08>
/mastodon/app/services/unsubscribe_service.rb:8:in `call'
/mastodon/lib/tasks/mastodon.rake:75:in `block (4 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:59:in `block (2 levels) in find_each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:59:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:59:in `block in find_each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:121:in `block in find_in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:214:in `block in in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:198:in `loop'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:198:in `in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:120:in `find_in_batches'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/batches.rb:58:in `find_each'
/mastodon/lib/tasks/mastodon.rake:73:in `block (3 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => mastodon:push:clear
(See full trace by running task with --trace)
```

The reason of this problem is similar to #2799 .
Below code is should be fixed like #2799 .
https://github.com/tootsuite/mastodon/blob/master/app/services/unsubscribe_service.rb#L8

Thank you.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yukota** [comment]
Fixed by 5bea4241 .
Thank you.
