### ISSUE TITLE
Rebalance Allocation fails when compiling assets

### ISSUE THREAD

**Issue by ozcanzaferayan** [tootsuite/mastodon#2883]
When i run `RAILS_ENV=production bundle exec rails assets:precompile -- trace` I get this error
 
```
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
** Invoke webpacker:yarn_install (first_time)
** Execute webpacker:yarn_install
yarn install v0.24.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 6.55s.
** Invoke webpacker:compile (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Execute webpacker:verify_install
Webpacker is installed 🎉 🍰
Using /home/mastodon/live/config/webpack/paths.yml file for setting up webpack paths
** Invoke environment
** Execute webpacker:compile
Compiling webpacker assets 🎉
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x12b82ac [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: 0xa98e0b [node]
 6: v8::internal::MarkCompactCollector::EvacuateNewSpaceAndCandidates() [node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: v8::internal::Heap::MarkCompact() [node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
10: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [node]
11: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
12: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
13: v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [node]
14: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
15: v8::internal::JsonStringifier::SerializeArrayLikeSlow(v8::internal::Handle<v8::internal::JSReceiver>, unsigned int, unsigned int) [node]
16: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
17: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
18: v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
19: v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [node]
20: 0xc938a84167
Killed
rails aborted!
JSON::ParserError: 765: unexpected token at '<--- Last few GCs --->

[14575:0x29226f0]   239265 ms: Scavenge 448.4 (613.9) -> 432.7 (613.9) MB, 15.4 / 0.0 ms  allocation failure
[14575:0x29226f0]   239582 ms: Scavenge 453.0 (614.7) -> 437.3 (614.7) MB, 16.5 / 0.0 ms  allocation failure
[14575:0x29226f0]   240437 ms: Scavenge 459.5 (617.6) -> 444.0 (617.6) MB, 39.7 / 0.8 ms  allocation failure
[14575:0x29226f0]   240992 ms: Scavenge 464.0 (617.6) -> 449.2 (617.6) MB, 65.4 / 1.3 ms  allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.
'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:13:in `block (2 levels) in <top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:compile`
* * * *
```

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Perhaps, you have less memory in your environment.

**Comment by Deimos620** [comment]
I think so
