### ISSUE TITLE
Mastodon Streaming Fails

### ISSUE THREAD

**Issue by oedipuscomplex** [tootsuite/mastodon#3108]
```
May 18 05:01:29 unikitty npm[32459]: > mastodon@ start /home/mastodon/live
May 18 05:01:29 unikitty npm[32459]: > babel-node ./streaming/index.js --presets es2015,stage-2
May 18 05:01:31 unikitty npm[32459]: /home/mastodon/live/node_modules/ws/lib/PerMessageDeflate.js:8
May 18 05:01:31 unikitty npm[32459]: const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
May 18 05:01:31 unikitty npm[32459]:                        ^
May 18 05:01:31 unikitty npm[32459]: TypeError: this is not a typed array.
May 18 05:01:31 unikitty npm[32459]:     at Function.from (native)
May 18 05:01:31 unikitty npm[32459]:     at Object.<anonymous> (/home/mastodon/live/node_modules/ws/lib/PerMessageDeflate.js:8:24)
May 18 05:01:31 unikitty npm[32459]:     at Module._compile (module.js:410:26)
May 18 05:01:31 unikitty npm[32459]:     at Module._extensions..js (module.js:417:10)
May 18 05:01:31 unikitty npm[32459]:     at Object.require.extensions.(anonymous function) [as .js] (/home/mastodon/live/node_modules/babel-register/lib/node.js:152:7)
May 18 05:01:31 unikitty npm[32459]:     at Module.load (module.js:344:32)
May 18 05:01:31 unikitty npm[32459]:     at Function.Module._load (module.js:301:12)
May 18 05:01:31 unikitty npm[32459]:     at Module.require (module.js:354:17)
May 18 05:01:31 unikitty npm[32459]:     at require (internal/module.js:12:17)
May 18 05:01:31 unikitty npm[32459]:     at Object.<anonymous> (/home/mastodon/live/node_modules/ws/lib/WebSocket.js:16:27)
May 18 05:01:31 unikitty npm[32459]: npm ERR! Linux 4.4.0-77-generic
May 18 05:01:31 unikitty npm[32459]: npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
May 18 05:01:31 unikitty npm[32459]: npm ERR! node v4.2.6
May 18 05:01:31 unikitty npm[32459]: npm ERR! npm  v3.5.2
May 18 05:01:31 unikitty npm[32459]: npm ERR! code ELIFECYCLE
May 18 05:01:31 unikitty npm[32459]: npm ERR! mastodon@ start: `babel-node ./streaming/index.js --presets es2015,stage-2`
May 18 05:01:31 unikitty npm[32459]: npm ERR! Exit status 1
May 18 05:01:31 unikitty npm[32459]: npm ERR!
May 18 05:01:31 unikitty npm[32459]: npm ERR! Failed at the mastodon@ start script 'babel-node ./streaming/index.js --presets es2015,stage-2'.
May 18 05:01:31 unikitty npm[32459]: npm ERR! Make sure you have the latest version of node.js and npm installed.
May 18 05:01:31 unikitty npm[32459]: npm ERR! If you do, this is most likely a problem with the mastodon package,
May 18 05:01:31 unikitty npm[32459]: npm ERR! not with npm itself.
May 18 05:01:31 unikitty npm[32459]: npm ERR! Tell the author that this fails on your system:
May 18 05:01:31 unikitty npm[32459]: npm ERR!     babel-node ./streaming/index.js --presets es2015,stage-2
May 18 05:01:31 unikitty npm[32459]: npm ERR! You can get information on how to open an issue for this project with:
May 18 05:01:31 unikitty npm[32459]: npm ERR!     npm bugs mastodon
May 18 05:01:31 unikitty npm[32459]: npm ERR! Or if that isn't available, you can get their info via:
May 18 05:01:31 unikitty npm[32459]: npm ERR!     npm owner ls mastodon
May 18 05:01:31 unikitty npm[32459]: npm ERR! There is likely additional logging output above.
May 18 05:01:31 unikitty npm[32459]: npm ERR! Please include the following file with any support request:
May 18 05:01:31 unikitty npm[32459]: npm ERR!     /home/mastodon/live/npm-debug.log
May 18 05:01:31 unikitty systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
May 18 05:01:31 unikitty systemd[1]: mastodon-streaming.service: Unit entered failed state.
May 18 05:01:31 unikitty systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
May 18 05:01:31 unikitty systemd[1]: mastodon-streaming.service: Service hold-off time over, scheduling restart.
May 18 05:01:31 unikitty systemd[1]: Stopped mastodon-streaming.
```
Unsure of what could be the problem.

**Comment by ykzts** [comment]
You are using the old Node.js. It is better to use Node.js v6.

**Comment by Gargron** [comment]
Please upgrade to Node 6.x and reinstall the dependencies.
