### ISSUE TITLE
1.4 RC3: error compiling webpacker assets 

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#3304]
I thought it was time to tryout building 1.4 RC3 (actually commit [9afd7da](https://github.com/tootsuite/mastodon/commit/9afd7dadbf5ffa6ad0686da197b927230a101bea), cause of a for my locale critical bug fix).

I run Mastodon using Docker (17.03.1-ce, build c6d412e) on a up-to-date Debian 8.  My git files are owned by user 'todon' and live in /home/todon/live. I have no problems with building and running 1.3.3.

Before I started I did as root 'chown -R 991:991 /home/todon/live/public/system'.

'docker-compose build' is successful.

But 'docker-compose run --rm web rails assets:precompile' **fails**. Everything goes well, until or after it tries to compile the 'webpacker assets'. This is output:

    [...]
    Webpacker is installed 🎉 🍰
    Using /mastodon/config/webpack/paths.yml file for setting up webpack paths
    Compiling webpacker assets 🎉
    rails aborted!
    JSON::ParserError: 743: unexpected token at 'Webpack Bundle Analyzer saved stats file to /mastodon/public/packs/stats.json
    Webpack Bundle Analyzer saved report to /mastodon/public/packs/report.html
    '
    /mastodon/vendor/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:13:in `block (2 levels) in <top (required)>'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.2.14/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
    /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
    bin/rails:4:in `<main>'
    Tasks: TOP => webpacker:compile
    (See full trace by running task with --trace)

Also see https://discourse.joinmastodon.org/t/1-4-rc3-error-compiling-webpacker-assets/223 and https://github.com/tootsuite/mastodon/issues/3251 (that is maybe related, but not the same according @nolanlawson).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jeroenpraat** [comment]
FYI: I repeated the process, but not as user 'todon', but as user 'root' (in a copy of /home/todon/live), but I receive the same error. So it looks not like a permission issue.

**Comment by jeroenpraat** [comment]
An update:

* I did a git clone in the directory /home/todon/test.
* I copied the .env.production from  /home/todon/live. 
* I successfully did a 'docker-compose build'
* And (now it comes) I **successfully** did a 'docker-compose run --rm web rails assets:precompile'
* In /home/todon/live I moved public/packs and public/assets away, but that didn't solved the initial problem
* One thing I noticed was that /home/todon/**test**/public/system was owned by root after the build.

**Comment by jeroenpraat** [comment]
Found it! This is related to another issue (#2922), about app/assets/stylesheets/custom.scss. When I remove that file, it works. In the above issue there is nothing about the errors I received, but I suppose [this pull request](https://github.com/tootsuite/mastodon/pull/3332) will solve it.

Closing for now.

**Comment by jeroenpraat** [comment]
FYI: [This comment](https://github.com/tootsuite/mastodon/issues/2922#issuecomment-303647692) solved it and I'm running 1.4RC4 now.
