### ISSUE TITLE
JSON::ParserError: 743: unexpected token at '' when upgading from v1.3.3 to v1.4.1

### ISSUE THREAD

**Issue by Champomix** [tootsuite/mastodon#3424]
When running RAILS_ENV=production bundle exec rails assets:precompile command, i get this error log : 

```
yarn install v0.25.3
[1/4] Resolving packages...
⠂ fsevents@*
success Already up-to-date.
$ npm rebuild node-sass

> node-sass@4.5.2 install /home/mastodon/live/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/mastodon/live/node_modules/node-sass/vendor/linux-x64-51/binding.node

> node-sass@4.5.2 postinstall /home/mastodon/live/node_modules/node-sass
> node scripts/build.js

Binary found at /home/mastodon/live/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Binary is fine
node-sass@4.5.2 /home/mastodon/live/node_modules/node-sass
Done in 9.07s.
Webpacker is installed 🎉 🍰
Using /home/mastodon/live/config/webpack/paths.yml file for setting up webpack paths
Compiling webpacker assets 🎉

Killed
rails aborted!
JSON::ParserError: 743: unexpected token at ''
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:13:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
```

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Champomix** [comment]
Mybe solution is here : https://github.com/tootsuite/mastodon/issues/3251

**Comment by Champomix** [comment]
#3251 resolution was the solution. Need 2Go to run RAILS_ENV=production bundle exec rails assets:precompile
