### ISSUE TITLE
v1.4.1: Error while running "rake mastodon:daily"

### ISSUE THREAD

**Issue by Neustrashimy** [tootsuite/mastodon#3531]
hi.
I've upgraded Mastodon v1.3.3 to v1.4.1. (Non docker environment)
and I noticed that daily task was not working.

When I manually ran daily task, I got an error like following:

```
[mastodon@mstdn live]$ RAILS_ENV=production
[mastodon@mstdn live]$ /home/mastodon/.rbenv/shims/bundle exec rake --trace mastodon:daily
rake aborted!
NameError: uninitialized constant Annotate
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `block in with_bootsnap_fallback'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `without_bootsnap_cache'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `rescue in with_bootsnap_fallback'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
/home/mastodon/live/lib/tasks/auto_annotate_models.rake:43:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:654:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:654:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/application.rb:443:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:457:in `load_tasks'
/home/mastodon/live/Rakefile:6:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/bin/rake:22:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/home/mastodon/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
NameError: uninitialized constant Annotate
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
/home/mastodon/live/lib/tasks/auto_annotate_models.rake:43:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:654:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:654:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/application.rb:443:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:457:in `load_tasks'
/home/mastodon/live/Rakefile:6:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/bin/rake:22:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/home/mastodon/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
```

Please give me advice. thanks.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
```console
$ export RAILS_ENV=production
$ /home/mastodon/.rbenv/shims/bundle exec rake --trace mastodon:daily
```

or 

```console
$ RAILS_ENV=production /home/mastodon/.rbenv/shims/bundle exec rake --trace mastodon:daily
```

How about doing as above?

**Comment by Neustrashimy** [comment]
it works!
thank you.
