### ISSUE TITLE
error 500 on follow salmons from hubzilla

### ISSUE THREAD

**Issue by zotlabs** [tootsuite/mastodon#3582]
Having a bit of difficulty finding the issue here. I'm sending a follow salmon, sent as application/magic-env+xml and Mastodon seems to consistently return error 500. I've been told the error in the Mastodon logs was nil content return from the salmon controller (and therefore un-parseable) but those notes with the precise message aren't available to me at the moment. 

It is difficult to include XML code in markdown without mangling so the example salmon as sent can be found at https://macgirvin.com/cloud/mike/slap.txt

The same construct works correctly in GNU-Social and other statusnet implementations but has consistently failed on Mastodon. I'm specifically testing against techn.ical.ist and not certain what version is in use there.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yookoala** [comment]
@zotlabs you can safely escape your xml or other source code with ``` quotes. please read more in [this guide](https://guides.github.com/features/mastering-markdown/), especially the "Code" example.

Embeding content of [slap.txt](https://macgirvin.com/cloud/mike/slap.txt) here:

```xml

<?xml version="1.0" encoding="UTF-8" ?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xmlns:as="http://activitystrea.ms/spec/1.0/" xmlns:georss="http://www.georss.org/georss" xmlns:ostatus="http://ostatus.org/schema/1.0" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:media="http://purl.org/syndication/atommedia" xmlns:statusnet="http://status.net/schema/api/1/">
<author>
  <as:object-type>http://activitystrea.ms/schema/1.0/person</as:object-type>
  <id>https://hz.macgirvin.com/channel/hubzilla</id>
  <name>hubzilla</name>
  <uri>https://hz.macgirvin.com/channel/hubzilla</uri>
  <link rel="alternate" type="text/html" href="https://hz.macgirvin.com/channel/hubzilla" />
  <link rel="photo"  type="image/jpeg" media:width="300" media:height="300" href="https://hz.macgirvin.com/photo/profile/l/2" />
  <link rel="avatar" type="image/jpeg" media:width="300" media:height="300" href="https://hz.macgirvin.com/photo/profile/l/2" />
  <poco:preferredUsername>hubzilla</poco:preferredUsername>
  <poco:displayName>Hubzilla</poco:displayName>
</author>


<id>https://hz.macgirvin.com/display/20ad2048d77fba0d4fa64d7f5f9c12ce5374ce71a7c6ce811333b4a5ca7380df</id>
<title>Follow</title>
<published>2017-06-05T05:03:37Z</published>
<content type="html" >Hubzilla is now following delgado</content>
<as:verb>http://activitystrea.ms/schema/1.0/follow</as:verb>

<as:object>
  <as:object-type>http://activitystrea.ms/schema/1.0/person</as:object-type>
  <id>https://techn.ical.ist/users/delgado</id>
  <name>delgado</name>
  <uri>https://techn.ical.ist/users/delgado</uri>
  <link rel="alternate" type="text/html" href="https://techn.ical.ist/users/delgado" />
  <link rel="photo"  type="image/png" media:width="300" media:height="300" href="https://hz.macgirvin.com/photo/f59c15ced025fa2c3196cdb24f460361-4" />
  <link rel="avatar" type="image/png" media:width="300" media:height="300" href="https://hz.macgirvin.com/photo/f59c15ced025fa2c3196cdb24f460361-4" />
  <poco:preferredUsername>delgado</poco:preferredUsername>
  <poco:displayName>delgado</poco:displayName>
</as:object>


</entry>

```

**Comment by zotlabs** [comment]
Offtopic: Thanks for that. there are a lot of flavours of markdown and code blocks have the widest variation of rules. In the original spec it's four space on each line. Some products use tildes and some backticks and the number you use turns out to be significant in how the rendering is accomplished, and this also varies from project to project. Some terminate with a double line break and some terminate with an identical tilde/backtick sequence. I use markdown in a number of different projects. I did try several variations of these rules which all mangled the code before posting a link that I knew would actually display the code without any alteration...

**Comment by zotlabs** [comment]
More info - here's the log of the event from the Hubzilla side (perhaps the only relevant info is the endpoint and the request headers)

```
2017-06-05 20:00:05:LOG_INFO::network.php:358:z_post_url: z_post_url: error: https://techn.ical.ist/api/salmon/17977:
2017-06-05 20:00:05:LOG_INFO::network.php:359:z_post_url: z_post_url: debug: Array
(
    [url] => https://techn.ical.ist/api/salmon/17977
    [content_type] => text/html; charset=utf-8
    [http_code] => 500
    [header_size] => 300
    [request_size] => 203
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 1.087936
    [namelookup_time] => 0.270176
    [connect_time] => 0.419504
    [pretransfer_time] => 0.777635
    [size_upload] => 3909
    [size_download] => 990
    [speed_download] => 909
    [speed_upload] => 3593
    [download_content_length] => 990
    [upload_content_length] => 3909
    [starttransfer_time] => 0.927529
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 91.121.209.125
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 64.90.40.239
    [local_port] => 54673
    [request_header] => POST /api/salmon/17977 HTTP/1.1^M
User-Agent: Mozilla/5.0 (compatible; zot)^M
Host: techn.ical.ist^M
Accept: */*^M
Content-type: application/magic-envelope+xml^M
Content-length: 3909^M
Expect: 100-continue^M
^M

)

2017-06-05 20:00:05:LOG_INFO::gnusoc.php:306:gnusoc_queue_deliver: slap_deliver: queue post returned 500 from https://techn.ical.ist/api/salmon/17977
```

An attempt a few weeks ago with a different Mastodon server where we had limited log access:

```
[33mweb_1        |[0m 2017-05-11T13:45:20.717013427Z [6afc0160-8e8e-4012-8b66-929341b1b6e5] method=POST path=/api/salmon/1158 format=*/* controller=Api::SalmonController action=update status=500 error='TypeError: no implicit conversion of nil into String' duration=22.52 view=0.00 db=1.62
[33mweb_1        |[0m 2017-05-11T13:45:20.723677601Z [6afc0160-8e8e-4012-8b66-929341b1b6e5]   
[33mweb_1        |[0m 2017-05-11T13:45:20.723756683Z [6afc0160-8e8e-4012-8b66-929341b1b6e5] TypeError (no implicit conversion of nil into String):
[33mweb_1        |[0m 2017-05-11T13:45:20.723764380Z [6afc0160-8e8e-4012-8b66-929341b1b6e5]   
[33mweb_1        |[0m 2017-05-11T13:45:20.723770121Z [6afc0160-8e8e-4012-8b66-929341b1b6e5] app/services/verify_salmon_service.rb:7:in `call'
[33mweb_1        |[0m 2017-05-11T13:45:20.723775671Z [6afc0160-8e8e-4012-8b66-929341b1b6e5] app/controllers/api/salmon_controller.rb:25:in `verify?'
[33mweb_1        |[0m 2017-05-11T13:45:20.723784694Z [6afc0160-8e8e-4012-8b66-929341b1b6e5] app/controllers/api/salmon_controller.rb:10:in `update'
```

I've examined the code and there are recent changes that touch this, but from my reading of the changes will only prevent a nil return from getting parsed. We're trying to determine why there is a nil response at all. Obviously the salmon controller is seeing activity and non-nil content has been sent; but it is not arriving intact for an as yet unknown reason.

**Comment by Gargron** [comment]
The actual error happens in the OStatus2 gem, and gem traces are stripped from Rails logs. From experience, this means something about the Salmon payload format from Hubzilla is inconsistent with what our OStatus2 gem expects.

**Comment by zotlabs** [comment]
Ah right - I did neglect to include the actual salmon.  I will try and find a copy of the gem and see if I can figure out what it wants/expects to see. Do you have a pointer? 

```
<?xml version="1.0" encoding="UTF-8"?>
<me:env xmlns:me="http://salmon-protocol.org/ns/magic-env">
<me:data type="application/atom+xml">
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiID8-CjxlbnRyeSB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwNS9BdG9tIiB4bWxuczp0aHI9Imh0dHA6Ly9wdXJsLm9yZy9zeW5kaWNhdGlvbi90aHJlYWQvMS4wIiB4bWxuczphcz0iaHR0cDovL2FjdGl2aXR5c3RyZWEubXMvc3BlYy8xLjAvIiB4bWxuczpnZW9yc3M9Imh0dHA6Ly93d3cuZ2VvcnNzLm9yZy9nZW9yc3MiIHhtbG5zOm9zdGF0dXM9Imh0dHA6Ly9vc3RhdHVzLm9yZy9zY2hlbWEvMS4wIiB4bWxuczpwb2NvPSJodHRwOi8vcG9ydGFibGVjb250YWN0cy5uZXQvc3BlYy8xLjAiIHhtbG5zOm1lZGlhPSJodHRwOi8vcHVybC5vcmcvc3luZGljYXRpb24vYXRvbW1lZGlhIiB4bWxuczpzdGF0dXNuZXQ9Imh0dHA6Ly9zdGF0dXMubmV0L3NjaGVtYS9hcGkvMS8iPgo8YXV0aG9yPg0KICA8YXM6b2JqZWN0LXR5cGU-aHR0cDovL2FjdGl2aXR5c3RyZWEubXMvc2NoZW1hLzEuMC9wZXJzb248L2FzOm9iamVjdC10eXBlPg0KICA8aWQ-aHR0cHM6Ly9oei5tYWNnaXJ2aW4uY29tL2NoYW5uZWwvaHViemlsbGE8L2lkPg0KICA8bmFtZT5odWJ6aWxsYTwvbmFtZT4NCiAgPHVyaT5odHRwczovL2h6Lm1hY2dpcnZpbi5jb20vY2hhbm5lbC9odWJ6aWxsYTwvdXJpPg0KICA8bGluayByZWw9ImFsdGVybmF0ZSIgdHlwZT0idGV4dC9odG1sIiBocmVmPSJodHRwczovL2h6Lm1hY2dpcnZpbi5jb20vY2hhbm5lbC9odWJ6aWxsYSIgLz4NCiAgPGxpbmsgcmVsPSJwaG90byIgIHR5cGU9ImltYWdlL2pwZWciIG1lZGlhOndpZHRoPSIzMDAiIG1lZGlhOmhlaWdodD0iMzAwIiBocmVmPSJodHRwczovL2h6Lm1hY2dpcnZpbi5jb20vcGhvdG8vcHJvZmlsZS9sLzIiIC8-DQogIDxsaW5rIHJlbD0iYXZhdGFyIiB0eXBlPSJpbWFnZS9qcGVnIiBtZWRpYTp3aWR0aD0iMzAwIiBtZWRp\
YTpoZWlnaHQ9IjMwMCIgaHJlZj0iaHR0cHM6Ly9oei5tYWNnaXJ2aW4uY29tL3Bob3RvL3Byb2ZpbGUvbC8yIiAvPg0KICA8cG9jbzpwcmVmZXJyZWRVc2VybmFtZT5odWJ6aWxsYTwvcG9jbzpwcmVmZXJyZWRVc2VybmFtZT4NCiAgPHBvY286ZGlzcGxheU5hbWU-SHViemlsbGE8L3BvY286ZGlzcGxheU5hbWU-DQo8L2F1dGhvcj4NCgoKPGlkPmh0dHBzOi8vaHoubWFjZ2lydmluLmNvbS9kaXNwbGF5LzIwYWQyMDQ4ZDc3ZmJhMGQ0ZmE2NGQ3ZjVmOWMxMmNlNTM3NGNlNzFhN2M2Y2U4MTEzMzNiNGE1Y2E3MzgwZGY8L2lkPgo8dGl0bGU-Rm9sbG93PC90aXRsZT4KPHB1Ymxpc2hlZD4yMDE3LTA2LTA1VDA1OjAzOjM3WjwvcHVibGlzaGVkPgo8Y29udGVudCB0eXBlPSJodG1sIiA-SHViemlsbGEgaXMgbm93IGZvbGxvd2luZyBkZWxnYWRvPC9jb250ZW50Pgo8YXM6dmVyYj5odHRwOi8vYWN0aXZpdHlzdHJlYS5tcy9zY2hlbWEvMS4wL2ZvbGxvdzwvYXM6dmVyYj4KCjxhczpvYmplY3Q-DQogIDxhczpvYmplY3QtdHlwZT5odHRwOi8vYWN0aXZpdHlzdHJlYS5tcy9zY2hlbWEvMS4wL3BlcnNvbjwvYXM6b2JqZWN0LXR5cGU-DQogIDxpZD5odHRwczovL3RlY2huLmljYWwuaXN0L3VzZXJzL2RlbGdhZG88L2lkPg0KICA8bmFtZT5kZWxnYWRvPC9uYW1lPg0KICA8dXJpPmh0dHBzOi8vdGVjaG4uaWNhbC5pc3QvdXNlcnMvZGVsZ2FkbzwvdXJpPg0KICA8bGluayByZWw9ImFsdGVybmF0ZSIgdHlwZT0idGV4dC9odG1sIiBocmVmPSJodHRwczovL3RlY2huLmljYWwuaXN0L3VzZXJzL2RlbGdhZG8iIC8-DQogIDxsaW5rIHJlbD0icGhvdG8iICB0eXBlPSJpbWFnZS9wbmciIG1lZGlhOndpZHRoPSIzMDAiIG1lZGlhOmhlaWdodD0iMzAwIiBocmVmPSJodHRwczovL2h6Lm1hY2dpcnZpbi5jb20vcGhvdG8vZjU5YzE1Y2VkMDI1ZmEyYzMxOTZjZGIyNGY0NjAzNjEtNCIgLz4NCiAgPGxpbmsgcmVsPSJhdmF0YXIiIHR5cGU9ImltYWdlL3BuZyIgbWVkaWE6d2lkdGg9IjMwMCIgbWVkaWE6aGVpZ2h0PSIzMDAiIGhyZWY9Imh0dHBzOi8vaHoubWFjZ2lydmluLmNvbS9waG90by9mNTljMTVjZWQwMjVmYTJjMzE5NmNkYjI0ZjQ2MDM2MS00IiAvPg0KICA8cG9jbzpwcmVmZXJyZWRVc2VybmFtZT5kZWxnYWRvPC9wb2NvOnByZWZlcnJlZFVzZXJuYW1lPg0KICA8cG9jbzpkaXNwbGF5TmFtZT5kZWxnYWRvPC9wb2NvOmRpc3BsYXlOYW1lPg0KPC9hczpvYmplY3Q-DQoKCjwvZW50cnk-Cgo=
</me:data>
<me:encoding>base64url</me:encoding>
<me:alg>RSA-SHA256</me:alg>
<me:sig key_id="MjZjYmY3ZjI4ODhlZjIzYjRjNGQ4OTQ5MDViOWY5YzEzZjY5ZTBhZjhkMDJmODU2M2JkNDQ5OTBmYTM0MWQzMA">m0lFhCYhX7dG8YP8SfEZInvpxNQgZxiWNaJfBgURjK6XVA9sZQxT6kZkiWdBv0eii_nXKsuej0egz6Z5Y1ix_7qGGCJ7nDqhudBdmpwJTSA0qUzQ6_JjhIqkSRdzf5qohYWsOG5doBwjfC_18kPc3__CONpIRNQUyDzDl7pFFEN3y7IIV-kDoHqFkh1z2SVN1xmcMB4yIu1d38zPhtZf3mmEaJB-lfozK-NSrIXY9fReNOOikZJCCu-EDxBPf6sVrkJqsUvSeR09d4lU1kwsSO1BaBe0Zm8oIzDa88p-G38jEXBQLHG3Lhj-CF1tF3KjoL8zxBXf9IK65DoGDnJDRaEkyX-jxYUUTpe8cKC5i8GF56lg43guEA1el734Lor1TRFrSQmYFKkgdfjAJcK0JKMOMsDN5ntO0f35SrfIOr644nPqWa88aFWGMkKzL34Z_pyCGJQYizT6eo-s8NCKReXy0hXuD1akBIVlqpJ-ZJGOJS9yy7AgYm-l176iyWFz1VAUc5I4XFevBIymUy4mifbzZyEdDW_nOrFJFAs0oI901XXM-nPZzwfItGMM4jDbKd5ibD1TfWnk17W-srOUaRKcv_sroCfpxpzrC03syRD35kUji_QoY5dtuSbsbagwrZxwf-9Pvof6y7JBS11TcwBsjdRfPPduBTESlosZC7w</me:sig>
</me:env>
```

**Comment by zotlabs** [comment]
Discovered the issue - I snagged a copy of the ostatus2 gem and ran through a bunch of stuff. The salmon controller isn't stripping whitespace (newlines, returns, spaces, tabs) as required by the salmon/magic-envelope spec. All whitespace must be removed *before* base64url decode. See section 5.2 of the magic-envelope spec. 

https://cdn.rawgit.com/salmon-protocol/salmon-protocol/master/draft-panzer-magicsig-01.html

The hubzilla magic-envelope has newlines between the data and the data tags. If these are removed the salmon is decoded properly. I can certainly get this to work on my end but it really needs to be fixed in the library.

**Comment by Gargron** [comment]
@zotlabs Do you mean all whitespace must be stripped out of this particular line? https://github.com/tootsuite/ostatus2/blob/master/lib/ostatus2/salmon.rb#L73

**Comment by zotlabs** [comment]
That one and the the signature on L75 as I believe both are subject to the magicsig "armoring" definition. I started doing something with .gsub("/\r\n\s+","") but haven't yet been able to test it.
