### ISSUE TITLE
We're sorry, but something went wrong. Error Just after updating

### ISSUE THREAD

**Issue by owlg** [tootsuite/mastodon#3951]
After updating by using `git fetch` and `git pull` and the docker updating steps, I am receiving this error everytime I try to log 

> We're sorry, but something went wrong.

When accessing the instance when logged out, I can still see the main page. But after logging in I get that error.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by noraworld** [comment]
It seems to be the browser cache. The same situation doesn't occur in my environment and instance.

Try it with the private browsing mode of your browser. Does such a situation still occur?

**Comment by owlg** [comment]
@noraworld Yes, I have already tried on Private Browsing on Chrome. The main page works but not after I logged in.

**Comment by noraworld** [comment]
@owlg After upgrading and taking a while (not after JUST upgrading), does the same situation still occur?

**Comment by owlg** [comment]
@noraworld After waiting for close to an hour, I am still encountering the same error

**Comment by noraworld** [comment]
@owlg Well, tell us the following 2 information.

- What versions did you upgrade from and to?
- Are you redirected to "/web/getting-started" when you access to the web root after logging in?

**Comment by Gargron** [comment]
You specified that this happens on master. Besides the warning not to run master in production environments, have you performed db:migrate?

**Comment by Magiccamera** [comment]
I was getting this after upgrading, but has somehow corrected itself after 10 or so mins of scratching my head. Could be a Rails cache thing.

**Comment by owlg** [comment]
@noraworld I've been redirected after logging in on incognito to "/auth/sign_in", on the normal web browser which I am already logged in to, I am not redirected.
I am upgraded from 1.4.3

**Comment by owlg** [comment]
@Gargron I've performed db:migrate and the precompile assets under Docker environment.

**Comment by noraworld** [comment]
@owlg I have no idea what is happening on your instance. How about trying to restart a Docker daemon? It helps when we don't know what is the cause. I resolved other issue by this way.

I tried:

```sh
$ systemctl restart docker
$ docker-compose kill
$ docker system prune -a
$ docker-compose build
```

**WARNING:** If the commands above run, all containers, images, volumes, and networks will be removed. So be carefully. If you would simply like to restart a Docker daemon, run `systemctl restart docker` only. All deletions are a last resort in case of a simple restart didn't solve the problem.

See also: #3817

Btw, if you would like to revert to v1.4.6, try this:

```sh
$ git fetch
$ git stash
$ git checkout v1.4.6
$ git stash pop
```

**Comment by Gargron** [comment]
Whenever you encounter a "something went wrong", please provide server logs. `docker logs mastodon_web_1` etc. The default error message is absolutely generic and provides no information other than there *is* an error.

**Comment by xvilo** [comment]
I have the exact same thing here. Just updated to lastest release with:
```cd live/
bundle install
yarn install
RAILS_ENV=production bundle exec rails db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
cd ../
```

I am not running this from docker. Where are the log files then @Gargron ?

**Comment by Gargron** [comment]
@xvilo The release notes for 1.4.1 ask you to run `mastodon:maintenance:prepare_for_foreign_keys` before `db:migrate`

**Comment by xvilo** [comment]
That did not work unfortunately. 
```journalctl -xf -u mastodon-*
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
mastodon@mastodon:~$ sudo journalctl -xf -u mastodon-*
-- Logs begin at Thu 2017-07-13 15:37:50 CEST. --
Jul 13 16:05:02 mastodon systemd[1]: Stopped mastodon-streaming.
-- Subject: Unit mastodon-streaming.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mastodon-streaming.service has finished shutting down.
Jul 13 16:05:02 mastodon systemd[1]: mastodon-streaming.service: Unit entered failed state.
Jul 13 16:05:02 mastodon systemd[1]: mastodon-streaming.service: Failed with result 'timeout'.
Jul 13 22:52:02 mastodon systemd[1]: Stopped mastodon-streaming.
-- Subject: Unit mastodon-streaming.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mastodon-streaming.service has finished shutting down.
Jul 13 22:52:02 mastodon systemd[1]: Started mastodon-streaming.
-- Subject: Unit mastodon-streaming.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mastodon-streaming.service has finished starting up.
-- 
-- The start-up result is done.
Jul 13 22:52:03 mastodon npm[12895]: > mastodon@ start /home/mastodon/live
Jul 13 22:52:03 mastodon npm[12895]: > node ./streaming/index.js
Jul 13 22:52:04 mastodon npm[12895]: info Starting streaming API server master with 1 workers
Jul 13 22:52:04 mastodon npm[12895]: info Starting worker 1
Jul 13 22:52:04 mastodon npm[12895]: info Worker 1 now listening on :::4000
Jul 13 22:56:36 mastodon systemd[1]: Stopping mastodon-streaming...
-- Subject: Unit mastodon-streaming.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mastodon-streaming.service has begun shutting down.
Jul 13 22:56:36 mastodon npm[12895]: info Worker 1 exiting, bye bye
Jul 13 22:56:51 mastodon systemd[1]: mastodon-streaming.service: State 'stop-final-sigterm' timed out. Killing.
Jul 13 22:56:51 mastodon systemd[1]: Stopped mastodon-streaming.
-- Subject: Unit mastodon-streaming.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mastodon-streaming.service has finished shutting down.
Jul 13 22:56:51 mastodon systemd[1]: mastodon-streaming.service: Unit entered failed state.
Jul 13 22:56:51 mastodon systemd[1]: mastodon-streaming.service: Failed with result 'timeout'.
Jul 13 22:56:51 mastodon systemd[1]: Started mastodon-streaming.
-- Subject: Unit mastodon-streaming.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mastodon-streaming.service has finished starting up.
-- 
-- The start-up result is done.
Jul 13 22:56:52 mastodon npm[13202]: > mastodon@ start /home/mastodon/live
Jul 13 22:56:52 mastodon npm[13202]: > node ./streaming/index.js
Jul 13 22:56:52 mastodon npm[13202]: info Starting streaming API server master with 1 workers
Jul 13 22:56:52 mastodon npm[13202]: info Starting worker 1
Jul 13 22:56:53 mastodon npm[13202]: info Worker 1 now listening on :::4000
```

I did a reload and a restart.

**Comment by xvilo** [comment]
@gargon Do you know anything for this? My instance has been down for 2 days now.....

**Comment by Gargron** [comment]
@xvilo Have you tried this? https://github.com/tootsuite/mastodon/issues/3884#issuecomment-310057798

**Comment by xvilo** [comment]
@gargo like I commented on there: 

Same here: 
```
$ gem update bundler

Updating installed gems
Updating bundler
Fetching: bundler-1.15.1.gem (100%)
Successfully installed bundler-1.15.1
Gems updated: bundler
```

And: 

```
$ rails -s

[!] There was an error parsing `Gemfile`: no implicit conversion of Symbol into Integer. Bundler cannot continue.

 #  from /home/mastodon/live/Gemfile:4
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  ruby '>= 2.3.0', '< 2.5.0'
 #  
 #  -------------------------------------------
```

**Comment by Gargron** [comment]
@xvilo Have you tried `bundle exec rails s` instead? Maybe it's picking up the wrong rails binary.

**Comment by xvilo** [comment]
@Gargron 
```$ bundle exec rails s
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant ActiveRecordQueryTrace (NameError)
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `block in with_bootsnap_fallback'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `without_bootsnap_cache'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `rescue in with_bootsnap_fallback'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
	from /home/mastodon/live/config/environments/development.rb:79:in `<top (required)>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:599:in `each'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:599:in `block in <class:Engine>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
	from /home/mastodon/live/config/environment.rb:5:in `<top (required)>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from config.ru:4:in `block in <main>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:7:in `new'
	from config.ru:7:in `<main>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:24:in `app'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:42:in `start'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by Gargron** [comment]
@xvilo Progress! Now just specify production environment with RAILS_ENV=production before the command :)

**Comment by xvilo** [comment]
@Gargron That seems to be working. I have it running in screen for now.... What would be a good long term solution for this issue?

**Comment by Gargron** [comment]
@xvilo I mean, prepending `bundle exec` and setting the environment are practically always recommended in production, so that *is* the solution. Presumably you won't be running a production server in screen though? Define a systemd service like the docs suggest.

**Comment by xvilo** [comment]
I should just edit my regular systemd then! Thanks for your help @Gargron

**Comment by Gargron** [comment]
@xvilo Check this out: <https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#systemd> it assumes you're using rbenv for the paths to the executables so YMMV

**Comment by gabelula** [comment]
I'm installing mastodon in the server and I get this same error:

mastodon@xxx:~/live$ bundle install --deployment --without development test

[!] There was an error parsing `Gemfile`: no implicit conversion of Symbol into Integer. Bundler cannot continue.

 #  from /home/mastodon/live/Gemfile:4
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  ruby '>= 2.3.0', '< 2.5.0'
 #  
 #  -------------------------------------------

I'm using rbenv with ruby 2.4.1

**Comment by ykzts** [comment]
@gabelula see #3884.

**Comment by gabelula** [comment]
yes @ykzts . Thanks. It worked for me after rbenv rehash.
