### ISSUE TITLE
instance hanging up with  "npm: TypeError: res.writeHead is not a function"

### ISSUE THREAD

**Issue by Neustrashimy** [tootsuite/mastodon#3997]
CentOS 7.3, Mastodon v1.4.6 and Nodejs 6.11

My instance hanging up with high loadaverage.
When checking the log, a lot of errors like the following :

/var/log/messages:
``` 
Jun 29 22:02:15 mstdn npm: ERR! [object Object]
Jun 29 22:02:15 mstdn npm: TypeError: res.writeHead is not a function
Jun 29 22:02:15 mstdn npm: at errorMiddleware (/home/mastodon/live/tmp/streaming/index.js:283:9)
Jun 29 22:02:15 mstdn npm: at Layer.handle [as handle_request] (/home/mastodon/live/node_modules/express/lib/router/layer.js:95:5)
Jun 29 22:02:15 mstdn npm: at trim_prefix (/home/mastodon/live/node_modules/express/lib/router/index.js:317:13)
Jun 29 22:02:15 mstdn npm: at /home/mastodon/live/node_modules/express/lib/router/index.js:284:7
Jun 29 22:02:15 mstdn npm: at Function.process_params (/home/mastodon/live/node_modules/express/lib/router/index.js:335:12)
Jun 29 22:02:15 mstdn npm: at next (/home/mastodon/live/node_modules/express/lib/router/index.js:275:10)
Jun 29 22:02:15 mstdn npm: at Query.client.query (/home/mastodon/live/tmp/streaming/index.js:238:9)
Jun 29 22:02:15 mstdn npm: at Query.handleReadyForQuery (/home/mastodon/live/node_modules/pg/lib/query.js:124:10)
Jun 29 22:02:15 mstdn npm: at Connection.<anonymous> (/home/mastodon/live/node_modules/pg/lib/client.js:178:19)
Jun 29 22:02:15 mstdn npm: at emitOne (events.js:101:20)
Jun 29 22:02:15 mstdn npm: at Connection.emit (events.js:188:7)
Jun 29 22:02:15 mstdn npm: ERR! [object Object]
Jun 29 22:02:15 mstdn npm: TypeError: res.writeHead is not a function
Jun 29 22:02:15 mstdn npm: at errorMiddleware (/home/mastodon/live/tmp/streaming/index.js:283:9)
Jun 29 22:02:15 mstdn npm: at Layer.handle [as handle_request] (/home/mastodon/live/node_modules/express/lib/router/layer.js:95:5)
Jun 29 22:02:15 mstdn npm: at trim_prefix (/home/mastodon/live/node_modules/express/lib/router/index.js:317:13)
Jun 29 22:02:15 mstdn npm: at /home/mastodon/live/node_modules/express/lib/router/index.js:284:7
Jun 29 22:02:15 mstdn npm: at Function.process_params (/home/mastodon/live/node_modules/express/lib/router/index.js:335:12)
Jun 29 22:02:15 mstdn npm: at next (/home/mastodon/live/node_modules/express/lib/router/index.js:275:10)
Jun 29 22:02:15 mstdn npm: at Query.client.query (/home/mastodon/live/tmp/streaming/index.js:238:9)
Jun 29 22:02:15 mstdn npm: at Query.handleReadyForQuery (/home/mastodon/live/node_modules/pg/lib/query.js:124:10)
Jun 29 22:02:15 mstdn npm: at Connection.<anonymous> (/home/mastodon/live/node_modules/pg/lib/client.js:178:19)
Jun 29 22:02:15 mstdn npm: at emitOne (events.js:101:20)
Jun 29 22:02:15 mstdn npm: at Connection.emit (events.js:188:7)
```

My instance has few users (~30).

What should i do?
Please give me advice. thanks.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
duplicated with #3913?

**Comment by Gargron** [comment]
Likely resolved by above PR, coming in upcoming version.
