### ISSUE TITLE
1.4.7: Issue starting background workers after upgrading to 1.4.7

### ISSUE THREAD

**Issue by Jehops** [tootsuite/mastodon#4039]
All the upgrade steps ran without errors, but new errors appear.

For the background workers:
```
(<unknown>): mapping values are not allowed in this context at line 19 column 31
/usr/local/lib/ruby/2.3/psych.rb:379:in `parse'
/usr/local/lib/ruby/2.3/psych.rb:379:in `parse_stream'
/usr/local/lib/ruby/2.3/psych.rb:327:in `parse'
/usr/local/lib/ruby/2.3/psych.rb:254:in `load'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/lib/sidekiq/cli.rb:388:in `parse_config'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/lib/sidekiq/cli.rb:225:in `setup_options'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/lib/sidekiq/cli.rb:39:in `parse'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/bin/sidekiq:11:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

For the streaming server:
```
$ NODE_ENV=production PORT=4000 npm run start

> mastodon@ start /usr/local/www/mastodon
> node ./streaming/index.js

/usr/local/www/mastodon/node_modules/uws/uws.js:38
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/usr/local/www/mastodon/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/usr/local/www/mastodon/node_modules/uws/uws.js:42:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/www/mastodon/streaming/index.js:10:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mastodon@ start: `node ./streaming/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mastodon@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/www/mastodon/.npm/_logs/2017-07-02T16_33_45_074Z-debug.log
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
For the 2nd error, try `npm rebuild uws`

For the first error, have you manually edited any YAML files?

**Comment by Jehops** [comment]
Same result after `npm rebuild uws`.  No YAML files were manually edited.  I noticed that streaming/.babelrc was missing after 1.4.6.

**Comment by Gargron** [comment]
There is no longer a need for .babelrc because streaming/index.js uses only features supported natively by Node.js 6.x. Besides, the problem is with npm/uws. What is your version of node?

**Comment by Jehops** [comment]
The version of node is 8.1.3.

**Comment by Jehops** [comment]
I tried downgrading to node.js version 6.11.0, but the results were the same.

**Comment by ykzts** [comment]
@Jehops I have some questions for you.

1. Is it an update from Mastodon v1.3.x?
    - `uws` was added in v1.4.
2. Are you using *BSD?
    - `uws` does supports Darwin, Linux and Windows

**Comment by Jehops** [comment]
@ykzts, It was an update from 1.4.6.  This work is for the [FreeBSD package](http://www.freshports.org/net-im/mastodon/).  Using version 1.4.6, the streaming server started without errors.

**Comment by ykzts** [comment]
@Jehops There is no change in `uws` between 1.4.6 and 1.4.7. It may be a bug in `uws`. Can you check whether `uws` only?

- https://github.com/uNetworking/uWebSockets
- https://github.com/uNetworking/bindings/tree/master/nodejs

**Comment by Jehops** [comment]
I've managed to get the streaming server started.  I'm not sure what the problem was; `uws` had compiled successfully, but after wiping out the directory and doing `yarn install` and the assets precompile steps again, it's now starting successfully.

So, now the problem is just starting the background workers.

**Comment by Jehops** [comment]
Web searches and @Gargron's hint suggest some yaml file has a format issue.  To confirm something hasn't been accidentally modified, I moved the old installation directory out of the way and started from scratch, but the same error is reported.  Here is the command (this time without bundler) and reported error.
```
$ RAILS_ENV=production DB_POOL=5 sidekiq -c 5 -q default -q mailers -q pull -q push
(<unknown>): mapping values are not allowed in this context at line 19 column 31
/usr/local/lib/ruby/2.3/psych.rb:379:in `parse'
/usr/local/lib/ruby/2.3/psych.rb:379:in `parse_stream'
/usr/local/lib/ruby/2.3/psych.rb:327:in `parse'
/usr/local/lib/ruby/2.3/psych.rb:254:in `load'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/lib/sidekiq/cli.rb:388:in `parse_config'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/lib/sidekiq/cli.rb:225:in `setup_options'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/lib/sidekiq/cli.rb:39:in `parse'
/usr/local/lib/ruby/gems/2.3/gems/sidekiq-5.0.3/bin/sidekiq:11:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<main>'
```

**Comment by saper** [comment]
the file in question is `config/sidekiq.yml`:

````yaml
---
:concurrency: 5
:queues:
  - default
  - push
  - pull
  - mailers
:schedule:
  subscriptions_scheduler:
    cron: '0 5 * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '5 4 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::FeedCleanupScheduler
:pidfile: tmp/mastodon_workers.pid
````

**Comment by Jehops** [comment]
Apologies.  This was a local patch to config/sidekiq.yml to create a pid file.  The patch still applied cleanly, but it placed the line below into the incorrect location.
