### ISSUE TITLE
Database migration problems

### ISSUE THREAD

**Issue by Luclu7** [tootsuite/mastodon#4084]
I can't migrate the DB when I try to upgrade to v1.4.7:

```
mastodon@7nw ~/live> env RAILS_ENV=production bundle exec rails db:migrate
Migrating to AddStatusesIndexOnAccountIdId (20170610000000)
== 20170610000000 AddStatusesIndexOnAccountIdId: migrating ====================
-- add_index("statuses", ["account_id", "id"], {:algorithm=>:concurrently, :name=>"index_statuses_on_account_id_id"})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_statuses_on_account_id_id' on table 'statuses' already exists
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1156:in 'add_index_options'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:483:in 'add_index'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:849:in 'block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in 'block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in 'say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:838:in 'method_missing'
/home/mastodon/live/db/migrate/20170610000000_add_statuses_index_on_account_id_id.rb:9:in 'change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:792:in 'exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:776:in 'block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:775:in 'block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in 'with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:774:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:953:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1230:in 'block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1300:in 'ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1229:in 'execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1201:in 'block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in 'each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in 'migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in 'block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1317:in 'with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in 'up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:985:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:171:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:58:in 'block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in 'block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in 'perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in 'invoke'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in '<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in 'require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in 'require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in 'block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in 'load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in 'require'
bin/rails:4:in '<main>'
ArgumentError: Index name 'index_statuses_on_account_id_id' on table 'statuses' already exists
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1156:in 'add_index_options'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:483:in 'add_index'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:849:in 'block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in 'block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in 'say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:838:in 'method_missing'
/home/mastodon/live/db/migrate/20170610000000_add_statuses_index_on_account_id_id.rb:9:in 'change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:792:in 'exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:776:in 'block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:775:in 'block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in 'with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:774:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:953:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1230:in 'block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1300:in 'ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1229:in 'execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1201:in 'block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in 'each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in 'migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in 'block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1317:in 'with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in 'up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:985:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:171:in 'migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:58:in 'block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in 'block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in 'perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in 'invoke'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in '<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in 'require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in 'require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in 'block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in 'load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in 'require'
bin/rails:4:in '<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Connect to the same DB via psql, and execute `DROP INDEX index_statuses_on_account_id_id;`

Then try again

**Comment by Luclu7** [comment]
Now I have:
````
mastodon@7nw ~/live> env RAILS_ENV=production bundle exec rails db:migrate
Migrating to AddStatusesIndexOnAccountIdId (20170610000000)
== 20170610000000 AddStatusesIndexOnAccountIdId: migrating ====================
-- add_index("statuses", ["account_id", "id"], {:algorithm=>:concurrently, :name=>"index_statuses_on_account_id_id"})
   -> 0.6201s
-- remove_index("statuses", {:algorithm=>:concurrently, :column=>"account_id", :name=>"index_statuses_on_account_id"})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

No indexes found on statuses with the options provided.
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1236:in `index_name_for_remove'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:503:in `remove_index'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:849:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:838:in `method_missing'
/home/mastodon/live/db/migrate/20170610000000_add_statuses_index_on_account_id_id.rb:11:in `change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:792:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:775:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:774:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:953:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1300:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in `up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:985:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
ArgumentError: No indexes found on statuses with the options provided.
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1236:in `index_name_for_remove'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:503:in `remove_index'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:849:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:818:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:838:in `method_missing'
/home/mastodon/live/db/migrate/20170610000000_add_statuses_index_on_account_id_id.rb:11:in `change'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:792:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:775:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:774:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:953:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1300:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1148:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in `up'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:985:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by Luclu7** [comment]
I reinstalled all the instance, so I close the issue.
