### ISSUE TITLE
Sidekiq error on Scalingo: [AV] “Unable to detect any supported library“

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#4168]
Seeing this Sidekiq error in the logs (“"Unable to detect any supported library”) on Scalingo:

```
2017-07-12 12:54:32.076358790 +0200 CEST [worker-1] Command :: file -b --mime '/tmp/8d777f385d3dfec8815d20f7496026dc20170712-23-13045qj.mp4'
2017-07-12 12:54:32.080426193 +0200 CEST [worker-1] [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
2017-07-12 12:54:32.081641870 +0200 CEST [worker-1] [AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
2017-07-12 12:54:32.089247083 +0200 CEST [worker-1] 2017-07-12T10:54:32.085Z 23 TID-ouzy3rdq8 WARN: {"context":"Job raised exception","job":{"class":"ProcessingWorker","args":[4509,"<?xml version=\"1.0\"?>\n<feed xmlns=\"http://www.w3.org/2005/Atom\" xmlns:thr=\"http://purl.org/syndication/thread/1.0\" xmlns:activity=\"http://activitystrea.ms/spec/1.0/\" xmlns:poco=\"http://portablecontacts.net/spec/1.0\" xmlns:media=\"http://purl.org/syndication/atommedia\" xmlns:ostatus=\"http://ostatus.org/schema/1.0\" xmlns:mastodon=\"http://mastodon.social/schema/1.0\">\n  <id>https://kitty.town/users/GinnyMcQueen.atom</id>\n  <title>Ginny McQueen 🌻</title>\n  <subtitle>👑 Mayor of Kitty.Town 🐈 Loves #Cats 🚫 Hates Nazis 🌆 #LosAngeles 🙏 http://patreon.com/ginnymcqueen 💸 http://paypal.me/ginnymcqueen 🎁 http://a.co/au3kqHt</subtitle>\n  <updated>2017-06-14T04:33:33Z</updated>\n  <logo>https://media.masto.host/kitty/accounts/avatars/000/000/001/original/bfa488b40a6a2eaf.jpg</logo>\n  <author>\n    <id>https://kitty.town/users/GinnyMcQueen</id>\n    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>\n    <uri>https://kitty.town/users/GinnyMcQueen</uri>\n    <name>GinnyMcQueen</name>\n    <email>GinnyMcQueen@kitty.town</email>\n    <summary type=\"html\">&lt;p&gt;👑 Mayor of Kitty.Town 🐈 Loves &lt;a href=\"https://kitty.town/tags/cats\" class=\"mention hashtag\" rel=\"tag\"&gt;#&lt;span&gt;Cats&lt;/span&gt;&lt;/a&gt; 🚫 Hates Nazis 🌆 &lt;a href=\"https://kitty.town/tags/losangeles\" class=\"mention hashtag\" rel=\"tag\"&gt;#&lt;span&gt;LosAngeles&lt;/span&gt;&lt;/a&gt; 🙏 &lt;a href=\"http://patreon.com/ginnymcqueen\" rel=\"nofollow noopener\" target=\"_blank\"&gt;&lt;span class=\"invisible\"&gt;http://&lt;/span&gt;&lt;span class=\"\"&gt;patreon.com/ginnymcqueen&lt;/span&gt;&lt;span class=\"invisible\"&gt;&lt;/span&gt;&lt;/a&gt; 💸 &lt;a href=\"http://paypal.me/ginnymcqueen\" rel=\"nofollow noopener\" target=\"_blank\"&gt;&lt;span class=\"invisible\"&gt;http://&lt;/span&gt;&lt;span class=\"\"&gt;paypal.me/ginnymcqueen&lt;/span&gt;&lt;span class=\"invisible\"&gt;&lt;/span&gt;&lt;/a&gt; 🎁 &lt;a href=\"http://a.co/au3kqHt\" rel=\"nofollow noopener\" target=\"_blank\"&gt;&lt;span class=\"invisible\"&gt;http://&lt;/span&gt;&lt;span class=\"\"&gt;a.co/au3kqHt&lt;/span&gt;&lt;span class=\"invisible\"&gt;&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;</summary>\n    <link rel=\"alternate\" type=\"text/html\" href=\"https://kitty.town/@GinnyMcQueen\"/>\n    <link rel=\"avatar\" type=\"image/jpeg\" media:width=\"120\" media:height=\"120\" href=\"https://media.masto.host/kitty/accounts/avatars/000/000/001/original/bfa488b40a6a2eaf.jpg\"/>\n    <link rel=\"header\" type=\"image/gif\" media:width=\"700\" media:height=\"335\" href=\"https://media.masto.host/kitty/accounts/headers/000/000/001/original/78a1353d22dc86f1.gif\"/>\n    <poco:preferredUsername>GinnyMcQueen</poco:preferredUsername>\n    <poco:displayName>Ginny McQueen 🌻</poco:displayName>\n    <poco:note>👑 Mayor of Kitty.Town 🐈 Loves #Cats 🚫 Hates Nazis 🌆 #LosAngeles 🙏 http://patreon.com/ginnymcqueen 💸 http://paypal.me/ginnymcqueen 🎁 http://a.co/au3kqHt</poco:note>\n    <mastodon:scope>public</mastodon:scope>\n  </author>\n  <link rel=\"alternate\" type=\"text/html\" href=\"https://kitty.town/@GinnyMcQueen\"/>\n  <link rel=\"self\" type=\"application/atom+xml\" href=\"https://kitty.town/users/GinnyMcQueen.atom\"/>\n  <link rel=\"hub\" href=\"https://kitty.town/api/push\"/>\n  <link rel=\"salmon\" href=\"https://kitty.town/api/salmon/1\"/>\n  <entry>\n    <id>tag:kitty.town,2017-07-08:objectId=703310:objectType=Status</id>\n    <published>2017-07-08T15:00:34Z</published>\n    <updated>2017-07-08T15:00:34Z</updated>\n    <title>New status by GinnyMcQueen</title>\n    <activity:object-type>http://activitystrea.ms/schema/1.0/comment</activity:object-type>\n    <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>\n    <content type=\"html\" xml:lang=\"en\">&lt;p&gt;&lt;span class=\"h-card\"&gt;&lt;a href=\"https://mastodon.host/@vespin_feebler\" class=\"u-url mention\"&gt;@&lt;span&gt;vespin_feebler&lt;/span&gt;&lt;/a&gt;&lt;/span&gt; &lt;a href=\"https://kitty.town/media/c6loGDyvScmuQtXncCw\" rel=\"nofollow noopener\" target=\"_blank\"&gt;&lt;span class=\"invisible\"&gt;https://&lt;/span&gt;&lt;span class=\"ellipsis\"&gt;kitty.town/media/c6loGDyvScmuQ&lt;/span&gt;&lt;span class=\"invisible\"&gt;tXncCw&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;</content>\n    <link rel=\"mentioned\" ostatus:object-type=\"http://activitystrea.ms/schema/1.0/person\" href=\"https://mastodon.host/users/vespin_feebler\"/>\n    <link rel=\"mentioned\" ostatus:object-type=\"http://activitystrea.ms/schema/1.0/collection\" href=\"http://activityschema.org/collection/public\"/>\n    <link rel=\"enclosure\" type=\"video/mp4\" length=\"180603\" href=\"https://media.masto.host/kitty/media_attachments/files/000/049/008/original/media.mp4\"/>\n    <mastodon:scope>public</mastodon:scope>\n    <link rel=\"alternate\" type=\"text/html\" href=\"https://kitty.town/users/GinnyMcQueen/updates/22890\"/>\n    <link rel=\"self\" type=\"application/atom+xml\" href=\"https://kitty.town/users/GinnyMcQueen/updates/22890.atom\"/>\n    <thr:in-reply-to ref=\"tag:mastodon.host,2017-07-08:objectId=17516080:objectType=Status\" href=\"https://mastodon.host/users/vespin_feebler/updates/26551\"/>\n    <ostatus:conversation ref=\"tag:kitty.town,2017-07-08:objectId=435020:objectType=Conversation\"/>\n  </entry>\n</feed>\n"],"retry":true,"queue":"default","backtrace":true,"jid":"068cf6313ac56edb6a93b67b","created_at":1499526048.8115704,"enqueued_at":1499856871.951017,"error_message":"Unable to detect any supported library","error_class":"Av::UnableToDetect","failed_at":1499526048.9641676,"retry_count":18,"error_backtrace":["/app/vendor/bundle/ruby/2.4.0/gems/av-0.9.0/lib/av/cli.rb:10:in `initialize'","/app/vendor/bundle/ruby/2.4.0/gems/av-0.9.0/lib/av.rb:24:in `new'","/app/vendor/bundle/ruby/2.4.0/gems/av-0.9.0/lib/av.rb:24:in `cli'","/app/lib/paperclip/video_transcoder.rb:8:in `make'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/processor.rb:34:in `make'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:528:in `block in post_process_style'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:527:in `each'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:527:in `inject'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:527:in `post_process_style'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:518:in `block in post_process_styles'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:517:in `each'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:517:in `post_process_styles'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:509:in `block (2 levels) in post_process'","/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:507:in `block in post_process'","/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:506:in `post_process'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:462:in `post_process_file'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:111:in `assign'","/app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'","/app/app/models/concerns/remotable.rb:25:in `block (3 levels) in <module:Remotable>'","/app/app/services/process_feed_service.rb:236:in `block in media_from_xml'","/app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190:in `block in each'","/app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `upto'","/app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `each'","/app/app/services/process_feed_service.rb:223:in `media_from_xml'","/app/app/services/process_feed_service.rb:162:in `status_from_xml'","/app/app/services/process_feed_service.rb:60:in `block in create_status'","/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'","/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'","/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'","/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'","/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'","/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/transactions.rb:210:in `transaction'","/app/app/services/process_feed_service.rb:59:in `create_status'","/app/app/services/process_feed_service.rb:33:in `call'","/app/app/services/process_feed_service.rb:19:in `block in process_entries'","/app/app/services/process_feed_service.rb:19:in `reverse_each'","/app/app/services/process_feed_service.rb:19:in `each'","/app/app/services/process_feed_service.rb:19:in `map'","/app/app/services/process_feed_service.rb:19:in `process_entries'","/app/app/services/process_feed_service.rb:9:in `call'","/app/app/workers/processing_work ... SNIP
2017-07-12 12:54:32.089440088 +0200 CEST [worker-1] 2017-07-12T10:54:32.085Z 23 TID-ouzy3rdq8 WARN: Av::UnableToDetect: Unable to detect any supported library
2017-07-12 12:54:32.089477017 +0200 CEST [worker-1] 2017-07-12T10:54:32.085Z 23 TID-ouzy3rdq8 WARN: /app/vendor/bundle/ruby/2.4.0/gems/av-0.9.0/lib/av/cli.rb:10:in `initialize'
2017-07-12 12:54:32.089500294 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/av-0.9.0/lib/av.rb:24:in `new'
2017-07-12 12:54:32.089522418 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/av-0.9.0/lib/av.rb:24:in `cli'
2017-07-12 12:54:32.089544931 +0200 CEST [worker-1] /app/lib/paperclip/video_transcoder.rb:8:in `make'
2017-07-12 12:54:32.089581112 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/processor.rb:34:in `make'
2017-07-12 12:54:32.089605877 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:528:in `block in post_process_style'
2017-07-12 12:54:32.089628115 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:527:in `each'
2017-07-12 12:54:32.089649748 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:527:in `inject'
2017-07-12 12:54:32.089670957 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:527:in `post_process_style'
2017-07-12 12:54:32.089707358 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:518:in `block in post_process_styles'
2017-07-12 12:54:32.089770915 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:517:in `each'
2017-07-12 12:54:32.089875298 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:517:in `post_process_styles'
2017-07-12 12:54:32.089903238 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:509:in `block (2 levels) in post_process'
2017-07-12 12:54:32.089950323 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
2017-07-12 12:54:32.089971779 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
2017-07-12 12:54:32.089992685 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:507:in `block in post_process'
2017-07-12 12:54:32.090024473 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
2017-07-12 12:54:32.090045330 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
2017-07-12 12:54:32.090074145 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:506:in `post_process'
2017-07-12 12:54:32.090096408 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:462:in `post_process_file'
2017-07-12 12:54:32.090117132 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:111:in `assign'
2017-07-12 12:54:32.090137610 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
2017-07-12 12:54:32.090182738 +0200 CEST [worker-1] /app/app/models/concerns/remotable.rb:25:in `block (3 levels) in <module:Remotable>'
2017-07-12 12:54:32.090207533 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:236:in `block in media_from_xml'
2017-07-12 12:54:32.090249443 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `upto'
2017-07-12 12:54:32.090228528 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190:in `block in each'
2017-07-12 12:54:32.090269902 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `each'
2017-07-12 12:54:32.090294835 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:223:in `media_from_xml'
2017-07-12 12:54:32.090344170 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:162:in `status_from_xml'
2017-07-12 12:54:32.090365051 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:60:in `block in create_status'
2017-07-12 12:54:32.090386901 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
2017-07-12 12:54:32.090407979 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
2017-07-12 12:54:32.090453212 +0200 CEST [worker-1] /app/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2017-07-12 12:54:32.090474123 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
2017-07-12 12:54:32.090495029 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
2017-07-12 12:54:32.090515328 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/transactions.rb:210:in `transaction'
2017-07-12 12:54:32.090535859 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:59:in `create_status'
2017-07-12 12:54:32.090556869 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:33:in `call'
2017-07-12 12:54:32.090618609 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:19:in `block in process_entries'
2017-07-12 12:54:32.090643481 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:19:in `reverse_each'
2017-07-12 12:54:32.090664956 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:19:in `each'
2017-07-12 12:54:32.090692813 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:19:in `map'
2017-07-12 12:54:32.090715775 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:19:in `process_entries'
2017-07-12 12:54:32.090736745 +0200 CEST [worker-1] /app/app/services/process_feed_service.rb:9:in `call'
2017-07-12 12:54:32.090758066 +0200 CEST [worker-1] /app/app/workers/processing_worker.rb:9:in `perform'
2017-07-12 12:54:32.090779836 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:199:in `execute_job'
2017-07-12 12:54:32.090830776 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
2017-07-12 12:54:32.090851350 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2017-07-12 12:54:32.090872564 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
2017-07-12 12:54:32.090893060 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-07-12 12:54:32.090913599 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2017-07-12 12:54:32.090941093 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:169:in `block in process'
2017-07-12 12:54:32.090982347 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
2017-07-12 12:54:32.091006527 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:97:in `local'
2017-07-12 12:54:32.091027425 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
2017-07-12 12:54:32.091047881 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/rails.rb:42:in `block in call'
2017-07-12 12:54:32.091068429 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
2017-07-12 12:54:32.091118538 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'
2017-07-12 12:54:32.091139602 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
2017-07-12 12:54:32.091162234 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'
2017-07-12 12:54:32.091183236 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/rails.rb:41:in `call'
2017-07-12 12:54:32.091203617 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
2017-07-12 12:54:32.091266154 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:215:in `stats'
2017-07-12 12:54:32.091289452 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
2017-07-12 12:54:32.091310479 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_logger.rb:7:in `call'
2017-07-12 12:54:32.091331480 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
2017-07-12 12:54:32.091372873 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:72:in `global'
2017-07-12 12:54:32.091398755 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:129:in `block in dispatch'
2017-07-12 12:54:32.091420405 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:44:in `with_context'
2017-07-12 12:54:32.091442259 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
2017-07-12 12:54:32.091462930 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:128:in `dispatch'
2017-07-12 12:54:32.091504819 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:168:in `process'
2017-07-12 12:54:32.091525893 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:85:in `process_one'
2017-07-12 12:54:32.091552877 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:73:in `run'
2017-07-12 12:54:32.091573649 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:16:in `watchdog'
2017-07-12 12:54:32.091594267 +0200 CEST [worker-1] /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [1.4.7](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
It needs ffmpeg for video/GIF attachments. ffmpeg is in the "Aptfile" but I am not sure if that file is used by Heroku or Scalingo or both.
