### ISSUE TITLE
401: Access token invalid

### ISSUE THREAD

**Issue by isati** [tootsuite/mastodon#4223]
I've searched through the issues and can see that others have been experiencing similar issues but I haven't come across a working resolve for it yet.

My instance is putting out "401: Access token invalid" errors in the UI after a seemingly undetermined time period.
This is also logged within mastodon-streaming.service as:
```
Jul 16 16:22:08 npm[23968]: ERR! Error: Invalid access token
Jul 16 16:22:08 npm[23968]: ERR! Error: Invalid access token
Jul 16 16:22:09 npm[23968]: ERR! Error: Invalid access token
Jul 16 16:22:09 npm[23968]: ERR! Error: Invalid access token
Jul 16 16:22:09 npm[23968]: ERR! Error: Invalid access token
Jul 16 16:22:09 npm[23968]: ERR! Error: Invalid access token
....
```

This only occurs after some minutes and can be resolved by reloading the page, until it happens again. This happens on both desktop & android Chrome. Any ideas how to debug this as the output is a bit vague?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Technowix** [comment]
wich version of Mastodon ? Master / Stable ?

**Comment by isati** [comment]
Ah yes sorry, this happened on stable 1.4.7, I took a chance on upgrading to master to hopefully resolve it and also to try out the push notifications. However this didn't resolve it and I'm assuming because of this 401 issue, it is also affecting the push notifications where the toggles are being reset to off and repeatedly showing the push notification subscription notification.

**Comment by clworld** [comment]
@isati try logout -> re-login. It may solve this.

**Comment by isati** [comment]
I've tried that numerous times, I've tried clearing node_modules/gems and rebuilding. I've tried different changes to nginx amongst numerous other things and nothing seems to be resolving this.

**Comment by Gargron** [comment]
Are the 3 secrets set in .env.production? Is the database up to date with migrations, has db:seed been run once after installation?

**Comment by isati** [comment]
Yes I've set all the secrets when the instance was original setup and they've not been changed since. I've done all the migrations and also ran db:seed again but again, no resolve.

**Comment by Gargron** [comment]
Are you using Safari?

**Comment by isati** [comment]
No, I've been using Chrome for Linux, Chrome & Chromium for Android and all experience this issue, however it seems to be a bit more prevalent on mobile - in regards to the time period where the 401 errors begin to occur. When the 401 errors occur the auto-loading of columns tends to break but also sometimes works, also this seems to switch the new push notifications back to off & display the subscription notice. Reloading the site/page will rectify the issue but only for the undetermined amount of time and then the 401 errors again. 

Apart from this repeating issue there seems to be no other issues with my instance, everything else functions as expected.

**Comment by isati** [comment]
Also this doesn't appear on a sign in or reload, signing back in or reloading actually temporarily resolves it.

**Comment by isati** [comment]
With further testing, the 401 breaking autoloading of columns only seems to affect the home & notification columns, the federated & local timelines continue to autoload despite the error.

**Comment by clworld** [comment]
Log "ERR! Error: Invalid access token" means access_token provided is not exists on database.
From 1.4.7, access_token is tied to sessions and only 10 recent session is allowed per user and older session+access_token will be revoked.
I think something happened to session (for example: a lot of new session is created on short time period)
Check sessions list on setting -> security and "Last activity" is long time ago enough.
Other checklist:
* There is record on "oauth_applications". name = 'Web' and superapp = true (which must be created by db:seed.)
* "_session_id" cookie value does not change frequently (which is used for managing session.)
* "access_token" JSON value in initial-state on source of page does not change frequently. (which is access_token WebUI uses.)

**Comment by Gargron** [comment]
>only seems to affect the home & notification columns, the federated & local timelines continue to autoload despite the error

For reference this is non-indicative. Federated & local timelines do not require an access token, when one is missing it still works, albeit without your personal filters.

**Comment by sorin-davidoi** [comment]
Might have some leads on this

> ```SELECT * FROM session_activations;```

```
id | user_id |            session_id            |         created_at         |         updated_at         |                                                                  user_agent                                                                   |    ip     | access_token_id | web_push_subscription_id 
----+---------+----------------------------------+----------------------------+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+-----------+-----------------+--------------------------
  6 |       1 | f84338ac841b8317217839d1f0234972 | 2017-07-16 19:28:39.578171 | 2017-07-17 16:19:56.020886 | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36                                     | 127.0.0.1 |               6 |                       43
  8 |       2 | 593e4fd3ba367361fd0f7d7e851bd7be | 2017-07-17 16:20:16.428769 | 2017-07-17 16:20:19.602528 | Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0                                                                          | 127.0.0.1 |               8 |                       44
 11 |       1 | 8a78df7accccc731948c3fed60cb946b | 2017-07-17 23:44:41.494871 | 2017-07-17 23:44:49.180294 | Mozilla/5.0 (Linux; Android 6.0; XT1068 Build/MPB24.65-34-3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36 | 127.0.0.1 |              11 |                       47
(3 rows)
```

> ```SELECT * FROM oauth_access_tokens;```

```
 id | resource_owner_id | application_id |                              token                               | refresh_token | expires_in | revoked_at |         created_at         |      scopes       
----+-------------------+----------------+------------------------------------------------------------------+---------------+------------+------------+----------------------------+-------------------
  1 |                 1 |              1 | 9b5dd4a14694609516404cd38077a9616e9b8abf6d256bdf6525350328a035dc |               |            |            | 2017-07-16 14:01:06.618695 | read write follow
  2 |                 1 |              1 | ad47ad7169c1089e847b52eff0d400d9eea5966ac179158edcab2ed04d5948f1 |               |            |            | 2017-07-16 14:54:10.960424 | read write follow
  3 |                 2 |              1 | 5877b1e014f65c27e9782e66338aa67575d0a8dedee1cf308f6060928f0abaa2 |               |            |            | 2017-07-16 15:56:40.139784 | read write follow
  4 |                 2 |              1 | 3f4ebc19959477c611a148b773c9151f253478ffe0cd3bb5305214e73ce75c13 |               |            |            | 2017-07-16 19:19:39.199745 | read write follow
  5 |                 1 |              1 | 821efb0d5f8ffc699209619e00599a67f342db920739a7fb1634c13d35c8837d |               |            |            | 2017-07-16 19:19:50.002074 | read write follow
  6 |                 1 |              1 | 0b17754a648c0b9d2bf5770b24d43402c396b4539727eec7c86b642dbb2f6b8c |               |            |            | 2017-07-16 19:28:39.580676 | read write follow
  8 |                 2 |              1 | 27f68bb561e657c0a6a4532005e9df2509d4104211228ce6d5a368c8e79631c6 |               |            |            | 2017-07-17 16:20:16.439711 | read write follow
 11 |                 1 |              1 | 35bb73b704d04b0a6538fd3f44683ee608b2f1e6b4d8cda1d226f084fa530217 |               |            |            | 2017-07-17 23:44:41.497385 | read write follow
(8 rows)
```

> ```SELECT * FROM web_push_subscriptions;```

```
id |                                                                                                                  endpoint                                                                                                                  |                                        key_p256dh                                        |         key_auth         |                                   data                                   |         created_at         |         updated_at         
----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------+--------------------------------------------------------------------------+----------------------------+----------------------------
 44 | https://updates.push.services.mozilla.com/wpush/v2/gAAAAABZbOPBa6UE6QA_tmqWkFcr4bCQ9iHmyAsFpfP8FVOTrLk4Wy5W2RdBrGcdjgslKOEc_lMJ9oSRH5Bw1XnCaRbcBbfHl7Bq-9dYdPu7xiQUuUFDv4Zn2VSqC2jq3dlePLrdleit_TK1LzeBedLKgmVg9MiU_wBqIwuk5ZQaYSOXPnikUr0 | BM7L95rRNSMW9r4R41ddXosbz6kWOKyLH8I9PDk3-vxosObdOEO4O5m4T3-b0xCFYPuJyJtBO1j8ZtmMqKsTBgw  | P0jWhbzbgNzonCB5VY2GPw   | {"alerts":{"follow":true,"favourite":true,"mention":true,"reblog":true}} | 2017-07-17 16:20:17.614941 | 2017-07-17 16:20:28.83207
 43 | https://fcm.googleapis.com/fcm/send/cq-aLd8WFFY:APA91bH9INgzPNLJiKU-vKwg-S6om9-dvcTVq4tFZKP9Kjes4Wcv2oP_R2-iZIKNcwRT2xkrSa3nY7JskTXmTXta1q5K_u8k_eIfCap2gTzfFYusLjR5rK-xVv5EUdOaSdq4Ynxil3vv                                               | BATLfGGFfDmMOCpU2wcmRWMt4K1UpPl9HiqCjRhectUOFH9v_-6k-K6SgZFvawHum-el3S5jDweXqQFAvVVBld4= | utKUR-4Sf3lSGxQiv8zW7g== | {"alerts":{"favourite":true,"follow":true,"mention":true,"reblog":true}} | 2017-07-17 16:19:54.873471 | 2017-07-17 16:20:07.103209
 47 | https://fcm.googleapis.com/fcm/send/eS253EZesko:APA91bESyix9dIMs8fEEX1UdB9LhuKcnvPNHCQMd6gdFsCaUlcv3zM5BLPxLwNHaQp1_f0IoftwRGO1XSxE0n5f0OAqJgnroaO5bO45i-bQZLkgY12Y1_z4DDzLQpLD785AjEdgPQj2h                                               | BDUrvdEy9jPA0RflhUYdcpqB2UC2m924GHgZ8NaVlwDp2LE4SsCNz4D-kFG-v0wlbeB0LRgLTz0_7XVZLYQ_R9E= | 4gQXI8QQiM0iMdPgM3MMeQ== |                                                                          | 2017-07-17 23:44:48.689775 | 2017-07-17 23:44:48.689775
(3 rows)
```

Found this in the logs

```
[StatsD] measure mastodon.performance.Api.V1.StatusesController.create.html.localhost.total_duration:118.359989
[StatsD] measure mastodon.performance.Api.V1.StatusesController.create.html.localhost.db_time:30.29084
[StatsD] measure mastodon.performance.Api.V1.StatusesController.create.html.localhost.view_time:7.989894001580931
[StatsD] increment mastodon.performance.Api.V1.StatusesController.create.html.localhost.status.200:1
Started GET "/api/v1/timelines/public?local=true" for 127.0.0.1 at 2017-07-18 01:44:41 +0200
Processing by Api::V1::Timelines::PublicController#show as HTML
  Parameters: {"local"=>"true"}
  Doorkeeper::AccessToken Load (0.2ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SessionActivation Load (0.2ms)  SELECT "session_activations".* FROM "session_activations" WHERE "session_activations"."session_id" = $1  [["session_id", "10790e4d8e1212593f6e12c61deef844"]]
   (0.1ms)  BEGIN
  SQL (0.2ms)  DELETE FROM "session_activations" WHERE "session_activations"."id" = $1  [["id", 10]]
  Doorkeeper::AccessToken Load (0.2ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."id" = $1 LIMIT $2  [["id", 10], ["LIMIT", 1]]
  SQL (0.3ms)  DELETE FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."id" = $1  [["id", 10]]
  Web::PushSubscription Load (0.2ms)  SELECT  "web_push_subscriptions".* FROM "web_push_subscriptions" WHERE "web_push_subscriptions"."id" = $1 LIMIT $2  [["id", 46], ["LIMIT", 1]]
  SQL (0.2ms)  DELETE FROM "web_push_subscriptions" WHERE "web_push_subscriptions"."id" = $1  [["id", 46]]
   (9.7ms)  COMMIT
   (0.3ms)  BEGIN
  Doorkeeper::Application Load (0.6ms)  SELECT  "oauth_applications".* FROM "oauth_applications" WHERE "oauth_applications"."superapp" = $1 LIMIT $2  [["superapp", "t"], ["LIMIT", 1]]
  Doorkeeper::Application Load (0.6ms)  SELECT  "oauth_applications".* FROM "oauth_applications" WHERE "oauth_applications"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Doorkeeper::AccessToken Exists (0.5ms)  SELECT  1 AS one FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "35bb73b704d04b0a6538fd3f44683ee608b2f1e6b4d8cda1d226f084fa530217"], ["LIMIT", 1]]
  SQL (1.1ms)  INSERT INTO "oauth_access_tokens" ("resource_owner_id", "application_id", "token", "created_at", "scopes") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["resource_owner_id", 1], ["application_id", 1], ["token", "35bb73b704d04b0a6538fd3f44683ee608b2f1e6b4d8cda1d226f084fa530217"], ["created_at", "2017-07-17 23:44:41.497385"], ["scopes", "read write follow"]]
  SQL (1.1ms)  INSERT INTO "session_activations" ("user_id", "session_id", "created_at", "updated_at", "user_agent", "ip", "access_token_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["user_id", 1], ["session_id", "8a78df7accccc731948c3fed60cb946b"], ["created_at", "2017-07-17 23:44:41.494871"], ["updated_at", "2017-07-17 23:44:41.494871"], ["user_agent", "Mozilla/5.0 (Linux; Android 6.0; XT1068 Build/MPB24.65-34-3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"], ["ip", "127.0.0.1/32"], ["access_token_id", 11]]
   (4.0ms)  COMMIT
  SessionActivation Load (0.7ms)  SELECT "session_activations".* FROM "session_activations" WHERE "session_activations"."user_id" = $1 ORDER BY created_at desc OFFSET $2  [["user_id", 1], ["OFFSET", 10]]
   (0.2ms)  BEGIN
  SQL (0.7ms)  UPDATE "users" SET "current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["current_sign_in_at", "2017-07-17 23:44:41.515768"], ["last_sign_in_at", "2017-07-17 23:38:08.811368"], ["sign_in_count", 389], ["updated_at", "2017-07-17 23:44:41.517242"], ["id", 1]]
   (4.1ms)  COMMIT
  Doorkeeper::AccessToken Load (0.8ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  CACHE Doorkeeper::AccessToken Load (0.1ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  CACHE Doorkeeper::AccessToken Load (0.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  CACHE Doorkeeper::AccessToken Load (0.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  CACHE Doorkeeper::AccessToken Load (0.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  CACHE Doorkeeper::AccessToken Load (0.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "c1deab875cd7973f26284e846448e7c18aeddeb5050b7375182e0f34cd9dc308"], ["LIMIT", 1]]
  Account Load (1.0ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  CACHE Doorkeeper::AccessToken Load (0.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", 
```

What I understand from this: the push subscription got deleted because the session activation got deleted, which in turn is deleted because the access token was deleted.

**Comment by sorin-davidoi** [comment]
Got suspicious when I finally managed to reproduce - by mistake - the fact that I got the welcome notification when I should not have.

**Comment by sorin-davidoi** [comment]
Also this (notice the Firefox session does not show up):
![image](https://user-images.githubusercontent.com/2109702/28295034-261800a0-6b5e-11e7-8581-b5669b217a6d.png)

**Comment by sorin-davidoi** [comment]
@Gargron It looks like [`Warden::Manager.after_set_user` from `devise.rb`](https://github.com/tootsuite/mastodon/blob/master/config/initializers/devise.rb#L1) is sometimes called after a refresh even if the user is logged in - deleting the session activation and the push subscription along with it. Cannot really reproduce it all the time. Shouldn't we bail out if the cookie is set and not expired?

**Comment by sorin-davidoi** [comment]
Attaching the relevant logs (opening Epiphany with the user already logged in, Query Trace enabled and some custom logs):

```
Started GET "/web/statuses/new" for 127.0.0.1 at 2017-07-21 13:09:41 +0200
Started GET "/api/v1/timelines/home" for 127.0.0.1 at 2017-07-21 13:09:41 +0200
Processing by HomeController#index as HTML
  Parameters: {"any"=>"statuses/new"}
Processing by Api::V1::Timelines::HomeController#show as HTML
Started GET "/api/v1/notifications" for 127.0.0.1 at 2017-07-21 13:09:41 +0200
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Query Trace > app/controllers/concerns/localized.rb:14:in `set_locale'
----------- DEACTIVATING 38a63955ddac01cffd13276d771eeaf2 (CALLED FROM Warden::Manager.after_set_user)
  Doorkeeper::AccessToken Load (0.5ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "84dcd2b9bf5c13bc3ddf4ed8d97411049b7d6953a703c03cf0765407ae9f8afc"], ["LIMIT", 1]]
  Query Trace > app/controllers/api/base_controller.rb:55:in `current_resource_owner'
     from app/controllers/api/base_controller.rb:59:in `current_user'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  SessionActivation Load (0.3ms)  SELECT "session_activations".* FROM "session_activations" WHERE "session_activations"."session_id" = $1  [["session_id", "38a63955ddac01cffd13276d771eeaf2"]]
  Query Trace > app/models/session_activation.rb:65:in `deactivate'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
Processing by Api::V1::NotificationsController#index as HTML
  User Load (4.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Query Trace > app/controllers/api/base_controller.rb:55:in `current_resource_owner'
     from app/controllers/api/base_controller.rb:59:in `current_user'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  Account Load (0.5ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Query Trace > app/controllers/application_controller.rb:43:in `check_suspension'
   (0.2ms)  BEGIN
  Query Trace > app/controllers/concerns/user_tracking_concern.rb:17:in `set_user_activity'
     from app/controllers/api/base_controller.rb:66:in `require_user!'
   (0.2ms)  BEGIN
  Query Trace > app/models/session_activation.rb:65:in `deactivate'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  SQL (0.4ms)  UPDATE "users" SET "current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["current_sign_in_at", "2017-07-21 11:09:41.524747"], ["last_sign_in_at", "2017-07-21 11:09:22.116661"], ["sign_in_count", 1744], ["updated_at", "2017-07-21 11:09:41.526719"], ["id", 1]]
  SQL (0.3ms)  DELETE FROM "session_activations" WHERE "session_activations"."id" = $1  [["id", 31]]
  Query Trace > app/controllers/concerns/user_tracking_concern.rb:17:in `set_user_activity'
     from app/controllers/api/base_controller.rb:66:in `require_user!'
  Query Trace > app/models/session_activation.rb:65:in `deactivate'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  Doorkeeper::AccessToken Load (0.3ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."id" = $1 LIMIT $2  [["id", 31], ["LIMIT", 1]]
  Doorkeeper::AccessToken Load (0.6ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "84dcd2b9bf5c13bc3ddf4ed8d97411049b7d6953a703c03cf0765407ae9f8afc"], ["LIMIT", 1]]
  Query Trace > app/models/session_activation.rb:65:in `deactivate'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  Query Trace > app/controllers/api/base_controller.rb:55:in `current_resource_owner'
     from app/controllers/api/base_controller.rb:59:in `current_user'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  SQL (0.3ms)  DELETE FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."id" = $1  [["id", 31]]
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Query Trace > app/controllers/api/base_controller.rb:55:in `current_resource_owner'
     from app/controllers/api/base_controller.rb:59:in `current_user'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  Query Trace > app/models/session_activation.rb:65:in `deactivate'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  Account Load (0.7ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Query Trace > app/controllers/application_controller.rb:43:in `check_suspension'
   (9.9ms)  COMMIT
  Query Trace > app/controllers/concerns/user_tracking_concern.rb:17:in `set_user_activity'
     from app/controllers/api/base_controller.rb:66:in `require_user!'
   (3.4ms)  BEGIN
  Query Trace > app/controllers/concerns/user_tracking_concern.rb:17:in `set_user_activity'
     from app/controllers/api/base_controller.rb:66:in `require_user!'
   (3.9ms)  COMMIT
  SQL (1.9ms)  UPDATE "users" SET "current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["current_sign_in_at", "2017-07-21 11:09:41.541991"], ["last_sign_in_at", "2017-07-21 11:09:22.116661"], ["sign_in_count", 1744], ["updated_at", "2017-07-21 11:09:41.547117"], ["id", 1]]
  Query Trace > app/models/session_activation.rb:65:in `deactivate'
     from app/controllers/concerns/localized.rb:14:in `set_locale'
  Query Trace > app/controllers/concerns/user_tracking_concern.rb:17:in `set_user_activity'
     from app/controllers/api/base_controller.rb:66:in `require_user!'
this line was reached by /home/sorin/Repositories/mastodon/config/initializers/devise.rb:7:in `block in <top (required)>'
```

**Comment by isati** [comment]
I'm thinking this issue might be related to accounts made before a certain time/commit as I've since created a new test account and do not appear to be experiencing this issue on the newer account, leading me to believe there may be some kind of 'corruption' with older profiles. Is there some way I can get some debugging output to get confirmation of this?

**Comment by sorin-davidoi** [comment]
Can you test if #4292 (in master) fixes the issue? Since it was deployed on glitch.social we've not been getting the welcome notifications anymore.

**Comment by isati** [comment]
Yep, I've just upgraded to master, ran all the usual bundle/yarn/rails commands and also the added mastodon:feeds:build. I'm unfortunately still experiencing this on the older accounts. I've tried revoking all the sessions on the account but it's still occurring.

**Comment by isati** [comment]
I know this probably isn't helpful in diagnosing this either but I've just tried running 'rake mastodon:feeds:clear_all' and cleared the cache from my browser (Chrome for Android) - this seemed to resolve the 401 issue (& push notifications resetting) for about an hour and then unfortunately it began again.

Is there somewhere I can look to get more info to debug this? Unfortunately this is only happening on my production setup and the aforementioned 'Invalid access token' error in the mastodon-streaming.service is the only place I've seen any errors about this and it's a bit vague to help diagnose the problem..

**Comment by Gargron** [comment]
You can find your supposed access token if you inspect the web UI page's networking requests. You can then find information about the access token in the database in the oauth_access_tokens table. A row for that token should exist and not be revoked. For that matter, make sure the streaming API is connecting to the same postgres database as the rails part.

**Comment by isati** [comment]
Ok I've seemingly resolved the issue with the 401 errors but I'm not entirely sure how or why this has worked. 

I've changed my redis.conf from `appendonly no` to `appendonly yes` and restarted redis-server. This has created an appendonly.aof file alongside the redis .rdb file and has now stopped producing the 401 errors.

I'm not entirely sure what has gone wrong, perhaps some kind of corruption/disparity with the .rdb file - yet the redis-check-rdb command returns no issues with the .rdb.

Can anyone offer any insight into what may have been the issue here and any advice on what I should possibly do next?

**Comment by isati** [comment]
Uh. Actually this isn't resolved by the method above. It seemed to prevent the 401 errors for about 24 hours and now they've kicked in again.

I'll have to continue to look into this.

**Comment by isati** [comment]
I've now managed to get this reproduced on desktop Chrome instead of Chrome for Android and can get some kind of client side output. The dev tools is now constantly spammed with the messages in the screenshots. This seemingly just started after about an hour of being logged into the site and active. Reloading the site will temporarily resolve it.

If I can provide any more useful client and/or server side information then please let me know because this has me baffled.

![screenshot_20170727_162927](https://user-images.githubusercontent.com/227061/28678766-20528c16-72e9-11e7-9a10-c386563cb19c.png)
![screenshot_20170727_163038](https://user-images.githubusercontent.com/227061/28678767-205b5c9c-72e9-11e7-827c-bca9dee87376.png)

**Comment by isati** [comment]
I'm now closing this issue as this appears to be related to the time on the server being out of sync. Since getting the correct time set on the server these errors have seemingly stopped (at least for now). Unfortunately none of the debugging output really pointed me towards this being a time related issue so it took a fair amount of experimenting with different things to resolve. Apologies for seemingly wasting peoples time over something quite trivial.

**Comment by JRelland** [comment]
> as this appears to be related to the time on the server being out of sync

Hi @isati, 
I have the same message on YUNOHOST Mastodon instance.
Thank you if you can summarize the solution (for a non-coder).

Best regards, José

**Comment by stemy2** [comment]
Same problem on my own instance since last upgrade.

**Comment by JRelland** [comment]
@stemy2 
Try to open it with FF on private mode. 
For me if works!

**Comment by 8cH9azbsFifZ** [comment]
> I'm now closing this issue as this appears to be related to the time on the server being out of sync. Since getting the correct time set on the server these errors have seemingly stopped (at least for now). Unfortunately none of the debugging output really pointed me towards this being a time related issue so it took a fair amount of experimenting with different things to resolve. Apologies for seemingly wasting peoples time over something quite trivial.

Same problem here with current version. Time sync is not the cause for me...

**Comment by danger89** [comment]
For some reason. I also have this issue still.

**Comment by kawainime** [comment]
raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'The access token is invalid')
