### ISSUE TITLE
MIME type error on master

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#4224]
Heyoo

Got that when I tried to launch master (033f970)

```
Content Security Policy: The settings on the page prevented the loading of a resource to 'self' (« script-src https://niu.moe »). Source: call to eval() or related function blocked by CSP.  (source inconnue)
The resource at « https://niu.moe/packs/features/getting_started-e3d830184e49186fcef1.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/community_timeline-1a77ddbef09e2329d15d.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/notifications-b1392535b163a801ad3a.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/home_timeline-d182432eb8d6a619e454.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/public_timeline-200d69f5bde37804bc7e.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/compose-873b744f8e83a6ba3bd6.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
GET 
https://niu.moe/packs/features/getting_started-e3d830184e49186fcef1.js [HTTP/2.0 404 Not Found 248 ms]
The resource at « https://niu.moe/packs/features/getting_started-e3d830184e49186fcef1.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/compose-873b744f8e83a6ba3bd6.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/home_timeline-d182432eb8d6a619e454.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/notifications-b1392535b163a801ad3a.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/community_timeline-1a77ddbef09e2329d15d.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/public_timeline-200d69f5bde37804bc7e.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
Error: Loading chunk 4 failed.
Stack trace :
n@https://niu.moe/packs/common-78f38e6ba0bf521142d5.js:1:554
  common-78f38e6ba0bf521142d5.js:1:358891
Error: Loading chunk 10 failed.
Stack trace :
n@https://niu.moe/packs/common-78f38e6ba0bf521142d5.js:1:554
  common-78f38e6ba0bf521142d5.js:1:358891
Error: Loading chunk 12 failed.
Stack trace :
n@https://niu.moe/packs/common-78f38e6ba0bf521142d5.js:1:554
  common-78f38e6ba0bf521142d5.js:1:358891
Error: Loading chunk 23 failed.
Stack trace :
n@https://niu.moe/packs/common-78f38e6ba0bf521142d5.js:1:554
  common-78f38e6ba0bf521142d5.js:1:358891
The resource at « https://niu.moe/packs/features/compose-873b744f8e83a6ba3bd6.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/home_timeline-d182432eb8d6a619e454.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/notifications-b1392535b163a801ad3a.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
The resource at « https://niu.moe/packs/features/getting_started-e3d830184e49186fcef1.js » Has been blocked due to an invalid MIME type (X-Content-Type-Options: nosniff).[En savoir plus]  getting-started
TypeError: ServiceWorker script at https://niu.moe/sw.js for scope https://niu.moe/ encountered an error during installation.  (Unknow source)
Waterfox cannot establish a connection with the server at the address wss://niu.moe/api/v1/streaming/?access_token=dd0a9ce41197ee6945c6619f89655c3f339d391e6a439c2d45a7e6aef47c5f1a&stream=user.  application-4db4048076a53cebc9c8.js:1:42981
Waterfox cannot establish a connection with the server at the address wss://niu.moe/api/v1/streaming/?access_token=dd0a9ce41197ee6945c6619f89655c3f339d391e6a439c2d45a7e6aef47c5f1a&stream=user.  application-4db4048076a53cebc9c8.js:1:42981
Waterfox cannot establish a connection with the server at the address wss://niu.moe/api/v1/streaming/?access_token=dd0a9ce41197ee6945c6619f89655c3f339d391e6a439c2d45a7e6aef47c5f1a&stream=user.  application-4db4048076a53cebc9c8.js:1:42981
Waterfox cannot establish a connection with the server at the address wss://niu.moe/api/v1/streaming/?access_token=dd0a9ce41197ee6945c6619f89655c3f339d391e6a439c2d45a7e6aef47c5f1a&stream=user.  application-4db4048076a53cebc9c8.js:1:42981
Waterfox cannot establish a connection with the server at the address wss://niu.moe/api/v1/streaming/?access_token=dd0a9ce41197ee6945c6619f89655c3f339d391e6a439c2d45a7e6aef47c5f1a&stream=user.  application-4db4048076a53cebc9c8.js:1:42981
Waterfox cannot establish a connection with the server at the address wss://niu.moe/api/v1/streaming/?access_token=dd0a9ce41197ee6945c6619f89655c3f339d391e6a439c2d45a7e6aef47c5f1a&stream=user.  application-4db4048076a53cebc9c8.js:1:42981
```

Any idea ? Might came from my nginx config... so there is :)

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen 80;
  listen [::]:80;
  server_name niu.moe;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name niu.moe;
  ssl_certificate "myAwesomeCert";
  ssl_certificate_key "myAwesomeKey";

  ssl_certificate "my2ndAwesomeCert";
  ssl_certificate_key "my2ndAwesomeKey";

  ssl_protocols TLSv1.2;
  ssl_ciphers EECDH+CHACHA20:EECDH+AESGCM;
  ssl_ecdh_curve X25519:P-521:P-384:P-256;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  keepalive_timeout 70;
  sendfile on;
  client_max_body_size 0;
  large_client_header_buffers 4 32k;

  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
  add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; media-src 'self'; font-src 'self'; img-src 'self' https://i.imgur.com data:; connect-src 'self' https://niu.moe/ wss://niu.moe/; upgrade-insecure-requests; frame-ancestors 'none'";
  add_header Referrer-Policy "no-referrer";

  root /home/technowix/mastodon/data/public;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  location / {
    try_files $uri @proxy;
  }

  location ~ ^/(assets|system/media_attachments/files|system/accounts/avatars) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri @proxy;
  }

  location @proxy {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    tcp_nodelay on;
  }

  location /api/v1/streaming {
    proxy_pass http://127.0.0.1:4000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    tcp_nodelay on;
  }

  error_page 500 501 502 503 504 /500.html;
}
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Technowix** [comment]
That was bad compiled assets, don't know why they haven't been fine even after 2 rebuild 🤔
