### ISSUE TITLE
DB migration failed when upgrading to v1.5.1

### ISSUE THREAD

**Issue by asterismo** [tootsuite/mastodon#4564]
RAILS_ENV=production bundle exec rails db:migrate
Migrating to AddForeignKeysForAccounts (20170604144747)
== 20170604144747 AddForeignKeysForAccounts: migrating ========================
-- add_foreign_key(:statuses, :accounts, {:on_delete=>:cascade})
   -> 1.3535s
-- add_foreign_key(:statuses, :accounts, {:column=>:in_reply_to_account_id, :on_delete=>:nullify})
   -> 0.5924s
-- add_foreign_key(:statuses, :statuses, {:column=>:in_reply_to_id, :on_delete=>:nullify})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::ForeignKeyViolation: ERROR:  insert or update on table "statuses" violates foreign key constraint "fk_rails_94a6f70399"
DETAIL:  Key (in_reply_to_id)=(22) is not present in table "statuses".
: ALTER TABLE "statuses" ADD CONSTRAINT "fk_rails_94a6f70399"
FOREIGN KEY ("in_reply_to_id")
  REFERENCES "statuses" ("id")
 ON DELETE SET NULL
/home/mastodon/live/db/migrate/20170604144747_add_foreign_keys_for_accounts.rb:5:in `change'
bin/rails:4:in `<main>'
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "statuses" violates foreign key constraint "fk_rails_94a6f70399"
DETAIL:  Key (in_reply_to_id)=(22) is not present in table "statuses".
: ALTER TABLE "statuses" ADD CONSTRAINT "fk_rails_94a6f70399"
FOREIGN KEY ("in_reply_to_id")
  REFERENCES "statuses" ("id")
 ON DELETE SET NULL
/home/mastodon/live/db/migrate/20170604144747_add_foreign_keys_for_accounts.rb:5:in `change'
bin/rails:4:in `<main>'
PG::ForeignKeyViolation: ERROR:  insert or update on table "statuses" violates foreign key constraint "fk_rails_94a6f70399"
DETAIL:  Key (in_reply_to_id)=(22) is not present in table "statuses".
/home/mastodon/live/db/migrate/20170604144747_add_foreign_keys_for_accounts.rb:5:in `change'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by asterismo** [comment]
This fixed the issue, closing.

`RAILS_ENV=production bundle exec rails mastodon:maintenance:prepare_for_foreign_keys`
