### ISSUE TITLE
Mastodon requires write access to tmp/ after a system update

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#4625]
Hi,

I recently restarted my server to apply a kernel upgrade. This was not a Mastodon update.
After the restart, mastodon-web crashes with the following error:

```
Aug 17 22:02:59 mastodon bundle[1386]: [1386] ! Unable to load application: Errno::EACCES: Permission denied @ rb_sysopen - tmp/cache/bootsnap-load-path-cache.89661.tmp
Aug 17 22:02:59 mastodon bundle[1386]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/store.rb:72:in `binwrite': Permission denied @ rb_sysopen - tmp/cache/bootsnap-load-path-cache.89661.tmp (Errno::EACCES)
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/store.rb:72:in `dump_data'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/store.rb:53:in `commit_transaction'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/store.rb:45:in `transaction'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/cache.rb:154:in `unshift_paths_locked'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/cache.rb:100:in `block in unshift_paths'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/cache.rb:100:in `synchronize'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/cache.rb:100:in `unshift_paths'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/change_observer.rb:27:in `block in register'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:555:in `block (2 levels) in <class:Engine>'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:554:in `reverse_each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:554:in `block in <class:Engine>'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/config/environment.rb:5:in `<top (required)>'
Aug 17 22:02:59 mastodon bundle[1386]: #011from config.ru:4:in `require'
Aug 17 22:02:59 mastodon bundle[1386]: #011from config.ru:4:in `block in <main>'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
Aug 17 22:02:59 mastodon bundle[1386]: #011from config.ru:in `new'
Aug 17 22:02:59 mastodon bundle[1386]: #011from config.ru:in `<main>'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:313:in `load_rackup'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:242:in `app'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/runner.rb:138:in `load_and_bind'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cluster.rb:391:in `run'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
Aug 17 22:02:59 mastodon bundle[1386]: #011from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<main>'
```

This is caused by `/home/mastodon-code/mastodon/` being read-only.

I had to re-run `RAILS_ENV=production bundle exec rails assets:precompile` to fix the issue.
Do you know why I had to re-run this command even without upgrading Mastodon?

Mastodon version: 1.4.7

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ProgVal** [comment]
Why? I still have the same issue

**Comment by Gargron** [comment]
The mastodon tmp directory must be writeable. It's used for temporary files and some cache.

Also:

We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

- https://discourse.joinmastodon.org
- #mastodon on irc.freenode.net

**Comment by ProgVal** [comment]
> The mastodon tmp directory must be writeable. It's used for temporary files and some cache.

It contains executable code (bootsnap), so it should not be written in at runtime.
Also, that's a blocker for #3576.

**Comment by Gargron** [comment]
Bootsnap caches the executable for faster boot time, that's the point of bootsnap. However, you can remove bootsnap if you want by modifying config/boot.rb
