### ISSUE TITLE
Newly setup instance fails when opening about page

### ISSUE THREAD

**Issue by artemist** [tootsuite/mastodon#4784]
I have been trying to setup a new mastodon instances, after destroying my old one a few months ago. All services are properly running, according to systemd, and I used the setup instructions in the documentation repo. However, when accessing the about page, the following appears in the journal:
```
Sep 02 13:43:59 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] [active_model_serializers] Rendered InitialStateSerializer with ActiveModelSerializers::Adapter::Attributes (1.03ms)
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] method=GET path=/about format=html controller=AboutController action=show status=500 error='ActionView::Template::Error: Name or service not known' duration=301.
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] ActionView::Template::Error (Name or service not known):
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]      5:   %script#initial-state{ type: 'application/json' }!= json_escape(@initial_state_json)
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]      6:   = javascript_pack_tag 'about', integrity: true, crossorigin: 'anonymous'
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]      7:
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]      8:   %meta{ property: 'og:site_name', content: site_title }/
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]      9:   %meta{ property: 'og:url', content: about_url }/
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]     10:   %meta{ property: 'og:type', content: 'website' }/
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]     11:   %meta{ property: 'og:title', content: site_hostname }/
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880]
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] app/models/setting.rb:26:in `[]'
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] app/helpers/instance_helper.rb:5:in `site_title'
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] app/views/about/show.html.haml:8:in `block in _app_views_about_show_html_haml___1176822784704555982_173863106760'
Sep 02 13:44:00 aragorn bundle[20888]: [deb4b52f-1266-48ab-9d46-36c131b1b880] app/views/about/show.html.haml:4:in `_app_views_about_show_html_haml___1176822784704555982_173863106760'
```

I am using Arch Linux. This appears both with and without a separate `WEB_DOMAIN`, and on both v1.5.1 and master. I can help in debugging, but I am not experienced in Ruby.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Wrong config for one of the databases hosts
