### ISSUE TITLE
Upgrade to 1.6 failed

### ISSUE THREAD

**Issue by Showfom** [tootsuite/mastodon#4884]
I try to use 

```
docker-compose run --rm web rails mastodon:maintenance:remove_deprecated_preview_cards
```

It shows

```
Starting mastodon_redis_1 ... done
Starting mastodon_db_1 ... done
Creating mastodon user (UID : 991 and GID : 991)...
Updating permissions...
Executing process...
rails aborted!
Don't know how to build task 'mastodon:maintenance:remove_deprecated_preview_cards' (see --tasks)
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

After restart docker using `docker-compose restart`

```
Restarting mastodon_sidekiq_1 ... done
Restarting mastodon_web_1 ... done
Restarting mastodon_streaming_1 ... done
Restarting mastodon_db_1 ... done
Restarting mastodon_redis_1 ... done
```

But seems our Mastodon is still 1.5.1

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Did you git pull/docker-compose build before trying anything else?

**Comment by Showfom** [comment]
Done, here is my steps for any newbies like me

```
cd /your/path/to/mastodon
docker-compose stop
git pull origin v1.6.0
docker-compose build
docker-compose run --rm web rails db:migrate
docker-compose run --rm web rails assets:precompile
docker-compose run --rm web rails mastodon:maintenance:remove_deprecated_preview_cards
docker-compose up -d
docker-compose restart
```

It works well
