### ISSUE TITLE
Request ran for longer than 90000ms

### ISSUE THREAD

**Issue by valentin2105** [tootsuite/mastodon#5176]
Hi !

Since I upgraded to 1.6.1, I got a lot of this error that cause big slow on Mastodon, 

```
[aeda5a4b-8601-465b-998a-d5b20522be55] method=GET path=/api/v1/timelines/public format=html controller=Api::V1::Timelines::PublicController action=show status=500 error='Rack::Timeout::RequestTimeoutException: Request ran for longer than 90000ms' duration=372619.05 view=0.00 db=0.00
[aeda5a4b-8601-465b-998a-d5b20522be55]
[aeda5a4b-8601-465b-998a-d5b20522be55] Rack::Timeout::RequestTimeoutException (Request ran for longer than 90000ms):
[aeda5a4b-8601-465b-998a-d5b20522be55]
[aeda5a4b-8601-465b-998a-d5b20522be55] app/controllers/api/base_controller.rb:55:in `current_resource_owner'
[aeda5a4b-8601-465b-998a-d5b20522be55] app/controllers/api/base_controller.rb:59:in `current_user'
[aeda5a4b-8601-465b-998a-d5b20522be55] app/controllers/concerns/localized.rb:14:in `set_locale'
[e03df4c2-848f-4293-862b-e7ee0bc23bf3] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (256.66ms)
[e03df4c2-848f-4293-862b-e7ee0bc23bf3] method=GET path=/api/v1/timelines/public format=html controller=Api::V1::Timelines::PublicController action=show status=200 duration=653.54 view=258.18 db=191.73
```

I use PGBouncer and `DB_POOL=100` on the web container (and 5 for each sidekiq).

Any idea ? 

My DB is > 35G.  

EDIT: 
and after few hours, I got that : `a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use`

**Comment by Gargron** [comment]
We removed Rack::Timeout
