### ISSUE TITLE
ActiveModel::MissingAttributeError: missing attribute: reblog_of_id 

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#5271]
produced in commit f0c939c431fc7b738208cfd2bc1ea914c8b03769

```
sidekiq_mailers_1  | 2017-10-08T12:00:07.922Z 11 TID-4lpn6w54 WARN: {"context":"Job raised exception","job":{"class":"UnmergeWorker","args":[26847,1451],"retry":true,"queue":"pull","jid":"0ad2b8911adc70684256e37c","created_at":1507462509.6353755,"enqueued_at":1507464007.8389301,"error_message":"missing attribute: reblog_of_id","error_class":"ActiveModel::MissingAttributeError","failed_at":1507462511.978429,"retry_count":6,"retried_at":1507464007.9182627},"jobstr":"{\"class\":\"UnmergeWorker\",\"args\":[26847,1451],\"retry\":true,\"queue\":\"pull\",\"jid\":\"0ad2b8911adc70684256e37c\",\"created_at\":1507462509.6353755,\"enqueued_at\":1507464007.8389301,\"error_message\":\"missing attribute: reblog_of_id\",\"error_class\":\"ActiveModel::MissingAttributeError\",\"failed_at\":1507462511.978429,\"retry_count\":5,\"retried_at\":1507463307.2973957}"}
sidekiq_mailers_1  | 2017-10-08T12:00:07.923Z 11 TID-4lpn6w54 WARN: ActiveModel::MissingAttributeError: missing attribute: reblog_of_id
sidekiq_mailers_1  | 2017-10-08T12:00:07.923Z 11 TID-4lpn6w54 WARN: /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/read.rb:71:in `block in _read_attribute'
sidekiq_mailers_1  | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_set.rb:45:in `block in fetch_value'
sidekiq_mailers_1  | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute.rb:219:in `value'
sidekiq_mailers_1  | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_set.rb:45:in `fetch_value'
sidekiq_mailers_1  | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/read.rb:71:in `_read_attribute'
sidekiq_mailers_1  | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/read.rb:36:in `__temp__275626c6f676f5f666f59646'
sidekiq_mailers_1  | /mastodon/app/models/status.rb:90:in `reblog?'
sidekiq_mailers_1  | /mastodon/app/lib/feed_manager.rb:198:in `remove_from_feed'
```

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Line touched by @aschmitz in 468523f4
