### ISSUE TITLE
Mastodon dev install assets:precompile error + workaround on macOS (charlock_holmes)

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#5726]
In the [dev installation instructions for macOS](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md), run:

`bin/rails assets:precompile --trace`

Output (error):

```
bin/rails assets:precompile --trace
rails aborted!
LoadError: dlopen(/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.5/lib/charlock_holmes/charlock_holmes.bundle, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.58.2.dylib
  Referenced from: /Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.5/lib/charlock_holmes/charlock_holmes.bundle
  Reason: image not found - /Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.5/lib/charlock_holmes/charlock_holmes.bundle
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.5/lib/charlock_holmes.rb:1:in `<top (required)>'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
/Users/aral/ind.ie/products/forks/mastodon/config/application.rb:7:in `<top (required)>'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/aral/ind.ie/products/forks/mastodon/Rakefile:4:in `<top (required)>'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.2.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:103:in `load_rakefile'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/aral/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
```

Workaround:

```
gem install charlock_holmes -- -- with-icu-dir=/usr/local/Cellar/icu4c
```

Post-workaround output:

```
bin/rails assets:precompile --trace
^[** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke yarn:install (first_time)
** Execute yarn:install
** Execute assets:precompile
** Invoke webpacker:compile (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Invoke webpacker:check_binstubs (first_time)
** Execute webpacker:check_binstubs
** Execute webpacker:verify_install
Webpacker is installed 🎉 🍰
Using /Users/aral/ind.ie/products/forks/mastodon/config/webpacker.yml file for setting up webpack paths
** Invoke environment
** Execute webpacker:compile
Compiling…
Compiled all packs in /Users/aral/ind.ie/products/forks/mastodon/public/packs
** Invoke assets:generate_static_pages (first_time)
** Execute assets:generate_static_pages
  Rendering errors/500.html.haml within layouts/error
  Rendered errors/500.html.haml within layouts/error (766.9ms)
```

*****

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on master

**Comment by wxcafe** [comment]
Please make a PR to tootsuite/documentation with that fix! Thanks a lot for your report :)
