### ISSUE TITLE
Error 500 when fetching certain users on 2.1.0rc2

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#5927]
One of the user on WitchesTown cannot be fetched using ActivityPub.

```
$ http https://witches.town/@Ewakhine 'Accept:application/activity+json, application/ld+json'
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 46
Content-Type: application/json; charset=UTF-8
Date: Fri, 08 Dec 2017 12:35:46 GMT
Vary: Origin
X-Request-Id: 05195cb3-2930-42cd-899b-84f01b844d0a
X-Runtime: 0.379211

{
    "error": "Internal Server Error",
    "status": 500
}
```

Here is the corresponding log : 

```
$ docker-compose logs web | grep 05195cb3-2930-42cd-899b-84f01b844d0a
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] [active_model_serializers] Rendered ActivityPub::ActorSerializer with ActivityPub::Adapter (372.84ms)
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] method=GET path=/@Ewakhine format=json controller=AccountsController action=show status=500 error='NoMethodError: undefined method `gsub' for nil:NilClass' duration=376.86 view=0.00 db=1.13
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a]   
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] NoMethodError (undefined method `gsub' for nil:NilClass):
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a]   
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] app/serializers/activitypub/actor_serializer.rb:93:in `header_exists?'
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] app/lib/activitypub/adapter.rb:34:in `serializable_hash'
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] app/controllers/accounts_controller.rb:29:in `block (2 levels) in show'
web_1        | [05195cb3-2930-42cd-899b-84f01b844d0a] app/controllers/accounts_controller.rb:8:in `show'
```

This issue cannot be reproduced on another user : 
```
$ http https://witches.town/@Sylvhem 'Accept:application/activity+json, application/ld+json'
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/activity+json; charset=utf-8
Date: Fri, 08 Dec 2017 12:37:44 GMT
ETag: W/"116fece77ff43940ef92b7569ac80833"
Link: <https://witches.town/.well-known/webfinger?resource=acct%3ASylvhem%40witches.town>; rel="lrdd"; type="application/xrd+xml", <https://witches.town/users/Sylvhem.atom>; rel="alternate"; type="application/atom+xml", <https://witches.town/users/Sylvhem>; rel="alternate"; type="application/activity+json"                                                                           
Server: Mastodon
Set-Cookie: _mastodon_session=MU9BbDIrTmFFSXJ6Z0szWXIzV29jRDJ5VEhPWEFXZzllTnlPeWVZdndwSzJNaE03cHJ3b1pzdWNoandKQ2tMamFzbVlxdlVkNXRYK0VTRzMraUdVQUNGQUR1UmJNQkxzOWlibXZMamdSS009LS0zS3hsUjBrb2ZuU0E1eUcwMlNzMDJRPT0%3D--a9a457c4cafdeba5cc623ecb3d2f7983602185f7; path=/; secure; HttpOnly                                                                                                      
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Request-Id: fa5a3a26-a944-448b-baf9-8fc28e9b2b1a
X-Robots-Tag: noindex
X-Runtime: 0.390982
X-XSS-Protection: 1; mode=block

{ /* TRUNCATED */ }
```

**Comment by Aldarone** [comment]
I have found a few other users : 

```
http https://witches.town/@sobarel 'Accept:application/activity+json, application/ld+json'
http https://witches.town/@yaymukund 'Accept:application/activity+json, application/ld+json'
http https://witches.town/@geekylou 'Accept:application/activity+json, application/ld+json'
```

I still don't know what they have in common to behave like this.

**Comment by Aldarone** [comment]
Ewakhine cannot change his header. The log contains a similar error : 

```
web_1        | [80c7ec49-20d7-4a26-9419-37c598331b67] method=PUT path=/settings/profile format=html controller=Settings::ProfilesController action=update status=500 error='NoMethodError: undefined method `gsub' for nil:NilClass' duration=292.01 view=0.00 db=3.14
web_1        | [80c7ec49-20d7-4a26-9419-37c598331b67]   
web_1        | [80c7ec49-20d7-4a26-9419-37c598331b67] NoMethodError (undefined method `gsub' for nil:NilClass):
web_1        | [80c7ec49-20d7-4a26-9419-37c598331b67]   
web_1        | [80c7ec49-20d7-4a26-9419-37c598331b67] app/services/update_account_service.rb:7:in `call'
web_1        | [80c7ec49-20d7-4a26-9419-37c598331b67] app/controllers/settings/profiles_controller.rb:17:in `update'
```

**Comment by ThibG** [comment]
I am pretty sure this is a PaperClip issue, but I don't understand why PaperClip and ActiveRecord methods aren't shown in the trace.

**Comment by Gargron** [comment]
>but I don't understand why PaperClip and ActiveRecord methods aren't shown in the trace.

Rails config strips backtraces that lead to gems from logs

**Comment by ThibG** [comment]
Alright. The logs would be interesting with those full backtraces.

**Comment by Gargron** [comment]
In any case if this is new in 2.1 and it seems to clearly come from paperclip, then it must be the `fog` gems added in #5604 @ykzts

**Comment by Aldarone** [comment]
Is there a way for me to enable the full trace even if I'm using docker ?

I can trigger the issue in the rails console by calling `Paperclip::Attachment.reprocess!` but I don't get the full trace.

(And I checked my minio log because… well… you know… and there is nothing wrong in it)

**Comment by ykzts** [comment]
@Gargron Since Minio occasionally does not return ETag, it seems that a problem is occurring. I do not know where this is occurring. Revert fog-aws. I will investigate after Mastodon v2.1 release.
