### ISSUE TITLE
500 error when following user 

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#5952]
when following user who is alreay follow requested, api returns server error.

method=POST path=/api/v1/follows format=html controller=Api::V1::FollowsController action=create status=500 error='NameError: undefined local variable or method `follow_requests' for #<FollowService:0x000055cede83f880 @_routes=nil>' duration=25.12 view=0.00 db=6.78
  
NameError (undefined local variable or method `follow_requests' for #<FollowService:0x000055cede83f880 @_routes=nil>):
  
app/services/follow_service.rb:25:in `call'
app/controllers/api/v1/follows_controller.rb:12:in `create'

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tateisu** [comment]
Thanks!
If it recurs, I will open again.
