### ISSUE TITLE
Account migration allow loop

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#6022]
Account migration setting allow redirect user himself.
(on 2.1.0 rc5)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tateisu** [comment]
after set loop, many request raises error.

method=GET path=/web/getting-started format=html controller=HomeController action=index status=500 error='SystemStackError: stack level too deep' duration=1759.01 view=0.00 db=20.11
  
SystemStackError (stack level too deep):
  
app/models/concerns/account_finder_concern.rb:41:in `block in scoped_accounts'
app/models/concerns/account_finder_concern.rb:39:in `tap'
app/models/concerns/account_finder_concern.rb:39:in `scoped_accounts'
app/models/concerns/account_finder_concern.rb:33:in `account'
app/models/concerns/account_finder_concern.rb:20:in `find_remote'
app/lib/formatter.rb:195:in `link_to_account'
app/lib/formatter.rb:185:in `link_to_mention'
app/lib/formatter.rb:90:in `block in encode_and_link_urls'
app/lib/formatter.rb:164:in `block in rewrite'
app/lib/formatter.rb:161:in `each'
app/lib/formatter.rb:161:in `reduce'
app/lib/formatter.rb:161:in `rewrite'
app/lib/formatter.rb:84:in `encode_and_link_urls'
app/lib/formatter.rb:68:in `linkify'
app/lib/formatter.rb:54:in `simplified_format'
app/serializers/rest/account_serializer.rb:19:in `note'
app/controllers/home_controller.rb:42:in `set_initial_state_json'
