### ISSUE TITLE
NameError: uninitialized constant Annotate

### ISSUE THREAD

**Issue by kpcyrd** [tootsuite/mastodon#6161]
I got this error after I followed the development instructions. I'm not sure if I did something wrong or if this is a dependency issue:
```
mastodon@ac3465cc152c:/mastodon$ bundle exec rails db:setup --trace
rails aborted!
NameError: uninitialized constant Annotate
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in load_missing_constant'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `rescue in load_missing_constant'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/mastodon/lib/tasks/auto_annotate_models.rake:44:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:648:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:648:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:648:in `run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:440:in `run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:457:in `load_tasks'
/mastodon/Rakefile:6:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
bin/rails:4:in `<main>'

Caused by:
NameError: uninitialized constant Annotate
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/mastodon/lib/tasks/auto_annotate_models.rake:44:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:648:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:648:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:648:in `run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:440:in `run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:457:in `load_tasks'
/mastodon/Rakefile:6:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
bin/rails:4:in `<main>'
mastodon@ac3465cc152c:/mastodon$ 
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on master

**Comment by Gargron** [comment]
Don't forget RAILS_ENV=production in front of CLI commands

**Comment by kpcyrd** [comment]
@Gargron got distracted and noticed I tried this caused a different error. This one is fine because I didn't configure this yet. There might be a problem with the [Development guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md) since I was told to omit `RAILS_ENV=production` for development. :)
```
mastodon@ac3465cc152c:/mastodon$ RAILS_ENV=production bundle exec rails db:setup 
fe_sendauth: no password supplied
Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>nil, "host"=>"localhost", "port"=>5432, "prepared_statements"=>true}
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
/mastodon/vendor/bundle/ruby/2.4.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/mastodon/vendor/bundle/ruby/2.4.0/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:695:in `connect'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:220:in `initialize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:10:in `connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:19:in `create'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:117:in `create'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
(See full trace by running task with --trace)
mastodon@ac3465cc152c:/mastodon$ 
```

**Comment by theowenyoung** [comment]
I solved this problem by run this command first:

```bash
bundle config set --local with 'development'
```

**Comment by Marty-Crabneck** [comment]
> I solved this problem by run this command first:
> 
> ```shell
> bundle config set --local with 'development'
> ```

That fixed it for me. Thanks!

**Comment by avdi** [comment]
> I solved this problem by run this command first:
> 
> ```shell
> bundle config set --local with 'development'
> ```

Worked for me too. Should I add a doc PR for this, I wonder?
