### ISSUE TITLE
Duplicate keys and failures to create indexes

### ISSUE THREAD

**Issue by vmatekole** [tootsuite/mastodon#6386]
We run 2.0.0 on social.coop and wish to bump to 2.1.3. We ran into failures during the migration step. An issue related to null values in the ``` mentions ``` table, we subsequently attempted a restore of the database and ran into the following issues. A number of duplicate keys have managed to find their way into our database – we are unaware of any manual changes to the datastore and have only deleted  accounts via the Rails console. Any advise or insight into these issues would be welcome. Attached is a dump of the restoration log. Additionally, see related bug #3005 
[restore.log](https://github.com/tootsuite/mastodon/files/1677921/restore.log)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Try the `rake mastodon:maintenance:prepare_for_foreign_keys` command, it's supposed to clean up foreign key violations.

**Comment by vmatekole** [comment]
@Gargron I get the following error when running prepare_for_foreign_keys:

```
bash-4.3#  rake mastodon:maintenance:prepare_for_foreign_keys
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column pc.status_id does not exist
LINE 1: ...G preview_cards pc LEFT JOIN statuses s ON s.id = pc.status_...
                                                             ^
: DELETE FROM preview_cards USING preview_cards pc LEFT JOIN statuses s ON s.id = pc.status_id WHERE preview_cards.id = pc.id AND s.id IS NULL
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/mastodon/lib/tasks/mastodon.rake:281:in `block (3 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```

**Comment by Gargron** [comment]
@vmatekole Hmm, that script hasn't been updated for a while. Can you comment out that particular line and retry? preview_cards table schema has changed so it chokes up.
