### ISSUE TITLE
PG::NotNullViolation: ERROR:  column "memorial" contains null values

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#6398]
When trying to upgrade my instance, I get this:

```
root@animalliberation:~/mastodon# docker-compose run --rm web rake db:migrate
Starting mastodon_redis_1 ... done
Starting mastodon_db_1 ... done
Creating mastodon user (UID : 991 and GID : 991)...
Updating permissions...
Executing process...
Migrating to AddMemorialToAccounts (20171107143332)
== 20171107143332 AddMemorialToAccounts: migrating ============================
-- transaction_open?()
   -> 0.0004s
-- execute("SET statement_timeout TO 0")
   -> 0.0013s
-- transaction()
-- add_column(:accounts, :memorial, :bool, {:default=>nil})
   -> 0.0080s
-- change_column_default(:accounts, :memorial, false)
   -> 0.0112s
   -> 0.0221s
-- transaction_open?()
   -> 0.0000s
-- exec_query("SELECT reltuples FROM pg_class WHERE relname = 'accounts'")
   -> 0.0008s
-- exec_query("SELECT  \"accounts\".\"id\" FROM \"accounts\" ORDER BY \"accounts\".\"id\" ASC LIMIT 1")
   -> 0.0028s
-- Migrating accounts.memorial (~16509 rows)
   -> Migrated 4956 rows (~30.02%, 0:02 remaining, DO NOT interrupt)
   -> Migrated 9912 rows (~60.04%, 0:01 remaining, DO NOT interrupt)
   -> Migrated 14042 rows (~85.06%, 0:00 remaining, DO NOT interrupt)
-- change_column_null(:accounts, :memorial, false)
-- remove_column(:accounts, :memorial)
   -> 0.0078s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::NotNullViolation: ERROR:  column "memorial" contains null values
: ALTER TABLE "accounts" ALTER "memorial" SET NOT NULL
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:458:in `change_column_null'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:63:in `method_missing'
/mastodon/lib/mastodon/migration_helpers.rb:456:in `add_column_with_default'
/mastodon/db/migrate/20171107143332_add_memorial_to_accounts.rb:9:in `block in up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:6:in `safety_assured'
/mastodon/db/migrate/20171107143332_add_memorial_to_accounts.rb:9:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  column "memorial" contains null values
: ALTER TABLE "accounts" ALTER "memorial" SET NOT NULL
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:458:in `change_column_null'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:63:in `method_missing'
/mastodon/lib/mastodon/migration_helpers.rb:456:in `add_column_with_default'
/mastodon/db/migrate/20171107143332_add_memorial_to_accounts.rb:9:in `block in up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:6:in `safety_assured'
/mastodon/db/migrate/20171107143332_add_memorial_to_accounts.rb:9:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
PG::NotNullViolation: ERROR:  column "memorial" contains null values
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:458:in `change_column_null'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:63:in `method_missing'
/mastodon/lib/mastodon/migration_helpers.rb:456:in `add_column_with_default'
/mastodon/db/migrate/20171107143332_add_memorial_to_accounts.rb:9:in `block in up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:6:in `safety_assured'
/mastodon/db/migrate/20171107143332_add_memorial_to_accounts.rb:9:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Considering this is the first time memorials are being added, it's weird the migrations are complaining about it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Weird. Mastodon uses some migration helpers that allow performing long migrations without locking the database. I guess there is a bug within this?

**Comment by nightpool** [comment]
Try running it again?
