### ISSUE TITLE
NameError when running db:migrate with docker-compose

### ISSUE THREAD

**Issue by gergelypolonkai** [tootsuite/mastodon#6413]
When I run `db:migrate` using the docker approach, I get a `NameError`.  SELinux is enabled on the host, but there are no AVC denials.

I got the same error (not sure about the traceback) when I ran `mastodon:webpush:generate_vapid_key`, but in that there was also some permission denied messages caused by the entrypoint script; after fixing that permission denied issue, I could generate the VAPID keys.

Here is a backtrace for the `db.migrate` run:

```
$ sudo docker-compose run --rm web rake db:migrate --trace
Updating permissions...
Executing process...
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Mastodon::Application::ApplicationExtension
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in load_missing_constant'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `rescue in load_missing_constant'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
/mastodon/config/application.rb:96:in `block in <class:Application>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `catch'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:198:in `block in halting'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `invoke_before'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:130:in `run_callbacks'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:87:in `prepare!'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/mastodon/config/environment.rb:5:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/redis-rack-2.0.3/bin/rake:17:in `load'
/mastodon/vendor/bundle/ruby/2.5.0/gems/redis-rack-2.0.3/bin/rake:17:in `<top (required)>'
/usr/local/bundle/bin/rake:29:in `load'
/usr/local/bundle/bin/rake:29:in `<main>'

Caused by:
NameError: uninitialized constant Mastodon::Application::ApplicationExtension
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/mastodon/config/application.rb:96:in `block in <class:Application>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `catch'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:198:in `block in halting'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `invoke_before'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:130:in `run_callbacks'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:87:in `prepare!'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/mastodon/config/environment.rb:5:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/redis-rack-2.0.3/bin/rake:17:in `load'
/mastodon/vendor/bundle/ruby/2.5.0/gems/redis-rack-2.0.3/bin/rake:17:in `<top (required)>'
/usr/local/bundle/bin/rake:29:in `load'
/usr/local/bundle/bin/rake:29:in `<main>'
Tasks: TOP => db:migrate => environment
```

**Update**: it seems the command actually runs, then throws the above error. Hence, I updated the title, too.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dlowe-net** [comment]
I have a similar problem, but was able to work around it (sort of) with
```
docker-compose run --rm web bash
rake db:migrate
```

**Comment by Gargron** [comment]
Very strange... Would be curious if someone who has this issue was able to remove the line `gem "bootsnap"` from the Gemfile, re-build, and try again - whether it will make a difference.

**Comment by gergelypolonkai** [comment]
Yes, now it’s missing bootsnap :smile:

```
$ sudo docker-compose run --rm web rake db:migrate
Updating permissions...
Executing process...
rake aborted!
LoadError: cannot load such file -- bootsnap
/mastodon/config/boot.rb:4:in `require'
/mastodon/config/boot.rb:4:in `<top (required)>'
/mastodon/config/application.rb:1:in `require_relative'
/mastodon/config/application.rb:1:in `<top (required)>'
/mastodon/Rakefile:4:in `require'
/mastodon/Rakefile:4:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```
