### ISSUE TITLE
mastodon:media:remove_remote fails after interrupt

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#6584]
Due to a SSH connection error my ```mastodon:media:remove_remote``` job was interrupted. I tried to resume it, but I got this error message:

```
[paperclip] deleting media_attachments/files/000/056/215/original/2ae553820e9b1811.jpg
rails aborted!
Errno::ENOENT: No such file or directory @ apply2files - /mastodon/public/system/media_attachments/files/000/056/215/original/2ae553820e9b1811.jpg
/mastodon/vendor/bundle/ruby/2.5.0/gems/fog-local-0.4.0/lib/fog/storage/local/models/file.rb:46:in `delete'
/mastodon/vendor/bundle/ruby/2.5.0/gems/fog-local-0.4.0/lib/fog/storage/local/models/file.rb:46:in `destroy'
/mastodon/vendor/bundle/ruby/2.5.0/gems/paperclip-5.1.0/lib/paperclip/storage/fog.rb:131:in `block in flush_deletes'
/mastodon/vendor/bundle/ruby/2.5.0/gems/paperclip-5.1.0/lib/paperclip/storage/fog.rb:129:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/paperclip-5.1.0/lib/paperclip/storage/fog.rb:129:in `flush_deletes'
/mastodon/vendor/bundle/ruby/2.5.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:240:in `save'
/mastodon/vendor/bundle/ruby/2.5.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:267:in `destroy'
/mastodon/lib/tasks/mastodon.rake:115:in `block (4 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block (2 levels) in find_each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block in find_each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:129:in `block in find_in_batches'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:230:in `block in in_batches'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `loop'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `in_batches'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:128:in `find_in_batches'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:62:in `find_each'
/mastodon/lib/tasks/mastodon.rake:114:in `block (3 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/mastodon/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => mastodon:media:remove_remote
(See full trace by running task with --trace)
```

Obviously the job breaks if any file cannot be found. 

My suggestion: **Please change the behavior to "ignore"** instead of "crash because a file, that we wanted to delete anyway, does not exist" ;-)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThomasLeister** [comment]
I'm not a Ruby expert but maybe the actions here: https://github.com/tootsuite/mastodon/blob/76198c63b613f353f2e4a82ce89a8450ca219b88/lib/tasks/mastodon.rake#L474 ... should only be executed if the file exists. A check should be introduced before 

```
media.file.destroy
media.save
```
