### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen on rails assets:precompile

### ISSUE THREAD

**Issue by Jack3113** [tootsuite/mastodon#6794]
I am trying to update my instance to v2.3.1 and I got an error when I execute the task "assets:precompile".

Here my logs :

```
$ sudo docker-compose run --rm web rails assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke yarn:install (first_time)
** Execute yarn:install
** Execute assets:precompile
I, [2018-03-16T04:53:30.065011 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js
I, [2018-03-16T04:53:30.066175 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js.gz
rails aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js.47308361575040.5.866765
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:278:in `initialize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:278:in `open'
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:278:in `atomic_write'
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:165:in `write_to'
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:209:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => assets:precompile
```

Maybe similar to #4625

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Jack3113** [comment]
My `docker-compose logs` is full of 
```
web_1        | [1b151688-0f4b-49c9-85c0-184beaed312d] Errno::EACCES (Permission denied @ rb_sysopen - /mastodon/public/system/accounts/avatars/000/003/724/original/ac82fcf142e32cd6.jpg):
```

**Comment by ykzts** [comment]
```console
$ sudo docker-compose run --rm -u root web chown -R mastodon:mastodon public/assets public/packs public/system
```

I think will fix it by run the above command.

**Comment by Jack3113** [comment]
Thank you !

**Comment by CSDUMMI** [comment]
I've just received a similar issue. And I'm unsure of whether this is a bug with the Dockerfile used?
