### ISSUE TITLE
Docker new installation: Compiling CSS/JS assets fails

### ISSUE THREAD

**Issue by RosaEinhorn** [tootsuite/mastodon#6840]
Hi everybody,

I am trying to deploy a new instance of mastodon using docker on Ubuntu 16.04.
using
`docker-compose run --rm web rake mastodon:setup`
to setup the instance. However, the last step always fails.
I also tried:
`docker-compose run --rm web rails assets:precompile`
to generate the assets - also fails.
I upgraded to a machine with 8GB RAM (+5GB swap), so this should not be the issue.

Any idea on how to solve that ?
Thanks a lot! :-)

```
The final step is compiling CSS/JS assets.
This may take a while and consume a lot of RAM.
Compile the assets now? Yes
Running `RAILS_ENV=production rails assets:precompile` ...

I, [2018-03-19T21:46:14.843296 #16]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css
I, [2018-03-19T21:46:14.843666 #16]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css.gz
I, [2018-03-19T21:46:14.864696 #16]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css
I, [2018-03-19T21:46:14.864832 #16]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css.gz
I, [2018-03-19T21:46:15.450674 #16]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js
I, [2018-03-19T21:46:15.451312 #16]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js.gz
I, [2018-03-19T21:46:15.512995 #16]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css
I, [2018-03-19T21:46:15.513162 #16]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css.gz
rails aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /mastodon/public/assets/doorkeeper
/mastodon/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:163:in `write_to'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:209:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

That failed! Maybe you need swap space?
```
-- trance is not giving any additional info.

**Comment by dollars0427** [comment]
Have same problem at Ubuntu 16.04:
```bash
Starting mastodon_redis_1 ...
Starting mastodon_db_1 ... done
I, [2018-03-20T04:07:46.096781 #5]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css
I, [2018-03-20T04:07:46.097924 #5]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css.gz
I, [2018-03-20T04:07:46.112354 #5]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css
I, [2018-03-20T04:07:46.113416 #5]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css.gz
I, [2018-03-20T04:07:46.546374 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js
I, [2018-03-20T04:07:46.547495 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js.gz
I, [2018-03-20T04:07:46.559751 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css
I, [2018-03-20T04:07:46.561018 #5]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css.gz
rails aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /mastodon/public/assets/doorkeeper
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:163:in `write_to'
/mastodon/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:209:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/mastodon/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by Gargron** [comment]
I think the documentation for Docker is missing a step. From within the cloned repository:

`chown -R 991:991 public`

**Comment by dollars0427** [comment]
@Gargron I can build the assets files by docker now. Thank you !

**Comment by RosaEinhorn** [comment]
Added this [here](https://github.com/tootsuite/documentation/pull/577/commits/6eb6f3bd05b9ad36108ec3681cd00959adee06ea).

I think this issue is solved. :-)

**Comment by StudioLE** [comment]
The same error occurs when attempting to install via docker using a prebuilt image.

It can be solved with `chown -R 991:991 public` however I'm not familiar enough with Mastodon to know at which stage this should be done. Could someone who is revised the [Using a prebuilt image](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md#using-a-prebuilt-image) section of the documentation?

**Comment by salsadoom** [comment]
I found if you are using the prebuilt images, you need to change the permissions right when it asks "Compile the assets now?". Fix the permissions before you answer, and the installation will continue.
