### ISSUE TITLE
module.js  throws error on latest master branch

### ISSUE THREAD

**Issue by nynhex** [tootsuite/mastodon#6897]
I forked master, and fetched/merged upstream this morning.  Re-bundled, and did a `foreman start` in my dev environment and received the following:

```
foreman start
11:11:12 web.1     | started with pid 23767
11:11:12 sidekiq.1 | started with pid 23768
11:11:12 stream.1  | started with pid 23769
11:11:12 webpack.1 | started with pid 23770
11:11:13 stream.1  | yarn run v1.5.1
11:11:13 stream.1  | $ node ./streaming/index.js
11:11:13 web.1     | [23767] Puma starting in cluster mode...
11:11:13 web.1     | [23767] * Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
11:11:13 web.1     | [23767] * Min threads: 5, max threads: 5
11:11:13 web.1     | [23767] * Environment: development
11:11:13 web.1     | [23767] * Process workers: 2
11:11:13 web.1     | [23767] * Preloading application
11:11:13 stream.1  | info Starting streaming API server master with 1 workers
11:11:13 webpack.1 | module.js:545
11:11:13 webpack.1 |     throw err;
11:11:13 webpack.1 |     ^
11:11:13 webpack.1 |
11:11:13 webpack.1 | Error: Cannot find module '../lib/polyfills'
11:11:13 webpack.1 |     at Function.Module._resolveFilename (module.js:543:15)
11:11:13 webpack.1 |     at Function.Module._load (module.js:470:25)
11:11:13 webpack.1 |     at Module.require (module.js:593:17)
11:11:13 webpack.1 |     at require (internal/module.js:11:18)
11:11:13 webpack.1 |     at Object.<anonymous> (/Users/nynhex/Dropbox/mastodon/node_modules/.bin/webpack-dev-server:6:1)
11:11:13 webpack.1 |     at Module._compile (module.js:649:30)
11:11:13 webpack.1 |     at Object.Module._extensions..js (module.js:660:10)
11:11:13 webpack.1 |     at Module.load (module.js:561:32)
11:11:13 webpack.1 |     at tryModuleLoad (module.js:501:12)
11:11:13 webpack.1 |     at Function.Module._load (module.js:493:3)
11:11:13 stream.1  | info Starting worker 1
11:11:13 stream.1  | info Worker 1 now listening on 0.0.0.0:4000
11:11:13 webpack.1 | exited with code 1
11:11:13 system    | sending SIGTERM to all processes
11:11:13 web.1     | [23767] === puma shutdown: 2018-03-24 11:11:13 -0500 ===
11:11:13 web.1     | [23767] - Goodbye!
11:11:13 web.1     | [23767] ! Unable to load application: SignalException: SIGTERM
11:11:13 stream.1  | info Worker 1 exiting, bye bye
11:11:13 stream.1  | info Worker 1 exiting, bye bye
11:11:14 stream.1  | exited with code 1
11:11:14 sidekiq.1 | terminated by SIGTERM
11:11:14 web.1     | terminated by SIGTERM
```
I'll start digging into it, but it basically broke my work, so I may have to revert commits.  I'd really like to keep upstream in sync with my fork, but concerned about regressions or breaking changes.  I'm not so great with JS (more ruby/rails) so any help would be appreciated.
* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Please don't use master for anything critical! I merged in new features today morning and it's not impossible that something broke.

**Comment by nynhex** [comment]
@Gargron Thanks for the super-fast reply.  Is there a branch/etc that I can fork again that is working/stable?  I'm trying to work on my instance today.  Otherwise, I guess I can revert to when it was last working? Sorry for the newb stuff, but just getting started 👍

**Comment by Gargron** [comment]
`git checkout v2.3.2` - then maybe create a new branch off of that

**Comment by nynhex** [comment]
@gandaro I was able to checkout `v2.3.2` and branch off of that, all is working now. 🥇 I'm wanting to launch my own instance next week, but at the same time, I'd like to keep up to date with whatever stable release gets cut.  Any suggestions on best practices to avoid divergence and preventing breakage in prod?

Also, I'm wanting to contribute to core.  As I see a lot of issues that I could probably PR for the team.  So hopefully I can help somewhere 😄
