### ISSUE TITLE
Error editing profile settings - undef method fields=

### ISSUE THREAD

**Issue by azah** [tootsuite/mastodon#7194]
```  
[be28693d-5596-478c-930b-fe5fabfe2268] NoMethodError (undefined method `fields=' for #<Account:0x00005556992d43b8>):
[be28693d-5596-478c-930b-fe5fabfe2268] app/models/account.rb:214:in `build_fields'
[be28693d-5596-478c-930b-fe5fabfe2268] app/controllers/settings/profiles_controller.rb:15:in `show'
```

Currently on commit 1663368724b0a0076823aa31459eb77b9264969b.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
rails db:migrate done?

**Comment by azah** [comment]
Looks like I forgot to do so, however, I get this issue now:
```
extract_foreign_key_action("c")

StandardError: An error has occurred, all later migrations canceled:

undefined method `extract_foreign_key_action' for #<IdsToBigints:0x0000555c06886168>
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:870:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:860:in `method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:75:in `method_missing'
/mastodon/lib/mastodon/migration_helpers.rb:614:in `block in cleanup_concurrent_column_type_change'
```

This is the same issue I ran into earlier, #7119
