### ISSUE TITLE
LengthValidationError while doing LinkCrawlWorker

### ISSUE THREAD

**Issue by Reverite** [tootsuite/mastodon#7198]
@Gargron suggests making an issue, so: at random times, Sidekiq will do a `LinkCrawlWorker` that attempts to fetch an image that is bigger than what Mastodon allows and throws a `LengthValidationError`. Stack trace below:

```
21:42:10 sidekiq.1 | 2018-04-19T21:42:10.988Z 10 TID-gtn1l406k WARN: {"context":"Job raised exception","job":{"class":"LinkCrawlWorker","args":[99883222350761087],"retry":0,"queue":"pull","jid":"1fe8117aebff38d52f87496d","created_at":1524097020.7592351,"enqueued_at":1524174130.8003056,"error_message":"Mastodon::LengthValidationError","error_class":"Mastodon::LengthValidationError","failed_at":1524097020.9222064,"retry_count":-1},"jobstr":"{\"class\":\"LinkCrawlWorker\",\"args\":[99883222350761087],\"retry\":0,\"queue\":\"pull\",\"jid\":\"1fe8117aebff38d52f87496d\",\"created_at\":1524097020.7592351,\"enqueued_at\":1524174130.8003056,\"error_message\":\"Mastodon::LengthValidationError\",\"error_class\":\"Mastodon::LengthValidationError\",\"failed_at\":1524097020.9222064,\"retry_count\":-1}"}
21:42:10 sidekiq.1 | 2018-04-19T21:42:10.988Z 10 TID-gtn1l406k WARN: Mastodon::LengthValidationError: Mastodon::LengthValidationError
21:42:10 sidekiq.1 | 2018-04-19T21:42:10.988Z 10 TID-gtn1l406k WARN: /mastodon/app/lib/request.rb:104:in `body_with_limit'
21:42:10 sidekiq.1 | /mastodon/app/models/concerns/remotable.rb:36:in `block (2 levels) in remotable_attachment'
21:42:10 sidekiq.1 | /mastodon/app/lib/request.rb:43:in `perform'
21:42:10 sidekiq.1 | /mastodon/app/models/concerns/remotable.rb:24:in `block in remotable_attachment'
21:42:10 sidekiq.1 | /mastodon/app/services/fetch_link_card_service.rb:149:in `attempt_opengraph'
21:42:10 sidekiq.1 | /mastodon/app/services/fetch_link_card_service.rb:58:in `process_url'
21:42:10 sidekiq.1 | /mastodon/app/services/fetch_link_card_service.rb:25:in `block in call'
21:42:10 sidekiq.1 | /mastodon/vendor/bundle/ruby/2.4.0/gems/mario-redis-lock-1.2.0/lib/redis_lock.rb:46:in `acquire'
21:42:10 sidekiq.1 | /mastodon/app/services/fetch_link_card_service.rb:22:in `call'
21:42:10 sidekiq.1 | /mastodon/app/workers/link_crawl_worker.rb:9:in `perform'
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
cc @akihikodaki

**Comment by Gargron** [comment]
While this issue is about LinkCrawlWorker, I believe this same issue could affect other optional images: avatars, headers, media attachments. I'll go double check

**Comment by akihikodaki** [comment]
Kind of stupid question: `FetchLinkCardService` rescues certain kind of exceptions, but why not rescue *all*? There could be more various exceptions can be triggered by remote hosts in `FetchLinkCardService`, and covering each of them is difficult and some kind of mistakes are inevitable.

**Comment by Gargron** [comment]
@akihikodaki We don't rescue from all exceptions exactly because we want to know when something unexpected occurs... We know there can be a HTTP timeout, unexpected status code, OpenSSL error, but if there is some edge case that suddenly appears, we need it in an error log so we can learn about it and provide an appropriate rescue for it in the future.

**Comment by akihikodaki** [comment]
Yes, it will work.

**Comment by Reverite** [comment]
Still a `LengthValidationError` issue here and there:

```
sidekiq_1    | 2018-05-06T04:46:21.562Z 5 TID-gn5ngk7b9 WARN: {"context":"Job raised exception","job":{"class":"LinkCrawlWorker","args":[99978171848054852],"retry":0,"queue":"pull","jid":"e9f0de3c0a8b5c24db6918be","created_at":1525545835.0998518,"enqueued_at":1525581980.6312747,"error_message":"Mastodon::LengthValidationError","error_class":"Mastodon::LengthValidationError","failed_at":1525545836.0777943,"retry_count":-1},"jobstr":"{\"class\":\"LinkCrawlWorker\",\"args\":[99978171848054852],\"retry\":0,\"queue\":\"pull\",\"jid\":\"e9f0de3c0a8b5c24db6918be\",\"created_at\":1525545835.0998518,\"enqueued_at\":1525581980.6312747,\"error_message\":\"Mastodon::LengthValidationError\",\"error_class\":\"Mastodon::LengthValidationError\",\"failed_at\":1525545836.0777943,\"retry_count\":-1}"}
sidekiq_1    | 2018-05-06T04:46:21.562Z 5 TID-gn5ngk7b9 WARN: Mastodon::LengthValidationError: Mastodon::LengthValidationError
sidekiq_1    | 2018-05-06T04:46:21.562Z 5 TID-gn5ngk7b9 WARN: /mastodon/app/lib/request.rb:116:in `body_with_limit'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:48:in `block in process_url'
sidekiq_1    | /mastodon/app/lib/request.rb:47:in `perform'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:46:in `process_url'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:25:in `block in call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:22:in `call'
sidekiq_1    | /mastodon/app/workers/link_crawl_worker.rb:9:in `perform'
```
