### ISSUE TITLE
Unable to load application: NameError: uninitialized constant ActiveRecordQueryTrace

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#749]
Hi,

When running Mastodon, I'm getting this error:

```
mastodon-run@ruby:/home/mastodon-code/mastodon$ NODE_ENV=production /home/mastodon-code/.gem/ruby/2.3.0/bin/bundle exec puma -C config/puma.rb 
[23464] Puma starting in cluster mode...
[23464] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
[23464] * Min threads: 5, max threads: 5
[23464] * Environment: development
[23464] * Process workers: 2
[23464] * Preloading application
[23464] ! Unable to load application: NameError: uninitialized constant ActiveRecordQueryTrace
/home/mastodon-code/mastodon/config/environments/development.rb:85:in `<top (required)>': uninitialized constant ActiveRecordQueryTrace (NameError)
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:599:in `each'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:599:in `block in <class:Engine>'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /home/mastodon-code/mastodon/config/environment.rb:5:in `<top (required)>'
	from config.ru:4:in `require'
	from config.ru:4:in `block in <main>'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:370:in `run'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
	from /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<main>'
```

I followed install instructions; the only difference is that I use Ruby 2.3.3 instead of 2.3.1.

**Comment by ProgVal** [comment]
Aaaaah, got it. The code in the systemd unit is broken. I'm adding that fix to #748.

**Comment by ProgVal** [comment]
Nevermind, I mixed two targets.

**Comment by kwaio** [comment]
I'm actually having this exact issue, care to detail what your problem was ?

**Comment by ProgVal** [comment]
@kwaio I used `RAILS_ENV` instead of `NODE_ENV` in one of the units.

**Comment by kwaio** [comment]
Same here, forgot to append the environnment variable.
