### ISSUE TITLE
ActiveRecord::StatementInvalid errors on 2.4.0rc4

### ISSUE THREAD

**Issue by Reverite** [tootsuite/mastodon#7559]
I've started to get some StatementInvalid errors for some reason, starting in 2.4.0rc4. Stack trace attached:

```
sidekiq_1    | 2018-05-20T20:22:44.183Z 5 TID-gtjgr08j1 WARN: ActiveRecord::StatementInvalid: PG::ProgramLimitExceeded: ERROR:  index row size 6792 exceeds maximum 2712 for index "index_preview_cards_on_url"
sidekiq_1    | HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
sidekiq_1    | Consider a function index of an MD5 hash of the value, or use full text indexing.
sidekiq_1    | : INSERT INTO "preview_cards" ("url", "title", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
sidekiq_1    | 2018-05-20T20:22:44.183Z 5 TID-gtjgr08j1 WARN: /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `async_exec'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `block (2 levels) in exec_no_cache'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_no_cache'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
sidekiq_1    | /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_no_cache'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:590:in `execute_and_clear'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:117:in `exec_insert'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:115:in `exec_insert'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:149:in `insert'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/persistence.rb:187:in `_insert_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/persistence.rb:733:in `_create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/counter_cache.rb:180:in `_create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/locking/optimistic.rb:70:in `_create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/attribute_methods/dirty.rb:137:in `_create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/callbacks.rb:342:in `block in _create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/callbacks.rb:342:in `_create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/timestamp.rb:95:in `_create_record'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/persistence.rb:704:in `create_or_update'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/callbacks.rb:338:in `block in create_or_update'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/callbacks.rb:338:in `create_or_update'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/persistence.rb:308:in `save!'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/validations.rb:52:in `save!'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:315:in `block in save!'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:386:in `block in with_transaction_returning_status'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
sidekiq_1    | /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:383:in `with_transaction_returning_status'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:315:in `save!'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/suppressor.rb:48:in `save!'
sidekiq_1    | /mastodon/app/models/preview_card.rb:49:in `save_with_optional_image!'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:153:in `attempt_opengraph'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:60:in `process_url'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:25:in `block in call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'
sidekiq_1    | /mastodon/app/services/fetch_link_card_service.rb:22:in `call'
sidekiq_1    | /mastodon/app/workers/link_crawl_worker.rb:9:in `perform'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
sidekiq_1    | /mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
sidekiq_1    | /mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Damn, this one is serious (not in a security way, but in a "this design needs fixing" way).

Ref: https://dba.stackexchange.com/questions/162820/values-larger-than-1-3-of-a-buffer-page-cannot-be-indexed

Basically the preview_cards table is getting huge and the unique index that ensures there should only be one preview card per URL can't keep all the data anymore. Solution should be to replace it with an md5 index and use md5 on the where-clause too when querying for it.

cc @akihikodaki

**Comment by akihikodaki** [comment]
> Basically the preview_cards table is getting huge and the unique index that ensures there should only be one preview card per URL can't keep all the data anymore.

Well, I think the total table size does not matter, but the size of each URLs do. In this case a preview card had a URL whose length is about 6792.
6KB URL is just insane. I don't think we have to deal with it. We may have `rescue` clause so that it does not abort a Sidekiq job or add a validation on ActiveRecord side.

**Comment by Gargron** [comment]
@akihikodaki Isn't the URL column a varchar with limited length (255)? I thought the URL would be cut off if it was longer than that. I'm trying to find documentation on what the "string" type in Rails migrations gets translated to through the Postgres adapter, but I always thought it was varchar (255)

**Comment by akihikodaki** [comment]
I forgot to mention that MD5 may not be optimal in this case. If you still want to deal with URLs longer than 2712, you should use a function with strong collision resistance like SHA-256.

**Comment by Gargron** [comment]
I have misread the error message in any case, I thought the issue was due to the number of rows, when it was the size of a particular row. a 6KB URL is unrealistic, somebody is (deliberately or accidentally) trying to overload your server, I would try to find who submitted that link and keep a close eye on them.

On the other hand, I found confirmation that yes, [string has a 255 limit in the database](https://rubyinrails.com/2014/03/16/rails-migration-difference-between-text-and-string/) by default. So I am not sure why the index would attempt to work on the full, uncut value. Something to look into, but not urgent for 2.4 as I thought initially.

**Comment by akihikodaki** [comment]
@Gargron
> Isn't the URL column a varchar with limited length (255)? I thought the  URL would be cut off if it was longer than that. I'm trying to find  documentation on what the "string" type in Rails migrations gets  translated to through the Postgres adapter, but I always thought it was  varchar (255)

A URL with 2,000 characters works for me. I don't think it has a limit other than 1GB limit (the maximum size of column.)

**Comment by Gargron** [comment]
Damn, you're right: rails/rails#14579 They changed this since I looked into it :weary: 

Well, that's quite unpleasant - since I was under the wrong impression that a lot of the columns would be limited to 255 chars at most. Knowing the limit is a whole 1GB makes me uncomfortable.

I believe URLs, e-mails, display names, list titles, URIs should get a db-level length constraint just to be sure. There is no use case for any of them to ever be 1GB in size.

**Comment by Gargron** [comment]
Adding those limits now could be problematic because if there is an offending row somewhere, it would prevent the constraint from being created. I'm also now reading about other issues related to having a varchar limit in postgres (apparently, constraint is recommended over changing table definition). Maybe just ensuring everything has a max length validation in Rails would be enough as a first step.
