### ISSUE TITLE
docker latest (2.4.0) mastodon:setup -> rake error

### ISSUE THREAD

**Issue by adlerweb** [tootsuite/mastodon#7612]
I am trying to set up a fresh docker/mastodon environment using the bundled [docker-compose](https://github.com/tootsuite/mastodon/blob/v2.4.0/docker-compose.yml)-File as desribed in the [Docker-Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md). While `docker-compose build` works as expected `docker-compose run --rm web rake mastodon:setup` aborts with the following message:

```
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 12.3.1. Prepending `bundle exec` to your command may solve this.
/mastodon/config/boot.rb:3:in `<top (required)>'
/mastodon/config/application.rb:1:in `require_relative'
/mastodon/config/application.rb:1:in `<top (required)>'
/mastodon/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
Full trace below

System info:
 - docker-compose version 1.21.2, build a133471
 - docker 18.03.1-ce

----
```
~/docker/mastodon# docker-compose run --rm web rake mastodon:setup --trace
Starting mastodon_db_1    ... done
Starting mastodon_redis_1 ... done
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 12.3.1. Prepending `bundle exec` to your command may solve this.
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:313:in `check_for_activated_spec!'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:31:in `block in setup'
/usr/local/lib/ruby/2.4.0/forwardable.rb:229:in `each'
/usr/local/lib/ruby/2.4.0/forwardable.rb:229:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:26:in `map'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:26:in `setup'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:10:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/mastodon/config/boot.rb:3:in `<top (required)>'
/mastodon/config/application.rb:1:in `require_relative'
/mastodon/config/application.rb:1:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/mastodon/Rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
EXIT 1
~/docker/mastodon#
```

**Comment by ykzts** [comment]
```console
$ docker-compose run --rm web rails mastodon:setup
```

`rake` -> `rails`

**Comment by adlerweb** [comment]
Yes, using rails instead of rake worked to get the setup to start. Sadly it did only change .env.production inside the container and as such fail to execute db:setup (missing/empty SECRET_KEY_BASE, seems to use the hosts .env.production). Manually generating and entering the keys lets the containers start as expected. Since there are several other things wrong (like uncommenting build, which wasn't commented for years as far as I can see) I would guess the whole guide is outdated...

**Comment by salsadoom** [comment]
Same issue here, except I'm updating from v2.3.3 to v2.4.1... 

Any solution?

**Comment by GitHubGeek** [comment]
Hi guys,

I'm getting the exact same error when running `mastodon:setup`

```
ArgumentError: `secret_key_base` for production environment must be a type of String
```

Running on a brand new Ubuntu 18.04 VPS.

I'm wondering if it's something to do with the step "Set correct file-owner with chown -R 991:991 public"? On my new Ubuntu install there's no UID 991 listed in `/etc/passwd`

Thanks!

**Comment by Aidot** [comment]
these issuses all caused by .env.production, the file is not automaticlly written. 
open a new terminal window,  copy the generated configuration text and paste it into .env.production manually.
then back to first window, run next step below "If the database already exists, this will erase its contents."

**Comment by zbuttram** [comment]
Just wanted to leave a note that I encountered the same issue. I just had to re-run the setup an extra time and the second time it ran the migrations without any problems.

**Comment by charlesreid1** [comment]
Same problem here, using latest docker tag, following the [docker guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md) to the letter:

```
rails aborted!
ArgumentError: `secret_key_base` for production environment must be a type of String`
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:583:in `validate_secret_key_base'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:432:in `secret_key_base'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:176:in `key_generator'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:205:in `message_verifier'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.1/lib/active_storage/engine.rb:67:in `block (2 levels) in <class:Engine>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
/mastodon/config/environment.rb:5:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:337:in `require_environment!'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)
That failed! Perhaps your configuration is not right
```

**Comment by LoganDark** [comment]
How am I supposed to delete the database after the Mastodon setup fucks up? I fixed .env.production, but now it can't create the database because it already exists!!

**Comment by Dekken** [comment]
@charlesreid1 would you care to post what you did?

>  I had to run the secrets task to generate a secret key string,

what is this precisely

**Comment by Dekken** [comment]
adding 

```
    environment:
      - SECRET_KEY_BASE=$$(bin/rake secret)
```

under

```
services:
  db:
```

resolved this

**Comment by flytreeleft** [comment]
> adding
> 
> ```
>     environment:
>       - SECRET_KEY_BASE=$$(bin/rake secret)
> ```
> 
> under
> 
> ```
> services:
>   db:
> ```
> 
> resolved this

Actually, it should be under:
```yaml
services:
  db:
```

**Comment by marekgit24** [comment]
> Same issue here, except I'm updating from v2.3.3 to v2.4.1...
> 
> Any solution?

You should use " 
Example:
SECRET_KEY_BASE="4f4f4f54f5f46f46d4f5464"

**Comment by Sachin-Suresh** [comment]
@marekgit24 , @PhilipDeegan - Could you please post the entire `.env.production` working copy for the benefit of others for reference.

**Comment by Sachin-Suresh** [comment]
Thanks, @charlesreid1 - I had to do the following:

**Step1:**
```
echo SECRET_KEY_BASE=$(docker-compose run --rm web bundle exec rake secret)
```
**Step2:** Copy and paste the generated `SECRET_KEY_BASE` into the `.env.production` file and then:

```
sed -i -e "s/SECRET_KEY_BASE=/&${SECRET_KEY_BASE}/" .env.production
```

**Step3:**
```
echo OTP_SECRET=$(docker-compose run --rm web bundle exec rake secret)
```
**Step4:** Same as Step 2 for the `OTP_SECRET`.

```
sed -i -e "s/OTP_SECRET=/&${OTP_SECRET}/" .env.production
```

**Step 5:**
When I run the following, I get the Private and Public Key, which again needs to be pasted in the `.env` file.

```
docker-compose run --rm web bundle exec rake mastodon:webpush:generate_vapid_key
```
