### ISSUE TITLE
Uploading webm with no video stream causes "500 Internal Server Error"

### ISSUE THREAD

**Issue by nivex** [tootsuite/mastodon#7619]
I have a .webm [test file](https://www.nivex.net/images/tmp/atest.webm) that contains only an audio stream. This file plays correctly in browser (Firefox 60.0.1). When I upload it to Mastodon to add to a toot I get a "500 Internal Server Error"

I had an instance admin attempt to upload this test file and report the error logs. It appears to be failing on generating a thumbnail for the timeline. I suggest two potential improved outcomes:

1) Dialog reports that there was a problem processing the media.
2) Media is accepted and a blank thumbnail is displayed.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nivex** [comment]
Oh dear, it seems I may not have searched well enough. This appears to be a duplicate of #6147.
I realize there is some contention about uploading audio files. This would tend to bias the fix toward my first suggestion to improve the feedback to the user.

**Comment by sammy8806** [comment]
Hmm .. this seems to be still happening when audio-only video files from other softwares are incoming.

Some options for files like this would be:
* handle the incoming audio-only video better
* just treat them as audio files
* convert them to be a proper audio-file

I would like to get better handling since #11123 is there now.

Here is some more info when files are incoming:

```
NoMethodError: undefined method `*' for nil:NilClass
  from app/models/media_attachment.rb:299:in `check_video_dimensions'
  from active_support/callbacks.rb:426:in `block in make_lambda'
  from active_support/callbacks.rb:198:in `block (2 levels) in halting'
  from paperclip/callbacks.rb:28:in `block in hasta_la_vista_baby'
  from active_support/callbacks.rb:199:in `block in halting'
  from active_support/callbacks.rb:513:in `block in invoke_before'
  from active_support/callbacks.rb:513:in `each'
  from active_support/callbacks.rb:513:in `invoke_before'
  from active_support/callbacks.rb:131:in `run_callbacks'
  from paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
  from paperclip/attachment.rb:509:in `post_process'
  from paperclip/attachment.rb:465:in `post_process_file'
  from paperclip/attachment.rb:113:in `assign'
  from paperclip/has_attached_file.rb:66:in `block in define_setter'
  from app/models/concerns/remotable.rb:40:in `block (2 levels) in remotable_attachment'
  from app/lib/request.rb:75:in `perform'
....
```

ffmpeg info:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'f41aec31432860bb50b881935602482afef8b9ac7218bbc759f47a70aa9a4bcd.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:03:31.31, start: 0.000000, bitrate: 130 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

Branch: master
Commit: 57d98b20f29650d7e8bcaa42b824ce4d794cbcbb

**Comment by vmstan** [comment]
Uploading test file using main, error is now '422: Validation failed: File has contents that are not what they are reported to be'
