### ISSUE TITLE
Upgrade 2.4.2 exec rails assets:clean uninitialized constant Rack

### ISSUE THREAD

**Issue by nemsia** [tootsuite/mastodon#7855]
Hello,
when i launch the assets:clean to upgrade from 2.4.1 to 2.4.2 i have this error:
```
RAILS_ENV=production bundle exec rails assets:clean
rails aborted!
NameError: uninitialized constant Rack::Timeout
/var/www/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/var/www/mastodon/live/config/initializers/timeout.rb:1:in `<top (required)>'
...
```
.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nemsia** [comment]
Ok thank you, i stop using git for update mastodon and that is the problem, config/initializers/timeout.rb stay in place.
Problem solved.
