### ISSUE TITLE
NoMethodError: undefined method `featured_collection_url' for nil:NilClass

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#7864]
Hi,

I have about 10k jobs in my sidekiq queue, most of which are `ActivityPub::SynchronizeFeaturedCollectionWorker` jobs for the same user (ID 29457 on my instance, oc.todon.fr): https://mastodon.rocks/@UBports
I increased the number of Sidekiq workers to 60, but that's not enough to clear the queue.

I applied the patch from #7284, but it doesn't help. My instance's version is 2.3.3.

All these jobs fail with this error:

```
Jun 20 21:20:13 mastodon bundle[20790]: 2018-06-20T19:20:13.417Z 20790 TID-ow01gcrqc WARN: NoMethodError: undefined method `featured_collection_url' for nil:NilClass
Jun 20 21:20:13 mastodon bundle[20790]: 2018-06-20T19:20:13.418Z 20790 TID-ow01gcrqc WARN: /home/mastodon-code/mastodon/app/services/activitypub/process_account_service.rb:30:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/services/activitypub/fetch_remote_account_service.rb:23:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/services/activitypub/fetch_remote_status_service.rb:19:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/services/activitypub/fetch_featured_collection_service.rb:28:in `block in process_items'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/services/activitypub/fetch_featured_collection_service.rb:28:in `map'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/services/activitypub/fetch_featured_collection_service.rb:28:in `process_items'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/services/activitypub/fetch_featured_collection_service.rb:19:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/workers/activitypub/synchronize_featured_collection_worker.rb:9:in `perform'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:188:in `execute_job'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:169:in `block in process'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:97:in `local'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:42:in `block in call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:41:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:204:in `stats'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/job_logger.rb:7:in `call'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:72:in `global'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:129:in `block in dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:44:in `with_context'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:128:in `dispatch'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:168:in `process'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:85:in `process_one'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:73:in `run'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:16:in `watchdog'
Jun 20 21:20:13 mastodon bundle[20790]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Please upgrade to at least 2.4.0

**Comment by ProgVal** [comment]
I can't because of #7642

**Comment by Gargron** [comment]
Oh crap. Sorry about that, slipped my mind. What prevents you from upgrading ruby?

`rbenv install 2.5.1 && gem install bundler --no-ri --no-rdoc && bundle install --deployment --without test development`

**Comment by ProgVal** [comment]
I prefer using the Debian's package instead of another source for various reasons: cleaner, doesn't need to trust Amazon (since rbenv uses ruby-build, whose mirror is hosted on Amazon and doesn't seem to sign their updates), security notices from Debian's Security Team, etc.

**Comment by Gargron** [comment]
Check out 2.4.2 then modify this line: https://github.com/tootsuite/mastodon/blob/master/app/models/concerns/attachmentable.rb#L31

Replace `!attachment.content_type.match?(/image.*/)` with `!attachment.content_type.match(/image.*/).nil?`

I think that should work

**Comment by nightpool** [comment]
the other alternative is to cherry pick the commit that makes this job
unique and not retried

**Comment by Gargron** [comment]
Master has the Ruby 2.3 compatibility fix so closing this
