### ISSUE TITLE
npm run start process consuming high CPU

### ISSUE THREAD

**Issue by njouanin** [tootsuite/mastodon#8005]
Hi,
Since I installed 2.4.3 yesterday, I have a npm run start process consuming a whole CPU core (see here: http://rochefort.beerfactory.org/munin/beerfactory.org/rochefort.beerfactory.org/cpu.html)
Tried to restart mastodon services but CPU usage comes up after restart.

* * * *

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ X ] This bug happens on a [2.4.3](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Are you sure the port is not taken? I know that the streaming server goes crazy with restarts and maxes out the CPU if the port cannot be bound.

**Comment by njouanin** [comment]
what is the used by default by streaming server ?

**Comment by njouanin** [comment]
May be I have a clue : journactl for streaming service shows:
```
Jul 12 22:38:01 rochefort npm[24566]: > node ./streaming/index.js
Jul 12 22:38:02 rochefort npm[24566]: /mnt/app/mastodon/live/node_modules/uws/uws.js:38
Jul 12 22:38:02 rochefort npm[24566]:             throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
Jul 12 22:38:02 rochefort npm[24566]:             ^
Jul 12 22:38:02 rochefort npm[24566]: Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
Jul 12 22:38:02 rochefort npm[24566]:     at native (/mnt/app/mastodon/live/node_modules/uws/uws.js:38:19)
Jul 12 22:38:02 rochefort npm[24566]:     at Object.<anonymous> (/mnt/app/mastodon/live/node_modules/uws/uws.js:42:3)
Jul 12 22:38:02 rochefort npm[24566]:     at Module._compile (module.js:652:30)
Jul 12 22:38:02 rochefort npm[24566]:     at Object.Module._extensions..js (module.js:663:10)
Jul 12 22:38:02 rochefort npm[24566]:     at Module.load (module.js:565:32)
Jul 12 22:38:02 rochefort npm[24566]:     at tryModuleLoad (module.js:505:12)
Jul 12 22:38:02 rochefort npm[24566]:     at Function.Module._load (module.js:497:3)
Jul 12 22:38:02 rochefort npm[24566]:     at Module.require (module.js:596:17)
Jul 12 22:38:02 rochefort npm[24566]:     at require (internal/module.js:11:18)
Jul 12 22:38:02 rochefort npm[24566]:     at Object.<anonymous> (/mnt/app/mastodon/live/streaming/index.js:10:19)
``` 

I already had this compilation but I don't remember how i dealt with it last time ...
