### ISSUE TITLE
Gem Bundler Install Question

### ISSUE THREAD

**Issue by alexnya** [tootsuite/mastodon#8042]
I'm trying to install Mastodon on my server and I'm at the part where I have to install bundler. I'm getting the following when I run bundle install --deployment --without development test:

Building native extensions.  This could take a while...
ERROR:  Error installing cld3:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/cld3-3.2.2/ext/cld3
/usr/bin/ruby2.3 -r ./siteconf20180717-2218-h7m2m1.rb extconf.rb
Failed to locate protobuf

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/cld3-3.2.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/cld3-3.2.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/cld3-3.2.2/gem_make.out 

It seems there is a problem with one of the packages (cld3) in the gem bundle but I don't know how to fix that issue.

**Comment by alexnya** [comment]
Yes I realized one of those packages I didn't have installed. Thanks so much! Now I'm getting another issue. By the way I'm following this guide right here: https://wogandotblog.files.wordpress.com/2017/04/mastodon-setup.pdf. I'm on step 9. I get the following message when I run the command bundle exec rake secret: 

rake aborted!
NameError: uninitialized constant Annotate
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/home/mastodon/live/lib/tasks/auto_annotate_models.rake:44:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:650:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:650:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:650:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:515:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:459:in `load_tasks'
/home/mastodon/live/Rakefile:6:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
NameError: uninitialized constant Annotate
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/home/mastodon/live/lib/tasks/auto_annotate_models.rake:44:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:650:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:650:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:650:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:515:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:459:in `load_tasks'
/home/mastodon/live/Rakefile:6:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by renatolond** [comment]
You have to run using `RAILS_ENV=production bundle exec rake secret`, however, that guide seems not to be up-to-date (current Mastodon recommended ruby is 2.5.1), you should take a look at the [production guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) instead :)

**Comment by alexnya** [comment]
Ok thanks that did the trick! Now in the production guide I'm at the step where you have to run the Mastodon setup wizard. The problem is when I run the command in my command shell (I'm using Webmin), even though I press enter once it enters repeatedly skipping all of the configuration options. So I'm doing each step in the setup wizard individually according to that other guide I showed you. Right now I'm trying to run the command RAILS_ENV=production bundle exec rails db:setup and I'm getting the following:

could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 3306?
received invalid response to SSL negotiation: j
Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>"wYXQ5pNezGwSZTKe", "host"=>"localhost", "port"=>3306, "prepared_statements"=>true}
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 3306?
received invalid response to SSL negotiation: j

Here is my database configuration on the .env.production file. I'm using MariaDB by the way instead of postgresql (is that why maybe?). I omitted the password for this post but it is there in the actual file.

# You may set DATABASE_URL instead for more advanced options
DB_HOST=localhost
DB_USER=mastodon
DB_NAME=mastodon_production
DB_PASS=
DB_PORT=3306

**Comment by Gargron** [comment]
>I'm using MariaDB by the way instead of postgresql

We use some postgres-specific functions so this won't work.

**Comment by alexnya** [comment]
Okay I installed postgresql and I ran the command. I'm getting this error:

could not translate host name "var/run/postgresql" to address: Name or service not known
Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>"", "host"=>"var/run/postgresql", "port"=>5432, "prepared_statements"=>true}
rails aborted!

**Comment by Gargron** [comment]
missing / at the beginning

**Comment by alexnya** [comment]
Thanks I didn't realize I was missing a / at the beginning. Okay now I'm getting this error:

FATAL:  Peer authentication failed for user "mastodon"
Couldn't create database for {"adapter"=>"postgresql", "pool"=>5, "timeout"=>5000, "encoding"=>"unicode", "database"=>"mastodon_production", "username"=>"mastodon", "password"=>"", "host"=>"/var/run/postgresql", "port"=>5432, "prepared_statements"=>true}
rails aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "mastodon"

Now I found solutions online for this, but I just want to hear your solution.

**Comment by alexnya** [comment]
Yes I did it in Webmin since I'm having issues using the command line (the repeated entering issue I told you about). I used the PostgreSQL Database Server Module to create the mastodon user. 

![image](https://user-images.githubusercontent.com/40904096/42841783-303ea8aa-89d9-11e8-8e1c-33e5b157c4d6.png)

**Comment by nightpool** [comment]
I don't really know anything about webmin, but it sounds like if it says "requires password" then it won't be using the `ident` authentication method the production guide set up above. You'll have to contact them or look through their documentation about the right way to configure your databases.

**Comment by alexnya** [comment]
I was able to fix it. I just added the following line to /etc/postgresql/9.5/main/pg_hba.conf:
local   all             mastodon                               md5        

It was able to create the database. Here is the full reply to running RAILS_ENV=production bundle exec rails db:setup:

Created database 'mastodon_production'
rails aborted!
Set SAFETY_ASSURED=1 to run this task in production
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/strong_migrations-0.2.2/lib/tasks/strong_migrations.rake:5:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:262:in `block (3 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:load => strong_migrations:safety_assured
(See full trace by running task with --trace)

Is this what I'm supposed to get?

**Comment by alexnya** [comment]
Ok I fixed by it following this: https://github.com/tootsuite/mastodon/issues/5484#issuecomment-338482619. Now when I enable and start the mastodon services, Im getting this error message when I go to my URL: We're sorry, but something went wrong on our end.

**Comment by alexnya** [comment]
Here is the output of journalctl -u mastodon.web

-- Logs begin at Sun 2018-07-15 08:20:47 CEST, end at Wed 2018-07-18 00:28:43 CEST. --
Jul 18 00:27:00 systemd[1]: Started mastodon-web.
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Unit entered failed state.
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
Jul 18 00:27:00 systemd[1]: Stopped mastodon-web.
Jul 18 00:27:00 systemd[1]: Started mastodon-web.
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Unit entered failed state.
Jul 18 00:27:00 systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
Jul 18 00:27:01 systemd[1]: Stopped mastodon-web.
Jul 18 00:27:01 systemd[1]: Started mastodon-web.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Unit entered failed state.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
Jul 18 00:27:01 systemd[1]: Stopped mastodon-web.
Jul 18 00:27:01 systemd[1]: Started mastodon-web.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Unit entered failed state.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
Jul 18 00:27:01 systemd[1]: Stopped mastodon-web.
Jul 18 00:27:01 systemd[1]: Started mastodon-web.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Unit entered failed state.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Service hold-off time over, scheduling restart.
Jul 18 00:27:01 systemd[1]: Stopped mastodon-web.
Jul 18 00:27:01 systemd[1]: mastodon-web.service: Start request repeated too quickly.
Jul 18 00:27:01 systemd[1]: Failed to start mastodon-web.

**Comment by renatolond** [comment]
You can try running the web command by hand using the mastodon user with 
```
cd ~/live
RAILS_ENV=production /home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
```
Then you can see which error it is complaining about. :)

**Comment by alexnya** [comment]
I'm getting this: 
sh: 1: /home/mastodon/.rbenv/shims/bundle: not found

I thought .rbenv exists in the root directory and not the mastodon directory. Also I couldn't find bundle in the shims directory. I followed the steps for mastodon in the production guide.

**Comment by alexnya** [comment]
Ok I deleted the rbenv directory in root did the following (Keep in mind I did this in the home/mastodon directory as the mastodon user).

git clone https://github.com/rbenv/rbenv.git .rbenv
cd .rbenv && src/configure && make -C src
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec bash

When I enter type rbenv I get the following error:
rbenv: not found

**Comment by alexnya** [comment]
Why is that when I run these commands as the mastodon user it clones it into the root directory instead of the home/mastodon directory?

git clone https://github.com/rbenv/rbenv.git ~/.rbenv
cd ~/.rbenv && src/configure && make -C src
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec bash

**Comment by Gargron** [comment]
Did you `sudo su - mastodon` to become the user mastodon? I don't see a way for that to happen unless you are running those commands as root.

**Comment by alexnya** [comment]
![image](https://user-images.githubusercontent.com/40904096/42978300-2b0ea494-8b9a-11e8-85fe-471dea6859e0.png)

**Comment by alexnya** [comment]
I get this error when I run the command @renatolond suggested.

[15757] Puma starting in cluster mode...
[15757] * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
[15757] * Min threads: 5, max threads: 5
[15757] * Environment: production
[15757] * Process workers: 2
[15757] * Preloading application
Default type scope order, limit and offset are ignored and will be nullified
Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
[15757] * Listening on tcp://0.0.0.0:3000
bundler: failed to load command: puma (/home/mastodon/live/vendor/bundle/ruby/2.5.0/bin/puma)
Errno::EADDRINUSE: Address already in use - bind(2) for "0.0.0.0" port 3000
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `initialize'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `new'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `add_tcp_listener'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/binder.rb:105:in `block in parse'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/binder.rb:88:in `each'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/binder.rb:88:in `parse'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/runner.rb:144:in `load_and_bind'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/cluster.rb:397:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/lib/puma/cli.rb:78:in `run'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/puma-3.11.4/bin/puma:10:in `<top (required)>'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
  /home/mastodon/live/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'

**Comment by alexnya** [comment]
I was able to install rbenv by using putty. Here is what was added to .bashrc

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

**Comment by alexnya** [comment]
Here is the output when I run the command again. This is after I killed the process running at port 3000.

[17824] Puma starting in cluster mode...
[17824] * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
[17824] * Min threads: 5, max threads: 5
[17824] * Environment: production
[17824] * Process workers: 2
[17824] * Preloading application
Default type scope order, limit and offset are ignored and will be nullified
Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
[17824] * Listening on tcp://0.0.0.0:3000
[17824] ! WARNING: Detected 1 Thread(s) started in app boot:
[17824] ! #<Thread:0x00005620d382f0b0@/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:297 sleep> - /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `sleep'
[17824] Use Ctrl-C to stop
[17824] - Worker 0 (pid: 17873) booted, phase: 0
[17824] - Worker 1 (pid: 17884) booted, phase: 0
[af7f947a-c60f-481f-9e07-1ee9f99faaa9] Chewy request strategy is `bypass`
[af7f947a-c60f-481f-9e07-1ee9f99faaa9] method=GET path=/ format=html controller=HomeController action=index status=302 duration=223.86 view=0.00 db=31.69

It sort of hangs at the last command.

**Comment by renatolond** [comment]
This last one seems like a successful start

```
[23779] Puma starting in cluster mode...
[23779] * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
[23779] * Min threads: 5, max threads: 5
[23779] * Environment: development
[23779] * Process workers: 2
[23779] * Preloading application
[23779] * Listening on tcp://0.0.0.0:3000
[23779] ! WARNING: Detected 1 Thread(s) started in app boot:
[23779] ! #<Thread:0x0000561df0cbd450@/home/renatolond/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:297 sleep> - /home/renatolond/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `sleep'
[23779] Use Ctrl-C to stop
[23779] - Worker 0 (pid: 23824) booted, phase: 0
[23779] - Worker 1 (pid: 23839) booted, phase: 0
```

You can try starting the service, it should work

**Comment by alexnya** [comment]
Ok it works now but for a different website than the one I had set for LOCAL_DOMAIN in .env.production. Why is that? I never included this site in the Mastodon setup.

**Comment by alexnya** [comment]
Ok I figured it out. It had to do with the configuration for the two sites in /etc/nginx/sites-available. Now both of them are running Mastodon. All I have to do is to change the database and the ports to make two separate Mastodon instances, right?
