### ISSUE TITLE
PG::DependentObjectsStillExist error on reblogs_count

### ISSUE THREAD

**Issue by Reverite** [tootsuite/mastodon#8262]
Going from 2.4.3 to latest master:

```
bash-4.4$ rake db:migrate
(in /mastodon)
Migrating to CopyStatusStatsCleanup (20180813113448)
== 20180813113448 CopyStatusStatsCleanup: migrating ===========================
-- remove_column(:statuses, :reblogs_count, :integer, {:default=>0, :null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::DependentObjectsStillExist: ERROR:  cannot drop table statuses column reblogs_count because other objects depend on it
DETAIL:  view public_toots depends on table statuses column reblogs_count
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: ALTER TABLE "statuses" DROP COLUMN "reblogs_count"
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:603:in `remove_column'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:840:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:860:in `method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:75:in `method_missing'
/mastodon/db/post_migrate/20180813113448_copy_status_stats_cleanup.rb:8:in `block in change'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:6:in `safety_assured'
/mastodon/db/post_migrate/20180813113448_copy_status_stats_cleanup.rb:7:in `change'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:814:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:796:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1345:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::DependentObjectsStillExist: ERROR:  cannot drop table statuses column reblogs_count because other objects depend on it
DETAIL:  view public_toots depends on table statuses column reblogs_count
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: ALTER TABLE "statuses" DROP COLUMN "reblogs_count"
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:603:in `remove_column'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:840:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:860:in `method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:75:in `method_missing'
/mastodon/db/post_migrate/20180813113448_copy_status_stats_cleanup.rb:8:in `block in change'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:6:in `safety_assured'
/mastodon/db/post_migrate/20180813113448_copy_status_stats_cleanup.rb:7:in `change'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:814:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:796:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1345:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'

Caused by:
PG::DependentObjectsStillExist: ERROR:  cannot drop table statuses column reblogs_count because other objects depend on it
DETAIL:  view public_toots depends on table statuses column reblogs_count
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:603:in `remove_column'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:840:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:860:in `method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:75:in `method_missing'
/mastodon/db/post_migrate/20180813113448_copy_status_stats_cleanup.rb:8:in `block in change'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:6:in `safety_assured'
/mastodon/db/post_migrate/20180813113448_copy_status_stats_cleanup.rb:7:in `change'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:814:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:796:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1345:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.2.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
`view public_toots depends on table statuses column reblogs_count`

What is this? public_toots? We don't have anything similar in our codebase because in code they're called "statuses"

**Comment by Reverite** [comment]
Oh interesting. This seems to be an error with the Ambassador bot, not with Mastodon. Sorry about that! Closing.
