### ISSUE TITLE
Before tagging 2.5.0rc1  .. Accessing /admin/action_logs returns an error.

### ISSUE THREAD

**Issue by jebuskrust** [tootsuite/mastodon#8371]
Before tagging the next RC (2.5.0rc1) could someone look into this following error that I'm receiving in current master. It's been happening for day(s)

When accessing /admin/action_logs. I recieve the following error:

![image](https://user-images.githubusercontent.com/4137216/44477199-f8907a00-a607-11e8-95a0-e9dae08009fb.png)

```
[6ba44f31-2673-48ca-bc4e-76afc88bee19]   Rendering admin/action_logs/index.html.haml within layouts/admin
[6ba44f31-2673-48ca-bc4e-76afc88bee19]   Rendered collection of admin/action_logs/_action_log.html.haml [40 times] (63.2ms)
[6ba44f31-2673-48ca-bc4e-76afc88bee19]   Rendered admin/action_logs/index.html.haml within layouts/admin (66.6ms)
[6ba44f31-2673-48ca-bc4e-76afc88bee19] method=GET path=/admin/action_logs format=html controller=Admin::ActionLogsController action=index status=500 error='ActionView::Template::Error: unknown attribute 'favourites_count' for Status.' duration=80.88 view=0.00 db=8.48
[6ba44f31-2673-48ca-bc4e-76afc88bee19]
[6ba44f31-2673-48ca-bc4e-76afc88bee19] ActionView::Template::Error (unknown attribute 'favourites_count' for Status.):
[6ba44f31-2673-48ca-bc4e-76afc88bee19]     4:       = image_tag action_log.account.avatar.url(:original), alt: '', width: 40, height: 40, class: 'avatar'
[6ba44f31-2673-48ca-bc4e-76afc88bee19]     5:     .log-entry__content
[6ba44f31-2673-48ca-bc4e-76afc88bee19]     6:       .log-entry__title
[6ba44f31-2673-48ca-bc4e-76afc88bee19]     7:         = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}", name: content_tag(:span, action_log.account.username, class: 'username'), target: content_tag(:span, log_target(action_log), class: 'target')).html_safe
[6ba44f31-2673-48ca-bc4e-76afc88bee19]     8:       .log-entry__timestamp
[6ba44f31-2673-48ca-bc4e-76afc88bee19]     9:         %time= l action_log.created_at
[6ba44f31-2673-48ca-bc4e-76afc88bee19]    10:     .spacer
[6ba44f31-2673-48ca-bc4e-76afc88bee19]
[6ba44f31-2673-48ca-bc4e-76afc88bee19] app/helpers/admin/action_logs_helper.rb:36:in `log_target_from_history'
[6ba44f31-2673-48ca-bc4e-76afc88bee19] app/helpers/admin/action_logs_helper.rb:8:in `log_target'
[6ba44f31-2673-48ca-bc4e-76afc88bee19] app/views/admin/action_logs/_action_log.html.haml:7:in `_app_views_admin_action_logs__action_log_html_haml___2189604459245688864_70316038311820'
[6ba44f31-2673-48ca-bc4e-76afc88bee19] app/views/admin/action_logs/index.html.haml:4:in `_app_views_admin_action_logs_index_html_haml___1569413268933995913_70316068040820'

```
Cheers

Any insight would be greatly appreciated.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jebuskrust** [comment]
@Gargron broke it.

**Comment by jebuskrust** [comment]
Ah neato, looks like schema.rb had favourites_count, and reblogs_count removed.. 
However, I don't see any migrations that actually removes the actual columns from the statuses table.

https://github.com/tootsuite/mastodon/commit/8e111b753a3411b258cdb008c9a53bad696f4df1#diff-1acd2e7e27a227829d5d14a91c863bb6

**Comment by ThibG** [comment]
@jebuskrust `db/post_migrate/20180813113448_copy_status_stats_cleanup.rb`

**Comment by jebuskrust** [comment]
I didn't see that, thanks. When I get back, I'll check and see if that migration was ran.
