### ISSUE TITLE
[Sidekiq - Current Master Branch] ArgumentError: comparison of ActiveSupport::TimeWithZone with nil failed

### ISSUE THREAD

**Issue by jebuskrust** [tootsuite/mastodon#8376]
Here's the "last outstanding issue" that i've been experiencing with the current master (up to date as of commit 56f882aed6fc81bbe4fb8821f11ba196795c99a8), which appears be sidekiq related. It happens rather frequently  

Hope you find this log error helpful. Good luck on the RC ;)

```
2018-08-22T19:36:47.650Z 7859 TID-gpg8p29hf ActivityPub::ProcessingWorker JID-727130666c359a14c36a4258 INFO: start
2018-08-22T19:36:48.837Z 7859 TID-gpg8p29hf ActivityPub::ProcessingWorker JID-727130666c359a14c36a4258 INFO: fail: 1.187 sec
2018-08-22T19:36:48.838Z 7859 TID-gpg8p29hf WARN: {"context":"Job raised exception","job":{"class":"ActivityPub::ProcessingWorker","args":[297,"{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"actor\":\"https://social.sakamoto.gq/users/eal\",\"cc\":[],\"context\":\"https://social.sakamoto.gq/contexts/a67fd08c-c506-4d56-ba89-f0d13517a11d\",\"context_id\":8936210,\"id\":\"https://social.sakamoto.gq/activities/bb197cee-7833-4b11-a346-bec6573f2808\",\"object\":{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"Emoji\":\"toot:Emoji\",\"Hashtag\":\"as:Hashtag\",\"atomUri\":\"ostatus:atomUri\",\"conversation\":\"ostatus:conversation\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"ostatus\":\"http://ostatus.org#\",\"sensitive\":\"as:sensitive\",\"toot\":\"http://joinmastodon.org/ns#\"}],\"context\":\"https://social.sakamoto.gq/contexts/a67fd08c-c506-4d56-ba89-f0d13517a11d\",\"context_id\":8936210,\"endpoints\":{\"sharedInbox\":\"https://social.sakamoto.gq/inbox\"},\"followers\":\"https://social.sakamoto.gq/users/eal/followers\",\"following\":\"https://social.sakamoto.gq/users/eal/following\",\"icon\":{\"type\":\"Image\",\"url\":\"https://social.sakamoto.gq/media/8bb12bf1-18de-4188-b56d-7864b362f6d4/94FD7BC06D73597D0CB3BCD74F053960E0BBDD4DDC5EF352917A79423C658739.png\"},\"id\":\"https://social.sakamoto.gq/users/eal\",\"image\":{\"type\":\"Image\",\"url\":\"https://social.sakamoto.gq/media/5addfb27-f481-434c-b5d5-57adf4a6f6b3/101331DF2220814A1DF49D41EF06EB1930C184F3276059DEE9BC8B513F5175D9.jpeg\"},\"inbox\":\"https://social.sakamoto.gq/users/eal/inbox\",\"manuallyApprovesFollowers\":false,\"name\":\"ふもふも\",\"outbox\":\"https://social.sakamoto.gq/users/eal/outbox\",\"preferredUsername\":\"eal\",\"publicKey\":{\"id\":\"https://social.sakamoto.gq/users/eal#main-key\",\"owner\":\"https://social.sakamoto.gq/users/eal\",\"publicKeyPem\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAz3pF85YOhhv2Zaxv9YQ7\\nrCe1aEhetCMVHtrK63tUVGoGdsblyKnVeJNbFcr6k3y35OpHS3HXIi6GzgihYcTu\\nONLP4eQMHTnLUNAQZi03mjJA4iIq8v/tm8ZkL2mXsQSAbWj6Iq518mHNN7OvCoNt\\n3Xjepl/0kgkc2gsund7m8r+Wu0Fusx6UlUyyAk3PexdDRdSSlVLeskqtP8jtdQDo\\nL70pMyL+VD+Qb9RKFdtgJ+M4OqYP+7FVzCqXN0QIPhFf/kvHSLr+c4Y3Wm0nAKHU\\n9CwXWXz5Xqscpv41KlgnUCOkTXb5eBSt23lNulae5srVzWBiFb6guiCpNzBGa+Sq\\nrwIDAQAB\\n-----END PUBLIC KEY-----\\n\\n\"},\"published\":\"2018-08-21T19:20:26.195716Z\",\"summary\":\"thundere | :moominmamma: | :gentoo: | :marko: | :cupofcoffee: | ISO 8601 advocate and International Organization for Standardization shill | sort-of pleroma maintainer I guess | XMPP eal@xmpp.sakamoto.gq | Matrix @eal:matrix.heldscal.la\",\"tag\":[{\"icon\":{\"type\":\"Image\",\"url\":\"https://social.sakamoto.gq/finmoji/128px/cupofcoffee-128.png\"},\"name\":\":cupofcoffee:\",\"type\":\"Emoji\"},{\"icon\":{\"type\":\"Image\",\"url\":\"https://social.sakamoto.gq/finmoji/128px/moominmamma-128.png\"},\"name\":\":moominmamma:\",\"type\":\"Emoji\"},{\"icon\":{\"type\":\"Image\",\"url\":\"https://social.sakamoto.gq/emoji/marko.png\"},\"name\":\":marko:\",\"type\":\"Emoji\"},{\"icon\":{\"type\":\"Image\",\"url\":\"https://social.sakamoto.gq/emoji/gentoo.png\"},\"name\":\":gentoo:\",\"type\":\"Emoji\"}],\"type\":\"Person\",\"url\":\"https://social.sakamoto.gq/users/eal\"},\"published\":\"2018-08-21T19:20:26.195666Z\",\"to\":[\"https://social.sakamoto.gq/users/eal/followers\"],\"type\":\"Update\"}"],"retry":true,"queue":"default","backtrace":true,"jid":"727130666c359a14c36a4258","created_at":1534879228.1195152,"enqueued_at":1534966607.6488934,"error_message":"comparison of ActiveSupport::TimeWithZone with nil failed","error_class":"ArgumentError","failed_at":1534879238.0334203,"retry_count":12,"error_backtrace":["/home/mastodon/live/app/services/activitypub/process_account_service.rb:229:in `>='","/home/mastodon/live/app/services/activitypub/process_account_service.rb:229:in `process_emoji'","/home/mastodon/live/app/services/activitypub/process_account_service
.rb:215:in `block in process_tags'","/home/mastodon/live/app/services/activitypub/process_account_service.rb:214:in `each'","/home/mastodon/live/app/services/activitypub/process_account_service.rb:214:in `process_tags'","/home/mastodon/live/app/services/activitypub/process_account_service.rb:25:in `block in call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'","/home/mastodon/live/app/services/activitypub/process_account_service.rb:17:in `call'","/home/mastodon/live/app/lib/activitypub/activity/update.rb:14:in `update_account'","/home/mastodon/live/app/lib/activitypub/activity/update.rb:7:in `perform'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:43:in `process_item'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `block in process_items'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `reverse_each'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `each'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `map'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `process_items'","/home/mastodon/live/app/services/activitypub/process_collection_service.rb:21:in `call'","/home/mastodon/live/app/workers/activitypub/processing_worker.rb:9:in `perform'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'","/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-unique-job
s-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:i
n `block (2 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'"],"retried_at":1534941542.8779957},"jobstr":"{\"class\":\"ActivityPub::ProcessingWorker\",\"args\":[297,\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"actor\\\":\\\"https://social.sakamoto.gq/users/eal\\\",\\\"cc\\\":[],\\\"context\\\":\\\"https://social.sakamoto.gq/contexts/a67fd08c-c506-4d56-ba89-f0d13517a11d\\\",\\\"context_id\\\":8936210,\\\"id\\\":\\\"https://social.sakamoto.gq/activities/bb197cee-7833-4b11-a346-bec6573f2808\\\",\\\"object\\\":{\\\"@context\\\":[\\\"https://www.w3.org/ns/activitystreams\\\",\\\"https://w3id.org/security/v1\\\",{\\\"Emoji\\\":\\\"toot:Emoji\\\",\\\"Hashtag\\\":\\\"as:Hashtag\\\",\\\"atomUri\\\":\\\"ostatus:atomUri\\\",\\\"conversation\\\":\\\"ostatus:conversation\\\",\\\"inReplyToAtomUri\\\":\\\"ostatus:inReplyToAtomUri\\\",\\\"manuallyApprovesFollowers\\\":\\\"as:manuallyApprovesFollowers\\\",\\\"ostatus\\\":\\\"http://ostatus.org#\\\",\\\
"sensitive\\\":\\\"as:sensitive\\\",\\\"toot\\\":\\\"http://joinmastodon.org/ns#\\\"}],\\\"context\\\":\\\"https://social.sakamoto.gq/contexts/a67fd08c-c506-4d56-ba89-f0d13517a11d\\\",\\\"context_id\\\":8936210,\\\"endpoints\\\":{\\\"sharedInbox\\\":\\\"https://social.sakamoto.gq/inbox\\\"},\\\"followers\\\":\\\"https://social.sakamoto.gq/users/eal/followers\\\",\\\"following\\\":\\\"https://social.sakamoto.gq/users/eal/following\\\",\\\"icon\\\":{\\\"type\\\":\\\"Image\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/media/8bb12bf1-18de-4188-b56d-7864b362f6d4/94FD7BC06D73597D0CB3BCD74F053960E0BBDD4DDC5EF352917A79423C658739.png\\\"},\\\"id\\\":\\\"https://social.sakamoto.gq/users/eal\\\",\\\"image\\\":{\\\"type\\\":\\\"Image\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/media/5addfb27-f481-434c-b5d5-57adf4a6f6b3/101331DF2220814A1DF49D41EF06EB1930C184F3276059DEE9BC8B513F5175D9.jpeg\\\"},\\\"inbox\\\":\\\"https://social.sakamoto.gq/users/eal/inbox\\\",\\\"manuallyApprovesFollowers\\\":false,\\\"name\\\":\\\"ふもふも\\\",\\\"outbox\\\":\\\"https://social.sakamoto.gq/users/eal/outbox\\\",\\\"preferredUsername\\\":\\\"eal\\\",\\\"publicKey\\\":{\\\"id\\\":\\\"https://social.sakamoto.gq/users/eal#main-key\\\",\\\"owner\\\":\\\"https://social.sakamoto.gq/users/eal\\\",\\\"publicKeyPem\\\":\\\"-----BEGIN PUBLIC KEY-----\\\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz3pF85YOhhv2Zaxv9YQ7\\\\nrCe1aEhetCMVHtrK63tUVGoGdsblyKnVeJNbFcr6k3y35OpHS3HXIi6GzgihYcTu\\\\nONLP4eQMHTnLUNAQZi03mjJA4iIq8v/tm8ZkL2mXsQSAbWj6Iq518mHNN7OvCoNt\\\\n3Xjepl/0kgkc2gsund7m8r+Wu0Fusx6UlUyyAk3PexdDRdSSlVLeskqtP8jtdQDo\\\\nL70pMyL+VD+Qb9RKFdtgJ+M4OqYP+7FVzCqXN0QIPhFf/kvHSLr+c4Y3Wm0nAKHU\\\\n9CwXWXz5Xqscpv41KlgnUCOkTXb5eBSt23lNulae5srVzWBiFb6guiCpNzBGa+Sq\\\\nrwIDAQAB\\\\n-----END PUBLIC KEY-----\\\\n\\\\n\\\"},\\\"published\\\":\\\"2018-08-21T19:20:26.195716Z\\\",\\\"summary\\\":\\\"thundere | :moominmamma: | :gentoo: | :marko: | :cupofcoffee: | ISO 8601 advocate and International Organization for Standardization shill | sort-of pleroma maintaine
r I guess | XMPP eal@xmpp.sakamoto.gq | Matrix @eal:matrix.heldscal.la\\\",\\\"tag\\\":[{\\\"icon\\\":{\\\"type\\\":\\\"Image\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/finmoji/128px/cupofcoffee-128.png\\\"},\\\"name\\\":\\\":cupofcoffee:\\\",\\\"type\\\":\\\"Emoji\\\"},{\\\"icon\\\":{\\\"type\\\":\\\"Image\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/finmoji/128px/moominmamma-128.png\\\"},\\\"name\\\":\\\":moominmamma:\\\",\\\"type\\\":\\\"Emoji\\\"},{\\\"icon\\\":{\\\"type\\\":\\\"Image\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/emoji/marko.png\\\"},\\\"name\\\":\\\":marko:\\\",\\\"type\\\":\\\"Emoji\\\"},{\\\"icon\\\":{\\\"type\\\":\\\"Image\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/emoji/gentoo.png\\\"},\\\"name\\\":\\\":gentoo:\\\",\\\"type\\\":\\\"Emoji\\\"}],\\\"type\\\":\\\"Person\\\",\\\"url\\\":\\\"https://social.sakamoto.gq/users/eal\\\"},\\\"published\\\":\\\"2018-08-21T19:20:26.195666Z\\\",\\\"to\\\":[\\\"https://social.sakamoto.gq/users/eal/followers\\\"],\\\"type\\\":\\\"Update\\\"}\"],\"retry\":true,\"queue\":\"default\",\"backtrace\":true,\"jid\":\"727130666c359a14c36a4258\",\"created_at\":1534879228.1195152,\"enqueued_at\":1534966607.6488934,\"error_message\":\"comparison of ActiveSupport::TimeWithZone with nil failed\",\"error_class\":\"ArgumentError\",\"failed_at\":1534879238.0334203,\"retry_count\":12,\"error_backtrace\":[\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:229:in `>='\",\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:229:in `process_emoji'\",\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:215:in `block in process_tags'\",\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:214:in `each'\",\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:214:in `process_tags'\",\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:25:in `block in call'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/mario-redis-lock-1.2.1/lib/redis_loc
k.rb:44:in `acquire'\",\"/home/mastodon/live/app/services/activitypub/process_account_service.rb:17:in `call'\",\"/home/mastodon/live/app/lib/activitypub/activity/update.rb:14:in `update_account'\",\"/home/mastodon/live/app/lib/activitypub/activity/update.rb:7:in `perform'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:43:in `process_item'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `block in process_items'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `reverse_each'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `each'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `map'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `process_items'\",\"/home/mastodon/live/app/services/activitypub/process_collection_service.rb:21:in `call'\",\"/home/mastodon/live/app/workers/activitypub/processing_worker.rb:9:in `perform'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\",\"/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq
-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/si
dekiq/logging.rb:48:in `with_context'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'\",\"/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'\"],\"retried_at\":1534941542.8779957}"}
2018-08-22T19:36:48.841Z 7859 TID-gpg8p29hf WARN: ArgumentError: comparison of ActiveSupport::TimeWithZone with nil failed
2018-08-22T19:36:48.841Z 7859 TID-gpg8p29hf WARN: /home/mastodon/live/app/services/activitypub/process_account_service.rb:229:in `>='
/home/mastodon/live/app/services/activitypub/process_account_service.rb:229:in `process_emoji'
/home/mastodon/live/app/services/activitypub/process_account_service.rb:215:in `block in process_tags'
/home/mastodon/live/app/services/activitypub/process_account_service.rb:214:in `each'
/home/mastodon/live/app/services/activitypub/process_account_service.rb:214:in `process_tags'
/home/mastodon/live/app/services/activitypub/process_account_service.rb:25:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'
/home/mastodon/live/app/services/activitypub/process_account_service.rb:17:in `call'
/home/mastodon/live/app/lib/activitypub/activity/update.rb:14:in `update_account'
/home/mastodon/live/app/lib/activitypub/activity/update.rb:7:in `perform'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:43:in `process_item'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `block in process_items'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `reverse_each'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `each'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `map'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `process_items'
/home/mastodon/live/app/services/activitypub/process_collection_service.rb:21:in `call'
/home/mastodon/live/app/workers/activitypub/processing_worker.rb:9:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
The remote message has a custom emoji with no `updated` attribute. I'm not sure what we should do with that. I suggest only updating if the URL changed.
