### ISSUE TITLE
Docker database setup failed with 2.5.0rc1

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#8488]
While setuping a new instance with the latest release-candidate I encountered the following database setup failure:
```
$ docker-compose run --rm web bundle exec rake mastodon:setup
[...]
Prepare the database now? Yes
Running `RAILS_ENV=production rails db:setup` ...


rails aborted!
ArgumentError: `secret_key_base` for production environment must be a type of String`
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:583:in `validate_secret_key_base'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:432:in `secret_key_base'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:176:in `key_generator'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:205:in `message_verifier'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.1/lib/active_storage/engine.rb:67:in `block (2 levels) in <class:Engine>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
/mastodon/config/environment.rb:5:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:337:in `require_environment!'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)
That failed! Perhaps your configuration is not right
```
Is it something on Mastodon's side or something I forgot to do?

**Comment by kit-ty-kate** [comment]
mmh no wrong fix, sorry. It worked when I copy-paste the new `.env.production` content by hand (instead of doing it later as implied in `It is also saved within this container so you can proceed with this wizard.`)

**Comment by kit-ty-kate** [comment]
My previous note on the empty postgres password is still valid though.

**Comment by cccaballero** [comment]
Hi, I am getting the exact same issue here.
@kit-ty-kate How did you copy the .env.production for make it work?

**Comment by cccaballero** [comment]
Solved copying the config result in prompt to the .env.production file and re running the setup

**Comment by kit-ty-kate** [comment]
Why has this been closed without any comment? I don't see any fix commits in the logs

**Comment by Gargron** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

- https://discourse.joinmastodon.org
- #mastodon on irc.freenode.net
