### ISSUE TITLE
Large number of Sidekiq failures and retries 

### ISSUE THREAD

**Issue by Syfaro** [tootsuite/mastodon#865]
Since updating my instance yesterday, I have gone from ~40 failures a day to over 1,400 so far today. 

There is a continuously growing number of retries, all from the same Job `ProcessingWorker`, in queues `default` and `pull`, all failing with the same error, `ActiveRecord::RecordInvalid: Validation failed: Username has already been taken`.

Error Backtrace: 
```
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/validations.rb:78:in `raise_validation_error'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/validations.rb:50:in `save!'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:324:in `block in save!'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:324:in `save!'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/suppressor.rb:45:in `save!'
/mastodon/app/models/account.rb:150:in `rescue in save_with_optional_avatar!'
/mastodon/app/models/account.rb:144:in `save_with_optional_avatar!'
/mastodon/app/services/update_remote_profile_service.rb:24:in `call'
/mastodon/app/services/process_feed_service.rb:16:in `update_author'
/mastodon/app/services/process_feed_service.rb:8:in `call'
/mastodon/app/workers/processing_worker.rb:9:in `perform'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:86:in `block in call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:85:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in '
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
/mastodon/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

The arguments for the jobs look something like: 
```
1142, "<?xml version=\"1.0\"?>\n<feed xmlns=\"http://www.w3.org/2005/Atom\" xmlns:thr=\"http://purl.org/syndication/thread/1.0\" xmlns:activity=\"http://activitystrea.ms/spec/1.0/\" xmlns:poco=\"http://portablecontacts.net/spec/1.0\" xmlns:media=\"http://purl.org/syndication/atommedia\" xmlns:ostatus=\"http://ostatus.org/schema/1.0\" xmlns:mastodon=\"http://mastodon.social/schema/1.0\">\n <id>https://mastodon.social/users/b_cavello.atom</id>\n <title>it's B! Cavello</title>\n <subtitle>activist, aspiring-polymath, problematic feminist working to better this world&#xD;\n&#xD;\nhttp://pronoun.is/they</subtitle>\n <updated>2017-04-04T16:21:47Z</updated>\n <logo>https://files.mastodon.social/accounts/avatars/000/006/827/original/media.png?1486510293</logo>\n <author>\n <id>https://mastodon.social/users/b_cavello</id>\n <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>\n <uri>https://mastodon.social/users/b_cavello</uri>\n <name>b_cavello</name>\n <email>b_cavello@mastodon.social</email>\n <summary>activist, aspiring-polymath, problematic feminist working to better this world&#xD;\n&#xD;\nhttp://pronoun.is/they</summary>\n <link rel=\"alternate\" type=\"text/html\" href=\"https://mastodon.social/@b_cavello\"/>\n <link rel=\"avatar\" type=\"image/png\" media:width=\"120\" media:height=\"120\" href=\"https://files.mastodon.social/accounts/avatars/000/006/827/original/media.png?1486510293\"/>\n <link rel=\"header\" type=\"\" media:width=\"700\" media:height=\"335\" href=\"/headers/original/missing.png\"/>\n <poco:preferredUsername>b_cavello</poco:preferredUsername>\n <poco:displayName>it's B! Cavello</poco:displayName>\n <poco:note>activist, aspiring-polymath, problematic feminist working to better this world&#xD;\n&#xD;\n&lt;a href=\"http://pronoun.is/they\" rel=\"nofollow noopener\" target=\"_blank\"&gt;&lt;span class=\"invisible\"&gt;http://&lt;/span&gt;&lt;span class=\"\"&gt;pronoun.is/they&lt;/span&gt;&lt;span class=\"invisible\"&gt;&lt;/span&gt;&lt;/a&gt;</poco:note>\n <mastodon:scope>public</mastodon:scope>\n </author>\n <link rel=\"alternate\" type=\"text/html\" href=\"https://mastodon.social/@b_cavello\"/>\n <link rel=\"self\" type=\"application/atom+xml\" href=\"https://mastodon.social/users/b_cavello.atom\"/>\n <link rel=\"hub\" href=\"https://mastodon.social/api/push\"/>\n <link rel=\"salmon\" href=\"https://mastodon.social/api/salmon/6827\"/>\n <entry>\n <id>tag:mastodon.social,2017-04-04:objectId=1587779:objectType=Status</id>\n <published>2017-04-04T16:21:47Z</published>\n <updated>2017-04-04T16:21:47Z</updated>\n <title>@it4sec Could you include a link?\nThanks so much!!</title>\n <content type=\"html\">&lt;p&gt;&lt;a href=\"https://mastodon.social/@it4sec\" class=\"h-card u-url p-nickname mention\"&gt;@&lt;span&gt;it4sec&lt;/span&gt;&lt;/a&gt; Could you include a link?&lt;br /&gt;Thanks so much!!&lt;/p&gt;</content>\n <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>\n <link rel=\"self\" type=\"application/atom+xml\" href=\"https://mastodon.social/users/b_cavello/updates/1593538.atom\"/>\n <link rel=\"alternate\" type=\"text/html\" href=\"https://mastodon.social/users/b_cavello/updates/1593538\"/>\n <activity:object-type>http://activitystrea.ms/schema/1.0/comment</activity:object-type>\n <thr:in-reply-to ref=\"tag:mastodon.social,2017-04-04:objectId=1578994:objectType=Status\" href=\"https://mastodon.social/@it4sec/1578994\" type=\"text/html\"/>\n <link rel=\"mentioned\" href=\"https://mastodon.social/users/it4sec\" ostatus:object-type=\"http://activitystrea.ms/schema/1.0/person\"/>\n <mastodon:scope>unlisted</mastodon:scope>\n </entry>\n</feed>\n"
```

I am on the latest revision at the time of writing this, 5f54981846508daf9558f66ffd70d42d8213bea9.

![image](https://cloud.githubusercontent.com/assets/1369709/24669443/1a4cd046-1930-11e7-80e7-ae2d5a9ba9e8.png)

**Comment by swaldie** [comment]
May be related to the influx of new users?

**Comment by krainboltgreene** [comment]
This worker should probably gracefully fail if this happens.

**Comment by Gargron** [comment]
update_author should not be creating a new record so the username violation error is bizarre. the methods in this stacktrace do not even modify usernames in any way.

**Comment by krainboltgreene** [comment]
I can grab this if you want @Gargron , after work. On my lunch break right now.

**Comment by Syfaro** [comment]
So I started looking through my database and found something very confusing. 

The username is not equal to any duplicates with the ID attached to the majority of the errors. 
![img_0013](https://cloud.githubusercontent.com/assets/1369709/24738292/58935bf6-1a5a-11e7-89b2-c9b438af35c6.jpg)

However, it is `like` the duplicate ID's username, and in fact, there are multiple duplicates for this username. 
![img_0014](https://cloud.githubusercontent.com/assets/1369709/24738328/9d7446f4-1a5a-11e7-952a-bf3687170926.jpg)

I expected that there was some kind of unicode or encoding issue that made them look identical with extra or different bytes, but that did not seem to be the case. The base64 representation of all the usernames are identical. 
![img_0015](https://cloud.githubusercontent.com/assets/1369709/24738347/b75c38ba-1a5a-11e7-9662-f77bbb2b5e68.jpg)

**Comment by Syfaro** [comment]
Well, it turns out my database is more than a little messed up. I'm not sure if there's some bug in Mastodon causing this, but it's likely it's an issue elsewhere. 

https://gist.github.com/Syfaro/e64d3a4db56eef354eb4a05f2fc23166

**Comment by Syfaro** [comment]
I'm closing this as it appears to have been an issue with my server, not anything to do with Mastodon. 

In case anyone else runs into a similar issue, you can run the following queries in psql:
```sql
DELETE FROM accounts WHERE id NOT IN (SELECT MIN(id) FROM accounts GROUP BY username, domain);
REINDEX TABLE accounts;
```
