### ISSUE TITLE
Missing mastodon Rake tasks

### ISSUE THREAD

**Issue by syumari** [tootsuite/mastodon#8705]
I noticed that mastodon Rake tasks that can run on that instance are missing.
instances are running version 2.5.0

```
mastodon@foobar:~/live$ RAILS_ENV=production bundle exec rails mastodon:media:redownload_avatars
rails aborted!
Don't know how to build task 'mastodon:media:redownload_avatars' (see --tasks)
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
mastodon@foobar:~/live$ RAILS_ENV=production bundle exec rails -T mastodon
rails mastodon:push:clear                    # Unsubscribes from PuSH updates of feeds nobody follows locally
rails mastodon:settings:close_registrations  # Close registrations on this instance
rails mastodon:settings:open_registrations   # Open registrations on this instance
rails mastodon:setup                         # Configure the instance for production use
rails mastodon:stats                         # Report code statistics (KLOCs, etc)
rails mastodon:webpush:generate_vapid_key    # Generate VAPID key
mastodon@foobar:~/live$
```
Please tell me if there is a way to fix this problem.

**Comment by ykzts** [comment]
https://github.com/tootsuite/mastodon/pull/8675

**Comment by Gargron** [comment]
I think you are on master, not 2.5.0...

**Comment by syumari** [comment]
Thanks for the reply.
I was updating with "git pull", so I attempted an update with "git checkout v2.5.0".
As a result, the problem has been resolved.
The update procedure should have been done properly.
