### ISSUE TITLE
/api/v1/timelines/direct might sometimes returns invalid JSON

### ISSUE THREAD

**Issue by wouwouwou** [tootsuite/mastodon#8928]
With two other undergraduate students, I am building a text-based MUD bot for the Mastodon of the University of Twente with Spring Boot. Currently, we are polling the direct timeline every two seconds (we will look into the notification system as soon as possible because of the server-load). At random moments we sometimes get the following exception:

```
Exception in thread "Timer-0" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:939)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at nl.utwente.mastodon.mudtwente.TimeLineHandler.handleDirectTimeline(TimeLineHandler.java:60)
	at nl.utwente.mastodon.mudtwente.MUDTwenteCommandLineRunner$1.run(MUDTwenteCommandLineRunner.java:104)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 7 more
```
Now, I am not sure if this is the Gson library which is failing or the api, but I just wanted to give you a headsup and let you know that we encounter this problem.

We also use the mastodon4j library of sys1yagi (https://github.com/sys1yagi/mastodon4j)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>Expected BEGIN_ARRAY but was BEGIN_OBJECT

Are you checking HTTP status codes to detect errors? What if there is a server error or authentication error? In that case, the JSON body might be `{ error: 'Some error message' }` which would fit your observations.

**Comment by wouwouwou** [comment]
Good point! We did not check HTTP status codes yet. I've put an `okhttp3.Response.isSuccessful()` check around it for our next release coming Friday. If the notification system is not implemented before Friday, this may actually confirm the problem and solve it.

I also now use Spring Boot's Schedule annotation. This may prevent the task or thread from being interrupted, which was probably happening with the Timer and TimerTask.

**Comment by nightpool** [comment]
Pretty hard to say more about this without knowing what the actual response returned from the server was
