### ISSUE TITLE
Mastodon error by following remote user

### ISSUE THREAD

**Issue by closebang** [tootsuite/mastodon#9001]
Hi together,
I currently setup the latest version via Docker

I just run it via docker over ssh and when I try to follow someone, *docker logs -t mastodon_web_1* send me following:

All I found via google according to this was [this](https://github.com/tootsuite/mastodon/issues/6911) 

```
2018-10-17T21:10:47.416366110Z [4c9c622c-177f-400b-830e-929f3b117e7f] method=GET path=/authorize_interaction format=html controller=AuthorizeInteractionsController action=show status=500 error='Errno::EACCES: Permission denied @ dir_s_mkdir - /var/lib/mastodon' duration=216.01 view=0.00 db=8.31
2018-10-17T21:10:47.417354413Z [4c9c622c-177f-400b-830e-929f3b117e7f]
2018-10-17T21:10:47.417398883Z [4c9c622c-177f-400b-830e-929f3b117e7f] Errno::EACCES (Permission denied @ dir_s_mkdir - /var/lib/mastodon):
2018-10-17T21:10:47.417449876Z [4c9c622c-177f-400b-830e-929f3b117e7f]
2018-10-17T21:10:47.417484417Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/models/account.rb:280:in `save_with_optional_media!'
2018-10-17T21:10:47.417488946Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/services/activitypub/process_account_service.rb:63:in `update_account'
2018-10-17T21:10:47.417492339Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/services/activitypub/process_account_service.rb:25:in `block in call'
2018-10-17T21:10:47.417495463Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/services/activitypub/process_account_service.rb:18:in `call'
2018-10-17T21:10:47.417498529Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/services/resolve_account_service.rb:102:in `handle_activitypub'
2018-10-17T21:10:47.417501522Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/services/resolve_account_service.rb:48:in `block in call'
2018-10-17T21:10:47.417509218Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/services/resolve_account_service.rb:43:in `call'
2018-10-17T21:10:47.417512517Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/controllers/authorize_interactions_controller.rb:48:in `account_from_remote_follow'
2018-10-17T21:10:47.417518995Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/controllers/authorize_interactions_controller.rb:43:in `located_resource'
2018-10-17T21:10:47.417522490Z [4c9c622c-177f-400b-830e-929f3b117e7f] app/controllers/authorize_interactions_controller.rb:35:in `set_resource'
2018-10-17T21:10:47.419643194Z [ef57057e-debc-41a7-a5f9-3b3272ab4554] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=401 duration=13.75 view=0.44 db=6.79
2018-10-17T21:10:47.471970813Z [34db4f81-9811-438a-b05c-6ecc852c9e0d] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=401 duration=12.50 view=0.59 db=2.75
```

**Comment by closebang** [comment]
It was the PAPERCLIP_ROOT_PATH, I reset it to default
