### ISSUE TITLE
Incoming Toots with "-" in tag-name are stuck

### ISSUE THREAD

**Issue by sammy8806** [tootsuite/mastodon#9115]
### Expected behaviour

A toot with tags that not passes the validation should still be delivered

### Actual behaviour

It seems as if a single misbehaving tag could get the whole toot to be not processed because the name of the tag doesn't get past the validation.

### Steps to reproduce the problem

An example for this could be https://squeet.me/display/962c3e1064dc778a38ff592c45f0c46bc7da9087 where Friendica allows a `-` in the tag

### Specifications

Seemingly since 790d3bc6370f1baf0d00ccf89e81387204c65194 in https://github.com/tootsuite/mastodon/blob/master/app/lib/activitypub/activity/create.rb#L104

**Comment by sammy8806** [comment]
Following a complete stack-trace
```
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: 2018-10-26T07:58:34.243Z 21088 TID-otktbetbg WARN: ActiveRecord::RecordInvalid: Validation failed: Name is invalid
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: 2018-10-26T07:58:34.243Z 21088 TID-otktbetbg WARN: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:80:in `raise_validation_error'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:52:in `save!'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `block in save!'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:252:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `save!'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/suppressor.rb:48:in `save!'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:375:in `insert_record'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:42:in `insert_record'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:438:in `block (2 levels) in concat_records'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:458:in `replace_on_target'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:282:in `add_to_target'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:436:in `block in concat_records'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:434:in `each'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:434:in `concat_records'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_association.rb:116:in `concat_records'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:27:in `concat_records'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:119:in `block in concat'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:134:in `block in transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:252:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:133:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:119:in `concat'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:21:in `concat'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_proxy.rb:1056:in `<<'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:104:in `block in attach_tags'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:103:in `each'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:103:in `attach_tags'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:35:in `block in process_status'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:33:in `process_status'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:13:in `block in perform'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/activitypub/activity/create.rb:10:in `perform'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:43:in `process_item'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `block in process_items'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `reverse_each'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `each'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `map'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:34:in `process_items'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/services/activitypub/process_collection_service.rb:21:in `call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/workers/activitypub/processing_worker.rb:9:in `perform'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:185:in `execute_job'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ddtrace-0.13.0/lib/ddtrace/contrib/sidekiq/tracer.rb:37:in `block in call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ddtrace-0.13.0/lib/ddtrace/tracer.rb:287:in `trace'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ddtrace-0.13.0/lib/ddtrace/contrib/sidekiq/tracer.rb:29:in `call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:166:in `block in process'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/job_retry.rb:98:in `local'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/rails.rb:42:in `block in call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/rails.rb:41:in `call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:243:in `stats'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/job_logger.rb:8:in `call'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/job_retry.rb:73:in `global'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:125:in `block in dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/logging.rb:48:in `with_context'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:124:in `dispatch'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:165:in `process'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:83:in `process_one'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:71:in `run'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/util.rb:16:in `watchdog'
Oct 26 07:58:34 vps9.dark-it.net bundle[21088]: /srv/mastodon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
```
