### ISSUE TITLE
Can't make myself admin

### ISSUE THREAD

**Issue by misaka00251** [tootsuite/mastodon#9433]
### Expected behaviour

Make myself admin account.

### Actual behaviour

```
Starting mastodon_db_1    ... done
Starting mastodon_redis_1 ... done
rails aborted!
Don't know how to build task 'mastodon:make_admin' (see --tasks)
Did you mean?  mastodon:stats
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1.1/lib/rails/command.rb:48:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1.1/lib/rails/commands.rb:18:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `require'
/mastodon/bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

### Steps to reproduce the problem

run `docker-compose run --rm web rails mastodon:make_admin USERNAME=<username_here>`

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/administration/post-installation/#using-the-command-line-interface

**Comment by misaka00251** [comment]
Nah, sadly this does not work... I'll try reinstall it again.

**Comment by Gargron** [comment]
`docker-compose run --rm web bin/tootctl accounts modify alice --role admin`

**Comment by blade10101** [comment]
> docker-compose run --rm web bin/tootctl accounts modify alice --role admin

Sorry that dosen't work...

Cannot find user role with that name
ERROR: 1
