### ISSUE TITLE
tootctl not working (traceback)

### ISSUE THREAD

**Issue by Perflyst** [tootsuite/mastodon#9876]
Maybe this is releated to #8593?
### Expected behaviour
tootctl should show the version

### Actual behaviour
I get a Traceback

### Steps to reproduce the problem
Execute `./tootctl --version` or any other command on v2.7.0 in live/bin/

### Specifications
Mastodon: v2.7.0
Ruby: 2.6.0

### Log / Traceback
```
$ ./tootctl --version
Traceback (most recent call last):
        53: from ./tootctl:4:in `<main>'
        52: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        51: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        50: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        49: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        48: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        47: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        46: from /home/mastodon/live/lib/cli.rb:4:in `<top (required)>'
        45: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        44: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        43: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        42: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        41: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        40: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        39: from /home/mastodon/live/lib/mastodon/media_cli.rb:4:in `<top (required)>'
        38: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        37: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        36: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        35: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        34: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        33: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        32: from /home/mastodon/live/config/environment.rb:5:in `<top (required)>'
        31: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
        30: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
        29: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        28: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        27: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        26: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
        25: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
        24: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        23: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        22: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `call'
        21: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
        20: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
        19: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        18: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        17: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        16: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        15: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        14: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        13: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
        12: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
        11: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:601:in `block in <class:Engine>'
        10: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:601:in `each'
         9: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:602:in `block (2 levels) in <class:Engine>'
         8: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         7: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         6: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         5: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
         4: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         3: from /home/mastodon/live/config/environments/development.rb:90:in `<top (required)>'
         2: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
         1: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant': uninitialized constant ActiveRecordQueryTrace (NameError)
        54: from ./tootctl:4:in `<main>'
        53: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        52: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        51: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        50: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        49: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        48: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        47: from /home/mastodon/live/lib/cli.rb:4:in `<top (required)>'
        46: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        45: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        44: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        43: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        42: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        41: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        40: from /home/mastodon/live/lib/mastodon/media_cli.rb:4:in `<top (required)>'
        39: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        38: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        37: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        36: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        35: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        34: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        33: from /home/mastodon/live/config/environment.rb:5:in `<top (required)>'
        32: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
        31: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
        30: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        29: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        28: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        27: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
        26: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
        25: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        24: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        23: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `call'
        22: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
        21: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
        20: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        19: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        18: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        17: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        16: from /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        15: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        14: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
        13: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
        12: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:601:in `block in <class:Engine>'
        11: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:601:in `each'
        10: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:602:in `block (2 levels) in <class:Engine>'
         9: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         8: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         7: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         6: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
         5: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         4: from /home/mastodon/live/config/environments/development.rb:90:in `<top (required)>'
         3: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:56:in `load_missing_constant'
         2: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `rescue in load_missing_constant'
         1: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `block in load_missing_constant': uninitialized constant ActiveRecordQueryTrace (NameError)
```

**Comment by Perflyst** [comment]
Executing `RAILS_ENV=production bin/tootcl` works. Can I somehow always have production? So that I can only execute tootctl without `RAILS_ENV=production`?

**Comment by Perflyst** [comment]
No way, found it `echo "export RAILS_ENV=production" >> ~/.bashrc`
