### ISSUE TITLE
SSO account creation fails with "Agreement must be accepted" 

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#9906]
Since upgrading, new users coming via SSO have not had new accounts created, and instead received a 422.

Looking in the logs, we see:

```
I, [2019-01-22T15:01:37.442903 #9]  INFO -- omniauth: (saml) Callback phase initiated.
[47653726-2c14-4441-83f6-11f8cf91073f] method=POST path=/auth/auth/saml/callback format=html controller=Auth::OmniauthCallbacksController action=saml status=422 error='ActiveRecord::RecordInvalid: Validation failed: Agreement must be accepted' duration=203.69 view=0.00 db=43.69
[47653726-2c14-4441-83f6-11f8cf91073f]   
[47653726-2c14-4441-83f6-11f8cf91073f] ActiveRecord::RecordInvalid (Validation failed: Agreement must be accepted):
[47653726-2c14-4441-83f6-11f8cf91073f]   
[47653726-2c14-4441-83f6-11f8cf91073f] app/models/concerns/omniauthable.rb:49:in `create_for_oauth'
[47653726-2c14-4441-83f6-11f8cf91073f] app/models/concerns/omniauthable.rb:30:in `find_for_oauth'
[47653726-2c14-4441-83f6-11f8cf91073f] app/controllers/auth/omniauth_callbacks_controller.rb:10:in `block in provides_callback_for'
```

**Comment by moritzheiber** [comment]
This is the breaking PR: #9572

**Comment by moritzheiber** [comment]
cc @Gargron as the original PR author, @nolanlawson @mayaeh as reviewers
