### ISSUE TITLE
Unknown primary key after upgrade

### ISSUE THREAD

**Issue by BastienDurel** [tootsuite/mastodon#9953]
Today I upgraded my system, I then had to re-compile some gems (I did re-compile all of them with `bundle install --force`), and to migrate postgresql data (to new postgresql server 11)

### Expected behaviour

Mastodon returns messages when asked for

### Actual behaviour

I got 500's errors when trying to get my posts (mastodon page starts, then I got "error 500" popups, but no message)

### Specifications

I run version 2.7.1

web process log shows the `UnknownPrimaryKey` message : 

```
[12826d70-6881-4380-840b-aeb25ec8cd08] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=500 error='ActiveRecord::UnknownPrimaryKey: Unknown primary key for table conversations in model Conversation.' duration=16.74 view=0.00 db=3.53
[12826d70-6881-4380-840b-aeb25ec8cd08]   
[12826d70-6881-4380-840b-aeb25ec8cd08] ActiveRecord::UnknownPrimaryKey (Unknown primary key for table conversations in model Conversation.):
[12826d70-6881-4380-840b-aeb25ec8cd08]   
[12826d70-6881-4380-840b-aeb25ec8cd08] app/controllers/application_controller.rb:116:in `each_with_object'
[12826d70-6881-4380-840b-aeb25ec8cd08] app/controllers/application_controller.rb:116:in `cache_collection'
[12826d70-6881-4380-840b-aeb25ec8cd08] app/controllers/api/v1/timelines/home_controller.rb:26:in `cached_home_statuses'
[12826d70-6881-4380-840b-aeb25ec8cd08] app/controllers/api/v1/timelines/home_controller.rb:22:in `load_statuses'
[12826d70-6881-4380-840b-aeb25ec8cd08] app/controllers/api/v1/timelines/home_controller.rb:11:in `show'
```

I've added the primary key definition in app/models/conversation.rb, and got the same problem for `Tag` then for `Mention`

With these patches, mastodon runs

```
diff --git a/app/models/conversation.rb b/app/models/conversation.rb
index 4dfaea889..97795f8bc 100644
--- a/app/models/conversation.rb
+++ b/app/models/conversation.rb
@@ -13,6 +13,7 @@ class Conversation < ApplicationRecord
   validates :uri, uniqueness: true, if: :uri?
 
   has_many :statuses
+  self.primary_key = "id"
 
   def local?
     uri.nil?
diff --git a/app/models/mention.rb b/app/models/mention.rb
index d01a88e32..f3b3448a5 100644
--- a/app/models/mention.rb
+++ b/app/models/mention.rb
@@ -29,6 +29,8 @@ class Mention < ApplicationRecord
     prefix: true
   )
 
+  self.primary_key = "id"
+
   def active?
     !silent?
   end
diff --git a/app/models/tag.rb b/app/models/tag.rb
index 99830ae92..ff61a8440 100644
--- a/app/models/tag.rb
+++ b/app/models/tag.rb
@@ -1,3 +1,4 @@
+# coding: utf-8
 # frozen_string_literal: true
 # == Schema Information
 #
@@ -33,6 +34,8 @@ class Tag < ApplicationRecord
 
   after_save :save_account_tag_stat
 
+  self.primary_key = "id"
+
   def account_tag_stat
     super || build_account_tag_stat
   end
```

**Comment by Gargron** [comment]
> I've added the primary key definition in app/models/conversation.rb, and got the same problem for Tag then for Mention

This should not be necessary and seems to point to a bigger problem. Are you sure that:

1. Your data still exists in the database
2. Mastodon connects to the right database

**Comment by BastienDurel** [comment]
My data is in the database, and mastodon connects to it, as it lets me connect and displays toots.

But there is probably other problem(s), as I did not get any toot since upgrade, 5 hours ago. (and people I follow on other instances have posted new toots)

**Comment by BastienDurel** [comment]
I've added `self.primary_key = "id"` in `app/models/media_attachment.rb` too

**Comment by Gargron** [comment]
Try https://stackoverflow.com/a/31921351 for every table in the database

**Comment by BastienDurel** [comment]
```
mastodon:~# echo '\dt'| psql -U mastodon mastodon_production|grep public|awk '{ print "ALTER TABLE " $3 " ADD PRIMARY KEY (id);"}'| psql -U mastodon mastodon_production
ERROR:  multiple primary keys for table "account_conversations" are not allowed
ERROR:  multiple primary keys for table "account_domain_blocks" are not allowed
ERROR:  multiple primary keys for table "account_moderation_notes" are not allowed
ERROR:  multiple primary keys for table "account_pins" are not allowed
ERROR:  multiple primary keys for table "account_stats" are not allowed
ERROR:  could not create unique index "account_tag_stats_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  multiple primary keys for table "account_warning_presets" are not allowed
ERROR:  multiple primary keys for table "account_warnings" are not allowed
ERROR:  multiple primary keys for table "accounts" are not allowed
ERROR:  column "id" named in key does not exist
ERROR:  multiple primary keys for table "admin_action_logs" are not allowed
ERROR:  column "id" named in key does not exist
ERROR:  multiple primary keys for table "backups" are not allowed
ERROR:  multiple primary keys for table "blocks" are not allowed
ERROR:  multiple primary keys for table "conversation_mutes" are not allowed
ALTER TABLE
ERROR:  multiple primary keys for table "custom_emojis" are not allowed
ERROR:  multiple primary keys for table "custom_filters" are not allowed
ERROR:  multiple primary keys for table "domain_blocks" are not allowed
ERROR:  multiple primary keys for table "email_domain_blocks" are not allowed
ERROR:  multiple primary keys for table "favourites" are not allowed
ERROR:  multiple primary keys for table "follow_requests" are not allowed
ERROR:  multiple primary keys for table "follows" are not allowed
ERROR:  multiple primary keys for table "identities" are not allowed
ERROR:  multiple primary keys for table "imports" are not allowed
ERROR:  multiple primary keys for table "invites" are not allowed
ERROR:  multiple primary keys for table "list_accounts" are not allowed
ERROR:  multiple primary keys for table "lists" are not allowed
ERROR:  could not create unique index "media_attachments_pkey"
DETAIL:  Key (id)=(2) is duplicated.
CONTEXT:  parallel worker
ERROR:  could not create unique index "mentions_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  multiple primary keys for table "mutes" are not allowed
ERROR:  multiple primary keys for table "notifications" are not allowed
ERROR:  multiple primary keys for table "oauth_access_grants" are not allowed
ERROR:  multiple primary keys for table "oauth_access_tokens" are not allowed
ERROR:  multiple primary keys for table "oauth_applications" are not allowed
ERROR:  multiple primary keys for table "pghero_space_stats" are not allowed
ERROR:  multiple primary keys for table "preview_cards" are not allowed
ERROR:  column "id" named in key does not exist
ERROR:  multiple primary keys for table "relays" are not allowed
ERROR:  multiple primary keys for table "report_notes" are not allowed
ERROR:  multiple primary keys for table "reports" are not allowed
ERROR:  multiple primary keys for table "scheduled_statuses" are not allowed
ERROR:  column "id" named in key does not exist
ERROR:  multiple primary keys for table "session_activations" are not allowed
ERROR:  multiple primary keys for table "settings" are not allowed
ERROR:  multiple primary keys for table "site_uploads" are not allowed
ERROR:  multiple primary keys for table "status_pins" are not allowed
ERROR:  could not create unique index "status_stats_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  multiple primary keys for table "statuses" are not allowed
ERROR:  column "id" named in key does not exist
ERROR:  multiple primary keys for table "stream_entries" are not allowed
ERROR:  multiple primary keys for table "subscriptions" are not allowed
ERROR:  could not create unique index "tags_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  multiple primary keys for table "tombstones" are not allowed
ERROR:  multiple primary keys for table "users" are not allowed
ERROR:  multiple primary keys for table "web_push_subscriptions" are not allowed
ERROR:  multiple primary keys for table "web_settings" are not allowed
```

I've de-duplicated the tags, status_stats, mentions, media_attachments, and account_tag_stats ids, and now it seems to work without the modifications of models

**Comment by Gargron** [comment]
Great! So this all happened because of the Postgres 11 upgrade. Could you tell what version you upgraded from and how, for future reference?

**Comment by BastienDurel** [comment]
I were coming from 10.5, to 11.1 via alpine linux upgrade.

```
pg_dumpall -U postgres > dumpfile
/etc/init.d/postgresql stop
apk add -u postgresql
/etc/init.d/postgresql setup
/etc/init.d/postgresql start
psql -U postgres -f dumpfile
```

**Comment by Gargron** [comment]
Hm. What about the pg_upgrade command? Trying to figure out why primary keys were lost for you.

**Comment by BastienDurel** [comment]
I ran the commands advised by alpine during upgrade, didn't checked them.

I did not removed the snapshot I made before upgrading, maybe I'll try to clone the VM from it tomorrow to try again ^^

**Comment by Gargron** [comment]
Try this guide: https://gorails.com/guides/upgrading-postgresql-version-on-ubuntu-server

**Comment by BastienDurel** [comment]
Hum ... With the pre-upgrade clone, upgrading went good. The primary keys didn't get lost.
